### ISSUE TITLE
是不是不支持 导出编辑好的图片?

### ISSUE THREAD

**Issue by lhj5426** [dmMaze/BallonsTranslator#1]
今天偶然看到这个工具 
下载试了试 还行把    随便编辑了几张图 之后发现???没有导出 图片的功能?
还有 没有原始图片文字 和  翻译文字的图片对吧功能(是直接在气泡上对比 不是在右侧的那个编辑里对吧 那个对比 不直观 ) 
图片修复这个功能真的很不错 没有很厚重的涂抹感 
大佬是不是可以考虑先吧 编辑翻译完的图片导出功能安排上?
还有百度 腾讯 翻译接口也安排一下?

**Comment by dmMaze** [comment]
带译文的结果就在打开目录的result文件夹下

对比什么的，点那个底部画板工具会出现一个滑条，控制原图透明度

我没申请别的翻译器api，这软件加个翻译器40行代码都不到会python就行，先蹲别的大佬提pr吧

**Comment by dmMaze** [comment]
哦我刚才复现了，result下第一张图不保存结果而是原图，这礼拜更新修
