### ISSUE TITLE
引入繁簡中文轉換

### ISSUE THREAD

**Issue by Gordon1301** [dmMaze/BallonsTranslator#100]
希望可以加入opencc開放中文轉換之類的繁簡轉換工具。
主要是為了把彩雲的簡體翻譯再轉換成繁體。

**Comment by dmMaze** [comment]
[v1.3.32](https://github.com/dmMaze/BallonsTranslator/releases/tag/v1.3.32) 彩云及DeepL可选目标语言为繁体
