### ISSUE TITLE
Bug with permanently disappearing toolbar

### ISSUE THREAD

**Issue by bropines** [dmMaze/BallonsTranslator#102]
https://user-images.githubusercontent.com/57861007/221894226-b8e06c63-985e-473e-8161-0398c0080a55.mp4

**Comment by dmMaze** [comment]
![textpanel](https://user-images.githubusercontent.com/51270320/222041064-f9fa6089-8ba8-4dc8-81fc-797b54ffa548.gif)

not sure if it was a bug, maybe you move the mouse too quickly or your mouse sensitivity is too high
