### ISSUE TITLE
BallonTranslator itself closes when close to paradise or when choosing the last (3) processor

### ISSUE THREAD

**Issue by My12123** [dmMaze/BallonsTranslator#104]
![2023-02-28_19-39-26](https://user-images.githubusercontent.com/49092250/221919394-c4258442-18d3-498b-abc7-a0b5b986d372.png)
![2023-02-28_19-39-55](https://user-images.githubusercontent.com/49092250/221919412-fb9ed23d-bc0f-44eb-953b-613a73e6c8ac.png)

**Comment by bropines** [comment]
You can do a primary initialization before startup, so that this item just doesn't work if it's not available.

**Comment by bropines** [comment]
> hip is for AMD gpu support, you have to install pytroch-ROCm and run the source code, and it has not been tested yet (#14) there should be some warning message instead of crashing the program though.

He's not getting anything out. It just crashes the program
