### ISSUE TITLE
一个bug 

### ISSUE THREAD

**Issue by lhj5426** [dmMaze/BallonsTranslator#107]
https://user-images.githubusercontent.com/30548000/222063056-8829a856-e713-497f-a8e5-b6647c478363.mp4

 在涂抹模式下 按pgup 切换到下一页之后 用右键涂抹 大概率 变成框选 而不是涂抹
 想要变回涂抹模式只能 先切换到 文字编辑模式 然后再切换回 涂抹模式 然后 右键才是涂抹而不拉框

**Comment by lhj5426** [comment]
忘记说了 用的是最新版   这应该是bug 吧 ？

**Comment by lhj5426** [comment]
https://user-images.githubusercontent.com/30548000/222064239-c596ecc9-1dd0-41ab-af02-107381ca20ad.mp4

**Comment by dmMaze** [comment]
v1.3.34已修

**Comment by lhj5426** [comment]
> v1.3.34已修

好快。。
