### ISSUE TITLE
字体与轮廓颜色 是否可以独立分开？

### ISSUE THREAD

**Issue by lhj5426** [dmMaze/BallonsTranslator#108]
https://user-images.githubusercontent.com/30548000/222196059-1399ede9-cd31-4d1a-bbff-d1e1c451a153.mp4

大佬我举个例子 
如视频所示 开了字体和轮廓由程序决定
然后程序觉决定之后 看不真亮 但是 只要稍微修改下 轮廓的颜色 你看 差别就出来了
刚才还看的不真亮的 字  一下子就清晰起来了
所以 字体和轮廓颜色
可以拆分 字体颜色和轮廓颜色吗
还有 那个 另外一个独立轮廓  选项 并不管理 轮廓颜色
这样独处拆分之后 像这样做 随便 程序 使用什么颜色 只要设置一个全局固定的轮廓颜色 啥色的字 都能看的清楚

**Comment by dmMaze** [comment]
啥叫独立轮廓？

**Comment by lhj5426** [comment]
![image](https://user-images.githubusercontent.com/30548000/222316572-26177ad3-08a9-4c08-be34-a7c353203785.png)
这个

**Comment by lhj5426** [comment]
所以才有这个 issues 需要把 这个独立出来 
要不有的自动生成的字体颜色 是暗色系 然后边框也是暗色系完全看不清
![image](https://user-images.githubusercontent.com/30548000/222317182-40fdb5ed-0202-4d6c-9872-ff1f6bbb65e1.png)

**Comment by dmMaze** [comment]
那这就是对需求的说明补充？这个issue就一个需求，就是把轮廓控制单独拆除？

**Comment by lhj5426** [comment]
> 那这就是对需求的说明补充？这个issue就一个需求，就是把轮廓控制单独拆出？

是的 字体与轮廓颜色
拆成字体颜色  轮廓颜色 2个独立设置 这个 issue 索要说的内容

**Comment by lhj5426** [comment]
![image](https://github.com/dmMaze/BallonsTranslator/assets/30548000/dcffba52-126c-4db0-9f6d-34200827aef9)
这个问题  什么时候可以修正下呀 jin今天运行最新版 还是存在这个问题 
![image](https://github.com/dmMaze/BallonsTranslator/assets/30548000/d2e9f568-0593-4769-bb8d-8f8040a8b601)
![image](https://github.com/dmMaze/BallonsTranslator/assets/30548000/ae224523-8e92-43cd-88f2-8560cf36ba39)
这轮廓颜色 和 字体颜色不分开 全部自动都看不清呀

**Comment by lhj5426** [comment]
外轮廓可以 色和字体颜色分开
这样可以手动设置一个全局轮廓色
然后 字体颜色继续又软件系统自带赋予
但是字体边框的 描边轮廓的颜色可以手动指定一个 这样就避免看图上的 资源核轮廓相同的颜色导致文字完全无法阅读的情况

**Comment by lhj5426** [comment]
![image](https://github.com/dmMaze/BallonsTranslator/assets/30548000/cb49128e-279a-4af1-a106-10fb1c2d776d)

![image](https://github.com/dmMaze/BallonsTranslator/assets/30548000/17ec52ca-bc68-4a6c-a596-3183313a92d5)
甚至还会出现这种 根本就不给你包轮廓的 情况 这个问题 是影响阅读的大问题 还恳求开发者能解决下

**Comment by dmMaze** [comment]
d9e308b 加了

**Comment by lhj5426** [comment]
![image](https://github.com/dmMaze/BallonsTranslator/assets/30548000/43a5ee05-1b4f-439b-a28f-5decbeb179eb)
![image](https://github.com/dmMaze/BallonsTranslator/assets/30548000/c4af1441-17c4-43a7-9e6a-7287b095ab1b)

![image](https://github.com/dmMaze/BallonsTranslator/assets/30548000/f7f8bb4f-9346-46f2-9ddf-365e024868e0)
![image](https://github.com/dmMaze/BallonsTranslator/assets/30548000/6d271e11-2891-4b7a-a906-be8cab0e20d2)
2个 问题都解决 
字体大小的问题 和字体轮廓和字体颜色分开的问题
厉害！感谢 GPT第三方API 还请 安排一下 哈哈 这个ocr的速度实在是太快了
