### ISSUE TITLE
手动ocr的bug

### ISSUE THREAD

**Issue by lhj5426** [dmMaze/BallonsTranslator#110]
https://user-images.githubusercontent.com/30548000/222340861-d240a5e3-5f0a-42e6-8f5c-a9f095ac5317.mp4

OCR没有识别对换另外一个ocr 之后 无论是OCR 还是ocr翻译 还是ocr翻译并涂抹 都会导致 该区域的文字消失
而且也不会有任何结果

**Comment by lhj5426** [comment]
https://user-images.githubusercontent.com/30548000/222341601-3657a1d5-3199-453a-a701-4f0190a0c7e9.mp4

删除 重新框选OCR 依旧无效
![image](https://user-images.githubusercontent.com/30548000/222341811-f803efc0-ea6d-4bda-b4b0-3f9aa38fd011.png)

**Comment by dmMaze** [comment]
如果用manga_ocr, 等到控制台出下面提示后再用
<img width="435" alt="image" src="https://user-images.githubusercontent.com/51270320/222354239-3e4e818b-142e-49e3-961c-841b8a0153c4.png">

这里消失的文字是机翻结果，因为没有识别到原文自然就没有机翻结果

**Comment by lhj5426** [comment]
> 如果用manga_ocr, 等到控制台出下面提示后再用 <img alt="image" width="435" src="https://user-images.githubusercontent.com/51270320/222354239-3e4e818b-142e-49e3-961c-841b8a0153c4.png">
> 
> 这里消失的文字是机翻结果，因为没有识别到原文自然就没有机翻结果

演示里 首先是先独立OCR  把原来错误的OCR 文字给抹掉 也有写入新的识别结果
然后 删除重新手动框选 OCR 也没有 识别任何结果
不是翻译的问题 是首先就没有OCR成功  是这个issues的核心内容是 手动OCR没有成果  3个OCR都没有成果

**Comment by dmMaze** [comment]
> > 如果用manga_ocr, 等到控制台出下面提示后再用 <img alt="image" width="435" src="https://user-images.githubusercontent.com/51270320/222354239-3e4e818b-142e-49e3-961c-841b8a0153c4.png">
> > 这里消失的文字是机翻结果，因为没有识别到原文自然就没有机翻结果
> 
> 演示里 首先是先独立OCR 把原来错误的OCR 文字给抹掉 也有写入新的识别结果 然后 删除重新手动框选 OCR 也没有 识别任何结果 不是翻译的问题 是首先就没有OCR成功 是这个issues的核心内容是 手动OCR没有成果 3个OCR都没有成果

mit32和48都是逐行识别的，需要框选贴合单行，所以这俩都没结果
我怀疑你manga_ocr还没加载成功就ocr了所以没结果，照上面说的等控制台出信息了后再试试

**Comment by dmMaze** [comment]
> > 如果用manga_ocr, 等到控制台出下面提示后再用 <img alt="image" width="435" src="https://user-images.githubusercontent.com/51270320/222354239-3e4e818b-142e-49e3-961c-841b8a0153c4.png">
> > 这里消失的文字是机翻结果，因为没有识别到原文自然就没有机翻结果
> 
> 演示里 首先是先独立OCR 把原来错误的OCR 文字给抹掉 也有写入新的识别结果 然后 删除重新手动框选 OCR 也没有 识别任何结果 不是翻译的问题 是首先就没有OCR成功 是这个issues的核心内容是 手动OCR没有成果 3个OCR都没有成果

另外mitxxx OCR还需要这个文本框横竖排和原文对应

**Comment by lhj5426** [comment]
> > > 如果用manga_ocr, 等到控制台出下面提示后再用 <img alt="image" width="435" src="https://user-images.githubusercontent.com/51270320/222354239-3e4e818b-142e-49e3-961c-841b8a0153c4.png">
> > > 这里消失的文字是_机翻_结果，因为没有识别到原文自然就没有_机翻_结果
> > 
> > 
> > 演示里 首先是先独立OCR 把原来错误的OCR 文字给抹掉 也有写入新的识别结果 然后 删除重新手动框选 OCR 也没有 识别任何结果 不是翻译的问题 是首先就没有OCR成功 是这个issues的核心内容是 手动OCR没有成果 3个OCR都没有成果
> 
> 另外mitxxx OCR还需要这个文本框横竖排和原文对应

![image](https://user-images.githubusercontent.com/30548000/222410720-8fe140a6-9f40-487d-a36c-58019a8ff5ff.png)
嗯  这样吧

MIT32和48 只能 1小条一小条的识别是么

**Comment by lhj5426** [comment]
非常感谢您的回复 ~~~~！！
确实
![image](https://user-images.githubusercontent.com/30548000/222411433-fee2fc38-92ab-472f-b3e6-191b53d0eebc.png)
只能一小条一小条的 OCR

**Comment by lhj5426** [comment]
那就黑白用MG 全彩用MIT 这样就行了 大概  因为全彩文字是有颜色的 黑白没有
