### ISSUE TITLE
没有python编程基础加不了翻译器，之后会加个百度或者有道什么的翻译api吗？

### ISSUE THREAD

**Issue by bzsk** [dmMaze/BallonsTranslator#112]
没有python编程基础加不了翻译器，之后会加个百度或者有道什么的翻译api吗？

**Comment by dmMaze** [comment]
我不打算加，当然有人pr我也不反对

**Comment by blacklein** [comment]
有道百度的api说到底还是机翻，比谷歌之类并无太大优势，但实测后建议加入openai api，日翻中确实可以大幅提高翻译准确度和通顺度，正儿八经的生产力提升，希望能加入openai api设置功能

**Comment by blacklein** [comment]
openai api的日翻中对机翻简直是天神下凡吊打级别的，我现在已经不用百度翻译api了，所有翻译全部走openai api

**Comment by bzsk** [comment]
> openai api的日翻中对机翻译简单直接接是天神下凡吊别的，我现在已经不用百度翻译api了，所有翻译全部走openai api

最近AI确实很牛掰，可惜我没有编程技术，兴趣使然的话是不是学点python就可以达到你所说的效果？
