### ISSUE TITLE
BallonTranslator.exe打不开

### ISSUE THREAD

**Issue by regentropfen2013** [dmMaze/BallonsTranslator#113]
双击打开瞬闪一个命令行对话框然后消失，没有反应。
使用cmd打开提示：

Microsoft Windows [版本 10.0.22621.1105]
(c) Microsoft Corporation。保留所有权利。

C:\Users\A\Documents\BallonTranslator-1.3.34>BallonTranslator.exe
Traceback (most recent call last):
  File "C:\Users\A\DOCUME~1\BALLON~1.34\__main__.py", line 2, in <module>
ModuleNotFoundError: No module named 'argparse'

C:\Users\Aidan\Documents\BallonTranslator-1.3.34>

**Comment by dmMaze** [comment]
![IMG_20230306_111628.jpg](https://user-images.githubusercontent.com/51270320/223011774-2bad58c9-1399-4788-965c-12762b6b4f1b.jpg)

**Comment by dmMaze** [comment]
旧版 (所有exe) 不再推荐使用
