### ISSUE TITLE
GD分享的提示病毒了

### ISSUE THREAD

**Issue by weiby3** [dmMaze/BallonsTranslator#116]
https://drive.google.com/file/d/17R7QUL7v5IrBwhslwCwVX8y5PJeG42fb/view

抱歉，此文件感染了病毒。

只有所有者才能下载感染了病毒的文件。

不行就加个密码吧

**Comment by dmMaze** [comment]
我又压了一遍
为啥谷歌盘会报毒

**Comment by weiby3** [comment]
要不你问下谷歌呗，估计是哪里误报了

**Comment by weiby3** [comment]
试了下现在倒是能下了

**Comment by dmMaze** [comment]
又被flag了, 现在换成了onedrive
