### ISSUE TITLE
Deepl api超时

### ISSUE THREAD

**Issue by 809509941** [dmMaze/BallonsTranslator#119]
试了下。deepl会经常超时。但是要翻译要么手动，要么重新开始。希望可以增加个断点续翻译的功能，就是可以从某一页开始继续翻译
![138](https://user-images.githubusercontent.com/62390747/224461878-4c1786c0-0af6-4d70-89a2-3aff748b3378.PNG)
ConnectionException: Request timed out: HTTPSConnectionPool(host='api-free.deepl.com', port=443): Read timed out. (read timeout=10.0)

**Comment by dmMaze** [comment]
要不先试试挂个快点的代理啥的？

**Comment by 809509941** [comment]
> 要不先试试挂个快点的代理啥的？

我直接在国外服务器上操作的。。。用谷歌翻译是正常的。deepl的话好像快了就是不行。我手动点翻译都偶尔会出现，只有慢慢来才行

**Comment by dmMaze** [comment]
现在可以加个延时(delay)了
