### ISSUE TITLE
How do I load a project from dl_manager.py

### ISSUE THREAD

**Issue by ROKOLYT** [dmMaze/BallonsTranslator#120]
How should I go about loading a project from dl_manager.py. I tried 
```py
self.imgtrans_proj.load(proj_path)
```
which worked like half a year ago but now I get painter not active error. The project itself does load as it creates folders and .json file. It also starts working (masking and inpainting work, the images are generated), but it fails to produce the results.

**Comment by dmMaze** [comment]
Not sure what you want to achive. Can you share the script or modified source file?

**Comment by ROKOLYT** [comment]
[https://github.com/ROKOLYT/BallonsTranslator/blob/0d2cac390f02748f3c40412faa2452735dd606f9/ballontranslator/ui/dl_manager.py#L573](url)

**Comment by ROKOLYT** [comment]
> https://github.com/ROKOLYT/BallonsTranslator/blob/0d2cac390f02748f3c40412faa2452735dd606f9/ballontranslator/ui/dl_manager.py#L573

I am aware that there are glitches when not using src download, I already fixed them locally, but didn't push them yet.

**Comment by dmMaze** [comment]
> https://github.com/ROKOLYT/BallonsTranslator/blob/0d2cac390f02748f3c40412faa2452735dd606f9/ballontranslator/ui/dl_manager.py#L573

imgtrans_proj.load here alone shouldn't trigger such error
To properly load a proj.json, call 
https://github.com/dmMaze/BallonsTranslator/blob/b625c891d7659b4b7e4b75fcbcb2410bba964093/ballontranslator/ui/mainwindow.py#L307

or 

https://github.com/dmMaze/BallonsTranslator/blob/b625c891d7659b4b7e4b75fcbcb2410bba964093/ballontranslator/ui/mainwindow.py#L327

And dl_mangager is messy enough without introducing some source control, please make something like SourceManger, and let it emit signals to call above functions to suit your needs.
