### ISSUE TITLE
能不能增加个GPT翻译呢

### ISSUE THREAD

**Issue by lhj5426** [dmMaze/BallonsTranslator#122]
![666641](https://user-images.githubusercontent.com/30548000/226268281-5fe02059-50c6-4c9a-8861-d29a1bf22956.gif)
清一色的全要api 增加个 chatGPT  api 不知道可不可呢？

**Comment by dmMaze** [comment]
可以，不过我自己没怎么用过chatgpt和它的api，最近也没时间
加一个翻译器大概也就50行不到的python，大部分还都是boilerplate code，可以试试把文档和几个例子贴给它问它怎么加
