### ISSUE TITLE
可以加个导入字体的功能吗

### ISSUE THREAD

**Issue by yongrenx** [dmMaze/BallonsTranslator#123]
嵌字需要的字体还蛮多的，默认的字体没有能用的，如果麻烦的话就算了

**Comment by dmMaze** [comment]
默认从系统字体读的，可以试试安装你的第三方字体，如果没有读到大概不支持
不过确实可以加个加载指定字体的功能

**Comment by Gordon1301** [comment]
可以加载指定字体的话会很实用
因为嵌字通常只会用到指定的七八只字体左右。

**Comment by dmMaze** [comment]
现在可以放到软件fonts目录下
