### ISSUE TITLE
OCR結果替換，關鍵詞不能含有空格

### ISSUE THREAD

**Issue by Gordon1301** [dmMaze/BallonsTranslator#134]
例子：
1. " " -> "" 含空格，失敗
2. "F " -> "" 含空格，失敗
3. "F" -> "" 不含空格，成功
4. Regex "[A-Za-z] " -> "" 含空格，失敗
5. Regex "[A-Za-z]" -> "" 不含空格，成功

OCR結果中，挺常在一句話中出現"F "、"P "、"Q "等等而影響翻譯，希望可以修正OCR有空格時不能替換的問題。

**Comment by dmMaze** [comment]
1失败是一个判断bug
其它的我试了一下替换结果没错，能不能把你试的待替换原文贴上来

**Comment by dmMaze** [comment]
> 无任何替换： この街はﾞフリージァﾞ 初心者冒険者が多く 子供でもやれる仕事はF すぐ見つかると思うぞ
> 
> 中间多了个"F "，欲连空格一起移除。
> 
> 1. " " -> ""
> 2. "F " -> ""
> 3. Regex "[A-Za-z] " -> ""
> 
> 以上仍然维持原文 この街はﾞフリージァﾞ 初心者冒険者が多く 子供でもやれる仕事はF すぐ見つかると思うぞ
> 
> 3. "F" -> ""
> 4. Regex "[A-Za-z]" -> ""
> 
> 以上可以替换走多馀的文字，证明是空格导致替换失败。 この街はﾞフリージァﾞ 初心者冒険者が多く 子供でもやれる仕事は すぐ見つかると思うぞ

除了1我这里都替换成功了，可能是ocr出了什么长得像空格的占位符...你贴的是直接从ocr复制的文本内容吗？如果方便的话给下原图

**Comment by Gordon1301** [comment]
原圖：
https://image.hachimanga.com/wp-content/uploads/WP-manga/data/manga_6252077174341/9ae62be7fbe96bc1a59a4544b91f319f/34.jpg

左上畫框的第二句話，會OCR成「この街はﾞフリージァﾞ 初心者冒険者が多く 子供でもやれる仕事はF すぐ見つかると思うぞ」(mit32px、chunk_size 8、cpu)

**Comment by dmMaze** [comment]
这个不是匹配bug而是ocr另一个后处理出了问题所以匹配不出来...v1.3.35已修

**Comment by Gordon1301** [comment]
v1.3.35修复成功了，谢谢
