### ISSUE TITLE
请问有添加外来字体的功能吗，还有字体识别的功能？

### ISSUE THREAD

**Issue by longfei796** [dmMaze/BallonsTranslator#136]
就是导入外来字体，
还有请问识别字体的功能可以有吗？

**Comment by tak2hu** [comment]
*I assume you are asking how to use other fonts*

This app uses fonts that are installed on the OS.

A font detector is not implemented.

But this app is based on [manga-image-translator](https://github.com/zyddnys/manga-image-translator) and this [font detector](https://github.com/JeffersonQin/YuzuMarker.FontDetection) could be added in the future.

**Comment by dmMaze** [comment]
把外来字体放进程序目录/fonts下就行了
