### ISSUE TITLE
可以调节字间距吗？还有有的背景字识别出来后被扣掉，背景黑漆漆的一片可以撤销吗？

### ISSUE THREAD

**Issue by longfei796** [dmMaze/BallonsTranslator#137]
没有找到调节方法

**Comment by longfei796** [comment]
大佬将来会添加更多的文本调节功能吗？

**Comment by dmMaze** [comment]
<img width="290" alt="屏幕截图 2023-04-24 122046" src="https://user-images.githubusercontent.com/51270320/233899461-4e1ba327-73d8-4ddc-9362-c8168351dc50.png">
字/行间距: 鼠标靠向上面的图标按下左键拖拽

 点run跑的不能撤消重做，可以自己手动修https://github.com/dmMaze/BallonsTranslator/blob/master/doc/src/rect_tool.gif

**Comment by longfei796** [comment]
> <img alt="屏幕截图 2023-04-24 122046" width="290" src="https://user-images.githubusercontent.com/51270320/233899461-4e1ba327-73d8-4ddc-9362-c8168351dc50.png">
> 
> 字/行间距: 鼠标靠向上面的图标按下左键拖拽
> 点run跑的不能撤消重做，可以自己手动修https://github.com/dmMaze/BallonsTranslator/blob/master/doc/src/rect_tool.gif

有时候结果result文件夹里会出现红色的文本框如何处理？

**Comment by longfei796** [comment]
> <img alt="屏幕截图 2023-04-24 122046" width="290" src="https://user-images.githubusercontent.com/51270320/233899461-4e1ba327-73d8-4ddc-9362-c8168351dc50.png">
> 
> 字/行间距: 鼠标靠向上面的图标按下左键拖拽
> 点run跑的不能撤消重做，可以自己手动修https://github.com/dmMaze/BallonsTranslator/blob/master/doc/src/rect_tool.gif

我用的是1.3.0没有这个按钮，是需要更新吗？google里面只有1.3.0的
![Uploading mmexport1682322410236.png…]()

**Comment by longfei796** [comment]
> @longfei796 谷歌盘更新包被flag了，从release或者mega下新包覆盖更新

您好，没有任何变化，我是从google下载的core跟data的压缩包，我把data的压缩包拖动到ballontranslator里面直接解压
然后用下载的新版本1.3.5压缩包，也是拖动到ballontranslator里直接解压的

**Comment by longfei796** [comment]
> @longfei796 谷歌盘更新包被flag了，从release或者mega下新包覆盖更新

成功了，打扰您不好意思了，谢谢您回复
