### ISSUE TITLE
两个问题，想请问大佬

### ISSUE THREAD

**Issue by longfei796** [dmMaze/BallonsTranslator#138]
请问您跑图的时候崩了，然后重新点开发现文本框都消失了怎么办
还有请问全选文本框的时候可以只选择改正一个吗，本来只想改字体，还是连型号，字间距都改了
还得自己一个一个拉文本框

**Comment by dmMaze** [comment]
> 请问您跑图的时候崩了，然后重新点开发现文本框都消失了怎么办

可以给我看看data/logs下面那次崩溃的日志，或者https://github.com/dmMaze/BallonsTranslator/blob/master/doc/src/run.gif 崩溃时黑框的输出结果我看看能不能修

> 还有请问全选文本框的时候可以只选择改正一个吗，本来只想改字体，还是连型号，字间距都改了

那就不要全选呗，双击编辑当前文本框后可以一个一个改

**Comment by longfei796** [comment]
> 

今天跑两三次图反而没问题了，奇怪，等我有问题，再截图发给您吧

**Comment by longfei796** [comment]
> > 请问您跑图的时候崩了，然后重新点开发现文本框都消失了怎么办
> 
> 可以给我看看data/logs下面那次崩溃的日志，或者https://github.com/dmMaze/BallonsTranslator/blob/master/doc/src/run.gif 崩溃时黑框的输出结果我看看能不能修
> 
> > 还有请问全选文本框的时候可以只选择改正一个吗，本来只想改字体，还是连型号，字间距都改了
> 
> 那就不要全选呗，双击编辑当前文本框后可以一个一个改

请问有时候生成的图片有蓝色文本框什么原因，挪一挪位置后就消失了

**Comment by dmMaze** [comment]
> > > 请问您跑图的时候崩了，然后重新点开发现文本框都消失了怎么办
> > 
> > 
> > 可以给我看看data/logs下面那次崩溃的日志，或者https://github.com/dmMaze/BallonsTranslator/blob/master/doc/src/run.gif 崩溃时黑框的输出结果我看看能不能修
> > > 还有请问全选文本框的时候可以只选择改正一个吗，本来只想改字体，还是连型号，字间距都改了
> > 
> > 
> > 那就不要全选呗，双击编辑当前文本框后可以一个一个改
> 
> 请问有时候生成的图片有蓝色文本框什么原因，挪一挪位置后就消失了

这种bug需要提供文字描述或者录屏让我能够复现
