### ISSUE TITLE
DOC可以导出原文吗

### ISSUE THREAD

**Issue by lhj5426** [dmMaze/BallonsTranslator#141]
这现实打脸啪啪啪的哈哈
我本来想 有导出dOC 那我 把文本批量那给 克劳德 来翻译然后在导入进去
结果 当我打开导出的DOC  黑人问号 没有原文可以复制只有 一个图片切片

想的 鸡你太美了
![image](https://user-images.githubusercontent.com/30548000/236470992-21487343-bb85-46ae-ad9b-be1905cd06dd.png)

**Comment by canon15167** [comment]
我也碰到同樣的問題，於是我讓ChatGPT幫我寫了一段Python代碼來從BallonsTranslator儲存資料的.json中提取出原文:
`import json

# Open and load your json file
with open('yourfile.json', 'r', encoding='utf-8') as f:
    data = json.load(f)

# Open the output file
with open('output.txt', 'w', encoding='utf-8') as f:
    # Iterate over each page
    for page_name, page_data in data.get('pages', {}).items():
        # Write the page name as a title
        f.write(page_name + '\n')

        # Collect the 'text' values for this page
        text_values = [item['text'] for item in page_data if 'text' in item]

        # Write each 'text' value to a separate line
        for item in text_values:
            # Assuming the text field is a list, join all the elements into a string
            text = ' '.join(item) if isinstance(item, list) else item
            f.write(text + '\n')

        # Write an extra newline to separate paragraphs
        f.write('\n')`
        
使用時將“yourfile.json”替換為你的 .json 的路徑

**Comment by lhj5426** [comment]
> 我也碰到同樣的問題，於是我讓ChatGPT幫我寫了一段Python代碼來從BallonsTranslator儲存資料的.json中提取出原文:
> 
> ```
> import json
> 
> # Open and load your json file
> with open('yourfile.json', 'r', encoding='utf-8') as f:
>     data = json.load(f)
> 
> # Open the output file
> with open('output.txt', 'w', encoding='utf-8') as f:
>     # Iterate over each page
>     for page_name, page_data in data.get('pages', {}).items():
>         # Write the page name as a title
>         f.write(page_name + '\n')
> 
>         # Collect the 'text' values for this page
>         text_values = [item['text'] for item in page_data if 'text' in item]
> 
>         # Write each 'text' value to a separate line
>         for item in text_values:
>             # Assuming the text field is a list, join all the elements into a string
>             text = ' '.join(item) if isinstance(item, list) else item
>             f.write(text + '\n')
> 
>         # Write an extra newline to separate paragraphs
>         f.write('\n')
> ```
> 
> 使用時將“yourfile.json”替換為你的 .json 的路徑

牛逼  那的需要2个脚本把 导出还得导入？

**Comment by canon15167** [comment]
把這段代碼輸入Spyder之類的編譯器就可以跑了

**Comment by canon15167** [comment]
啊 我的確沒考慮導入的問題 我都逐句潤色再手動輸入XD
我研究看看

**Comment by lhj5426** [comment]
> 啊 我的確沒考慮導入的問題 我都逐句潤色再手動輸入XD 我研究看看

我导出是为了想先让GPT全跑一遍 只会再导入回去 然后在软件里润色还有调整文字大小位置什么的 是这个意思 

而且就是不润色 自己用啃生肉  直接看也是可以的 用GPT

**Comment by canon15167** [comment]
````
import json

# Open and load your json file
with open('yourfile.json', 'r', encoding='utf-8') as f:
    data = json.load(f)

# Open your .txt file
with open('translate.txt', 'r', encoding='utf-8') as f:
    lines = f.readlines()

page_name = None
translations = []
for line in lines:
    stripped_line = line.strip()
    # If the line is not empty
    if stripped_line:
        # If we're on the first line of a paragraph, this is the page name
        if page_name is None:
            page_name = stripped_line
        # Otherwise, this line is a translation
        else:
            translations.append(stripped_line)
    # If the line is empty, we're at the end of a paragraph
    else:
        # Update the 'translation' fields for this page
        if page_name is not None:
            page_data = data.get('pages', {}).get(page_name, [])
            for item, translation in zip(page_data, translations):
                if 'translation' in item:
                    item['translation'] = translation
        # Reset for the next paragraph
        page_name = None
        translations = []

# Don't forget to update the last page
if page_name is not None:
    page_data = data.get('pages', {}).get(page_name, [])
    for item, translation in zip(page_data, translations):
        if 'translation' in item:
            item['translation'] = translation

# Write the updated data back to the .json file
with open('yourfile.json', 'w', encoding='utf-8') as f:
    json.dump(data, f, ensure_ascii=False, indent=4)
````
'yourfile.json'改BallonsTranslator的.json的路徑
'translate.txt'改你翻譯文字檔的路徑
內容格式需與之前輸出一致，一句一行、以頁碼名稱為段落標題

**Comment by lhj5426** [comment]
> ```
> import json
> 
> # Open and load your json file
> with open('yourfile.json', 'r', encoding='utf-8') as f:
>     data = json.load(f)
> 
> # Open your .txt file
> with open('translate.txt', 'r', encoding='utf-8') as f:
>     lines = f.readlines()
> 
> page_name = None
> translations = []
> for line in lines:
>     stripped_line = line.strip()
>     # If the line is not empty
>     if stripped_line:
>         # If we're on the first line of a paragraph, this is the page name
>         if page_name is None:
>             page_name = stripped_line
>         # Otherwise, this line is a translation
>         else:
>             translations.append(stripped_line)
>     # If the line is empty, we're at the end of a paragraph
>     else:
>         # Update the 'translation' fields for this page
>         if page_name is not None:
>             page_data = data.get('pages', {}).get(page_name, [])
>             for item, translation in zip(page_data, translations):
>                 if 'translation' in item:
>                     item['translation'] = translation
>         # Reset for the next paragraph
>         page_name = None
>         translations = []
> 
> # Don't forget to update the last page
> if page_name is not None:
>     page_data = data.get('pages', {}).get(page_name, [])
>     for item, translation in zip(page_data, translations):
>         if 'translation' in item:
>             item['translation'] = translation
> 
> # Write the updated data back to the .json file
> with open('yourfile.json', 'w', encoding='utf-8') as f:
>     json.dump(data, f, ensure_ascii=False, indent=4)
> ```
> 
> 'yourfile.json'改BallonsTranslator的.json的路徑 'translate.txt'改你翻譯文字檔的路徑 內容格式需與之前輸出一致，一句一行、以頁碼名稱為段落標題

这是怎么让GPT 写出来的

**Comment by canon15167** [comment]
一開始我是這樣問GPT的:
````
I have a bunch of data that is stored as a .json file. 
This is how some of my data looks like:

(節錄一段json的文件格式)

Can I export all the content of "text" as a .txt file with Spyder?
````
之後進一步要求GPT將輸出結果依照頁碼分段
````
This works great! Thank you.
But if possible, can you help enhance the code, making the output text from different pages separate to individual paragraphs, and set the value of "pages" as the title for each paragraph?
````
最後再要求它寫一段代碼將翻譯結果導入json
````
This is perfect!
I have another question:
Now I have a .txt file, each value in this file is written to a separate line, with the page names (keys from the 'pages' dictionary) as titles for the paragraphs. Can you help me write a script that import the values to the "translation" fields in the original .json file?
````

**Comment by lhj5426** [comment]
> 一開始我是這樣問GPT的:
> 
> ```
> I have a bunch of data that is stored as a .json file. 
> This is how some of my data looks like:
> 
> (節錄一段json的文件格式)
> 
> Can I export all the content of "text" as a .txt file with Spyder?
> ```
> 
> 之後進一步要求GPT將輸出結果依照頁碼分段
> 
> ```
> This works great! Thank you.
> But if possible, can you help enhance the code, making the output text from different pages separate to individual paragraphs, and set the value of "pages" as the title for each paragraph?
> ```
> 
> 最後再要求它寫一段代碼將翻譯結果導入json
> 
> ```
> This is perfect!
> I have another question:
> Now I have a .txt file, each value in this file is written to a separate line, with the page names (keys from the 'pages' dictionary) as titles for the paragraphs. Can you help me write a script that import the values to the "translation" fields in the original .json file?
> ```

我也试着问过我是用中文 问的 同时问的GPT和 竞品 Claude  都在胡扯 甚至一次次输出 相同的代码 像复读机一样

**Comment by lhj5426** [comment]
> ```
> import json
> 
> # Open and load your json file
> with open('yourfile.json', 'r', encoding='utf-8') as f:
>     data = json.load(f)
> 
> # Open your .txt file
> with open('translate.txt', 'r', encoding='utf-8') as f:
>     lines = f.readlines()
> 
> page_name = None
> translations = []
> for line in lines:
>     stripped_line = line.strip()
>     # If the line is not empty
>     if stripped_line:
>         # If we're on the first line of a paragraph, this is the page name
>         if page_name is None:
>             page_name = stripped_line
>         # Otherwise, this line is a translation
>         else:
>             translations.append(stripped_line)
>     # If the line is empty, we're at the end of a paragraph
>     else:
>         # Update the 'translation' fields for this page
>         if page_name is not None:
>             page_data = data.get('pages', {}).get(page_name, [])
>             for item, translation in zip(page_data, translations):
>                 if 'translation' in item:
>                     item['translation'] = translation
>         # Reset for the next paragraph
>         page_name = None
>         translations = []
> 
> # Don't forget to update the last page
> if page_name is not None:
>     page_data = data.get('pages', {}).get(page_name, [])
>     for item, translation in zip(page_data, translations):
>         if 'translation' in item:
>             item['translation'] = translation
> 
> # Write the updated data back to the .json file
> with open('yourfile.json', 'w', encoding='utf-8') as f:
>     json.dump(data, f, ensure_ascii=False, indent=4)
> ```
> 
> 'yourfile.json'改BallonsTranslator的.json的路徑 'translate.txt'改你翻譯文字檔的路徑 內容格式需與之前輸出一致，一句一行、以頁碼名稱為段落標題

我没看明白 
 
![image](https://github.com/dmMaze/BallonsTranslator/assets/30548000/8d85e633-81cd-474a-8894-9dd59067fae6)
明白 翻译 位置 写的222  但是重新打开软件 之后 还是原来的机翻  并不是瞎写的测试 文本

**Comment by dmMaze** [comment]
> 明白 翻译 位置 写的222 但是重新打开软件 之后 还是原来的机翻 并不是瞎写的测试 文本

``` python
import json

# Open and load your json file
with open('yourfile.json', 'r', encoding='utf-8') as f:
    data = json.load(f)

# Open your .txt file
with open('translate.txt', 'r', encoding='utf-8') as f:
    lines = f.readlines()

page_name = None
translations = []
for line in lines:
    stripped_line = line.strip()
    # If the line is not empty
    if stripped_line:
        # If we're on the first line of a paragraph, this is the page name
        if page_name is None:
            page_name = stripped_line
        # Otherwise, this line is a translation
        else:
            translations.append(stripped_line)
    # If the line is empty, we're at the end of a paragraph
    else:
        # Update the 'translation' fields for this page
        if page_name is not None:
            page_data = data.get('pages', {}).get(page_name, [])
            for item, translation in zip(page_data, translations):
                if 'translation' in item:
                    item['translation'] = translation
                if 'rich_text' in item:
                    item['rich_text'] = ''
        # Reset for the next paragraph
        page_name = None
        translations = []

# Don't forget to update the last page
if page_name is not None:
    page_data = data.get('pages', {}).get(page_name, [])
    for item, translation in zip(page_data, translations):
        if 'translation' in item:
            item['translation'] = translation
        if 'rich_text' in item:
            item['rich_text'] = ''
# Write the updated data back to the .json file
with open('yourfile.json', 'w', encoding='utf-8') as f:
    json.dump(data, f, ensure_ascii=False, indent=4)
```

我改了下，这样应该就行了

**Comment by lhj5426** [comment]
> > 明白 翻译 位置 写的222 但是重新打开软件 之后 还是原来的_机翻_ 并不是瞎写的测试 文本
> 
> ```python
> import json
> 
> # Open and load your json file
> with open('yourfile.json', 'r', encoding='utf-8') as f:
>     data = json.load(f)
> 
> # Open your .txt file
> with open('translate.txt', 'r', encoding='utf-8') as f:
>     lines = f.readlines()
> 
> page_name = None
> translations = []
> for line in lines:
>     stripped_line = line.strip()
>     # If the line is not empty
>     if stripped_line:
>         # If we're on the first line of a paragraph, this is the page name
>         if page_name is None:
>             page_name = stripped_line
>         # Otherwise, this line is a translation
>         else:
>             translations.append(stripped_line)
>     # If the line is empty, we're at the end of a paragraph
>     else:
>         # Update the 'translation' fields for this page
>         if page_name is not None:
>             page_data = data.get('pages', {}).get(page_name, [])
>             for item, translation in zip(page_data, translations):
>                 if 'translation' in item:
>                     item['translation'] = translation
>                 if 'rich_text' in item:
>                     item['rich_text'] = ''
>         # Reset for the next paragraph
>         page_name = None
>         translations = []
> 
> # Don't forget to update the last page
> if page_name is not None:
>     page_data = data.get('pages', {}).get(page_name, [])
>     for item, translation in zip(page_data, translations):
>         if 'translation' in item:
>             item['translation'] = translation
>         if 'rich_text' in item:
>             item['rich_text'] = ''
> # Write the updated data back to the .json file
> with open('yourfile.json', 'w', encoding='utf-8') as f:
>     json.dump(data, f, ensure_ascii=False, indent=4)
> ```
> 
> 我改了下，这样应该就行了

![image](https://github.com/dmMaze/BallonsTranslator/assets/30548000/71fcaae9-ff7d-4a4e-964b-7f188800134c)
开发者大佬亲自出手   解决了 这样就可以配合最开始导出 脚本 修改完后进行导入了

**Comment by longfei796** [comment]
> > > 明白 翻译 位置 写的222 但是重新打开软件 之后 还是原来的_机翻_ 并不是瞎写的测试 文本
> > 
> > 
> > ```python
> > import json
> > 
> > # Open and load your json file
> > with open('yourfile.json', 'r', encoding='utf-8') as f:
> >     data = json.load(f)
> > 
> > # Open your .txt file
> > with open('translate.txt', 'r', encoding='utf-8') as f:
> >     lines = f.readlines()
> > 
> > page_name = None
> > translations = []
> > for line in lines:
> >     stripped_line = line.strip()
> >     # If the line is not empty
> >     if stripped_line:
> >         # If we're on the first line of a paragraph, this is the page name
> >         if page_name is None:
> >             page_name = stripped_line
> >         # Otherwise, this line is a translation
> >         else:
> >             translations.append(stripped_line)
> >     # If the line is empty, we're at the end of a paragraph
> >     else:
> >         # Update the 'translation' fields for this page
> >         if page_name is not None:
> >             page_data = data.get('pages', {}).get(page_name, [])
> >             for item, translation in zip(page_data, translations):
> >                 if 'translation' in item:
> >                     item['translation'] = translation
> >                 if 'rich_text' in item:
> >                     item['rich_text'] = ''
> >         # Reset for the next paragraph
> >         page_name = None
> >         translations = []
> > 
> > # Don't forget to update the last page
> > if page_name is not None:
> >     page_data = data.get('pages', {}).get(page_name, [])
> >     for item, translation in zip(page_data, translations):
> >         if 'translation' in item:
> >             item['translation'] = translation
> >         if 'rich_text' in item:
> >             item['rich_text'] = ''
> > # Write the updated data back to the .json file
> > with open('yourfile.json', 'w', encoding='utf-8') as f:
> >     json.dump(data, f, ensure_ascii=False, indent=4)
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > 我改了下，这样应该就行了
> 
> ![image](https://user-images.githubusercontent.com/30548000/238115057-71fcaae9-ff7d-4a4e-964b-7f188800134c.png) 开发者大佬亲自出手 解决了 这样就可以配合最开始导出 脚本 修改完后进行导入了

请问怎么弄的，我不懂代码，看不明白什么意思，
是改什么东西吗

**Comment by lhj5426** [comment]
> > > > 明白 翻译 位置 写的222 但是重新打开软件 之后 还是原来的__机翻__ 并不是瞎写的测试 文本
> > > 
> > > 
> > > ```python
> > > import json
> > > 
> > > # Open and load your json file
> > > with open('yourfile.json', 'r', encoding='utf-8') as f:
> > >     data = json.load(f)
> > > 
> > > # Open your .txt file
> > > with open('translate.txt', 'r', encoding='utf-8') as f:
> > >     lines = f.readlines()
> > > 
> > > page_name = None
> > > translations = []
> > > for line in lines:
> > >     stripped_line = line.strip()
> > >     # If the line is not empty
> > >     if stripped_line:
> > >         # If we're on the first line of a paragraph, this is the page name
> > >         if page_name is None:
> > >             page_name = stripped_line
> > >         # Otherwise, this line is a translation
> > >         else:
> > >             translations.append(stripped_line)
> > >     # If the line is empty, we're at the end of a paragraph
> > >     else:
> > >         # Update the 'translation' fields for this page
> > >         if page_name is not None:
> > >             page_data = data.get('pages', {}).get(page_name, [])
> > >             for item, translation in zip(page_data, translations):
> > >                 if 'translation' in item:
> > >                     item['translation'] = translation
> > >                 if 'rich_text' in item:
> > >                     item['rich_text'] = ''
> > >         # Reset for the next paragraph
> > >         page_name = None
> > >         translations = []
> > > 
> > > # Don't forget to update the last page
> > > if page_name is not None:
> > >     page_data = data.get('pages', {}).get(page_name, [])
> > >     for item, translation in zip(page_data, translations):
> > >         if 'translation' in item:
> > >             item['translation'] = translation
> > >         if 'rich_text' in item:
> > >             item['rich_text'] = ''
> > > # Write the updated data back to the .json file
> > > with open('yourfile.json', 'w', encoding='utf-8') as f:
> > >     json.dump(data, f, ensure_ascii=False, indent=4)
> > > ```
> > > 
> > > 
> > >     
> > >       
> > >     
> > > 
> > >       
> > >     
> > > 
> > >     
> > >   
> > > 我改了下，这样应该就行了
> > 
> > 
> > ![image](https://user-images.githubusercontent.com/30548000/238115057-71fcaae9-ff7d-4a4e-964b-7f188800134c.png) 开发者大佬亲自出手 解决了 这样就可以配合最开始导出 脚本 修改完后进行导入了
> 
> 请问怎么弄的，我不懂代码，看不明白什么意思， 是改什么东西吗
[BallonTranslator拖拽导入导出.zip](https://github.com/dmMaze/BallonsTranslator/files/13219352/BallonTranslator.zip)

已经简化到 拖拽 就行了 下载这个zip包 有2个文件 一个导入一个导出 都是拖拽
 不管是导入还是导出 都拖拽 JSON到 PY文件上

**Comment by longfei796** [comment]
> > > > > 明白 翻译 位置 写的222 但是重新打开软件 之后 还是原来的__机翻__ 并不是瞎写的测试 文本
> > > > 
> > > > 
> > > > ```python
> > > > import json
> > > > 
> > > > # Open and load your json file
> > > > with open('yourfile.json', 'r', encoding='utf-8') as f:
> > > >     data = json.load(f)
> > > > 
> > > > # Open your .txt file
> > > > with open('translate.txt', 'r', encoding='utf-8') as f:
> > > >     lines = f.readlines()
> > > > 
> > > > page_name = None
> > > > translations = []
> > > > for line in lines:
> > > >     stripped_line = line.strip()
> > > >     # If the line is not empty
> > > >     if stripped_line:
> > > >         # If we're on the first line of a paragraph, this is the page name
> > > >         if page_name is None:
> > > >             page_name = stripped_line
> > > >         # Otherwise, this line is a translation
> > > >         else:
> > > >             translations.append(stripped_line)
> > > >     # If the line is empty, we're at the end of a paragraph
> > > >     else:
> > > >         # Update the 'translation' fields for this page
> > > >         if page_name is not None:
> > > >             page_data = data.get('pages', {}).get(page_name, [])
> > > >             for item, translation in zip(page_data, translations):
> > > >                 if 'translation' in item:
> > > >                     item['translation'] = translation
> > > >                 if 'rich_text' in item:
> > > >                     item['rich_text'] = ''
> > > >         # Reset for the next paragraph
> > > >         page_name = None
> > > >         translations = []
> > > > 
> > > > # Don't forget to update the last page
> > > > if page_name is not None:
> > > >     page_data = data.get('pages', {}).get(page_name, [])
> > > >     for item, translation in zip(page_data, translations):
> > > >         if 'translation' in item:
> > > >             item['translation'] = translation
> > > >         if 'rich_text' in item:
> > > >             item['rich_text'] = ''
> > > > # Write the updated data back to the .json file
> > > > with open('yourfile.json', 'w', encoding='utf-8') as f:
> > > >     json.dump(data, f, ensure_ascii=False, indent=4)
> > > > ```
> > > > 
> > > > 
> > > >     
> > > >       
> > > >     
> > > > 
> > > >       
> > > >     
> > > > 
> > > >     
> > > >   
> > > > 我改了下，这样应该就行了
> > > 
> > > 
> > > ![image](https://user-images.githubusercontent.com/30548000/238115057-71fcaae9-ff7d-4a4e-964b-7f188800134c.png) 开发者大佬亲自出手 解决了 这样就可以配合最开始导出 脚本 修改完后进行导入了
> > 
> > 
> > 请问怎么弄的，我不懂代码，看不明白什么意思， 是改什么东西吗
> > [BallonTranslator拖拽导入导出.zip](https://github.com/dmMaze/BallonsTranslator/files/13219352/BallonTranslator.zip)
> 
> 已经简化到 拖拽 就行了 下载这个zip包 有2个文件 一个导入一个导出 都是拖拽 不管是导入还是导出 都拖拽 JSON到 PY文件上 python 环境 还是要安装的

可以再请问汉化的什么漫画吗，看起来萌萌的

**Comment by lhj5426** [comment]
> > > > > > 明白 翻译 位置 写的222 但是重新打开软件 之后 还是原来的___机翻___ 并不是瞎写的测试 文本
> > > > > 
> > > > > 
> > > > > ```python
> > > > > import json
> > > > > 
> > > > > # Open and load your json file
> > > > > with open('yourfile.json', 'r', encoding='utf-8') as f:
> > > > >     data = json.load(f)
> > > > > 
> > > > > # Open your .txt file
> > > > > with open('translate.txt', 'r', encoding='utf-8') as f:
> > > > >     lines = f.readlines()
> > > > > 
> > > > > page_name = None
> > > > > translations = []
> > > > > for line in lines:
> > > > >     stripped_line = line.strip()
> > > > >     # If the line is not empty
> > > > >     if stripped_line:
> > > > >         # If we're on the first line of a paragraph, this is the page name
> > > > >         if page_name is None:
> > > > >             page_name = stripped_line
> > > > >         # Otherwise, this line is a translation
> > > > >         else:
> > > > >             translations.append(stripped_line)
> > > > >     # If the line is empty, we're at the end of a paragraph
> > > > >     else:
> > > > >         # Update the 'translation' fields for this page
> > > > >         if page_name is not None:
> > > > >             page_data = data.get('pages', {}).get(page_name, [])
> > > > >             for item, translation in zip(page_data, translations):
> > > > >                 if 'translation' in item:
> > > > >                     item['translation'] = translation
> > > > >                 if 'rich_text' in item:
> > > > >                     item['rich_text'] = ''
> > > > >         # Reset for the next paragraph
> > > > >         page_name = None
> > > > >         translations = []
> > > > > 
> > > > > # Don't forget to update the last page
> > > > > if page_name is not None:
> > > > >     page_data = data.get('pages', {}).get(page_name, [])
> > > > >     for item, translation in zip(page_data, translations):
> > > > >         if 'translation' in item:
> > > > >             item['translation'] = translation
> > > > >         if 'rich_text' in item:
> > > > >             item['rich_text'] = ''
> > > > > # Write the updated data back to the .json file
> > > > > with open('yourfile.json', 'w', encoding='utf-8') as f:
> > > > >     json.dump(data, f, ensure_ascii=False, indent=4)
> > > > > ```
> > > > > 
> > > > > 
> > > > >     
> > > > >       
> > > > >     
> > > > > 
> > > > >       
> > > > >     
> > > > > 
> > > > >     
> > > > >   
> > > > > 我改了下，这样应该就行了
> > > > 
> > > > 
> > > > ![image](https://user-images.githubusercontent.com/30548000/238115057-71fcaae9-ff7d-4a4e-964b-7f188800134c.png) 开发者大佬亲自出手 解决了 这样就可以配合最开始导出 脚本 修改完后进行导入了
> > > 
> > > 
> > > 请问怎么弄的，我不懂代码，看不明白什么意思， 是改什么东西吗
> > > [BallonTranslator拖拽导入导出.zip](https://github.com/dmMaze/BallonsTranslator/files/13219352/BallonTranslator.zip)
> > 
> > 
> > 已经简化到 拖拽 就行了 下载这个zip包 有2个文件 一个导入一个导出 都是拖拽 不管是导入还是导出 都拖拽 JSON到 PY文件上 python 环境 还是要安装的
> 
> 可以再请问_汉化_的什么漫画吗，看起来萌萌的

这个问题就跟这个差不多
![image](https://github.com/dmMaze/BallonsTranslator/assets/30548000/9c280441-da51-4367-9d9c-a784952bd022)

**Comment by longfei796** [comment]
> > > > > > > 明白 翻译 位置 写的222 但是重新打开软件 之后 还是原来的___机翻___ 并不是瞎写的测试 文本
> > > > > > 
> > > > > > 
> > > > > > ```python
> > > > > > import json
> > > > > > 
> > > > > > # Open and load your json file
> > > > > > with open('yourfile.json', 'r', encoding='utf-8') as f:
> > > > > >     data = json.load(f)
> > > > > > 
> > > > > > # Open your .txt file
> > > > > > with open('translate.txt', 'r', encoding='utf-8') as f:
> > > > > >     lines = f.readlines()
> > > > > > 
> > > > > > page_name = None
> > > > > > translations = []
> > > > > > for line in lines:
> > > > > >     stripped_line = line.strip()
> > > > > >     # If the line is not empty
> > > > > >     if stripped_line:
> > > > > >         # If we're on the first line of a paragraph, this is the page name
> > > > > >         if page_name is None:
> > > > > >             page_name = stripped_line
> > > > > >         # Otherwise, this line is a translation
> > > > > >         else:
> > > > > >             translations.append(stripped_line)
> > > > > >     # If the line is empty, we're at the end of a paragraph
> > > > > >     else:
> > > > > >         # Update the 'translation' fields for this page
> > > > > >         if page_name is not None:
> > > > > >             page_data = data.get('pages', {}).get(page_name, [])
> > > > > >             for item, translation in zip(page_data, translations):
> > > > > >                 if 'translation' in item:
> > > > > >                     item['translation'] = translation
> > > > > >                 if 'rich_text' in item:
> > > > > >                     item['rich_text'] = ''
> > > > > >         # Reset for the next paragraph
> > > > > >         page_name = None
> > > > > >         translations = []
> > > > > > 
> > > > > > # Don't forget to update the last page
> > > > > > if page_name is not None:
> > > > > >     page_data = data.get('pages', {}).get(page_name, [])
> > > > > >     for item, translation in zip(page_data, translations):
> > > > > >         if 'translation' in item:
> > > > > >             item['translation'] = translation
> > > > > >         if 'rich_text' in item:
> > > > > >             item['rich_text'] = ''
> > > > > > # Write the updated data back to the .json file
> > > > > > with open('yourfile.json', 'w', encoding='utf-8') as f:
> > > > > >     json.dump(data, f, ensure_ascii=False, indent=4)
> > > > > > ```
> > > > > > 
> > > > > > 
> > > > > >     
> > > > > >       
> > > > > >     
> > > > > > 
> > > > > >       
> > > > > >     
> > > > > > 
> > > > > >     
> > > > > >   
> > > > > > 我改了下，这样应该就行了
> > > > > 
> > > > > 
> > > > > ![image](https://user-images.githubusercontent.com/30548000/238115057-71fcaae9-ff7d-4a4e-964b-7f188800134c.png) 开发者大佬亲自出手 解决了 这样就可以配合最开始导出 脚本 修改完后进行导入了
> > > > 
> > > > 
> > > > 请问怎么弄的，我不懂代码，看不明白什么意思， 是改什么东西吗
> > > > [BallonTranslator拖拽导入导出.zip](https://github.com/dmMaze/BallonsTranslator/files/13219352/BallonTranslator.zip)
> > > 
> > > 
> > > 已经简化到 拖拽 就行了 下载这个zip包 有2个文件 一个导入一个导出 都是拖拽 不管是导入还是导出 都拖拽 JSON到 PY文件上 python 环境 还是要安装的
> > 
> > 
> > 可以再请问_汉化_的什么漫画吗，看起来萌萌的
> 
> 这个问题就跟这个差不多 ![image](https://user-images.githubusercontent.com/30548000/279695851-9c280441-da51-4367-9d9c-a784952bd022.png)

记不清了是吗
知道了打扰您了，不好意思
