### ISSUE TITLE
使用疑问

### ISSUE THREAD

**Issue by sleeterly** [dmMaze/BallonsTranslator#142]
请问一下大佬，我运行的时候图片gif都检索不出来，这是为什么，安装的步骤不对吗
![image](https://user-images.githubusercontent.com/132740157/236609458-f3f63f92-2bd6-47a5-97ff-f668f14ef240.png)
![image](https://user-images.githubusercontent.com/132740157/236609471-076ac2f0-6f55-414e-85ea-6eddbb55dda6.png)

**Comment by dmMaze** [comment]
程序现在不读.gif

**Comment by sleeterly** [comment]
那是翻译不了吗，能翻译那些呀

**Comment by dmMaze** [comment]
> 那是翻译不了吗，能翻译那些呀

读图片, .jpg .png这些
