### ISSUE TITLE
Vertical output when translating to Korean

### ISSUE THREAD

**Issue by dnr111222** [dmMaze/BallonsTranslator#147]
Currently, when I translate Japanese manga into Korean, the text is displayed vertically, but is there any way to change it to be displayed horizontally like when translating into English?

Using core version

**Comment by dmMaze** [comment]
The text orientation will be setted to vertical if the source and target are CJK, there is no way to change it in the automated processing. Maybe I'll add a text-orientation decide-by-program/use global setting like other lettering options.

**Comment by dmMaze** [comment]
config panel -> lettering -> writing mode -> use global format, and set your global font format to horizontal (uncheck the T button
