### ISSUE TITLE
DEEPL翻譯的KEY??

### ISSUE THREAD

**Issue by leo751026** [dmMaze/BallonsTranslator#148]
DEEPL翻譯的KEY??

**Comment by bropines** [comment]
> DEEPL翻譯的KEY??

And what is wrong? Submit here if available
![image](https://github.com/dmMaze/BallonsTranslator/assets/57861007/996f61a0-d1bc-46be-b582-907d6df157b4)

If not, we can't give it to you. It costs money, at least in Russia it is very difficult to get it

**Comment by bropines** [comment]
> > > DEEPL翻譯的KEY？？
> > 
> > 
> > And what is wrong? Submit here if available (where it's blurry) ![image](https://user-images.githubusercontent.com/57861007/239740003-996f61a0-d1bc-46be-b582-907d6df157b4.png)
> > If not, we can't give it to you. It costs money, at least in Russia it is very difficult to get it
> 
> How to buy??

Judging by your first post, you live in China, I think either on the sites selling all sorts of content (if any), or make your own free api in the profile. Russia is not on this list, nor is China. See if anyone from your country is selling keys

**Comment by aqssxlzc** [comment]
> DEEPL翻譯的KEY??
这是你需要向deepL付费才能用的
