### ISSUE TITLE
每次都会爆储存

### ISSUE THREAD

**Issue by waterTG** [dmMaze/BallonsTranslator#149]
![image](https://github.com/dmMaze/BallonsTranslator/assets/79299882/2e42dabd-9b6d-4e6a-ba34-a066735dc633)
跑不到两张图就寄，是我电脑太菜了吗

**Comment by bropines** [comment]
> 跑不到两张图就寄，是我电脑太菜了吗

您可以将您的 PC 规格发送给我们。还有更详细的你想做什么

**Comment by waterTG** [comment]
> 

核显轻薄本，就是想跑漫画机翻。似乎很多有关深度学习的代码都容易出现这种问题

**Comment by waterTG** [comment]
> 

核显轻薄本，就是想跑漫画机翻。似乎很多有关深度学习的代码都容易出现这种问题

**Comment by waterTG** [comment]
> > 跑不到两张图就寄，是我电脑太菜了吗
> 
> 您可以将您的 PC 规格发送给我们。还有更详细的你想做什么
核显轻薄本，就是想跑漫画机翻。似乎很多有关深度学习的代码都容易出现这种问题

**Comment by dmMaze** [comment]
没独显cpu跑的时候炸了，试下调低inpaint size，或者用别的修复方法

**Comment by waterTG** [comment]
> 没独显cpu跑的时候炸了，试下调低inpaint size，或者用别的修复方法

所以inpaint size在哪个脚本代码里面，界面中只有一个chunk_size

**Comment by dmMaze** [comment]
> > 没独显cpu跑的时候炸了，试下调低inpaint size，或者用别的修复方法
> 
> 所以inpaint size在哪个脚本代码里面，界面中只有一个chunk_size

inpaint size只有aot和lamampe有这个参数
看你截图F.conv_transpose好像就是跑detector的时候炸了...你电脑内存多大, 小于2G就不用试了, 内存小试试清下后台啥的

**Comment by waterTG** [comment]
> > > 没独显cpu跑的时候炸了，试下调低inpaint size，或者用别的修复方法
> > 
> > 
> > 所以inpaint size在哪个脚本代码里面，界面中只有一个chunk_size
> 
> inpaint size只有aot和lamampe有这个参数 看你截图F.conv_transpose好像就是跑detector的时候炸了...你电脑内存多大, 小于2G就不用试了, 内存小试试清下后台啥的

8g，这个跟后台感觉关系不大，调了虚拟内存略有好转
