### ISSUE TITLE
关于deepl翻译

### ISSUE THREAD

**Issue by Yezhoubing** [dmMaze/BallonsTranslator#153]
有没有考虑过不用deepl的key，而是用其他方法，国内还是不好弄这个key

**Comment by pein0saga** [comment]
不是还有其他翻译选项吗？总不能因为一部分人用不了就删除这个翻译器接口吧？

`如需添加新的翻译器请参考[加别的翻译器](https://github.com/dmMaze/BallonsTranslator/blob/master/doc/%E5%8A%A0%E5%88%AB%E7%9A%84%E7%BF%BB%E8%AF%91%E5%99%A8.md), 本程序添加新翻译器只需要继承基类实现两个接口即可不需要理会代码其他部分, 欢迎大佬提pr`
