### ISSUE TITLE
期待添加GPT API

### ISSUE THREAD

**Issue by fanxingyuye** [dmMaze/BallonsTranslator#154]
整体可用性很强了，目前主要受限于翻译器。
gpt翻译可以理解上下语境，效果远超其他翻译。
期待大佬更新。

**Comment by ikazoa** [comment]
同求
https://github.com/dmMaze/BallonsTranslator/blob/master/doc/%E5%8A%A0%E5%88%AB%E7%9A%84%E7%BF%BB%E8%AF%91%E5%99%A8.md

**Comment by hq5566** [comment]
很希望增加OPENAI API翻译

**Comment by dmMaze** [comment]
dev branch 已支持chat gpt

**Comment by hq5566** [comment]
谢谢告知！我是Win11，先在GoogleDrive下了Core，然后用的是Github上的发布版去覆盖它，就可以成功运行了，只是没有OPENAI。

已从Github上下了刚刚更新的BallonsTranslator-dev.zip，但是不知道如何安装。

还请更新发布版。谢谢！

**Comment by dmMaze** [comment]
> 谢谢告知！我是Win11，先在GoogleDrive下了Core，然后用的是Github上的发布版去覆盖它，就可以成功运行了，只是没有OPENAI。
> 
> 已从Github上下了刚刚更新的BallonsTranslator-dev.zip，但是不知道如何安装。
> 
> 还请更新发布版。谢谢！

暂时不整发布版，可以参考https://github.com/dmMaze/BallonsTranslator/issues/160#issuecomment-1602064296 怎么跑dev

**Comment by hq5566** [comment]
谢谢告知。我现在在手机上，无法在电脑上运用你的方法。会按你说的来，学用Dev版。

想来我在安装Win11发行版时，下了多个G的文件，解压覆盖应用发行版更新后，发现Ballon文件夹已超过5个G。我此前已在本地windows系统中安装部署了CUDA和Whisper GPU加速命令行版。还好以前的DOS基础还在。

看到有网友留言关于OPENAI翻译，好像还不完善，我希望大家都能用上。

发行版Releases是我上GitHub网站时，总是最先关注的地方。

祝此app越来越好用，具有全世界最强的翻译漫画功能，我希望利用它来看uncle gladstone ducktales 1987，那个年代的漫画真是值得一读，没有引进版。

谢谢大家！谢谢dmMaze！

**Comment by hq5566** [comment]
已成功使用OpenAI API翻译漫画。效果很好。谢谢！和（可以参考https://github.com/dmMaze/BallonsTranslator/issues/160#issuecomment-1602064296 怎么跑dev）里面一位网友说的一样，我是用Core整合版下的Data目录进行覆盖。安装完成后BallonsTranslator目录是6.55G
