### ISSUE TITLE
Additional feature request: Current page only 

### ISSUE THREAD

**Issue by dnr111222** [dmMaze/BallonsTranslator#156]
Currently, the entire project is automatically translated when run, but it would be nice if it could be modified to work for the current page as well.

**Comment by tak2hu** [comment]
You can do this with the buttons(?) on the bottom. You can toggle them.

![AEB4EBBC-DFE6-4ECF-8A4C-C2D8ECC5DA54](https://github.com/dmMaze/BallonsTranslator/assets/73519753/d2d9dc63-5ee3-4092-ab6e-e46fe309fe53)
