### ISSUE TITLE
運行到一半就跳掉了

### ISSUE THREAD

**Issue by ddab03467** [dmMaze/BallonsTranslator#157]
想問一下按run運行一下程式就會自行關閉是怎麼回事?

**Comment by bropines** [comment]
> 想問一下按run運行一下程式就會自行關閉是怎麼回事?

Exe or python source version?

**Comment by aqssxlzc** [comment]
看一下程序输出，是不是存在cuda内存分配不足，我怀疑图片过大的时候缩放翻译存在bug
一般图片小一点的时候就没有问题

Sergey Pinus ***@***.***> 于2023年6月16日周五 04:54写道：
