### ISSUE TITLE
思源宋体排版有bug

### ISSUE THREAD

**Issue by wjz2001** [dmMaze/BallonsTranslator#160]
如图画圈的地方，字是歪歪扭扭的，根本不成一行。解决方案是每一个字中间都空一格，这样就对正了
https://s1.ax1x.com/2023/06/21/pCGy6uq.png

**Comment by dmMaze** [comment]
我也用这个字体复现了，只是只有特定字符会排歪，比如"发明家产生了感情"只有感这个字是歪的，请问你也是这样吗

**Comment by dmMaze** [comment]
dev  branch最新的commit 尝试修复了这个bug(和#158), 这个版本及以后都不再编译成exe发布而是直接跑源码类似sdwebui, 因为编译工具对pyqt线程模块的支持问题，这样也更方便更新
所以如果你已经是从源码运行了可以先切到这个branch试试，否则不嫌麻烦的话我可以简单介绍一下怎么运行这个版本

**Comment by wjz2001** [comment]
> dev branch最新的commit 尝试修复了这个bug(和#158), 这个版本及以后都不再编译成exe发布而是直接跑源码类似sdwebui, 因为编译工具对pyqt线程模块的支持有问题，这样也更方便更新 所以如果你已经是从源码运行了可以先切到这个branch试试，否则不嫌麻烦的话我可以简单介绍一下怎么运行这个版本

辛苦了。我这边运行源码的时候配置了半天也没成功，问题解决完一个又来一个，所以暂时是无法测试了。

**Comment by dmMaze** [comment]
感谢尝试，如果你还想试试的话可以按下面步骤来
1. 安装git, 克隆仓库
git clone https://github.com/dmMaze/BallonsTranslator
cd BallonsTranslator
git switch dev

2. 配置python3.10环境安装依赖库，或者从https://mega.nz/folder/gmhmACoD#dkVlZ2nphOkU5-2ACb5dKw 下载完整的py环境包ballontrans_pylibs_win.7z，解压到BallonsTranslator目录下(ballontrans_pylibs_win这个文件夹和launch_win.bat同级)

3. 将之前发布版的data文件复制到BallonsTranslator目录下

4. 双击launch_win.bat运行，如果出现任何问题可以把命令行黑框截图贴上来

**Comment by bropines** [comment]
> 感谢尝试，如果你还想试试的话可以按下面步骤来
> 
> 1. 安装git, 克隆仓库
>    git clone https://github.com/dmMaze/BallonsTranslator
>    cd BallonsTranslator
>    git switch dev
> 2. 配置python3.10环境安装依赖库，或者从https://mega.nz/folder/gmhmACoD#dkVlZ2nphOkU5-2ACb5dKw 下载完整的py环境包ballontrans_pylibs_win.7z，解压到BallonsTranslator目录下(ballontrans_pylibs_win这个文件夹和launch_win.bat同级)
> 3. 将之前发布版的data文件夹复制到BallonsTranslator目录下
> 4. 双击launch_win.bat运行，如果出现任何问题可以把命令行黑框截图贴上来

Maybe i create PyEnv Venv autoinstall script? I think it will be easier, plus I will add a choice of the main branch and a way to change the branch, in which case. Like SD but with its own downloadable python exe.

**Comment by dmMaze** [comment]
> > 感谢尝试，如果你还想试试的话可以按下面步骤来
> > 
> > 1. 安装git, 克隆仓库
> >    git clone https://github.com/dmMaze/BallonsTranslator
> >    cd BallonsTranslator
> >    git switch dev
> > 2. 配置python3.10环境安装依赖库，或者从https://mega.nz/folder/gmhmACoD#dkVlZ2nphOkU5-2ACb5dKw 下载完整的py环境包ballontrans_pylibs_win.7z，解压到BallonsTranslator目录下(ballontrans_pylibs_win这个文件夹和launch_win.bat同级)
> > 3. 将之前发布版的data文件夹复制到BallonsTranslator目录下
> > 4. 双击launch_win.bat运行，如果出现任何问题可以把命令行黑框截图贴上来
> 
> Maybe i create PyEnv Venv autoinstall script? I think it will be easier, plus I will add a choice of the main branch and a way to change the branch, in which case. Like SD but with its own downloadable python exe.

It is a headache for users in mainland China to use these autoinstall scripts because of the GFW thus I would provide these archives contain models and py libraries ( not sure whether MEGA is blocked though
It would be appreciated if you could make any further contributions to dev branch

**Comment by dmMaze** [comment]
> 

<img width="396" alt="image" src="https://github.com/dmMaze/BallonsTranslator/assets/51270320/f054545b-d46f-4a59-8a10-dd93120375ff">

ballontrans_pylibs_win里面的numpy版本是1.24.1
那个打包发布版是1.22.2, 它覆盖了ballontrans_pylibs_win里面的库
所以不要解压覆盖到原来那个Ballonstranslator

**Comment by hq5566** [comment]
已成功使用OpenAI API翻译漫画。效果很好。谢谢！和上面的网友说的一样，我是用Core整合版下的Data目录进行覆盖。安装完成后BallonsTranslator目录是6.55G

**Comment by GHOST2023li** [comment]
> 謝謝嘗試，如果您還想嘗試的話可以按下面步驟來
> 
> 1. 安裝git，克隆倉庫
>    git clone https://github.com/dmMaze/BallonsTranslator 
>    cd BallonsTranslator 
>    git switch dev
> 2. 配置python3.10環境安裝依賴庫，或者從https://mega.nz/folder/gmhmACoD#dkVlZ2nphOkU5-2ACb5dKw下載完整的py環境包ballontrans_pylibs_win.7z，解壓到BallonsTranslator目錄下(ballontrans_pylibs_win這個文件夾和launch_win.bat同級)
> 3. 將之前發布版本的數據文件夾複製到BallonsTranslator目錄下
> 4. 側面launch_win.bat運行，如果出現任何問題可以把命令行黑框截圖貼上來

第2點解壓到BallonsTranslator目錄下 這個(BallonsTranslator)是哪來的檔案夾? 我裡面沒有launch_win.bat這個文件

**Comment by hq5566** [comment]
只要你执行了git clone，Ballonstranslator项目会被转移到本地 （你的电脑上）。对磁盘目录结构不太了解的，可以下载安装一个Everything （全盘搜索软件），安好后键入Ballonstranslator即可找到，再点击进入。

On Jul 18, 2023, at 10:24 AM, GHOST2023li ***@***.***> wrote:

﻿

謝謝嘗試，如果您還想嘗試的話可以按下面步驟來

  1.  安裝git，克隆倉庫
git clone https://github.com/dmMaze/BallonsTranslator
cd BallonsTranslator
git switch dev
  2.  配置python3.10環境安裝依賴庫，或者從https://mega.nz/folder/gmhmACoD#dkVlZ2nphOkU5-2ACb5dKw下載完整的py環境包ballontrans_pylibs_win.7z，解壓到BallonsTranslator目錄下(ballontrans_pylibs_win這個文件夾和launch_win.bat同級)<https://mega.nz/folder/gmhmACoD#dkVlZ2nphOkU5-2ACb5dKw%E4%B8%8B%E8%BC%89%E5%AE%8C%E6%95%B4%E7%9A%84py%E7%92%B0%E5%A2%83%E5%8C%85ballontrans_pylibs_win.7z%EF%BC%8C%E8%A7%A3%E5%A3%93%E5%88%B0BallonsTranslator%E7%9B%AE%E9%8C%84%E4%B8%8B(ballontrans_pylibs_win%E9%80%99%E5%80%8B%E6%96%87%E4%BB%B6%E5%A4%BE%E5%92%8Claunch_win.bat%E5%90%8C%E7%B4%9A)>
  3.  將之前發布版本的數據文件夾複製到BallonsTranslator目錄下
  4.  側面launch_win.bat運行，如果出現任何問題可以把命令行黑框截圖貼上來

第2點解壓到BallonsTranslator目錄下 這個(BallonsTranslator)是哪來的檔案夾? 我裡面沒有launch_win.bat這個文件

**Comment by j6qup3** [comment]
在新目錄 git clone -b dev https://github.com/dmMaze/BallonsTranslator.git 並下載 pylib 解壓縮後
運行 bat 出現  `No such file or directory: 'data/models/comictextdetector.pt'` 等好幾個錯誤，後面把 Release 版的 data/models 複製過來這錯誤沒有出現，但 Run 時出現以下錯誤
```
Traceback (most recent call last):
  File "D:\AI\dev\BallonsTranslator\ui\module_manager.py", line 420, in run
    self.job()
  File "D:\AI\dev\BallonsTranslator\ui\module_manager.py", line 352, in _imgtrans_pipeline
    mask, blk_list = self.textdetector.detect(img)
AttributeError: 'NoneType' object has no attribute 'detect'
```
是還缺什麼檔案嗎，還是過程有誤？

**Comment by dmMaze** [comment]
@j6qup3 你需要把旧的data整个复制到新的文件夹下，见上面教程第三步
另外等模型加载完再点RUN，如下图所示XXX SET TO XXX
<img width="621" alt="image" src="https://github.com/dmMaze/BallonsTranslator/assets/51270320/1a820f90-546a-47fc-88de-8c44e054d854">

**Comment by j6qup3** [comment]
好的
