### ISSUE TITLE
最近用智能修图用失败了，扣的非常杂乱

### ISSUE THREAD

**Issue by longfei796** [dmMaze/BallonsTranslator#162]
![mmexport1687790444113](https://github.com/dmMaze/BallonsTranslator/assets/117554192/22e0c945-8cc8-481d-a129-b3f421da0268)
![mmexport1687790427141](https://github.com/dmMaze/BallonsTranslator/assets/117554192/05557788-dd55-4264-a1d1-80f7cdd05dd6)
这是用aot，对话框修的乱七八糟
用其他的更糟糕，对话框大面积黑色杂块
有无解决办法，一个以前的一个现在的，怎么么会这样

**Comment by dmMaze** [comment]
<img width="283" alt="image" src="https://github.com/dmMaze/BallonsTranslator/assets/51270320/64da710b-10c5-4655-97fe-32d231d3da1a">
那个矩形工具第一个滑条拉小，这个是影响全局的
