### ISSUE TITLE
NMS time limit 10.0s exceeded

### ISSUE THREAD

**Issue by gsxgmpkt9020** [dmMaze/BallonsTranslator#164]
有没有解释和优化方法？

文档里貌似没有对这个警告的说明

**Comment by dmMaze** [comment]
检测后处理炸了，可能是文字框太多，方便的话传下原图我复现一下

**Comment by dmMaze** [comment]
> > 检测后处理炸了，可能是文字框太多，方便的话传下原图我复现一下
> 
> 请问NMS是什么模块的缩写? 我其他遇到的bug不知道是否是这个问题间接产生的后果

源码里搜torchvision.ops.nms, 这个是那个检测模块的后处理，不会影响界面交互什么的
可以二分法选出那张warning的图...

**Comment by dmMaze** [comment]
> > > > 检测后处理炸了，可能是文字框太多，方便的话传下原图我复现一下
> > > 
> > > 
> > > 请问NMS是什么模块的缩写? 我其他遇到的bug不知道是否是这个问题间接产生的后果
> > 
> > 
> > 源码里搜torchvision.ops.nms, 这个是那个检测模块的后处理，不会影响界面交互什么的 可以二分法选出那张warning的图...
> 
> log后面一堆音标不知道什么意思
> 
> `[INFO ] dl_manager:on_finish_settranslator:742 - Translator set to Deepl [INFO ] dl_manager:on_finish_settranslator:742 - Translator set to caiyun WARNING: NMS time limit 10.0s exceeded WARNING: NMS time limit 10.0s exceeded WARNING: NMS time limit 10.0s exceeded WARNING: NMS time limit 10.0s exceeded a ai an ang ao a in b ao c ai d e ei en eng er e en f eng g ang h ch i an j uai ing k iang uang l ian m iao n uo o ou o ie p iu q uan van r ong iong s ue ve t sh u zh ui v ei w ia ua x un vn y ou z
> 
> QTextCursor::setPosition: Position '5' out of range QTextCursor::setPosition: Position '6' out of range DirectWrite: CreateFontFaceFromHDC() failed (Indicates an error in an input file such as a font file.) for QFontDef(Family="Fixedsys", pointsize=16, pixelsize=20, styleHint=5, weight=400, stretch=100, hintingPreference=0) LOGFONT("Fixedsys", lfWidth=0, lfHeight=-20) dpi=144 DirectWrite: CreateFontFaceFromHDC() failed (Indicates an error in an input file such as a font file.) for QFontDef(Family="Fixedsys", pointsize=16, pixelsize=20, styleHint=5, weight=400, stretch=100, hintingPreference=0) LOGFONT("Fixedsys", lfWidth=0, lfHeight=-20) dpi=144 DirectWrite: CreateFontFaceFromHDC() failed (Indicates an error in an input file such as a font file.) for QFontDef(Family="MS Sans Serif", pointsize=16, pixelsize=20, styleHint=5, weight=400, stretch=100, hintingPreference=0) LOGFONT("MS Sans Serif", lfWidth=0, lfHeight=-20) dpi=144 DirectWrite: CreateFontFaceFromHDC() failed (Indicates an error in an input file such as a font file.) for QFontDef(Family="MS Serif", pointsize=16, pixelsize=21, styleHint=5, weight=400, stretch=100, hintingPreference=0) LOGFONT("MS Serif", lfWidth=0, lfHeight=-21) dpi=144 DirectWrite: CreateFontFaceFromHDC() failed (Indicates an error in an input file such as a font file.) for QFontDef(Family="Small Fonts", pointsize=16, pixelsize=13, styleHint=5, weight=400, stretch=100, hintingPreference=0) LOGFONT("Small Fonts", lfWidth=0, lfHeight=-13) dpi=144 DirectWrite: CreateFontFaceFromHDC() failed (Indicates an error in an input file such as a font file.) for QFontDef(Family="System", pointsize=16, pixelsize=20, styleHint=5, weight=400, stretch=100, hintingPreference=0) LOGFONT("System", lfWidth=0, lfHeight=-20) dpi=144 DirectWrite: CreateFontFaceFromHDC() failed (Indicates an error in an input file such as a font file.) for QFontDef(Family="Terminal", pointsize=16, pixelsize=20, styleHint=5, weight=400, stretch=100, hintingPreference=0) LOGFONT("Terminal", lfWidth=0, lfHeight=-20) dpi=144`

我也看不懂，不方便直接贴github的话可以找个第三方图床或者网盘啥的传下链接
