### ISSUE TITLE
手动区域OCR没有结果输出

### ISSUE THREAD

**Issue by gsxgmpkt9020** [dmMaze/BallonsTranslator#165]
本来自动RUN OCR一切都很好。但是有个框误删了一个，后来手动OCR怎么都添加不上去。

inpaint都没问题
<img width="354" alt="Snipaste_2023-06-29_15-48-55" src="https://github.com/dmMaze/BallonsTranslator/assets/2074641/72487d5e-7708-4543-b08d-3ca149776551">
<img width="354" alt="Snipaste_2023-06-29_15-48-43" src="https://github.com/dmMaze/BallonsTranslator/assets/2074641/0b5ca27a-4d0c-457a-8a4c-36b5d0a668be">

本来两个气泡是分开自动RUN OCR的，第二个的自动RUN OCR结果一直保留着。但是第一个的框怎么都OCR不出来

<img width="432" alt="Snipaste_2023-06-29_16-00-06" src="https://github.com/dmMaze/BallonsTranslator/assets/2074641/e977a6aa-f0a7-4394-b04e-2e70c438a1c3">

**Comment by dmMaze** [comment]
看不懂啊, 你的意思是一直OCR不出文字内容还是什么bug
如果是OCR不出文字内容那大概不是bug, 是OCR模型的问题:
如果你OCR模型选的是mit_xxx, 它只能逐行识别，所以你拉的框得贴合单行文字，而且对竖排文字框得改成竖排
或者你可以把OCR模型换成MangaOCR, 它能整块识别日语

**Comment by BinChen68** [comment]
> > > 看不懂啊, 你的意思是一直OCR不出文字内容还是什么bug 如果是OCR不出文字内容那大概不是bug, 是OCR模型的问题: 如果你OCR模型选的是mit_xxx, 它只能逐行识别，所以你拉的框得贴合单行文字，而且对竖排文字框得改成竖排 或者你可以把OCR模型换成MangaOCR, 它能整块识别日语
> > 
> > 
> > OCR模型是不是只针对手动OCR？因为我自动RUN的时候OCR 没问题。
> > 建议mit_xxx 、MangaOCR 选项旁边加下备注，文档上单行多行没有备注
> > ```
> > mit_32px模型来自manga-image-translator, 支持日英汉识别和颜色提取
> > mit48px_ctc模型来自manga-image-translator, 支持日英汉韩语识别和颜色提取
> > [manga_ocr](https://github.com/kha-white/manga-ocr)来自[kha-white](https://github.com/kha-white), 支持日语识别, 注意选用该模型程序不会提取颜色
> > ```
> 
> 本来打算炼个更robust的识别模型就不用管这些了不过一直鸽着

嗨，现在有除了mit_ocr以外，更好的能同时识别颜色的ocr模型吗？
