### ISSUE TITLE
QTextCursor::setPosition: Position '15' out of range 在右侧程序框编辑区粘贴中文文字的时候，漫画区域的框有时候会被清空只留下最后的标点。

### ISSUE THREAD

**Issue by gsxgmpkt9020** [dmMaze/BallonsTranslator#166]
<img width="291" alt="Snipaste_2023-06-29_16-03-23" src="https://github.com/dmMaze/BallonsTranslator/assets/2074641/80f953dc-d483-4e7d-a561-72eed2c23697">

在右侧程序框编辑粘贴中文文字替换原有文字的时候，漫画区域的框有时候会被清空只留下最后的标点。这时候右侧程序框编辑区是有完整文字的

然后切换页面在切回以后，发现右侧程序框编辑区也只剩下了一个标点

**Comment by dmMaze** [comment]
需要给下输入历史(输入了什么内容删除了什么内容造成了这个bug)让我复现

**Comment by dmMaze** [comment]
> > 需要给下输入历史(输入了什么内容删除了什么内容造成了这个bug)让我复现，录个屏也行
> 
> 微软雅黑,竖排文字.就是健全的普通的中文内容.概率出现.

那我还是需要能稳定复现这个 bug的步骤描述啊... 
1...2...3...这样文字描述或者录个屏都行
另外你是跑的什么版本...如果不是dev branch麻烦切一下(参考#160)

**Comment by dmMaze** [comment]
> > > > 需要给下输入历史(输入了什么内容删除了什么内容造成了这个bug)让我复现，录个屏也行
> > > 
> > > 
> > > 微软雅黑,竖排文字.就是健全的普通的中文内容.概率出现.
> > 
> > 
> > 那我还是需要能稳定复现这个 bug的步骤描述啊... 1...2...3...这样文字描述或者录个屏都行 另外你是跑的什么版本...如果不是dev branch麻烦切一下(参考#160)
> 
> DEV好像是下载了就能直接bat运行用的吗？能覆盖安装吗？我先翻译完了再说

对，不过你可能得先了解下git基本用法, 得先用git克隆这个仓库切到dev啥的, 没有什么覆盖安装，你把之前的data\config\config.json贴到这个dev branch下面的config文件夹里就能保留原来程序里的设置

**Comment by dmMaze** [comment]
> > 
> 
> * 都是没有torch文件夹的，还是要覆盖安装之前的core的吧？虽然我不是N卡不用cuda
> * 我又不PR，应该只要zip下载DEV分支就行了
> * 需要提前单独把配置文件config备份出来。
> * workspace状态的相关文件是不是存在漫画目录里面的那个imgtrans_r.json ,升级到DEV也能恢复上次的工作状态？是完全向下兼容的吗？

不用覆盖(直接覆盖也不行)，照https://github.com/dmMaze/BallonsTranslator/issues/160#issuecomment-1602064296做就行了，git clone下来就可以git pull来更新了更方便吧，兼容以前的项目文件imgtrans_xxx.json

**Comment by dmMaze** [comment]
这个bug是右键菜单的，快捷键粘贴就没事，[d2ca02d](https://github.com/dmMaze/BallonsTranslator/commit/d2ca02d38c984a38b218fe2d51ef42d974e8905c) 修好了右键菜单
