### ISSUE TITLE
“右键拖拽手动增加选取框” 的开启条件

### ISSUE THREAD

**Issue by gsxgmpkt9020** [dmMaze/BallonsTranslator#168]
开启条件是“点下右下角那个框推出创建文本框模式”

<del> 我用master 发布版的时候摸索出来右键拖拽选取是可以增加选取框的（以便手动OCR）
现在用了DEV分支反而没有这个功能了（已经关闭沙拉查词），实际上就是只能弹出右键菜单而已（临时解决方案只能是复制借用其他的框）</del>

**Comment by dmMaze** [comment]
![sel](https://github.com/dmMaze/BallonsTranslator/assets/51270320/0edb8b06-e1bc-493a-8924-2e8e9d9bb455)
你是说这个还是啥
dev可以啊，要点下右下角那个框推出创建文本框模式...
