### ISSUE TITLE
普通搜索能搜到,全局搜索搜不到

### ISSUE THREAD

**Issue by gsxgmpkt9020** [dmMaze/BallonsTranslator#169]
普通搜索能搜到,全局搜索搜不到

<img width="165" alt="Snipaste_2023-07-02_16-33-04" src="https://github.com/dmMaze/BallonsTranslator/assets/2074641/37aa7f41-6863-4afa-b7d8-fad5e7a47514">
<img width="223" alt="Snipaste_2023-07-02_16-32-50" src="https://github.com/dmMaze/BallonsTranslator/assets/2074641/4c05adfb-2e20-4140-80a6-d60cf24b23c1">
<img width="268" alt="Snipaste_2023-07-02_16-32-17" src="https://github.com/dmMaze/BallonsTranslator/assets/2074641/17eb54b4-38f0-48d4-8f7c-e15dc302dbc4">

**Comment by dmMaze** [comment]
全局搜索要敲一下空格
