### ISSUE TITLE
Not working Translate popup menu on right click

### ISSUE THREAD

**Issue by bropines** [dmMaze/BallonsTranslator#174]
https://github.com/dmMaze/BallonsTranslator/assets/57861007/02317c8f-11f8-4416-a55a-75fda5d64543

Python 3.10.6
py version:  3.10.6 (tags/v3.10.6:9c7b4bd, Aug  1 2022, 21:53:49) [MSC v.1932 64 bit (AMD64)]
py executable:  D:\AI\BallonsTranslator\venv\Scripts\python.exe
version: 1.4.0
branch: dev
Commit hash: c3f81c3d82296698ae418442a07e66f9b31494ed

**Comment by bropines** [comment]
There is also a bug when you translate using GPT and change the page, when you return to the previous one, the changes are not saved

**Comment by dmMaze** [comment]
> python_AaE0Bd9dGj.mp4 
> Python 3.10.6 py version: 3.10.6 (tags/v3.10.6:9c7b4bd, Aug 1 2022, 21:53:49) [MSC v.1932 64 bit (AMD64)] py executable: D:\AI\BallonsTranslator\venv\Scripts\python.exe version: 1.4.0 branch: dev Commit hash: [c3f81c3](https://github.com/dmMaze/BallonsTranslator/commit/c3f81c3d82296698ae418442a07e66f9b31494ed)

fixed https://github.com/dmMaze/BallonsTranslator/commit/70fa2c1c36dfa472f76bef71528560101beec6f4



> There is also a bug when you translate using GPT and change the page, when you return to the previous one, the changes are not saved

Did chatgpt finish before you turn to another page? If not, the translation thread will be terminated once you turn the page, thus the translations are not saved

**Comment by bropines** [comment]
> > python_AaE0Bd9dGj.mp4
> > Python 3.10.6 py version: 3.10.6 (tags/v3.10.6:9c7b4bd, Aug 1 2022, 21:53:49) [MSC v.1932 64 bit (AMD64)] py executable: D:\AI\BallonsTranslator\venv\Scripts\python.exe version: 1.4.0 branch: dev Commit hash: [c3f81c3](https://github.com/dmMaze/BallonsTranslator/commit/c3f81c3d82296698ae418442a07e66f9b31494ed)
> 
> fixed [70fa2c1](https://github.com/dmMaze/BallonsTranslator/commit/70fa2c1c36dfa472f76bef71528560101beec6f4)
> 
> > There is also a bug when you translate using GPT and change the page, when you return to the previous one, the changes are not saved
> 
> Did chatgpt finish before you turn to another page? If not, the translation thread will be terminated once you turn the page, thus the translations are not saved

he just finished the translation, and so far I haven't changed it (he just translated) then when you change the page, it resets the changes. but if I write a space in any block, it saves the change

**Comment by dmMaze** [comment]
> > > python_AaE0Bd9dGj.mp4
> > > Python 3.10.6 py version: 3.10.6 (tags/v3.10.6:9c7b4bd, Aug 1 2022, 21:53:49) [MSC v.1932 64 bit (AMD64)] py executable: D:\AI\BallonsTranslator\venv\Scripts\python.exe version: 1.4.0 branch: dev Commit hash: [c3f81c3](https://github.com/dmMaze/BallonsTranslator/commit/c3f81c3d82296698ae418442a07e66f9b31494ed)
> > 
> > 
> > fixed [70fa2c1](https://github.com/dmMaze/BallonsTranslator/commit/70fa2c1c36dfa472f76bef71528560101beec6f4)
> > > There is also a bug when you translate using GPT and change the page, when you return to the previous one, the changes are not saved
> > 
> > 
> > Did chatgpt finish before you turn to another page? If not, the translation thread will be terminated once you turn the page, thus the translations are not saved
> 
> If there was a translation (any) on the page, then when chatgpt finishes its work and you change the page, it returns all the changes. If there was no translation, then it is saved. Also, if you slightly change the translation of ChatGPT, then the translation is saved (any space in the block saves everything).
> 
>  bug.video-converter.com.mp4

should be fixed by add378adb95bf908fcac8b0f6cbef64f66cca85a
