### ISSUE TITLE
Make a WebUI or other service for the colab via API

### ISSUE THREAD

**Issue by bropines** [dmMaze/BallonsTranslator#177]
There is an idea to create a version for api access with some web framework. 
As an example in python via: [Reflex](https://github.com/pynecone-io/reflex) or gradio(but he's a retarded piece of garbage)

**Comment by dhana-exe** [comment]
i really sure on github we had some like this
similar to ballons translator but for more than 1 people
but the feature isn't as good as BT now....

i forget the name let me search it again soon
