### ISSUE TITLE
使用OpenAi API漫画翻译经验分享

### ISSUE THREAD

**Issue by hq5566** [dmMaze/BallonsTranslator#178]
想来我在安装Win11发行版时，下了多个G的文件，解压覆盖应用发行版更新后，发现Ballon文件夹已超过5个G

按照作者的说明，使用DEV版：https://github.com/dmMaze/BallonsTranslator/issues/154
https://github.com/dmMaze/BallonsTranslator/issues/160#issuecomment-1602064296

已成功使用OpenAI API翻译漫画。效果很好。谢谢！和（https://github.com/dmMaze/BallonsTranslator/issues/160#issuecomment-1602064296）里面一位网友说的一样，我是用Core整合版下的Data目录进行覆盖。安装覆盖后最终BallonsTranslator目录的大小是6.55G

翻译uncle gladstone ducktales 1987漫画时，我不得不更改setting里面的OCR为“32”，实现成功翻译。可读性已经很可以了。

我查了发现此漫画仍有版权，无法分享。因为可以阅读一直想读的漫画，内心喜悦！以后甚至可以翻译各种外刊：Time， Fortune，WSJ

谢谢APP作者的无私分享。祝一切顺利，万事如意！

**Comment by GHOST2023li** [comment]
可否給個詳細步驟，看的不是很懂 ， 我的資料夾沒有這個文件launch_win.bat

**Comment by hq5566** [comment]
抱歉，我暂时没有时间写详细步骤。现在的安装方法好像下载量有点大。

记得我用了windows带的Powershell， 执行git clone那步（将github上的项目通过命令行转移到本地），就会有launch_win那个文件。

如作者说的：

1.（安装git, 克隆仓库）
（打开powershell，命令行执行：）
git clone https://github.com/dmMaze/BallonsTranslator
cd BallonsTranslator
git switch dev

2.（配置python3.10环境安装依赖库，或者）从https://mega.nz/folder/gmhmACoD#dkVlZ2nphOkU5-2ACb5dKw 下载完整的py环境包ballontrans_pylibs_win.7z，解压到BallonsTranslator目录下(ballontrans_pylibs_win这个文件夹和launch_win.bat同级)

3. 将之前发布版的data文件夹复制到BallonsTranslator目录下

4. 双击launch_win.bat运行.

请多尝试，你一定会成功！

**Comment by young-liuos** [comment]
> 抱歉，我暂时没有时间写详细步骤。现在的安装方法好像下载量有点大。
> 
> 记得我用了windows带的Powershell， 执行git clone那步（将github上的项目通过命令行转移到本地），就会有launch_win那个文件。
> 
> 如作者说的：
> 
> 1.（安装git, 克隆仓库） （打开powershell，命令行执行：） git clone https://github.com/dmMaze/BallonsTranslator cd BallonsTranslator git switch dev
> 
> 2.（配置python3.10环境安装依赖库，或者）从https://mega.nz/folder/gmhmACoD#dkVlZ2nphOkU5-2ACb5dKw 下载完整的py环境包ballontrans_pylibs_win.7z，解压到BallonsTranslator目录下(ballontrans_pylibs_win这个文件夹和launch_win.bat同级)
> 
> 3. 将之前发布版的data文件夹复制到BallonsTranslator目录下
> 4. 双击launch_win.bat运行.
> 
> 请多尝试，你一定会成功！

可以用国内网盘发一下git clone 下来的文件吗？ 感谢

**Comment by hq5566** [comment]
很想帮你。但我的上传速度不到1M，几个G的上传基本上不现实。下Mega Drive的经验是：我当时是将文件转存到自己的mega盘，再用Mega客户端进行下载。下载过程中速度经常为零，不过还好完成了下载。你问问其他网友看有没有下好了的，请他们分享一下。其实我有句话想跟大家分享：周末时间宝贵，好好休息，多陪陪家人。自从我上次试译成功，到现在没有时间看漫画。很感谢软件作者，祝软件越来越好！On Jul 21, 2023, at 12:37 AM, liu liyang ***@***.***> wrote:﻿

抱歉，我暂时没有时间写详细步骤。现在的安装方法好像下载量有点大。
记得我用了windows带的Powershell， 执行git clone那步（将github上的项目通过命令行转移到本地），就会有launch_win那个文件。
如作者说的：
1.（安装git, 克隆仓库） （打开powershell，命令行执行：） git clone https://github.com/dmMaze/BallonsTranslator cd BallonsTranslator git switch dev
2.（配置python3.10环境安装依赖库，或者）从https://mega.nz/folder/gmhmACoD#dkVlZ2nphOkU5-2ACb5dKw 下载完整的py环境包ballontrans_pylibs_win.7z，解压到BallonsTranslator目录下(ballontrans_pylibs_win这个文件夹和launch_win.bat同级)

将之前发布版的data文件夹复制到BallonsTranslator目录下
双击launch_win.bat运行.

请多尝试，你一定会成功！

可以用国内网盘发一下git clone 下来的文件吗？ 感谢

**Comment by bropines** [comment]
> ![未命名](https://user-images.githubusercontent.com/136751317/255850634-04f3d59c-e9d4-4b2d-aec4-dff958df3fb2.png) 第一步就卡住了 怎麼用啊

Install Git

**Comment by ddab03467** [comment]
> > ![未命名](https://user-images.githubusercontent.com/136751317/255850634-04f3d59c-e9d4-4b2d-aec4-dff958df3fb2.png) 第一步就卡住了 怎麼用啊
> 
> Install Git

可以了謝謝
只是最後一步我的資料夾裡沒有launch_win.bat這個檔案

**Comment by hq5566** [comment]
要一步一步的执行， 先在命令行输入Git Clone那一行，回车等待执行完成后。再在命令行输入Cd那行（进入目录），完成后。输入第三行， 等待完成。你最后的文件夹不是C：\user\Kevin，而是BallonTranslator（记不清了）。用dir launch_win.bat可以看到文件，也可用Explorer（windows资源浏览器）进入最后的目录看到。On Jul 25, 2023, at 5:16 AM, ddab03467 ***@***.***> wrote:﻿


 第一步就卡住了 怎麼用啊

Install Git

可以了謝謝
只是最後一步我的資料夾裡沒有launch_win.bat這個檔案

**Comment by hq5566** [comment]
不用客气，有问题尽管问！我也在不断学习使用新的技术和软件。

On Jul 25, 2023, at 7:13 AM, ddab03467 ***@***.***> wrote:

﻿

要一步一步的执行， 先在命令行输入Git Clone那一行，回车等待执行完成后。再在命令行输入Cd那行（进入目录），完成后。输入第三行， 等待完成。你最后的文件夹不是C：\user\Kevin，而是BallonTranslator（记不清了）。用dir launch_win.bat可以看到文件，也可用Explorer（windows资源浏览器）进入最后的目录看到。On Jul 25, 2023, at 5:16 AM, ddab03467 @.> wrote:﻿ 第一步就卡住了 怎麼用啊 Install Git 可以了謝謝 只是最後一步我的資料夾裡沒有launch_win.bat這個檔案 —Reply to this email directly, view it on GitHub, or unsubscribe.You are receiving this because you authored the thread.Message ID: @.>

成功了 謝謝!

**Comment by longfei796** [comment]
克隆仓库在哪里下载？

**Comment by hq5566** [comment]
请自己在互联网上搜索：“如何克隆GitHub上的项目”。谢谢🙏On Sep 25, 2023, at 11:06 PM, longfei796 ***@***.***> wrote:﻿
克隆仓库在哪里下载？
