### ISSUE TITLE
Drag and drop error

### ISSUE THREAD

**Issue by bropines** [dmMaze/BallonsTranslator#180]
[INFO   ] util:log_info:49 - DeepL API response status_code=200 url=https://api-free.deepl.com/v2/translate
Traceback (most recent call last):
  File "D:\AI\BallonsTranslator\ui\canvas.py", line 282, in dropEvent
    self.drop_open_folder.emit(self.drop_folder)
AttributeError: 'NoneType' object has no attribute 'emit'
Press any key . . . to continue.

**Comment by dmMaze** [comment]
fixed
