### ISSUE TITLE
怎么添加第三方GPT API？

### ISSUE THREAD

**Issue by lhj5426** [dmMaze/BallonsTranslator#181]
![image](https://github.com/dmMaze/BallonsTranslator/assets/30548000/b6d8b10c-69df-468e-bc02-255ddd421193)
今天闲着没事干 
就好奇 1月8日就停更了 怎么议题 一直在增加 仔细看发现
原来换了运行方式 
找了一圈总算在
https://github.com/dmMaze/BallonsTranslator/issues/160#issuecomment-1602064296
找到了运行方式
并且成功运行了 
不过 打开GPT选项我懵 了  没看到第三方API的添加地方 比如
![image](https://github.com/dmMaze/BallonsTranslator/assets/30548000/9f85d59c-99ca-4cff-9037-61fcae350f35)
![image](https://github.com/dmMaze/BallonsTranslator/assets/30548000/3dd9a3ce-209b-4273-b038-ce81328c3a7f)
![image](https://github.com/dmMaze/BallonsTranslator/assets/30548000/182d8918-053e-4bed-8d4c-3caf3eea34fc)
可以自己自定义 第三方 转发API的地址。。。 好像在界面里没有看到这些设置
只有一个 API key 
那这意思 现在只能用官方的api? 拿来翻译用官方的很贵啊。。。 
可以增加一个第三方 镜像网址自定义 的功能吗

**Comment by lhj5426** [comment]
前两个月又120刀的黑号 这样行 现在没有 官方黑号了 还是第三方 的API 价格骗3块钱20刀 可以翻译很多漫画 
希望开发者可以 添加上GPT代理转发设置地址功能

**Comment by lhj5426** [comment]
还有不是每次更新都要这么走一边流程吧 

              感谢尝试，如果你还想试试的话可以按下面步骤来
1. 安装git, 克隆仓库
git clone https://github.com/dmMaze/BallonsTranslator
cd BallonsTranslator
git switch dev

2. 配置python3.10环境安装依赖库，或者从https://mega.nz/folder/gmhmACoD#dkVlZ2nphOkU5-2ACb5dKw 下载完整的py环境包ballontrans_pylibs_win.7z，解压到BallonsTranslator目录下(ballontrans_pylibs_win这个文件夹和launch_win.bat同级)

3. 将之前发布版的data文件夹复制到BallonsTranslator目录下

4. 双击launch_win.bat运行，如果出现任何问题可以把命令行黑框截图贴上来

**Comment by dmMaze** [comment]
这个第三方api咋调用啊给下链接或者文档

如果你是git clone的直接本地git pull就能更新了，或者下最新源码压缩包本地覆盖

**Comment by lhj5426** [comment]
> 这个第三方api咋调用啊给下链接或者文档
> 
> 如果你是git clone的直接本地git pull就能更新了，或者下最新源码压缩包本地覆盖

https://openai-sb.com/api/openai/ 可以参考下这个文档 

或者这个文档 
https://api2d.com/wiki/doc

或者官方文档
https://platform.openai.com/docs/models/model-endpoint-compatibility

**Comment by lhj5426** [comment]
> 这个第三方api咋调用啊给下链接或者文档
> 
> 如果你是git clone的直接本地git pull就能更新了，或者下最新源码压缩包本地覆盖

源码包 是什么 ？
![image](https://github.com/dmMaze/BallonsTranslator/assets/30548000/a26dc4e2-bf43-41ce-a4a2-c89f153c7361)
是这个吗？ 
![image](https://github.com/dmMaze/BallonsTranslator/assets/30548000/a53d1d42-8f05-4c34-8fea-0395d168feec)
git pull 又是什么

**Comment by lhj5426** [comment]
![image](https://github.com/dmMaze/BallonsTranslator/assets/30548000/ee29109e-0e52-4d2e-9195-6e390922e912)
搞不明白怎么更新删掉重新按照安装流程走一边试试是不是最新的

**Comment by dmMaze** [comment]
> > 这个第三方api咋调用啊给下链接或者文档
> > 如果你是git clone的直接本地git pull就能更新了，或者下最新源码压缩包本地覆盖
> 
> 源码包 是什么 ？ ![image](https://user-images.githubusercontent.com/30548000/255326706-a26dc4e2-bf43-41ce-a4a2-c89f153c7361.png) 是这个吗？ ![image](https://user-images.githubusercontent.com/30548000/255326717-a53d1d42-8f05-4c34-8fea-0395d168feec.png) git pull 又是什么

图2是对的，它报错是目录权限问题，先按它说的git config --global --add safe.directory XXX(你的目录) 然后git pull

**Comment by lhj5426** [comment]
> > > 这个第三方api咋调用啊给下链接或者文档
> > > 如果你是git clone的直接本地git pull就能更新了，或者下最新源码压缩包本地覆盖
> > 
> > 
> > 源码包 是什么 ？ ![image](https://user-images.githubusercontent.com/30548000/255326706-a26dc4e2-bf43-41ce-a4a2-c89f153c7361.png) 是这个吗？ ![image](https://user-images.githubusercontent.com/30548000/255326717-a53d1d42-8f05-4c34-8fea-0395d168feec.png) git pull 又是什么
> 
> 图2是对的，它报错是目录权限问题，先按它说的git config --global --add safe.directory XXX(你的目录) 然后git pull

非常 感谢 我捅咕捅咕 先

**Comment by lhj5426** [comment]
修改路径下的这个文件的
\BallonsTranslator\ballontrans_pylibs_win\Lib\site-packages\openai\__init__.py
![image](https://github.com/dmMaze/BallonsTranslator/assets/30548000/7a96e466-28bd-4d73-9890-e4e1506a87b8)
这里就可以实现调用自定义api 希望开发者可以把这里的修改做到界面里 

![image](https://github.com/dmMaze/BallonsTranslator/assets/30548000/aa596573-fec1-46a9-9a80-56b9d160cee8)
实测 好使

**Comment by ddab03467** [comment]
![未命名](https://github.com/dmMaze/BallonsTranslator/assets/136751317/37421cf4-cec7-4376-9320-f0efee347a2c)
第4步運行後變這樣 按任意見就跳掉了

**Comment by dmMaze** [comment]
> 修改路径下的这个文件的 \BallonsTranslator\ballontrans_pylibs_win\Lib\site-packages\openai__init__.py ![image](https://user-images.githubusercontent.com/30548000/255816813-7a96e466-28bd-4d73-9890-e4e1506a87b8.png) 这里就可以实现调用自定义ap 原来是 https://api.openai.com 现在是https://api.aiguoguo199.com 后边的斜杠V1不用动
> 
> i 希望开发者可以把这里的修改做到界面里
> 
> ![image](https://user-images.githubusercontent.com/30548000/255816673-aa596573-fec1-46a9-9a80-56b9d160cee8.png) 实测 好使

感谢，加了，另外你最好把自己改的ballontrans_pylibs_win下面的东西改回来

**Comment by lhj5426** [comment]
> > 修改路径下的这个文件的 \BallonsTranslator\ballontrans_pylibs_win\Lib\site-packages\openai__init__.py ![image](https://user-images.githubusercontent.com/30548000/255816813-7a96e466-28bd-4d73-9890-e4e1506a87b8.png) 这里就可以实现调用自定义ap 原来是 https://api.openai.com 现在是https://api.aiguoguo199.com 后边的斜杠V1不用动
> > i 希望开发者可以把这里的修改做到界面里
> > ![image](https://user-images.githubusercontent.com/30548000/255816673-aa596573-fec1-46a9-9a80-56b9d160cee8.png) 实测 好使
> 
> 感谢，加了，另外你最好把自己改的ballontrans_pylibs_win下面的东西改回来

嗯  收到 更新的时候 应该就覆盖了吧

**Comment by dmMaze** [comment]
> 嗯 收到 更新的时候 应该就覆盖了吧

git pull不会改你本地修改过的源码，更不会改ballontrans_pylibs_win这个源码里本来就没有的第三方库文件夹

**Comment by lhj5426** [comment]
> > 嗯 收到 更新的时候 应该就覆盖了吧
> 
> git pull不会改你本地修改过的源码，更不会改ballontrans_pylibs_win这个源码里本来就没有的第三方库文件夹

好的 感谢 我已经重新解压了
在修改之前我打了个压缩包备份
现在已经解压回去了
![image](https://github.com/dmMaze/BallonsTranslator/assets/30548000/7e8f2a8f-e9d3-4b28-8c4f-f6daa8669c02)
更新完看到了 填写位置

**Comment by lhj5426** [comment]
![image](https://github.com/dmMaze/BallonsTranslator/assets/30548000/2e5b1139-5e2f-4832-bc8a-0a3fbd0e1cd2)
原来要加V1 哈哈 任意第三方API反斜杠V1才可以 感谢 ！
