### ISSUE TITLE
全局字体大小 不生效 

### ISSUE THREAD

**Issue by lhj5426** [dmMaze/BallonsTranslator#183]
https://github.com/dmMaze/BallonsTranslator/assets/30548000/1964509a-b7ac-4c33-acca-47b06285a898

如视频里演示那样 
首先演示的是今天安装的这个版本
![image](https://github.com/dmMaze/BallonsTranslator/assets/30548000/adf03e4b-289e-43d4-9367-a63b17174698)
设置里全部都是全局  
在全局里修改了字体字号 不生效
之后演示的是1.8号的EXE发行版
同样全局设置 在设置里修改了 字号 重新运行可以看到 字号是会修改的

**Comment by dmMaze** [comment]
其实是生效的，如果存在轮廓，实际应用的全局字体大小会减去轮廓大小，而轮廓大小是按字体大小比例算的，你第一个视频里轮廓大小调成了1.0，得到的实际字体大小是0
不过这里做减法的逻辑确实是错的，e04c168已修
