### ISSUE TITLE
[Feature Request] Add shortcut to delete in selection tool in brush mode (and more)

### ISSUE THREAD

**Issue by tak2hu** [dmMaze/BallonsTranslator#185]
In brush mode with the select tool, when failing to select some text multiple times, having a keyboard shortcut like backspace or escape would be nice to “deselect” 

(P.S: in the english readme I updated, I changed the shortcut for undo/redo into ctrl+z/ctrl+shift+z because it works like that on linux. now i’m using windows in another laptop turns out it’s still ctrl+y, sorry. 

there’s also a tiny typo in the readme, the translators available section: “Caiyun, Baidu. Papago“ supposed to be a coma, sorry again.

long P.S about more feature requests:
also another thing I want to mention add is a feature request (albeit a kind of major one), which is adding something [this photoshop plugin](https://swirt.github.io/typertools/) which I saw someone recommend in scanlation school (a discord server). this is really beneficial especially after I tried scanlating [this](https://www.pixiv.net/user/37274/series/172402) which uses at least 8 fonts. I don’t really use the “decide by program” option because it’s usually too big or small and vertical.

ofc there’s other things I would like to be added but they’re trivial features (to use, not to implement at least for me) and I’ve mentioned some of them before but I’ll just say it here again to remind myself: 
- auto download model file if missing
- configurable shortcuts (like tapping 1 to apply speech font and 2 to apply thinking font if a typesetter tool (above) was added
- add some (context) menu to copy source text as plain text (and newline separated if multiple) or a shortcut like ctrl+shift+c (I like using the deepl editor because it has good word alternatives then copy paste it back one by one into ballonstranslator)
- i’m currently using a laptop with a touchscreen and pinching to zoom in the canvas doesn’t work but this would be just slightly useful for those who have this kind of hardware though
- rearrange the (source and translation) text panels and be able to select multiple of them for copy the source text (like ctrl or shift in google sheets or files explorer)

thanks for reading, that’s all)

**Comment by tak2hu** [comment]
I did not realize there's already Text Style Presets

**Comment by dmMaze** [comment]
> I did not realize there's already Text Style Presets

I intend to rework it referring to typertool, but not very soon

**Comment by dmMaze** [comment]
> * i’m currently using a laptop with a touchscreen and pinching to zoom in the canvas doesn’t work but this would be just slightly useful for those who have this kind of hardware though

the fix adaeebb for macos touchpad could probably be generalized to other devices
