### ISSUE TITLE
能不能在有翻译的情况下 重新进行颜色识别

### ISSUE THREAD

**Issue by lhj5426** [dmMaze/BallonsTranslator#189]
![image](https://github.com/dmMaze/BallonsTranslator/assets/30548000/973e4cd6-24b8-4557-961e-d2f821619809)

![image](https://github.com/dmMaze/BallonsTranslator/assets/30548000/ee08de87-161a-449c-9657-677e6be204e5)

大佬如图 300多页 我用GPT跑完了
但是 跑完之后 我发现 忘记改回 字体颜色由 软件决定了 

然后现在就遇到了个问题
如果想让软件重新识别颜色
就相当于重新跑一边 翻译 又要二次消费GPT额度

然后
![image](https://github.com/dmMaze/BallonsTranslator/assets/30548000/ba68dc1e-a9d3-420a-8f26-4f3f5bc44043)
这下边一排 如果 关闭翻译 那么 软件将会 重新OCR 并且重新修图 并且删除翻译的文本
如果关闭OCR和翻译那么 软件将会清空所有 的ocr原文和译文 
这个逻辑就很冲突

我觉得 应该还有个逻辑
在有译文的情况下 可以重新跑OCR 不修图  或者 不修图不OCR 不翻译但是 重新跑新的字体方案？

现在 就目前无论下边这一排我怎么设置 都得2次消费GPT的额度

**Comment by bropines** [comment]
By the way, yes, I don’t like it at all that it deletes the text when the translator is turned off. Can separately implement the functions of translation, recognition and painting?

**Comment by dmMaze** [comment]
<img width="843" alt="image" src="https://github.com/dmMaze/BallonsTranslator/assets/51270320/02a368e7-4898-4dd3-a96e-b7deab9aace8">

现在各阶段可以各跑各的(#190)，除了第一个检测阶段, Run的时候启用的阶段不会覆盖未启用阶段的已有结果, 包括人为修改的部分, 而且会按照现有规则重新做文本后处理和渲染. 
比如你想重新做颜色识别, 取消OCR以外的勾就行了. 取消所有的勾会按照现有规则, 比如替换某些关键词, 字体样式是否采用全局等等重新渲染文字. 

@bropines Disable / Enable certain stages is supported now, the "Run" will not overwrite disabled stages results including those modified manually, except for the detection stage.
Disable all stages will only run postprocessing including rerendering all text according to specified rules.

**Comment by lhj5426** [comment]
> <img alt="image" width="843" src="https://user-images.githubusercontent.com/51270320/259046368-02a368e7-4898-4dd3-a96e-b7deab9aace8.png">
> 现在各阶段可以各跑各的(#190)，除了第一个检测阶段, Run的时候启用的阶段不会覆盖未启用阶段的已有结果, 包括人为修改的部分, 而且会按照现有规则重新做文本后处理和渲染. 比如你想重新做颜色识别, 取消OCR以外的勾就行了. 取消所有的勾会按照现有规则, 比如替换某些关键词, 字体样式是否采用全局等等重新渲染文字.
> 
> @bropines Disable / Enable certain stages is supported now, the "Run" will not overwrite disabled stages results including those modified manually, except for the detection stage. Disable all stages will only run postprocessing including rerendering all text according to specified rules.

![image](https://github.com/dmMaze/BallonsTranslator/assets/30548000/3fc4f205-669f-4138-ba2e-ce001525380c)
不知道为什么突然变成横排显示了 而且
只运行OCR的时候  原文框 内的文字变空白了 

虽然有进行重新文字识别并上色 但是原文没了
![image](https://github.com/dmMaze/BallonsTranslator/assets/30548000/f55a6c70-bcd3-4861-a5f9-8cbc4fae5b08)

**Comment by dmMaze** [comment]
> > <img alt="image" width="843" src="https://user-images.githubusercontent.com/51270320/259046368-02a368e7-4898-4dd3-a96e-b7deab9aace8.png">
> > 现在各阶段可以各跑各的(#190)，除了第一个检测阶段, Run的时候启用的阶段不会覆盖未启用阶段的已有结果, 包括人为修改的部分, 而且会按照现有规则重新做文本后处理和渲染. 比如你想重新做颜色识别, 取消OCR以外的勾就行了. 取消所有的勾会按照现有规则, 比如替换某些关键词, 字体样式是否采用全局等等重新渲染文字.
> > @bropines Disable / Enable certain stages is supported now, the "Run" will not overwrite disabled stages results including those modified manually, except for the detection stage. Disable all stages will only run postprocessing including rerendering all text according to specified rules.
> 
> ![image](https://user-images.githubusercontent.com/30548000/259112288-3fc4f205-669f-4138-ba2e-ce001525380c.png) 不知道为什么突然变成横排显示了 而且 只运行OCR的时候 原文框 内的文字变空白了
> 
> 虽然有进行重新文字识别并上色 但是原文没了 ![image](https://user-images.githubusercontent.com/30548000/259112565-f55a6c70-bcd3-4861-a5f9-8cbc4fae5b08.png)

这是项目文件初始化问题，刚修了，不过你这个项目(.json)内容已经改了，可以本地大概搜索"src_is_vertical": true全部替换成"src_is_vertical": false

**Comment by lhj5426** [comment]
> > > <img alt="image" width="843" src="https://user-images.githubusercontent.com/51270320/259046368-02a368e7-4898-4dd3-a96e-b7deab9aace8.png">
> > > 现在各阶段可以各跑各的(#190)，除了第一个检测阶段, Run的时候启用的阶段不会覆盖未启用阶段的已有结果, 包括人为修改的部分, 而且会按照现有规则重新做文本后处理和渲染. 比如你想重新做颜色识别, 取消OCR以外的勾就行了. 取消所有的勾会按照现有规则, 比如替换某些关键词, 字体样式是否采用全局等等重新渲染文字.
> > > @bropines Disable / Enable certain stages is supported now, the "Run" will not overwrite disabled stages results including those modified manually, except for the detection stage. Disable all stages will only run postprocessing including rerendering all text according to specified rules.
> > 
> > 
> > ![image](https://user-images.githubusercontent.com/30548000/259112288-3fc4f205-669f-4138-ba2e-ce001525380c.png) 不知道为什么突然变成横排显示了 而且 只运行OCR的时候 原文框 内的文字变空白了
> > 虽然有进行重新文字识别并上色 但是原文没了 ![image](https://user-images.githubusercontent.com/30548000/259112565-f55a6c70-bcd3-4861-a5f9-8cbc4fae5b08.png)
> 
> 这是项目文件初始化问题，刚修了，不过你这个项目(.json)内容已经改了，可以本地打开项目文件搜索"src_is_vertical": true全部替换成"src_is_vertical": false

我再重新更新一下
JSON 是上次 提问的时候 上次版本软件跑的 不影响吧
JSON 我有做备份 哈哈 就怕 跑一下把翻译搞没了还得重新跑GPT额度 所以提前做了备份

**Comment by lhj5426** [comment]
> > > > > <img alt="image" width="843" src="https://user-images.githubusercontent.com/51270320/259046368-02a368e7-4898-4dd3-a96e-b7deab9aace8.png">
> > > > > 现在各阶段可以各跑各的(#190)，除了第一个检测阶段, Run的时候启用的阶段不会覆盖未启用阶段的已有结果, 包括人为修改的部分, 而且会按照现有规则重新做文本后处理和渲染. 比如你想重新做颜色识别, 取消OCR以外的勾就行了. 取消所有的勾会按照现有规则, 比如替换某些关键词, 字体样式是否采用全局等等重新渲染文字.
> > > > > @bropines Disable / Enable certain stages is supported now, the "Run" will not overwrite disabled stages results including those modified manually, except for the detection stage. Disable all stages will only run postprocessing including rerendering all text according to specified rules.
> > > > 
> > > > 
> > > > ![image](https://user-images.githubusercontent.com/30548000/259112288-3fc4f205-669f-4138-ba2e-ce001525380c.png) 不知道为什么突然变成横排显示了 而且 只运行OCR的时候 原文框 内的文字变空白了
> > > > 虽然有进行重新文字识别并上色 但是原文没了 ![image](https://user-images.githubusercontent.com/30548000/259112565-f55a6c70-bcd3-4861-a5f9-8cbc4fae5b08.png)
> > > 
> > > 
> > > 这是项目文件初始化问题，刚修了，不过你这个项目(.json)内容已经改了，可以本地打开项目文件搜索"src_is_vertical": true全部替换成"src_is_vertical": false
> > 
> > 
> > 我再重新更新一下 JSON 是上次 提问的时候 上次版本软件跑的 不影响吧 JSON 我有做备份 哈哈 就怕 跑一下把翻译搞没了还得重新跑GPT额度 所以提前做了备份
> 
> 有备份那你再pull一下跑备份的，不用替换了

![image](https://github.com/dmMaze/BallonsTranslator/assets/30548000/1007e626-94cb-4104-91af-bbe760342e5f)
嗯 我 去跑一遍看看

**Comment by lhj5426** [comment]
> > > > > <img alt="image" width="843" src="https://user-images.githubusercontent.com/51270320/259046368-02a368e7-4898-4dd3-a96e-b7deab9aace8.png">
> > > > > 现在各阶段可以各跑各的(#190)，除了第一个检测阶段, Run的时候启用的阶段不会覆盖未启用阶段的已有结果, 包括人为修改的部分, 而且会按照现有规则重新做文本后处理和渲染. 比如你想重新做颜色识别, 取消OCR以外的勾就行了. 取消所有的勾会按照现有规则, 比如替换某些关键词, 字体样式是否采用全局等等重新渲染文字.
> > > > > @bropines Disable / Enable certain stages is supported now, the "Run" will not overwrite disabled stages results including those modified manually, except for the detection stage. Disable all stages will only run postprocessing including rerendering all text according to specified rules.
> > > > 
> > > > 
> > > > ![image](https://user-images.githubusercontent.com/30548000/259112288-3fc4f205-669f-4138-ba2e-ce001525380c.png) 不知道为什么突然变成横排显示了 而且 只运行OCR的时候 原文框 内的文字变空白了
> > > > 虽然有进行重新文字识别并上色 但是原文没了 ![image](https://user-images.githubusercontent.com/30548000/259112565-f55a6c70-bcd3-4861-a5f9-8cbc4fae5b08.png)
> > > 
> > > 
> > > 这是项目文件初始化问题，刚修了，不过你这个项目(.json)内容已经改了，可以本地打开项目文件搜索"src_is_vertical": true全部替换成"src_is_vertical": false
> > 
> > 
> > 我再重新更新一下 JSON 是上次 提问的时候 上次版本软件跑的 不影响吧 JSON 我有做备份 哈哈 就怕 跑一下把翻译搞没了还得重新跑GPT额度 所以提前做了备份
> 
> 有备份那你再pull一下跑备份的，不用替换了

![image](https://github.com/dmMaze/BallonsTranslator/assets/30548000/529db3a9-f3d0-4f61-9571-4d9090449f42)
 ^_^ 这次 竖排了 而且OCR文字也保留了！！！！ 感谢 大佬

**Comment by bropines** [comment]
it remains to improve the recognition of Japanese, Korean and English and it will be fine
