### ISSUE TITLE
彩云翻译用不了

### ISSUE THREAD

**Issue by pjwhnx1995** [dmMaze/BallonsTranslator#191]
如题，我申请了彩云token，这个token在别的翻译器能用，翻译字数也有大量剩余，在ballons上使用翻译始终为空，是否有问题

**Comment by dmMaze** [comment]
我试了下有用啊，控制台有啥报错信息吗，版本号是啥

**Comment by hagrid-105** [comment]
彩云的token不能挂vpn使用
