### ISSUE TITLE
在哪里切换语言

### ISSUE THREAD

**Issue by Rayforward** [dmMaze/BallonsTranslator#192]
软件打开是英文的，虽然看得懂，但很麻

**Comment by bropines** [comment]
As such, there is no language change. Set the system to Chinese (in the operating system).

**Comment by Rayforward** [comment]
> As such, there is no language change. Set the system to Chinese (in the operating system).

The strange thing is that all my system Settings are in Chinese, and other software that relies on system Settings displays Chinese normally

**Comment by dmMaze** [comment]
be72aa4 以后能界面里改了

**Comment by Rayforward** [comment]
> [be72aa4](https://github.com/dmMaze/BallonsTranslator/commit/be72aa40cb4ea08443a8f134cd52ed0d5b5edf37) 以后能界面里改了

好耶，感谢。还有就是，现在的dev分支还不能改是吗

**Comment by dmMaze** [comment]
> > [be72aa4](https://github.com/dmMaze/BallonsTranslator/commit/be72aa40cb4ea08443a8f134cd52ed0d5b5edf37) 以后能界面里改了
> 
> 好耶，感谢。还有就是，现在的dev分支还不能改是吗

这个就是在dev啊

**Comment by Rayforward** [comment]
> > > [be72aa4](https://github.com/dmMaze/BallonsTranslator/commit/be72aa40cb4ea08443a8f134cd52ed0d5b5edf37) 以后能界面里改了
> > 
> > 
> > 好耶，感谢。还有就是，现在的dev分支还不能改是吗
> 
> 这个就是在dev啊

我是指，我克隆了dev分支到本地，复制粘贴覆盖进core文件夹，好像还是没找到切换语言功能，于是我在想“以后”是指功能还没添加完成

**Comment by bropines** [comment]
> 我是指，我克隆了dev分支到本地，复制粘贴覆盖进core文件夹，好像还是没找到切换语言功能，于是我在想“以后”是指功能还没添加完成

I'll check now. A few minutes

**Comment by bropines** [comment]
> > > > [be72aa4](https://github.com/dmMaze/BallonsTranslator/commit/be72aa40cb4ea08443a8f134cd52ed0d5b5edf37) 以后能界面里改了
> > > 
> > > 
> > > 好耶，感谢。还有就是，现在的dev分支还不能改是吗
> > 
> > 
> > 这个就是在dev啊
> 
> 我是指，我克隆了dev分支到本地，复制粘贴覆盖进core文件夹，好像还是没找到切换语言功能，于是我在想“以后”是指功能还没添加完成

![image](https://github.com/dmMaze/BallonsTranslator/assets/57861007/c6728733-e27e-4262-b000-b2ee626d41e5)

**Comment by dmMaze** [comment]
> > > > [be72aa4](https://github.com/dmMaze/BallonsTranslator/commit/be72aa40cb4ea08443a8f134cd52ed0d5b5edf37) 以后能界面里改了
> > > 
> > > 
> > > 好耶，感谢。还有就是，现在的dev分支还不能改是吗
> > 
> > 
> > 这个就是在dev啊
> 
> 我是指，我克隆了dev分支到本地，复制粘贴覆盖进core文件夹，好像还是没找到切换语言功能，于是我在想“以后”是指功能还没添加完成

你应该没在跑dev branch，参考#160

**Comment by bropines** [comment]
Try this install method 

https://github.com/dmMaze/BallonsTranslator/issues/187

**Comment by Rayforward** [comment]
> Try this install method
> 
> #187

我没有Run launch_win.bat
当运行时他显示exit code: 1

stderr:
Could not import runpy module
Traceback (most recent call last):
  File "<frozen runpy>", line 15, in <module>
  File "<frozen importlib.util>", line 2, in <module>
ModuleNotFoundError: No module named 'importlib._abc'

Launch unsuccessful. Exiting.

我已经下载了requirements.txt和importlib依赖

**Comment by Rayforward** [comment]
> > > > > [be72aa4](https://github.com/dmMaze/BallonsTranslator/commit/be72aa40cb4ea08443a8f134cd52ed0d5b5edf37) 以后能界面里改了
> > > > 
> > > > 
> > > > 好耶，感谢。还有就是，现在的dev分支还不能改是吗
> > > 
> > > 
> > > 这个就是在dev啊
> > 
> > 
> > 我是指，我克隆了dev分支到本地，复制粘贴覆盖进core文件夹，好像还是没找到切换语言功能，于是我在想“以后”是指功能还没添加完成
> 
> 你应该没在跑dev branch，参考#160

![image](https://github.com/dmMaze/BallonsTranslator/assets/45681350/c003cdc8-3734-482c-b3de-18e974d3f12b)
我在git桌面里切换了分支，应该是对的吧。

**Comment by dmMaze** [comment]
> > > > > > [be72aa4](https://github.com/dmMaze/BallonsTranslator/commit/be72aa40cb4ea08443a8f134cd52ed0d5b5edf37) 以后能界面里改了
> > > > > 
> > > > > 
> > > > > 好耶，感谢。还有就是，现在的dev分支还不能改是吗
> > > > 
> > > > 
> > > > 这个就是在dev啊
> > > 
> > > 
> > > 我是指，我克隆了dev分支到本地，复制粘贴覆盖进core文件夹，好像还是没找到切换语言功能，于是我在想“以后”是指功能还没添加完成
> > 
> > 
> > 你应该没在跑dev branch，参考#160
> 
> ![image](https://user-images.githubusercontent.com/45681350/257519455-c003cdc8-3734-482c-b3de-18e974d3f12b.png) 我在git桌面里切换了分支，应该是对的吧。

你py环境不对，请严格按那四步走，报错先去爬下那楼

**Comment by Rayforward** [comment]
我大概是明白为什么了，我也一样1.22的numpy污染了环境，而且我全程在发行的core包里操作的，应该是克隆dev分支、粘贴依赖库、粘贴发行data，运行launch_win.bat
https://github.com/dmMaze/BallonsTranslator/issues/160#issuecomment-1602064296
接下来就是手动装模型了是吧

**Comment by Rayforward** [comment]
torch.cuda.OutOfMemoryError: CUDA out of memory. Tried to allocate 512.00 MiB (GPU 0; 6.00 GiB total capacity; 4.65 GiB already allocated; 0 bytes free; 5.13 GiB reserved in total by PyTorch) If reserved memory is >> allocated memory try setting max_split_size_mb to avoid fragmentation.  See documentation for Memory Management and PYTORCH_CUDA_ALLOC_CONF

是我没启用GPU加速的关系吗？还是2060也就7张图的水准了……

**Comment by Rayforward** [comment]
此外针对chatgpt断行问题，毛遂自荐一个gpt4帮我写的手动程度高的一键chatgpt翻译脚本，支持自定义墙内api url
https://github.com/Rayforward/ChatGPT-Simple-Translator

**Comment by bropines** [comment]
> torch.cuda.OutOfMemoryError: CUDA out of memory. Tried to allocate 512.00 MiB (GPU 0; 6.00 GiB total capacity; 4.65 GiB already allocated; 0 bytes free; 5.13 GiB reserved in total by PyTorch) If reserved memory is >> allocated memory try setting max_split_size_mb to avoid fragmentation. See documentation for Memory Management and PYTORCH_CUDA_ALLOC_CONF
> 
> 是我没启用GPU加速的关系吗？还是2060也就7张图的水准了……
![image](https://github.com/dmMaze/BallonsTranslator/assets/57861007/b0441d2d-6993-40ee-b714-d930cc58a230)


Play around with the settings so you don't get any errors

**Comment by Rayforward** [comment]
> > torch.cuda.OutOfMemoryError: CUDA out of memory. Tried to allocate 512.00 MiB (GPU 0; 6.00 GiB total capacity; 4.65 GiB already allocated; 0 bytes free; 5.13 GiB reserved in total by PyTorch) If reserved memory is >> allocated memory try setting max_split_size_mb to avoid fragmentation. See documentation for Memory Management and PYTORCH_CUDA_ALLOC_CONF
> > 是我没启用GPU加速的关系吗？还是2060也就7张图的水准了……
> > ![image](https://user-images.githubusercontent.com/57861007/257541658-b0441d2d-6993-40ee-b714-d930cc58a230.png)
> 
> Play around with the settings so you don't get any errors

Lower the size works.Thanks a lot!
