### ISSUE TITLE
让A卡在windows下跑cuda

### ISSUE THREAD

**Issue by qianzhou123** [dmMaze/BallonsTranslator#193]
AMD好像在最近放出了个sdk
能让A卡变相跑cuda
而且支持在win下运行
希望能够支持

**Comment by dmMaze** [comment]
这个项目的独显加速主要是pytorch在用，A卡和N卡的pytorch接口是一样的(https://pytorch.org/docs/stable/notes/hip)，所以只要能装上了pytorch-ROCm应该就能加速，项目代码是不需要改的。pytorch目前还没windows ROCm包需要自己编译，我也没A卡
