### ISSUE TITLE
可以 给 删除并恢复被抹除文字 增加快捷键吗

### ISSUE THREAD

**Issue by lhj5426** [dmMaze/BallonsTranslator#196]
![image](https://github.com/dmMaze/BallonsTranslator/assets/30548000/39eb7123-445c-41f2-a98d-81e7d61815c6)
感谢大佬更新 增加了 分步骤 操作
分布操作 就是为了  多删 少补 
但是 在实际使用的过程中 发现
在 多删 的这个 步骤里 删除的时候 要一直右键  有点 不方便

被误识别的 拟声词 这个数量 是非常庞大的 所以 

可以给这个 功能添加一个 快捷键么  方便快速进行操作

![image](https://github.com/dmMaze/BallonsTranslator/assets/30548000/5c210152-8c7d-4109-8404-aac8f3c03d81)
另外如果可以直接放在delete上 一个按钮来删除就更好了
因为在 操作的时候左手 是在6个按钮上 
左手食指在 UP DN 上一页 下一页 来翻页
左手无名指刚好放在DELETE上如果 用这个一个按钮来 进行  删除并恢复被抹除文字
会非常舒服 和方便  如果用组合键的话 手指 要反复横跳  也不很舒服 
还请考虑一下

**Comment by dmMaze** [comment]
加了, ctrl+shift+d或者delete

**Comment by lhj5426** [comment]
> 加了, ctrl+shift+d或者delete

我去？？？这快  我用右键删了100来页  哈哈 这就更新
