### ISSUE TITLE
[Feauture request] ChatGPT promt and text-blocks copy.

### ISSUE THREAD

**Issue by bropines** [dmMaze/BallonsTranslator#197]
Due to the impossibility of paying for api from Russia, you have to use the free one, but it, in turn, has a limit of 3 requests per minute. The version on the site, in turn, does not have such a minus (in Russia, no one deals with api mirrors, and buying a paid key is very expensive). The idea is that when we select the chatgpt translator, it takes our text blocks and, according to the prompt, sends them to the gpt api. For me, the function "copy all text blocks and promt for gpt" would be useful. It actually copies the system prompt and blocks of text that we paste on the chatgpt site. This will be easier than manually copying all the blocks. In the same way, we can insert the received answer if it is formatted correctly (or enter the translation into blocks with pens). The main thing for me is to give the bot data, and then somehow I will figure it out myself

**Comment by lhj5426** [comment]
> Due to the impossibility of paying for api from Russia, you have to use the free one, but it, in turn, has a limit of 3 requests per minute. The version on the site, in turn, does not have such a minus (in Russia, no one deals with api mirrors, and buying a paid key is very expensive). The idea is that when we select the chatgpt translator, it takes our text blocks and, according to the prompt, sends them to the gpt api. For me, the function "copy all text blocks and promt for gpt" would be useful. It actually copies the system prompt and blocks of text that we paste on the chatgpt site. This will be easier than manually copying all the blocks. In the same way, we can insert the received answer if it is formatted correctly (or enter the translation into blocks with pens). The main thing for me is to give the bot data, and then somehow I will figure it out myself

https://github.com/dmMaze/BallonsTranslator/issues/141#

This Python script in the issues can export the content of JSON to a TXT file. Then you can take the TXT file and use it to feed GPT with the prompts on the website. After receiving the results, you can write them back to the TXT file in the corresponding format. Once you're done, you can use another Python script to import the data back into JSON.

Before the software adds the GPT translation engine, I used this method for a long time.

**Comment by dmMaze** [comment]
copy/paste multiple selected blocks as multiple lines are already supported, I'd suggest prepending the prompt manually

**Comment by bropines** [comment]
@dmMaze isn't he copying a translation? Like the idea was to copy exactly with numbering, blocks of the original text.

**Comment by dmMaze** [comment]
> @dmMaze isn't he copying a translation? The idea was to copy exactly with numbering, blocks of the original text.

<img width="382" alt="image" src="https://github.com/dmMaze/BallonsTranslator/assets/51270320/32f9cd23-3aa0-40a8-84ad-5dbcfe6556b2">

**Comment by bropines** [comment]
Hmm. It works almost the same way, but the great and dumb GPT keeps messing up the line order. Is it possible to add copying with line numbering?

**Comment by tak2hu** [comment]
I’d like a setting option to enable line numbering on copy source text and/or with newline per line too
