### ISSUE TITLE
关于爆显存的问题

### ISSUE THREAD

**Issue by lhj5426** [dmMaze/BallonsTranslator#198]
开发者大佬你好
在单独只跑修复的时候
![image](https://github.com/dmMaze/BallonsTranslator/assets/30548000/13b24f5f-50e1-4129-987b-af33bc7e9a29)
如果这样一次跑500页
就会有大概率出现在350页到400页之间 出现爆显存的问题
![image](https://github.com/dmMaze/BallonsTranslator/assets/30548000/debe0cd4-2547-46dc-9a03-bba0b5a52bd4)

但是把这500页分成 5个文件夹每个文件夹100页分开跑
就不会出现这个问题
所以 想问下 是不是 在大批量运行的时候 没有释放 内存显存 才会导致这个问题
如果是图片的问题的话 
那么 单独运行300 和400 页的文件夹里的图进行修复应该也会爆显存才对
而且这样分开跑修复图 就没有爆过
现在是这样分开跑修复跑完之后 全部移动到 500页全页的 修图文件夹下 

按照 这个操作 是不是可以 每跑一定数量的时候暂停一下释放一下缓存 然后再继续 ？ 
因程序 自身没有暂停 继续 这个功能

**Comment by dmMaze** [comment]
8e8f463 修了

**Comment by lhj5426** [comment]
嗯 平均100页 会吃掉2.9G显存
