### ISSUE TITLE
重新跑 修改字体大小的问题

### ISSUE THREAD

**Issue by lhj5426** [dmMaze/BallonsTranslator#202]
大佬您好
之前
https://github.com/dmMaze/BallonsTranslator/issues/189
这个提到过 忘记修改颜色 导致全部变成了统一颜色
当时您 说
现在各阶段可以各跑各的(#190)，除了第一个检测阶段, Run的时候启用的阶段不会覆盖未启用阶段的已有结果, 包括人为修改的部分, 而且会按照现有规则重新做文本后处理和渲染.
比如你想重新做颜色识别, 取消OCR以外的勾就行了. 取消所有的勾会按照现有规则, 比如替换某些关键词, 字体样式是否采用全局等等重新渲染文字.

今天出现了另外一种情况

因为每部漫画的 图片分辨率不一样 有的时候 使用 机器自动设定字体大小 实际设置的字体大小 偏大 或者偏小
所以有的时候会启动手动全局字体
今天就遇到了这种问题
上一部是需要手动指定字体大小的

而这一步跑的时候忘记了 先设置字体大小 或者让软件自动设置大小
直接使用了上一部的 使用全局字体 这就打导致了
![image](https://github.com/dmMaze/BallonsTranslator/assets/30548000/0c90abc2-5971-4ae8-908a-845dd373d4e0)
这本跑翻译后完字体超大的问题
然后我想到之前 修改字体颜色的操作 就是什么都不开唯独开OCR
但是实际并没有效果
![image](https://github.com/dmMaze/BallonsTranslator/assets/30548000/fd98cb04-7dc9-4513-8309-c9f96627ddcb)
 然后我想 是不是出问题了 又把 颜色改成了全局 还是只开ocr跑
![image](https://github.com/dmMaze/BallonsTranslator/assets/30548000/1baca4f0-d538-47bb-a10a-5611da32dca1)
结果 字体的颜色变了 但是字体的大小没变

然后看到 上次您说的这句话

取消所有的勾会按照现有规则, 比如替换某些关键词, 字体样式是否采用全局等等重新渲染文字.
我又取消了全部的勾选  并运行
结果无事发生？
![image](https://github.com/dmMaze/BallonsTranslator/assets/30548000/ab6bf77e-acba-40f9-86f6-913855d27e6c)

所以 要怎么 在不丢失 翻译和OCR的基础上 重新自动调整文字大小？

现在重新OCR 是会重新调整文字的颜色 但好像不会重新 按照设置 重新调整文字的大小？ 

然后我想 反正页数不多 重新跑也消耗不了多少额度
在设置里 改成 字体大小 由程序决定之和
重新单独跑翻译
![image](https://github.com/dmMaze/BallonsTranslator/assets/30548000/028524a4-e1aa-48dd-a40b-3d7e17372ba6)
结果 字体的大小还是没有改变 

我已经有点懵了 
然后现在正确的 重新修正字体大小的方式是 
3开 1检测 2 ocr 3翻译
![image](https://github.com/dmMaze/BallonsTranslator/assets/30548000/5c385abf-27e1-461c-808b-3c4d9e894fdb)
再然后 

我又只开了OCR 和翻译 然后 设置全局字体大小
![image](https://github.com/dmMaze/BallonsTranslator/assets/30548000/9f3b7c04-b7c2-4350-9799-48cace0b5970)

结果 字体大小 由刚才的 系统决定的小字 变成了大字 

这个 字体大小 到底是由 谁控制的？
 单开 OCR 字体不变 单开 翻译字体不变  双开OCR和翻译字体大小改变 
 
因为这次遇到的问题 的本子页数少 可以任性 一遍一遍的重跑哈哈
所以 还是楼上的问题 要怎么 在不丢失 翻译 的基础上 重新按照 设置里的规则 重新 调整文字大小？

**Comment by dmMaze** [comment]
修了, 现在除了跑inpainting其它都会根据设置重设字体大小
"由程序决定"的字体大小是检测阶段决定的, 所以自己挖的框不受影响

**Comment by lhj5426** [comment]
> 修了, 现在除了跑inpainting其它都会根据设置重设字体大小 "由程序决定"的字体大小是检测阶段决定的, 所以自己挖的框不受影响

非常的感谢！！
![image](https://github.com/dmMaze/BallonsTranslator/assets/30548000/97f0398f-707c-47b3-9416-7c2fd4216f4b)

刚试过了 现在 更新之后 只单独跑OCR的情况下  会 同时重设 字体的大小 以及 颜色 设置了！

**Comment by lhj5426** [comment]
不过这个边框 没有跟着缩小 哈哈
![image](https://github.com/dmMaze/BallonsTranslator/assets/30548000/2ae8a27f-ef36-46b9-82a2-6245aedd3856)
![image](https://github.com/dmMaze/BallonsTranslator/assets/30548000/8a0818da-42c9-4815-94e2-0347d58ef93c)
每个q气泡的边框都 很大

**Comment by lhj5426** [comment]
而且 只有第一页的边框没有 修正
![image](https://github.com/dmMaze/BallonsTranslator/assets/30548000/985e4585-438d-449b-9ade-6c2ff8548882)
后面页数里的气泡边框都是围绕着文字的
![image](https://github.com/dmMaze/BallonsTranslator/assets/30548000/5c7fadb7-8fb9-4b76-b53d-1fe042428a44)
![image](https://github.com/dmMaze/BallonsTranslator/assets/30548000/de812ba8-9056-4b45-86b9-46b516a902e7)
![image](https://github.com/dmMaze/BallonsTranslator/assets/30548000/4d02ed9d-c971-49ad-9406-53f603d9d58e)
上边都气泡都是后边页数的
这是第一页的
![image](https://github.com/dmMaze/BallonsTranslator/assets/30548000/1bbfaf06-beaf-4527-b187-439270b81442)
没有修正

**Comment by dmMaze** [comment]
大小也修了 a3f2493

**Comment by lhj5426** [comment]
确实 这次 修正了 非常感谢
