### ISSUE TITLE
url 超过最大重试次数  由 ProxyError 引起（无法连接到代理。RemoteDisconnected（远程结束没有关闭连接）

### ISSUE THREAD

**Issue by sssman234** [dmMaze/BallonsTranslator#205]
ProxyError(MaxRetryError("HTTPSConnectionPool(host=papago.naver.com,"port=443):MAX retries exceeded with url :/apis/n2mt/translate(Caused by ProxyError(Cannot connect to proxy. RemoteDisconnected(Remote end closed connection without response)

ProxyError(MaxRetryError("HTTPSConnectionPool(host=papago.naver.com,"port=443): url 超过最大重试次数：/apis/n2mt/translate（由 ProxyError 引起（无法连接到代理。RemoteDisconnected（远程结束没有关闭连接）

请问这是什么问题呀？

**Comment by dmMaze** [comment]
你是不是开了系统代理
你运行的是发布版还是源码, 源码试试装urllib3==1.25.11
