### ISSUE TITLE
Auto layout on textblocks that goes out of canvas crashes: OpenCV(4.8.0) error: (-215:Assertion failed) !ssize.empty() in function 'cv::resize'

### ISSUE THREAD

**Issue by tak2hu** [dmMaze/BallonsTranslator#207]
Windows 11 Python 3.9 dev branch.
It works on the main branch.
```
Traceback (most recent call last):
  File "C:\Users\widi\BallonsTranslator\ui\scenetext_manager.py", line 692, in onAutoLayoutTextblks
    self.layout_textblk(blkitem)
  File "C:\Users\widi\BallonsTranslator\ui\scenetext_manager.py", line 722, in layout_textblk
    mask, ballon_area, mask_xyxy, region_rect = extract_ballon_region(img, bounding_rect, enlarge_ratio=enlarge_ratio, cal_region_rect=True)
  File "C:\Users\widi\BallonsTranslator\utils\imgproc_utils.py", line 275, in extract_ballon_region
    img = cv2.resize(img, (int(w*scaleR), int(h*scaleR)), interpolation=cv2.INTER_AREA)
cv2.error: OpenCV(4.8.0) D:\a\opencv-python\opencv-python\opencv\modules\imgproc\src\resize.cpp:4062: error: (-215:Assertion failed) !ssize.empty() in function 'cv::resize'
```

**Comment by tak2hu** [comment]
Update: yeah it also doesn't work on the main branch

and it's not about multiple textblocks, but when accidentally typing a huge font size (like 300), the textblock goes out of screen. When selecting that textblock and applying auto layout, it crashes with `error: (-215:Assertion failed) !ssize.empty() in function 'cv::resize'`

**Comment by dmMaze** [comment]
> accidentally typing 300 font size which auto resizes the textblock, then typing 30 font size but the textblock remains the same

I cant reproduce, it works fine on my side

> Windows 11 Python 3.9 dev branch. It works on the main branch.
> 
> ```
> Traceback (most recent call last):
>   File "C:\Users\widi\BallonsTranslator\ui\scenetext_manager.py", line 692, in onAutoLayoutTextblks
>     self.layout_textblk(blkitem)
>   File "C:\Users\widi\BallonsTranslator\ui\scenetext_manager.py", line 722, in layout_textblk
>     mask, ballon_area, mask_xyxy, region_rect = extract_ballon_region(img, bounding_rect, enlarge_ratio=enlarge_ratio, cal_region_rect=True)
>   File "C:\Users\widi\BallonsTranslator\utils\imgproc_utils.py", line 275, in extract_ballon_region
>     img = cv2.resize(img, (int(w*scaleR), int(h*scaleR)), interpolation=cv2.INTER_AREA)
> cv2.error: OpenCV(4.8.0) D:\a\opencv-python\opencv-python\opencv\modules\imgproc\src\resize.cpp:4062: error: (-215:Assertion failed) !ssize.empty() in function 'cv::resize'
> ```

fixed

**Comment by tak2hu** [comment]
it works great, thanks!
