### ISSUE TITLE
用Ｍac開啟程式總是Crash

### ISSUE THREAD

**Issue by claire20230828** [dmMaze/BallonsTranslator#208]
我用Mac應用程式開啟總是會Crash，有人遇到相同問題嗎？

<img width="998" alt="截圖 2023-08-28 下午2 46 40" src="https://github.com/dmMaze/BallonsTranslator/assets/143456084/ea527eb0-2914-484d-92d8-f33cfbc0530d">

**Comment by tak2hu** [comment]
It crashed for me too (macOS Ventura) but the error message was “NoneType” on 3 specific lines, so I [commented](https://github.com/dmMaze/BallonsTranslator/blob/cfde1f6834bc25339b9053cb1f5e44cfeb2ff677/ui/framelesswindow/fw_qt6/mac/__init__.py#L71) those out in the [dev branch](https://github.com/dmMaze/BallonsTranslator/tree/dev).

I recommend commenting those lines too for now or install the dev branch.
