### ISSUE TITLE
I don't know how to install the program on linux ( linux mint ).

### ISSUE THREAD

**Issue by Quike45** [dmMaze/BallonsTranslator#210]
Hi good I am new to linux and I would like to have the program, but I do not know how to install it, sorry if this is a silly question but since there is no installation guide I am left with the doubt, thank you in advance for your help.

**Comment by dmMaze** [comment]
follow the Run source code in English readme, switch to dev branch, finally run python launch.py

**Comment by Quike45** [comment]
seems to give me an error

![image](https://github.com/dmMaze/BallonsTranslator/assets/117871380/d907046c-75b6-4c07-b374-2783014714a8)

**Comment by dmMaze** [comment]
> seems to give me an error
> 
> ![image](https://github.com/dmMaze/BallonsTranslator/assets/117871380/d907046c-75b6-4c07-b374-2783014714a8)
> 

try updating numpy and opencv-python

**Comment by Quike45** [comment]
perfect thank you very much for helping me

![image](https://github.com/dmMaze/BallonsTranslator/assets/117871380/0f535ff9-1ae3-43b6-9e12-c77c8cd704eb)

**Comment by Quike45** [comment]
none thanks for the support, an apology for the delay in the response
