### ISSUE TITLE
关于一键翻译后的json

### ISSUE THREAD

**Issue by huangjiahui233** [dmMaze/BallonsTranslator#212]
我用完一件翻译后把json里面的翻译进行的润色，然后产生了新的json，但这个新的json只能在软件里面预览润色结果，并不能把润色后的图片进行保存，该怎么办？

**Comment by dmMaze** [comment]
进软件每页都CTRL+S保存一下，或者删掉result下的图进界面一页页翻过去
如果在用dev版可以吧四个步骤的勾都去掉点下Run重新渲染

**Comment by huangjiahui233** [comment]
小白不懂就问，dev版在哪

**Comment by dmMaze** [comment]
> 小白不懂就问，dev版在哪

https://github.com/dmMaze/BallonsTranslator/issues/160#issuecomment-1602064296

**Comment by huangjiahui233** [comment]
请问可以把您的文件上传到mega吗，实在是不会用git命令

**Comment by huangjiahui233** [comment]
解决了，感谢！
