### ISSUE TITLE
failed to load config file 什么意思

### ISSUE THREAD

**Issue by longfei796** [dmMaze/BallonsTranslator#215]
请问如何处理？

**Comment by longfei796** [comment]
> 看不懂你在说什么...实在不行你可以**完整**录个屏

那个我搞好了，请问百度翻译
我申请到了appid，在token那输入了秘钥
delay是啥？

**Comment by bropines** [comment]
> 那个我搞好了，请问百度翻译
> 我申请到了appid，在token那输入了秘钥
> delay是啥？

This is the time between each request. Some services like deepL cannot send requests every 3 nanoseconds
