### ISSUE TITLE
Suggestion for Chatgpt and some minor feature

### ISSUE THREAD

**Issue by dhana-exe** [dmMaze/BallonsTranslator#216]
1. can we use chatgpt free from openai? i think the translation is best and free, since current chatgpt that we had looks like from paid version only
2. Can we had "read" feature on "text" or "translation" panel to show how the word is read? example this i asking to chatgpt
![image](https://github.com/dmMaze/BallonsTranslator/assets/29838157/0b0018a1-ddb2-42dc-9465-9b91d0ac287a)

and this i asking to translate all the text from 1 page
![image](https://github.com/dmMaze/BallonsTranslator/assets/29838157/a61864eb-1936-4949-a4c8-bc61fd431d84)

since on this we know that word on first picture is Minedera
i ask him again and resulting on this
![image](https://github.com/dmMaze/BallonsTranslator/assets/29838157/9f6e6353-9f92-4d11-8ff8-a7849bafac67)
i think this is good result for now... just need to be "re-corrected" little bit to be perfect.....

and this consider the best from other translator engine compared to what we had it now....

maybe you can reconsider this :> anyway thanks alot, your app already help me alot to fastly translate text on my local school festival (we translate it into 3 language, english, national language and local language XD) less than 1 hour while using this app

you're best guys

**Comment by bropines** [comment]
In theory. The problem is that ChatGPT is protected from automated systems. Sometimes when we try to log in to the site through an account, we may get caught in a captcha and then we have to think about something

**Comment by bropines** [comment]
If there is a project on Github that allows you to use GPT through a website and account, then you should try to find it

**Comment by dhana-exe** [comment]
> In theory. The problem is that ChatGPT is protected from automated systems. Sometimes when we try to log in to the site through an account, we may get caught in a captcha and then we have to think about something

ahhh i see....:( sorry about it 
i think they as simple as steal the session or something like that 
and that will works....

sorry again :(

**Comment by bropines** [comment]
> > In theory. The problem is that ChatGPT is protected from automated systems. Sometimes when we try to log in to the site through an account, we may get caught in a captcha and then we have to think about something
> 
> ahhh i see....:( sorry about it i think they as simple as steal the session or something like that and that will works....
> 
> sorry again :(

Just open it for now, I’ll try to write a plugin, but for it you will have to constantly log in through the browser every session. It's a crutch but it will work.
