### ISSUE TITLE
一些小问题

### ISSUE THREAD

**Issue by qianzhou123** [dmMaze/BallonsTranslator#22]
1.竖向文本排版中，符号不会转
2. 在软件中的快捷键说明不够
3. 画笔工具会在所有图片上生效
4. 1.3.0相对1.2.0更容易崩溃

**Comment by dmMaze** [comment]
> 3. 画笔工具会在所有图片上生效

这个v1.3.0没有吧



> 4. 1.3.0相对1.2.0更容易崩溃

崩溃了请提供报错信息

**Comment by qianzhou123** [comment]
好的谢谢

同时希望可以增加批量查找与替换
我之前试图直接修改json但会和json的一些代码冲突。比如说括号
因为我翻译的大多是竖向排列的文本
那么在图片里的 （      ）    ...     会看起来很怪
我想替换为︵︶┇
如果你能直接解决符号的旋转那就更好了

**Comment by qianzhou123** [comment]
GitHub无法显示横着的括号

**Comment by dmMaze** [comment]
> 如果你能直接解决符号的旋转那就更好了

[v1.3.4](https://github.com/dmMaze/BallonsTranslator/releases/tag/v1.3.4)及以后竖排支持特定符号旋转, 规则详见https://github.com/dmMaze/BallonsTranslator/pull/30
