### ISSUE TITLE
【UI bug】右边侧栏被折叠、收缩以后再也无法展开

### ISSUE THREAD

**Issue by gsxgmpkt9020** [dmMaze/BallonsTranslator#220]
右边侧栏被折叠、收缩以后再也无法展开

![image](https://github.com/dmMaze/BallonsTranslator/assets/2074641/06b80d7a-41af-494f-8295-3581d0057c74)

**Comment by dmMaze** [comment]
<img width="150" alt="image" src="https://github.com/dmMaze/BallonsTranslator/assets/51270320/8fa326f5-57ea-4762-949e-68b2b0492b11">
画板和文本编辑模式其中一个选中了右侧面板才会生效, 这时候手动折叠了右边才会有一个槽让你展开(箭头指的地方

**Comment by dmMaze** [comment]
> > 4K
> 
> 就是4K，有些情况下就是出现无法拖动的现象

我现在没有4K显示器, 你可以试试在下面这这行
https://github.com/dmMaze/BallonsTranslator/blob/19ab98b3dc89ef3cd809827aa58742be1d273dcf/ui/mainwindow.py#L205
后新添一行
``` python
self.comicTransSplitter.setHandleWidth(NUMBER)
```
NUMBER是你自己尝试合适的拖动范围宽度(整数), 然后把结果告诉我
