### ISSUE TITLE
求助，用GPT3.5的接口结果ocr出原文但是没给翻译

### ISSUE THREAD

**Issue by OKtheMirror** [dmMaze/BallonsTranslator#221]
[WARNING] trans_chatgpt:_translate:226 - Restarting request due to a server error. Attempt: 1
[WARNING] trans_chatgpt:_translate:226 - Restarting request due to a server error. Attempt: 2
[WARNING] trans_chatgpt:_translate:226 - Restarting request due to a server error. Attempt: 3
[WARNING] trans_chatgpt:_translate:226 - Restarting request due to a server error. Attempt: 4
[ERROR  ] trans_chatgpt:_translate:223 - OpenAI encountered a server error, possibly due to high server load. Use a different translator or try again later.
这是翻译没结果时的代码

**Comment by dmMaze** [comment]
如果API啥的没填错大概是OpenAI那边堵了，换个时间段试试

**Comment by OKtheMirror** [comment]
> 如果API啥的没填错大概是OpenAI又堵了，换个时间段尝试一下

我开始也是这么想，然后昨天半夜测试了一下，还是翻译不了，代码没变

**Comment by OKtheMirror** [comment]
> 如果API啥的没填错大概是OpenAI那边堵了，换个时间段试试

刚刚又试了一遍，还是堵车不成功
