### ISSUE TITLE
添加图片文件夹后不显示图片，点run有没有任何反应

### ISSUE THREAD

**Issue by 55kai-niubi** [dmMaze/BallonsTranslator#223]
![2023-9-15 21-55-0](https://github.com/dmMaze/BallonsTranslator/assets/70558961/c5e8ca10-527d-4907-8b66-0a5ee5611fb3)
之前是可以用的，隔了一段时间后今天用就用不了了，不管添加什么图片，他都不显示有图片，点run也没有任何反应

**Comment by bropines** [comment]
> ![2023-9-15 21-55-0](https://user-images.githubusercontent.com/70558961/268301267-c5e8ca10-527d-4907-8b66-0a5ee5611fb3.jpg) 之前是可以用的，隔了一段时间后今天用就用不了了，不管添加什么图片，他都不显示有图片，点run也没有任何反应

Does it output anything to the console?

**Comment by 55kai-niubi** [comment]
![2023-9-15 22-34-32](https://github.com/dmMaze/BallonsTranslator/assets/70558961/a168da87-76f1-45c7-93d1-c235f8971c6e)
什么都没有

**Comment by bropines** [comment]
> ![2023-9-15 22-34-32](https://user-images.githubusercontent.com/70558961/268312291-a168da87-76f1-45c7-93d1-c235f8971c6e.jpg) 什么都没有

How did you install the program?

**Comment by 55kai-niubi** [comment]
> > ![2023-9-15 22-34-32](https://user-images.githubusercontent.com/70558961/268312291-a168da87-76f1-45c7-93d1-c235f8971c6e.jpg)什么都没有
> 
> 你是如何安装该程序的？

我在[bilibili](https://www.bilibili.com/video/BV1LM4y1Z7y5/?spm_id_from=333.999.
![2023-9-16 10-31-19](https://github.com/dmMaze/BallonsTranslator/assets/70558961/5bfbd6a8-0b29-4a22-a27f-97104e161d57)
0.0) 了解到的这款应用，使用作者覆盖好python38.dll打包的软件，下载链接https://cowtransfer.com/s/ff0d6e84e1c64c

**Comment by dmMaze** [comment]
@55kai-niubi 大部分第三方分享都过时了，我也暂时不打算打包新版，你可以试试运行源码(参考 #160  #187)
不读图可能是因为你自己不知道什么时候转了文件格式, 或者这个版本就是不读.webp, 就算你用上新版我也建议你把这些老的生成文件(imgtrans_xxx.json啥的)先删掉
