### ISSUE TITLE
透明度滑块这里可以绑定快捷键吗

### ISSUE THREAD

**Issue by lhj5426** [dmMaze/BallonsTranslator#224]
![image](https://github.com/dmMaze/BallonsTranslator/assets/30548000/83e397ac-7921-4aff-a019-a9b339d574a4)

大佬就是这里 
可以设置2个快捷键吗 
一个是 按下之后 
嵌字图层100%
![image](https://github.com/dmMaze/BallonsTranslator/assets/30548000/a12413ec-e441-45c1-8136-5ce7a3116951)

  原图图层0 
![image](https://github.com/dmMaze/BallonsTranslator/assets/30548000/4f3bdfaa-6de8-432c-8ee6-1fb181bb7e91)

然后再设置一个 快捷键 反向的  
嵌字图层0
![image](https://github.com/dmMaze/BallonsTranslator/assets/30548000/9897a5ed-bb6c-42e3-98d8-7370731bb0a4)
原文图层
![image](https://github.com/dmMaze/BallonsTranslator/assets/30548000/918d1443-6e2b-4370-a831-1556c8624c12)

为什么要这么设置 呢
方便一键 在 翻译 和 原文 直接 快速切换

现在这样脱掉滑块 太慢了 

而且就是做了鼠标宏 也要疯狂点好几下 这2个滑块的 左边 右边 才能 到0  和100 的 透明度 

所以 如果 大佬 可以 设置2 组 快捷键的 话 会方便很多

或者直接在界面上 添加一个按钮 按钮 点击 就 原图0 嵌字100  再点击就 嵌字0 原图100 
也会比现在方便 
主要ocr 不是100%准确 方便 快速 查看 原文 对比oCR 识别结果
有时候读起来很别扭 就像快速看一下 是不是ocr 没O对 然后 再去重新翻译

https://github.com/dmMaze/BallonsTranslator/assets/30548000/66bddf94-30a7-4699-87b1-06413cd0baa6

现在这样 在滑块的顶端或者底端 都要点好几下 才能 到顶 到底

再或者  大佬 您把 滑块 的 2端 顶端 设置成 一键点击一下就到顶 到底
如果能点一下 滑道顶部 或者底部 也可以 用鼠标宏轻松的的实现一键 0 100

这样就可以 用宏绑定到 旋钮上 了
![image](https://github.com/dmMaze/BallonsTranslator/assets/30548000/00473da4-e047-4d08-b08c-fa5e1e1022d2)

现在用鼠标宏实现的就是这样

https://github.com/dmMaze/BallonsTranslator/assets/30548000/222466d5-c140-4322-ba44-7fb470914f88
对着 顶端或者底端疯狂点击
![image](https://github.com/dmMaze/BallonsTranslator/assets/30548000/a867ac15-8d53-4806-af6f-85a088c10c39)

**Comment by dmMaze** [comment]
26a0284 将数字键设为图层透明度快捷键。按下0-9会同时调整嵌字和原图层不透明度。嵌字层不透明度为0时再按0会置为100

**Comment by lhj5426** [comment]
> [26a0284](https://github.com/dmMaze/BallonsTranslator/commit/26a02843a5d4747b37a54d823d6098b42ea40dbf) 将数字键设为图层透明度快捷键。按下0-9会同时调整嵌字和原图层不透明度。嵌字层不透明度为0时再按0会置为100
 这个设置有意思哈哈  我更新去试试

**Comment by lhj5426** [comment]
好玩 感谢
