### ISSUE TITLE
chatGPT翻译报错。

### ISSUE THREAD

**Issue by dlslin** [dmMaze/BallonsTranslator#227]
使用chatgpt出现错误显示如下
 Restarting request due to ratelimiting by openai servers. Attempt: 2
[INFO   ] util:log_info:67 - error_code=insufficient_quota error_message='You exceeded your current quota, please check your plan and billing details.' error_param=None error_type=insufficient_quota message='OpenAI API error received' stream_error=False
已尝试过两个gpt的账号的api，应该不是账号的api的问题。。。
![图片](https://github.com/dmMaze/BallonsTranslator/assets/52952797/d415f86d-9641-41c4-91e0-a0766ef6044a)
![图片](https://github.com/dmMaze/BallonsTranslator/assets/52952797/ddece945-9403-42b8-9211-4388127d60dc)
![图片](https://github.com/dmMaze/BallonsTranslator/assets/52952797/8d6a81a3-22c8-46d7-9fe9-d83f44a0af86)

**Comment by dmMaze** [comment]
You exceeded your current quota, please check your plan and billing details
