### ISSUE TITLE
分页排序不恰当

### ISSUE THREAD

**Issue by 6486449j** [dmMaze/BallonsTranslator#228]
![image](https://github.com/dmMaze/BallonsTranslator/assets/27111822/c4814c82-4158-4601-a798-bcc0cee23572)

如图，合适的排序应该是1..2....10，而这里却优先根据第一位数字排了，翻阅起来很不方便

版本：dev分支

系统：arch linux

**Comment by bropines** [comment]
> ![image](https://user-images.githubusercontent.com/27111822/270098130-c4814c82-4158-4601-a798-bcc0cee23572.png)
> 
> 如图，合适的排序应该是1..2....10，而这里却优先根据第一位数字排了，翻阅起来很不方便
> 
> 版本：dev分支
> 
> 系统：arch linux

That's the norm). The problem is in the file names. You can fix it with a sorting crutch, but it's easier to use power rename from powertoys or Advanced Renamer for that.

**Comment by dmMaze** [comment]
da7a26d 已修

**Comment by Mistermozg1** [comment]
How to contact the developer. I even subscribed to patreon, but he doesn't answer me there)
My telegram @mistermo1

**Comment by Mistermozg1** [comment]
> [da7a26d](https://github.com/dmMaze/BallonsTranslator/commit/da7a26dfc8b5071fb5eb23f4d7f8b28abc6c03c7) 已修

I was wondering if there is any way to add a function to the python script to save the result as a psd or other file, so that images and text are saved as separate layers?

**Comment by bropines** [comment]
> > [da7a26d](https://github.com/dmMaze/BallonsTranslator/commit/da7a26dfc8b5071fb5eb23f4d7f8b28abc6c03c7) 已修
> 
> I was wondering if there is any way to add a function to the python script to save the result as a psd or other file, so that images and text are saved as separate layers?

I can ask what your native language is, I myself speak Russian and your nickname is a little strange to me. If you are subscribed to patreon, then you are subscribed to the developer of the manga translation algorithm, and not dmmaze, which develops and improves gui.
