### ISSUE TITLE
dev版无法启用cuda

### ISSUE THREAD

**Issue by blackpumpkin** [dmMaze/BallonsTranslator#233]
cpu切到cuda就会卡死并退出，但是已发行版的设置里自动就是cuda了，很神奇

**Comment by dmMaze** [comment]
你是如何运行dev版的? 如果是用源码覆盖发行版那试试找个干净的地方重开。
你用的python环境是自己配置的还是网盘里给的那个python，不管是哪种, 试试运行下面代码
``` python
import torch
torch.cuda.is_available()
```
如果有报错, 请给个报错信息和显卡型号

**Comment by blackpumpkin** [comment]
好的我来复现一下全部的操作：

1. 在git bash中依次运行以下指令 
```
git clone git@github.com:dmMaze/BallonsTranslator.git

cd BallonsTranslator

pip install -r requirements.txt

pip install torch torchvision torchaudio --index-url https://download.pytorch.org/whl/cu116
```

2. 从mega盘上下载了data文件夹，其中包含models、libs文件夹和pkusegscores.json，将以上复制到BallonsTranslator/data中（此处发现一个问题，从 MEGA or Google Drive下载data文件夹并移动到 BallonsTranslator/ballontranslator目录中，但是我clone的文件夹里面并没有发现ballontranslator，只是BallonsTranslator中有一个data文件夹，里面有个自带的pkusegscores.json，因此我将以上三者复制进其中并替换pkusegscores.json）
3. 打开launch_win.bat，此时cmd界面显示`[ERROR  ] launch:main:175 - [Errno 2] No such file or directory: 'E:\\Translator\\BallonsTranslator\\config/config.json'`，但仍然可以打开程序
4. 更改设置：Text Detection-device默认为cpu，切换为cuda时程序卡死并退出，cmd报错`RuntimeError: PyTorch is not linked with support for hip devices`
5. 运行作者大大上述代码```import torch
torch.cuda.is_available()```
仍然出现上述问题
显卡型号为RTX3060Laptop，python版本为3.11.6
![图1](https://github.com/dmMaze/BallonsTranslator/assets/51166905/728295e5-0c99-424d-ae51-e5a9a821f119)

**Comment by dmMaze** [comment]
> 5\. 运行作者大大上述代码`import torch torch.cuda.is_available()`
>     仍然出现上述问题

你运行这两行代码也报PyTorch is not linked with support for hip devices？

**Comment by blackpumpkin** [comment]
> > 5. 运行作者大大上述代码`import torch torch.cuda.is_available()`
> > 仍然出现上述问题
> 
> 你运行这两行代码也报PyTorch is not linked with support for hip devices？
是的，刚刚我在PyCharm里又运行了一遍，结果还是卡死并退出

**Comment by dmMaze** [comment]
> > > 5. 运行作者大大上述代码`import torch torch.cuda.is_available()`
> > >    仍然出现上述问题
> > 
> > 
> > 你运行这两行代码也报PyTorch is not linked with support for hip devices？
> > 是的，刚刚我在PyCharm里又运行了一遍，结果还是卡死并退出

如果仅运行这两行代码都报错就是你pytorch cuda安装的问题了... 建议重装pytorch, 完了再pull一下, 搞不顶配置环境你可以用网盘里那个ballontrans_pylibs_win那个包, 跑launch.bat

hip是给A卡用的(其实在win上还没法用)而且这个选项其实多余我给去掉了
