### ISSUE TITLE
可以在只有 方块的情况下可以进行ocr吗

### ISSUE THREAD

**Issue by lhj5426** [dmMaze/BallonsTranslator#237]
事情是这个样子滴
前几天 我跟GPT 实现了 2个漫画软件 
的JSON 互相转换 脚本
BallonTranslator转ImageTrans
ImageTransz转BallonTranslator
![image](https://github.com/dmMaze/BallonsTranslator/assets/30548000/9e07e969-9f57-4a9d-9d24-297e94c8ebe2)
转换完之后 如图 是缺少一部分数据的
在这个情况下
可以把另外一个软件识别的字幕框复刻移植过来
![image](https://github.com/dmMaze/BallonsTranslator/assets/30548000/712ab095-777f-4436-a273-abe86b0c36f6)
像这样 不过 在这个情况下直接运行 OCR 是无法进行ocr的

然后呢 如果切换到
![image](https://github.com/dmMaze/BallonsTranslator/assets/30548000/9fab968b-d2e9-4a28-86f6-67acc40e6950)

这个OCR 之后 在页面上 ctrl + A 全选 然后右键 就可以OCR到
所以 想问下 开发者大佬 能不能 在 只有 文本框的情况下进行OCR ?

**Comment by lhj5426** [comment]
为什么这么做呢 2个软件 各有优缺点 作为一个成年人 肯定是
![image](https://github.com/dmMaze/BallonsTranslator/assets/30548000/c5294ba0-7828-489e-ab19-38c456340a00)
BallonTranslator 这边 ocr速度快 但是 文字框选 太啰嗦了 经常会把无关的拟声词也选上 修理要修理好半天 
所以选择用ImageTrans 识别 气泡文字  然后 用BallonTranslator来  OCR

**Comment by lhj5426** [comment]
然后就想如果能再只有框线气泡的情况下 运行OCR 也能OCR就好了

**Comment by lhj5426** [comment]
然后如果在这个情况下重新检测呢 又会覆盖 已经复刻过来的气泡

**Comment by dmMaze** [comment]
R18示例图最好打个码
https://docs.github.com/zh/site-policy/acceptable-use-policies/github-sexually-obscene-content

**Comment by lhj5426** [comment]
> R18示例图最好打个码 https://docs.github.com/zh/site-policy/acceptable-use-policies/github-sexually-obscene-content

抱歉 我把那张图去掉 了 是我疏忽了
