### ISSUE TITLE
Font format not working

### ISSUE THREAD

**Issue by hollobar** [dmMaze/BallonsTranslator#250]
1. I instell use Auto installer. 
2. Change Global Font Format and run translator, My options don't apply. only effect option apply.
-> I scellect lettering option all 'use global setting', uncheck ' Auto layout'.
3. When I change Global Font Format, cmd show me [AttributeError: 'NoneType' object has no attribute 'get']

This problem was not found 1.3.0-core and 1.3.5,

Use instell [gitBash], font format is working, but font size is sometime not working. I set font size 18, translated file's font is 13.

**Comment by bropines** [comment]
> 1. I instell use Auto installer.
> 2. Change Global Font Format and run translator, My options don't apply. only effect option apply.
>    -> I scellect lettering option all 'use global setting', uncheck ' Auto layout'.
> 3. When I change Global Font Format, cmd show me [AttributeError: 'NoneType' object has no attribute 'get']
> 
> This problem was not found 1.3.0-core and 1.3.5,
> 
> Use instell [gitBash], font format is working, but font size is sometime not working. I set font size 18, translated file's font is 13.

Maybe it's a glitch in my config. Try deleting the config and let the program create it itself

Here is the path to the config:
`Ballon-translator-portable-main\config\config.json`

Also, you do not need to install core, all libraries are loaded by the auto-installer themselves, just like my config. If deleting the config fixes everything, I'll remove it from the download.

**Comment by dmMaze** [comment]
> When I change Global Font Format, cmd show me [AttributeError: 'NoneType' object has no attribute 'get']

fixed by https://github.com/dmMaze/BallonsTranslator/commit/0c4e98bdf6f6eed8c7ac4c3c43d8e026904b9e9e 
run git pull to get the update

the font size will be recalculated if autolayout is checked

**Comment by hollobar** [comment]
> > 1. I instell use Auto installer.
> > 2. Change Global Font Format and run translator, My options don't apply. only effect option apply.
> >    -> I scellect lettering option all 'use global setting', uncheck ' Auto layout'.
> > 3. When I change Global Font Format, cmd show me [AttributeError: 'NoneType' object has no attribute 'get']
> > 
> > This problem was not found 1.3.0-core and 1.3.5,
> > Use instell [gitBash], font format is working, but font size is sometime not working. I set font size 18, translated file's font is 13.
> 
> Maybe it's a glitch in my config. Try deleting the config and let the program create it itself
> 
> Here is the path to the config: `Ballon-translator-portable-main\config\config.json`
> 
> Also, you do not need to install core, all libraries are loaded by the auto-installer themselves, just like my config. If deleting the config fixes everything, I'll remove it from the download.

Thanks for answering me.
I did as you said deleting 'config.json' file and restart program, It works

And core is Auto installer's BallonsTranslator have something problem. so i tset gitbush instell, core and 1.3.5 BallonsTranslator
thank you for the program you created.
I'll have to use it more, but your solution works well for now.

**Comment by bropines** [comment]
> Thanks for answering me. I did as you said deleting 'config.json' file and restart program, It works
> 
> And instell core is Auto installer's BallonsTranslator have something problem. so i tset gitbush instell, core and 1.3.5 BallonsTranslator thank you for the program you created. I'll have to use it more, but your solution works well for now.

Hmmmm. I'll recheck the auto-installer today, I want to understand what the problems are there. In fact, everything you need is downloaded without unnecessary stuff, and the repository is taken from here. And the author is DmMaze)

**Comment by hollobar** [comment]
> > Thanks for answering me. I did as you said deleting 'config.json' file and restart program, It works
> > And instell core is Auto installer's BallonsTranslator have something problem. so i tset gitbush instell, core and 1.3.5 BallonsTranslator thank you for the program you created. I'll have to use it more, but your solution works well for now.
> 
> Hmmmm. I'll recheck the auto-installer today, I want to understand what the problems are there. In fact, everything you need is downloaded without unnecessary stuff, and the repository is taken from here. And the author is DmMaze)

Oh I thought you made auto installer so I wanted to say thank you.
I know DmMaze is the author. Looking at the above text, you may think that I have mistaken the author.

**Comment by hollobar** [comment]
> > When I change Global Font Format, cmd show me [AttributeError: 'NoneType' object has no attribute 'get']
> 
> fixed by [0c4e98b](https://github.com/dmMaze/BallonsTranslator/commit/0c4e98bdf6f6eed8c7ac4c3c43d8e026904b9e9e) run git pull to get the update
> 
> the font size will be recalculated if autolayout is checked

Sorry for the delay in thanking Dev DmMaze.
I used it again after the update as you answered. Now the font size is saved in the file as I set it.
Thank you so much for developing this program.

**Comment by bropines** [comment]
> Oh I thought you made auto installer so I wanted to say thank you.
> I know DmMaze is the author. Looking at the above text, you may think that I have mistaken the author.

So. I'm stupid (my English is even worse). The program was written by the great DmMaze, I spent a couple of hours making an auto-installer. In fact, he loads Python and Git himself, so as not to load them separately. And then it downloads the models, that is, what is stored in Core 1.3.5. 

That's why
Auto installer - questions to @bropines
Questions about theprogram - dmMaze 

Someday I'll have to sign whoever made the auto installer so they can come and beat me with slippers
