### ISSUE TITLE
Free chatgpt?

### ISSUE THREAD

**Issue by dhana-exe** [dmMaze/BallonsTranslator#251]
can't we using free chatgpt? (for now version GPT-3.5 model)
from https://chat.openai.com/ 
example https://chat.openai.com/c/fd38ad79-8a6f-4095-b595-xxxxx (the chat window)
maybe with approach like take the session or something like that?

i been translating something like
"第２話せきばくこ いびっなり" and the result from other Online translator is very funny and seems goes far from the meaning
while on there (chatgpt free 3.5) i just need to write
**"第２話せきばくこ いびっなり" translate common ways** 
and they translated in few second and the result is consistent

any vision to add Free Chatgpt? i think any ways to make it works is okay.....

**Comment by dmMaze** [comment]
Some automatic stuff with selenium probably would work, but i neither have time nor interested, you may ask chatgpt to hack itself

**Comment by bropines** [comment]
> Some automatic stuff with selenium probably would work, but i neither have time nor interested, you may ask chatgpt to hack itself

Alas, I tried. It works, and then protection against automation from cloudflyer turns on
