### ISSUE TITLE
resize.cpp:4052: error: (-215:Assertion failed) !ssize.empty() in function 'cv::resize'

### ISSUE THREAD

**Issue by j6qup3** [dmMaze/BallonsTranslator#252]
翻了一下好像沒人提出過這issue

今天Run時出現以下錯誤並閃退

```
Traceback (most recent call last):
  File "D:\AI\BallonTranslator\ui\mainwindow.py", line 430, in pageListCurrentItemChanged
  File "D:\AI\BallonTranslator\ui\scenetext_manager.py", line 334, in updateSceneTextitems
  File "D:\AI\BallonTranslator\ui\scenetext_manager.py", line 352, in addTextBlock
  File "D:\AI\BallonTranslator\ui\scenetext_manager.py", line 606, in layout_textblk
  File "D:\AI\BallonTranslator\utils\imgproc_utils.py", line 275, in extract_ballon_region
cv2.error: OpenCV(4.5.5) E:\packages\opencv-4.5.5\modules\imgproc\src\resize.cpp:4052: error: (-215:Assertion failed) !ssize.empty() in function 'cv::resize'
```

之後 Run 了幾次經過交叉比對確認是某頁的問題，移除就不會報錯，想問一下有方法可以解決嗎，不然單獨的頁處理起來也很麻煩

**Comment by j6qup3** [comment]
![205](https://github.com/dmMaze/BallonsTranslator/assets/11219909/61fcf5f3-00d9-40e7-bb4b-2cd0701989db)

設置參數我印象中沒什麼動過
文字偵測 ctd/1280/4/cuda
OCR mit48px_ctc/16/cuda
Inprint iama_mpe/2048/cuda

**Comment by dmMaze** [comment]
我没法复现，你翻译时的目标语言是 ？你使用的软件版本是？

**Comment by j6qup3** [comment]
繁體中文
1.3.35

**Comment by dmMaze** [comment]
这个bug在dev分支应该是修过了，目前出于各种原因没更新打包发布版，可以尝试运行dev分支，教程如下：
https://github.com/dmMaze/BallonsTranslator/issues/160#issuecomment-1602064296

**Comment by j6qup3** [comment]
好的，我稍後來試試，先close了，如果不行再開

**Comment by j6qup3** [comment]
使用dev版後可以順利Run完了，感謝協助

**Comment by wagannan** [comment]
> 使用dev版本後可以順利運行完成，感謝幫助

請問可以教我嗎?!
我目前也遇到這個問題 
![image](https://github.com/user-attachments/assets/3223ba21-559e-4387-ad3a-b4cb4b63274a)
我看了#160 也是不懂怎麼操作 ...

**Comment by j6qup3** [comment]
> > 使用dev版本後可以順利運行完成，感謝幫助
> 
> 請問可以教我嗎?! 我目前也遇到這個問題 ![Snipaste_2024-08-14_14-52-28](https://private-user-images.githubusercontent.com/98313788/357706491-b19746a0-f52f-4073-a7c9-672e82a71c2e.jpg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjM2NTc5MjUsIm5iZiI6MTcyMzY1NzYyNSwicGF0aCI6Ii85ODMxMzc4OC8zNTc3MDY0OTEtYjE5NzQ2YTAtZjUyZi00MDczLWE3YzktNjcyZTgyYTcxYzJlLmpwZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA4MTQlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwODE0VDE3NDcwNVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWFhZjQ4MzE5NWRlYmViZmUzMWE2ZDkxOTY4ODk3Y2E5ZDVhMzA4ZDY5MTU1YjQ1ZTA5NDYxYjUxMjdjNGRkOTImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.zRLT16OqM6LYrxZclYuB7xWn00X1KD2-8LjpUB1p6C0)
> 
> 我看了#160 也是不懂怎麼操作 ...

作者已經更新打包版了，如果你用1.4.0還是沒辦法的話只能等作者回答了

**Comment by wagannan** [comment]
> > > 使用dev版本後可以順利運行完成，感謝幫助
> > 
> > 
> > 請問可以教我嗎？ 我目前也遇到了這個問題![Snipaste_2024-08-14_14-52-28](https://private-user-images.githubusercontent.com/98313788/357706491-b19746a0-f52f-4073-a7c9-672e82a71c2e.jpg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjM2NTc5MjUsIm5iZiI6MTcyMzY1NzYyNSwicGF0aCI6Ii85ODMxMzc4OC8zNTc3MDY0OTEtYjE5NzQ2YTAtZjUyZi00MDczLWE3YzktNjcyZTgyYTcxYzJlLmpwZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA4MTQlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwODE0VDE3NDcwNVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWFhZjQ4MzE5NWRlYmViZmUzMWE2ZDkxOTY4ODk3Y2E5ZDVhMzA4ZDY5MTU1YjQ1ZTA5NDYxYjUxMjdjNGRkOTImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.zRLT16OqM6LYrxZclYuB7xWn00X1KD2-8LjpUB1p6C0)
> > 我看了#160也不懂怎麼操作...
> 
> 作者已經更新資源版本了，如果你用1.4.0沒辦法的話只能等作者回答了

好的謝謝您 因為我也不知道是甚麼狀況 我也不了解編碼 都跟著別人一步一步做
但還是只有幾頁圖片會這樣
