### ISSUE TITLE
free deepl translator not working

### ISSUE THREAD

**Issue by papaj-na-wrotkach** [dmMaze/BallonsTranslator#254]
First of all, I would like to express my utmost appreciation. 
Thank you for such a great piece of software! It's really useful for improving your language skills by translating comics when you don't want to clean up and redraw the pages. The application does the work for you, and the quality of the work is by no means inferior to what a human could do!

While playing around with the various options of the application, I came across a bug. After changing `Translator` to `DeepL Free` I cannot translate anything automatically. In the logs I get the following:
```
[INFO   ] _client:_send_single_request:1013 - HTTP Request: %s %s "%s %d %s"
Error 400
```
I can use DeepL at [deepl.com](https://deepl.com) normally (in fact, it helped me formulate this problem). After further investigation with HTTP Toolkit, I discovered that the server returns a response that indicates an incorrect value for `target_lang`.

request:
```http
POST https://www2.deepl.com/jsonrpc HTTP/1.1
Accept: */*
Accept-Encoding: gzip, deflate, br
Accept-Language: en-US,en;q=0.9
Connection: keep-alive
Content-Length: 382
Content-Type: application/json
Host: www2.deepl.com
User-Agent: DeepL-iOS/2.9.1 iOS 16.3.0 (iPhone13,2)
x-app-build: 510265
x-app-device: iPhone13,2
x-app-os-name: iOS
x-app-os-version: 16.3.0
x-app-version: 2.9.1

{
  "jsonrpc": "2.0",
  "method": "LMT_handle_texts",
  "id": 8382178000,
  "params": {
    "texts": [
      {
        "text": "はい！この棍棒でわたしを滅多打ちにしてください",
        "requestAlternatives": 0
      }
    ],
    "splitting": "newlines",
    "lang": {
      "source_lang_user_selected": "ja",
      "target_lang": "EN-US"
    },
    "timestamp": 1697666385125,
    "commonJobParams": {
      "wasSpoken": false,
      "transcribe_as": ""
    }
  }
}
```

response:
```http
HTTP/1.1 400 Bad Request
access-control-expose-headers: Server-Timing
content-type: application/json; charset=utf-8
date: Wed, 18 Oct 2023 21:59:45 GMT
server-timing: l7_lb_tls;dur=82, l7_lb_idle;dur=0, l7_lb_receive;dur=2, l7_lb_total;dur=85
set-cookie: LMTBID=v2|d155f927-d2dc-47a7-9ae3-0779c45b1216|e9064523513a79c85e7c295271f3dd79; version=1; Path=/; Domain=.deepl.com; Secure; HttpOnly; Expires=Thu, 18-Apr-2024 00:00:00 GMT
strict-transport-security: max-age=63072000; includeSubDomains; preload
transfer-encoding: chunked

{
  "jsonrpc": "2.0",
  "id": -207756592,
  "error": {
    "code": -32600,
    "message": "Invalid Request",
    "data": {
      "what": "Invalid target_lang."
    }
  }
}
```

Info from the app output:
py version:  3.11.5 (main, Sep  2 2023, 14:16:33) [GCC 13.2.1 20230801]
py executable:  **_PATH OMMITED_**/BallonsTranslator/venv/bin/python
version: 1.4.0
branch: dev
Commit hash: 580ecca84182c17db6414637e8c9033742a9fe38

**Comment by dmMaze** [comment]
So its more like the "free" version messed up the translation
https://github.com/dmMaze/BallonsTranslator/blob/d0a50418d4b47e80d7eaa9956cc9bb24bf90bed9/modules/translators/base.py#L159-L160
For those translators which don't support a text list as input, the source lines in a page were concatenated to a string, separated by some line breaker, and the translation was split by the same breaker afterward. So if the translator messed up these breakers would result in inconsistency.

**Comment by papaj-na-wrotkach** [comment]
> For those translators which don't support a text list as input, the source lines in a page were concatenated to a string, separated by some line breaker, and the translation was split by the same breaker afterward. So if the translator messed up these breakers would result in inconsistency.

I think it's a good idea to concatenate them, because this way - as opposed to sending a separate request for each line - DeepL can more or less guess the context and choose a better translation based on that.

> [d0a5041](https://github.com/dmMaze/BallonsTranslator/commit/d0a50418d4b47e80d7eaa9956cc9bb24bf90bed9) may fix it for deepl free, temporarily perhaps, but I haven't run enough text to make sure and it keeps blocking my ip.

If you request translation of more than one "bubble" per time, DeepL blocks your IP for some time and the app crashes.
```
Traceback (most recent call last):
  File "/home/lolicon/.pkgsrc/ballonstranslator-git/src/BallonsTranslator/ui/module_manager.py", line 420, in run
    self.job()
  File "/home/lolicon/.pkgsrc/ballonstranslator-git/src/BallonsTranslator/ui/module_manager.py", line 304, in <lambda>
    self.job = lambda : self._blktrans_pipeline(blk_list, tgt_img, mode, blk_ids)
                        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/lolicon/.pkgsrc/ballonstranslator-git/src/BallonsTranslator/ui/module_manager.py", line 312, in _blktrans_pipeline
    self.translate_thread.module.translate_textblk_lst(blk_list)
  File "/home/lolicon/.pkgsrc/ballonstranslator-git/src/BallonsTranslator/modules/translators/base.py", line 183, in translate_textblk_lst
    translations = self.translate(text_list)
                   ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/lolicon/.pkgsrc/ballonstranslator-git/src/BallonsTranslator/modules/translators/base.py", line 145, in translate
    text_trans = self._translate([text_source])[0]
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/lolicon/.pkgsrc/ballonstranslator-git/src/BallonsTranslator/modules/translators/trans_deeplx.py", line 230, in _translate
    tl = translate(t,source,target)
         ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/lolicon/.pkgsrc/ballonstranslator-git/src/BallonsTranslator/modules/translators/trans_deeplx.py", line 153, in translate
    raise TooManyRequestsException
modules.translators.trans_deeplx.TooManyRequestsException: Error: Too many requests, your IP has been blocked by DeepL temporarily, please don't request it frequently in a short time.
zsh: IOT instruction (core dumped)  LD_PRELOAD=/usr/lib/libgomp.so python launch.py
```
Maybe you could use a request limiter and have the application display an error message instead of crashing when a `TooManyRequestsException` exception is thrown...

**Comment by dmMaze** [comment]
> Maybe you could use a request limiter 

there is a delay parameter for each online translator in the config panel

**Comment by papaj-na-wrotkach** [comment]
Thanks! I changed the parameter and it's working without issues. I am closing this as the issue is resolved for now.
