### ISSUE TITLE
OCR的替换数据存在哪里呀

### ISSUE THREAD

**Issue by lhj5426** [dmMaze/BallonsTranslator#255]
大佬是这样子我自己在做 OCR 的拟声字 替换数据
![image](https://github.com/dmMaze/BallonsTranslator/assets/30548000/6783097e-505f-4d7a-a864-56268c157021)
但是做的多了... 列表很长 而且 没有查询
所以我想这些东西应该是存在软件的某个文件里吧?
能告诉我 这个数据存在软件的哪个目录下的哪个文件里吗
这样一个方便添加 一个用文本工具也方便查选.
主要还是为了方便查询 

因为我发现这个ocr每一页 每次重新OCR内容是一样的
这样 做一个替换为空的替换 积累的多了 再 下次再跑其他漫画的时候 就可以直接被替换
非常的方便..  不过就多了不好查询 是否添加过  所以想知道具体存放在哪里

**Comment by lhj5426** [comment]
如果可以的话 要是可以 在替换为空的时候自动删除空白的气泡就更好了 哈哈

**Comment by lhj5426** [comment]
然后还有这种 无法被替换的 无论是正则 还是普通都无效的

这个 字符串  ぞくぬち”
![image](https://github.com/dmMaze/BallonsTranslator/assets/30548000/f0195c55-2543-4734-a2a8-5d98d9f33b47)

**Comment by lhj5426** [comment]
还有为了测试单页方便可以增加个单页进行重新ocr么
![image](https://github.com/dmMaze/BallonsTranslator/assets/30548000/4dccbe30-886a-4648-a46a-42696caad95f)
我现在是
新建个文件夹每次放一张图进去
然后用鼠标宏 
这样 单页OCR 测试 
![image](https://github.com/dmMaze/BallonsTranslator/assets/30548000/6d2bab19-c0c5-48f9-b291-6cb18dcf5efd)

![image](https://github.com/dmMaze/BallonsTranslator/assets/30548000/bef531de-30a5-4ab1-910e-10cc117912eb)

**Comment by dmMaze** [comment]
所有界面参数都在config/config.json里，ocr替换内容在"ocr_sublist"下面

**Comment by lhj5426** [comment]
> 所有界面参数都在config/config.json里，ocr替换内容在"ocr_sublist"下面

![image](https://github.com/dmMaze/BallonsTranslator/assets/30548000/a3cd7180-ccb0-49c5-b285-e571bcc60df8)
但是 好像对不上？ 我在软件里添加了1000条 
我电脑里 D:\BL\BallonsTranslator\config\config.json 的这个配置 才200多？

**Comment by lhj5426** [comment]
![image](https://github.com/dmMaze/BallonsTranslator/assets/30548000/cd2aea56-5835-4232-97de-deec274674cb)
这种 也 无法 被替换   主っぁっ元ッ♡

**Comment by dmMaze** [comment]
你可能需要保存一些设置，从设置面板切回显示漫画的页面或者退出程序能保存设置，你可以看下config.json最后修改时间确认已经是最近保存的

**Comment by lhj5426** [comment]
> 你可能需要保存一下设置，从设置面板切回显示漫画的页面或者退出程序能保存设置，你可以看下config.json最后修改时间确认已经是最近保存的

![image](https://github.com/dmMaze/BallonsTranslator/assets/30548000/87df004f-b80c-4c5c-b715-33bb17a265d9)
大佬 我 按照您说 保存了项目然后关闭了软件  查看了配置的更新时间 然后 打开 还是200多

**Comment by dmMaze** [comment]
是不是你vscode又保存了一下把本地的给盖了
你重新打开软件还是有1000多条吗

**Comment by lhj5426** [comment]
> 是不是你vscode又保存了一下把本地的给盖了 你重新打开软件还是有1000多条吗

经您这么一说 我换两个 查看器
![image](https://github.com/dmMaze/BallonsTranslator/assets/30548000/2e134648-fae8-49bf-b8f8-10af68d41244)
虽然不 知道数量 但是 可以和软件上的对上了
