### ISSUE TITLE
我主要是日文黑白漫画，请问OCR，图像修复里面，应该选择什么设置效果比较好？

### ISSUE THREAD

**Issue by fanglangxinghai** [dmMaze/BallonsTranslator#256]
如题

**Comment by dmMaze** [comment]
如果背景是全白那都差不多，如果修复的地方主要是某些材质选patchmatch比较好，否则就lamampe，如果修复看起来非常脏就在画板里拉一下那个kernel size膨胀一下mask，如果你还是觉得结果不行那就没必要再试了

我最近在试微调sd 1.5那些东西去搞日漫，现在合成结果看起来还挺像样。但是用来做漫画inpainting这种场景考虑显存开销和VAE重建啥的可能还得先把分镜截出来一个一个做。我有空了也会用新数据重新finetune一个lama

**Comment by dmMaze** [comment]
新加的lama_large_512px在日漫上表现更好，详见https://huggingface.co/dreMaz/AnimeMangaInpainting/blob/main/README.md

**Comment by fanglangxinghai** [comment]
> 新加的lama_large_512px在日漫上表现更好，详见https://huggingface.co/dreMaz/AnimeMangaInpainting/blob/main/README.md 直接拉最新源码后launch自动下载

。。。下载过google drive里的BallonsTranslator_dev_src_with_gitpython，然后运行launch.bat，安装到最后失败。然后手动下载data和ballontrans_pylibs_win.7z，覆盖进去，运行scripts/local_gitpull.bat，显示“fatal: unable to access 'https://github.com/dmMaze/BallonsTranslator/': Recv failure: Connection was reset”

真的是搞不来。。

**Comment by dmMaze** [comment]
@fanglangxinghai 那个config报错不用管
你需要重新下载一下BallonsTranslator_dev_src_with_gitpython.7z然后解压覆盖
启动时如果报丢模型手动下载网盘里的data/models/lama_large_512px.ckpt (刚上传的)放到对应位置

**Comment by fanglangxinghai** [comment]
@dmMaze 
感谢你的耐心回复，现在我打开local_gitpull.bat后显示更新到最新版本了，但是现在应该怎么打开软件呢？我没有看到exe文件。打开launch.bat，依旧是显示config的错误。。。我暂时是放弃了。。。

**Comment by dmMaze** [comment]
> @dmMaze 感谢你的耐心回复，现在我打开local_gitpull.bat后显示更新到最新版本了，但是现在应该怎么打开软件呢？我没有看到exe文件。打开launch.bat，依旧是显示config的错误。。。我暂时是放弃了。。。

啊就直接launch.bat啊，那个config错误不用管，出界面了吧，你随便跑一下看没问题就行了

**Comment by fanglangxinghai** [comment]
@dmMaze 
![2023-11-12 02_27_21-Window](https://github.com/dmMaze/BallonsTranslator/assets/55346060/164f49c9-5c0d-481a-9c64-6249929f357c)
哦，好像问题不是config，是“IndexError: list index out of range”，这是什么问题？你解决不了也无所谓的，已经麻烦你很多时间回复了，老版本用着也还行。

**Comment by dmMaze** [comment]
> @dmMaze ![2023-11-12 02_27_21-Window](https://user-images.githubusercontent.com/55346060/282259548-164f49c9-5c0d-481a-9c64-6249929f357c.jpg) 哦，好像问题不是config，是“IndexError: list index out of range”，这是什么问题？你解决不了也无所谓的，已经麻烦你很多时间回复了，老版本用着也还行。

b87ce79 修了，这样试错并发现问题并不只是利己的

**Comment by fanglangxinghai** [comment]
@dmMaze 
非常感谢，现在能正常打开了。我提几个建议：

1. 设置中的OCR部分的“忽略OCR结果为空的区域”这个选项，最好默认打开。如果关闭的话，就会导致翻译串行。比如第6个OCR结果为空，第7个OCR到了日文，那么会导致，第7个的翻译内容被嵌到了第6个的位置，第8个的的翻译内容被嵌到了第7个的位置......
![1](https://github.com/dmMaze/BallonsTranslator/assets/55346060/f3bcb87c-5100-4e17-b6f4-1a67639736ca)

2. 希望在软件内可以随时方便切换到当前页对应的日文原图，进行对比。
3. OCR一些框外的日文，经常会出现日文字被涂白的现象，希望图像修复的能好一些。
![Snipaste_2023-11-12_14-30-49](https://github.com/dmMaze/BallonsTranslator/assets/55346060/becce815-8599-4043-812c-a0d55cede81b)
![Snipaste_2023-11-12_14-29-39](https://github.com/dmMaze/BallonsTranslator/assets/55346060/723bb2c7-2c5d-4bdb-95ff-24cdcc6a187c)

**Comment by dmMaze** [comment]
> 1. 设置中的OCR部分的“忽略OCR结果为空的区域”这个选项，最好默认打开。如果关闭的话，就会导致翻译串行。比如第6个OCR结果为空，第7个OCR到了日文，那么会导致，第7个的翻译内容被嵌到了第6个的位置，第8个的的翻译内容被嵌到了第7个的位置......

不勾选也不应该串行，fb540ac 修了

> 2. 希望在软件内可以随时方便切换到当前页对应的日文原图，进行对比。

数字键可以调嵌字层和原图相对透明度，按0就两者间切换



> 3\. OCR一些框外的日文，经常会出现日文字被涂白的现象，希望图像修复的能好一些。

这个问题应该不是框外是字有白边，暂时只能膨胀掩膜(前面提到的)了
