### ISSUE TITLE
mac构建版本manga-ocr无法使用

### ISSUE THREAD

**Issue by longyiqiang** [dmMaze/BallonsTranslator#257]
提示信息为
`Failed to set manga_ocr: No package metadata was found for The 'tqdm>=4.27' distribution was not found and is required by this application`
已经安装相关依赖
torch==2.2.0.dev20231022
torch-summary==1.4.5
torchaudio==2.2.0.dev20231022
torchvision==0.17.0.dev20231022
tqdm==4.66.1
transformers==4.34.1
据推测为编译时未引入对应包
mps构建后倒是成功运行

**Comment by longyiqiang** [comment]
@hyrulelinks 还望不吝赐教

**Comment by bropines** [comment]
> @hyrulelinks 还望不吝赐教

Did you install the dev version?

**Comment by longyiqiang** [comment]
sure,all the other can run successfully.

**Comment by dmMaze** [comment]
可以参考下https://github.com/pyinstaller/pyinstaller/issues/5878

**Comment by longyiqiang** [comment]
> 可以参考下[pyinstaller/pyinstaller#5878](https://github.com/pyinstaller/pyinstaller/issues/5878)

感谢作者大大的回复，折腾了两天还是放弃了，mac端ui有许多的小毛病，很多按钮完全没反应，只能一次性全部跑完所选图片。可能是我本地环境有问题。m1的性能跑起来速度倒是可以，平均1分钟5-10张比t4要快。不能顺畅使用太可惜了。

**Comment by hyrulelinks** [comment]
抱歉这两天忙没看到，请问是从源代码运行还是打包成app运行？虚拟环境依赖是否安装齐全？请检查下manga ocr的data是否下载完整，因为是从huggingface下载，有时候文件下载了其实不完整，也会运行报错

我这边打包好的app的ui正常，并未能复现上面的报错，是否是用一键打包脚本打包的？打包脚本的运行输出信息贴一下方便我查找问题@longyiqiang

**Comment by longyiqiang** [comment]
感谢回复。
打包运行的，按照readme安装了相关组件和data，文件树与展示的一致，文件是否完好不确定没有md5校验，从说给mega下载。
使用的一件打包脚本，运行输出信息没有留存，现在也无法复现了，相关的环境和软件我都已经删除。
ui问题具体来说就是对于单个图片进行编辑时，右键功能失效，运行相应的翻译，ocr，和重绘没反应，sync直接卡死。
而且运行中，所有的窗口都不能移动，运行信息窗口置顶无法隐藏。
再次感谢您的回复，抱歉没法提供更详细的输出信息和日志。

**Comment by longyiqiang** [comment]
重现了，打包后还是失败。
STEP 7: Delete .DS_Store files.
INFO: Permission required to delete .DS_Store files.
Password:
.//ui/.DS_Store
.//.DS_Store
.//venv/.DS_Store
.//venv/lib/python3.11/site-packages/.DS_Store
.//.git/.DS_Store
.//modules/.DS_Store
.//data/.DS_Store
.//data/models/.DS_Store
INFO: ✅ .DS_Store files all deleted.
STEP 8: Create packaged app.
INFO: Use the pyinstaller spec file to bundle the app.
120 INFO: PyInstaller: 6.1.0
120 INFO: Python: 3.11.6
128 INFO: Platform: macOS-14.0-arm64-arm-64bit
146 INFO: Extending PYTHONPATH with paths
['/Users/expoem/Dev/BallonsTranslator',
 '/Users/expoem/Dev/BallonsTranslator/scripts']
351 INFO: Appending 'datas' from .spec
363 INFO: checking Analysis
363 INFO: Building Analysis because Analysis-00.toc is non existent
363 INFO: Initializing module dependency graph...
364 INFO: Caching module graph hooks...
368 INFO: Analyzing base_library.zip ...
798 INFO: Loading module hook 'hook-heapq.py' from '/Users/expoem/Dev/BallonsTranslator/venv/lib/python3.11/site-packages/PyInstaller/hooks'...
838 INFO: Loading module hook 'hook-encodings.py' from '/Users/expoem/Dev/BallonsTranslator/venv/lib/python3.11/site-packages/PyInstaller/hooks'...
1519 INFO: Loading module hook 'hook-pickle.py' from '/Users/expoem/Dev/BallonsTranslator/venv/lib/python3.11/site-packages/PyInstaller/hooks'...
2229 INFO: Caching module dependency graph...
2274 INFO: Running Analysis Analysis-00.toc
2274 INFO: Looking for Python shared library...
2277 INFO: Using Python shared library: /opt/homebrew/Cellar/python@3.11/3.11.6/Frameworks/Python.framework/Versions/3.11/Python
2277 INFO: Analyzing /Users/expoem/Dev/BallonsTranslator/launch.py
2318 INFO: Loading module hook 'hook-pkg_resources.py' from '/Users/expoem/Dev/BallonsTranslator/venv/lib/python3.11/site-packages/PyInstaller/hooks'...
2671 INFO: Loading module hook 'hook-platform.py' from '/Users/expoem/Dev/BallonsTranslator/venv/lib/python3.11/site-packages/PyInstaller/hooks'...
2686 INFO: Loading module hook 'hook-xml.py' from '/Users/expoem/Dev/BallonsTranslator/venv/lib/python3.11/site-packages/PyInstaller/hooks'...
2702 INFO: Loading module hook 'hook-sysconfig.py' from '/Users/expoem/Dev/BallonsTranslator/venv/lib/python3.11/site-packages/PyInstaller/hooks'...
2754 INFO: Loading module hook 'hook-packaging.py' from '/Users/expoem/Dev/BallonsTranslator/venv/lib/python3.11/site-packages/PyInstaller/hooks'...
2800 INFO: Loading module hook 'hook-cv2.py' from '/Users/expoem/Dev/BallonsTranslator/venv/lib/python3.11/site-packages/_pyinstaller_hooks_contrib/hooks/stdhooks'...
3208 INFO: Loading module hook 'hook-numpy.py' from '/Users/expoem/Dev/BallonsTranslator/venv/lib/python3.11/site-packages/numpy/_pyinstaller'...
3473 INFO: Loading module hook 'hook-difflib.py' from '/Users/expoem/Dev/BallonsTranslator/venv/lib/python3.11/site-packages/PyInstaller/hooks'...
3581 INFO: Loading module hook 'hook-multiprocessing.util.py' from '/Users/expoem/Dev/BallonsTranslator/venv/lib/python3.11/site-packages/PyInstaller/hooks'...
4878 INFO: Processing pre-safe import module hook urllib3.packages.six.moves from '/Users/expoem/Dev/BallonsTranslator/venv/lib/python3.11/site-packages/PyInstaller/hooks/pre_safe_import_module/hook-urllib3.packages.six.moves.py'.
5122 INFO: Loading module hook 'hook-charset_normalizer.py' from '/Users/expoem/Dev/BallonsTranslator/venv/lib/python3.11/site-packages/_pyinstaller_hooks_contrib/hooks/stdhooks'...
5182 INFO: Loading module hook 'hook-certifi.py' from '/Users/expoem/Dev/BallonsTranslator/venv/lib/python3.11/site-packages/_pyinstaller_hooks_contrib/hooks/stdhooks'...
5236 INFO: Loading module hook 'hook-PIL.py' from '/Users/expoem/Dev/BallonsTranslator/venv/lib/python3.11/site-packages/PyInstaller/hooks'...
5275 INFO: Loading module hook 'hook-PIL.Image.py' from '/Users/expoem/Dev/BallonsTranslator/venv/lib/python3.11/site-packages/PyInstaller/hooks'...
5561 INFO: Loading module hook 'hook-PIL.ImageFilter.py' from '/Users/expoem/Dev/BallonsTranslator/venv/lib/python3.11/site-packages/PyInstaller/hooks'...
5649 INFO: Loading module hook 'hook-shapely.py' from '/Users/expoem/Dev/BallonsTranslator/venv/lib/python3.11/site-packages/_pyinstaller_hooks_contrib/hooks/stdhooks'...
5747 INFO: Loading module hook 'hook-torch.py' from '/Users/expoem/Dev/BallonsTranslator/venv/lib/python3.11/site-packages/_pyinstaller_hooks_contrib/hooks/stdhooks'...
5747 INFO: hook-torch: raising recursion limit to 5000
6410 INFO: Loading module hook 'hook-sympy.py' from '/Users/expoem/Dev/BallonsTranslator/venv/lib/python3.11/site-packages/_pyinstaller_hooks_contrib/hooks/stdhooks'...
12479 INFO: Loading module hook 'hook-xml.dom.domreg.py' from '/Users/expoem/Dev/BallonsTranslator/venv/lib/python3.11/site-packages/PyInstaller/hooks'...
12610 INFO: Loading module hook 'hook-lxml.py' from '/Users/expoem/Dev/BallonsTranslator/venv/lib/python3.11/site-packages/_pyinstaller_hooks_contrib/hooks/stdhooks'...
15049 INFO: Loading module hook 'hook-xml.etree.cElementTree.py' from '/Users/expoem/Dev/BallonsTranslator/venv/lib/python3.11/site-packages/PyInstaller/hooks'...
17121 INFO: Processing pre-safe import module hook tensorflow from '/Users/expoem/Dev/BallonsTranslator/venv/lib/python3.11/site-packages/_pyinstaller_hooks_contrib/hooks/pre_safe_import_module/hook-tensorflow.py'.
17134 INFO: Loading module hook 'hook-jinja2.py' from '/Users/expoem/Dev/BallonsTranslator/venv/lib/python3.11/site-packages/_pyinstaller_hooks_contrib/hooks/stdhooks'...
18848 INFO: Loading module hook 'hook-torchvision.ops.py' from '/Users/expoem/Dev/BallonsTranslator/venv/lib/python3.11/site-packages/_pyinstaller_hooks_contrib/hooks/stdhooks'...
19959 INFO: Loading module hook 'hook-setuptools.py' from '/Users/expoem/Dev/BallonsTranslator/venv/lib/python3.11/site-packages/PyInstaller/hooks'...
20405 INFO: Processing pre-safe import module hook distutils from '/Users/expoem/Dev/BallonsTranslator/venv/lib/python3.11/site-packages/PyInstaller/hooks/pre_safe_import_module/hook-distutils.py'.
20405 INFO: Processing pre-find module path hook distutils from '/Users/expoem/Dev/BallonsTranslator/venv/lib/python3.11/site-packages/PyInstaller/hooks/pre_find_module_path/hook-distutils.py'.
20496 INFO: Loading module hook 'hook-distutils.py' from '/Users/expoem/Dev/BallonsTranslator/venv/lib/python3.11/site-packages/PyInstaller/hooks'...
20526 INFO: Loading module hook 'hook-distutils.util.py' from '/Users/expoem/Dev/BallonsTranslator/venv/lib/python3.11/site-packages/PyInstaller/hooks'...
21014 INFO: Processing pre-safe import module hook win32com from '/Users/expoem/Dev/BallonsTranslator/venv/lib/python3.11/site-packages/_pyinstaller_hooks_contrib/hooks/pre_safe_import_module/hook-win32com.py'.
23841 INFO: Loading module hook 'hook-regex.py' from '/Users/expoem/Dev/BallonsTranslator/venv/lib/python3.11/site-packages/_pyinstaller_hooks_contrib/hooks/stdhooks'...
33692 INFO: Loading module hook 'hook-sqlite3.py' from '/Users/expoem/Dev/BallonsTranslator/venv/lib/python3.11/site-packages/PyInstaller/hooks'...
35397 INFO: Loading module hook 'hook-docx.py' from '/Users/expoem/Dev/BallonsTranslator/venv/lib/python3.11/site-packages/_pyinstaller_hooks_contrib/hooks/stdhooks'...
36056 INFO: Loading module hook 'hook-opencc.py' from '/Users/expoem/Dev/BallonsTranslator/venv/lib/python3.11/site-packages/_pyinstaller_hooks_contrib/hooks/stdhooks'...
36351 INFO: Analyzing hidden import 'deepl'
36371 INFO: Analyzing hidden import 'ctranslate2'
36454 INFO: Analyzing hidden import 'httpx'
36640 INFO: Loading module hook 'hook-anyio.py' from '/Users/expoem/Dev/BallonsTranslator/venv/lib/python3.11/site-packages/_pyinstaller_hooks_contrib/hooks/stdhooks'...
37103 INFO: Analyzing hidden import 'langdetect'
37104 INFO: Loading module hook 'hook-langdetect.py' from '/Users/expoem/Dev/BallonsTranslator/venv/lib/python3.11/site-packages/_pyinstaller_hooks_contrib/hooks/stdhooks'...
37133 INFO: Processing pre-safe import module hook six.moves from '/Users/expoem/Dev/BallonsTranslator/venv/lib/python3.11/site-packages/PyInstaller/hooks/pre_safe_import_module/hook-six.moves.py'.
37179 INFO: Analyzing hidden import 'srsly'
37470 INFO: Processing module hooks...
37547 INFO: Loading module hook 'hook-srsly.msgpack._packer.py' from '/Users/expoem/Dev/BallonsTranslator/venv/lib/python3.11/site-packages/_pyinstaller_hooks_contrib/hooks/stdhooks'...
37668 INFO: Loading module hook 'hook-lxml.isoschematron.py' from '/Users/expoem/Dev/BallonsTranslator/venv/lib/python3.11/site-packages/_pyinstaller_hooks_contrib/hooks/stdhooks'...
37670 INFO: Loading module hook 'hook-lxml.etree.py' from '/Users/expoem/Dev/BallonsTranslator/venv/lib/python3.11/site-packages/_pyinstaller_hooks_contrib/hooks/stdhooks'...
37909 INFO: Loading module hook 'hook-PyQt6.QtWidgets.py' from '/Users/expoem/Dev/BallonsTranslator/venv/lib/python3.11/site-packages/PyInstaller/hooks'...
38018 INFO: Loading module hook 'hook-PyQt6.QtGui.py' from '/Users/expoem/Dev/BallonsTranslator/venv/lib/python3.11/site-packages/PyInstaller/hooks'...
38063 INFO: Loading module hook 'hook-PyQt6.QtCore.py' from '/Users/expoem/Dev/BallonsTranslator/venv/lib/python3.11/site-packages/PyInstaller/hooks'...
38121 INFO: Loading module hook 'hook-setuptools.msvc.py' from '/Users/expoem/Dev/BallonsTranslator/venv/lib/python3.11/site-packages/PyInstaller/hooks'...
38707 INFO: Loading module hook 'hook-PIL.SpiderImagePlugin.py' from '/Users/expoem/Dev/BallonsTranslator/venv/lib/python3.11/site-packages/PyInstaller/hooks'...
38725 INFO: Loading module hook 'hook-PyQt6.py' from '/Users/expoem/Dev/BallonsTranslator/venv/lib/python3.11/site-packages/PyInstaller/hooks'...
38735 INFO: Loading module hook 'hook-PyQt6.QtOpenGLWidgets.py' from '/Users/expoem/Dev/BallonsTranslator/venv/lib/python3.11/site-packages/PyInstaller/hooks'...
38771 INFO: Loading module hook 'hook-PyQt6.QtOpenGL.py' from '/Users/expoem/Dev/BallonsTranslator/venv/lib/python3.11/site-packages/PyInstaller/hooks'...
38810 INFO: Loading module hook 'hook-lxml.objectify.py' from '/Users/expoem/Dev/BallonsTranslator/venv/lib/python3.11/site-packages/_pyinstaller_hooks_contrib/hooks/stdhooks'...
38811 INFO: Loading module hook 'hook-PyQt6.QtDBus.py' from '/Users/expoem/Dev/BallonsTranslator/venv/lib/python3.11/site-packages/PyInstaller/hooks'...
39745 INFO: Looking for ctypes DLLs
39773 WARNING: Library vcruntime140_1.dll required via ctypes not found
39774 WARNING: Library vcruntime140.dll required via ctypes not found
39776 WARNING: Library msvcp140.dll required via ctypes not found
39791 WARNING: Library libnvidia-ml.so.1 required via ctypes not found
39840 WARNING: Ignoring /usr/lib64/libgomp.so.1 imported from /Users/expoem/Dev/BallonsTranslator/venv/lib/python3.11/site-packages/torch/_inductor/codecache.py - only basenames are supported with ctypes imports!
39910 WARNING: Library user32 required via ctypes not found
39911 WARNING: Library dwmapi required via ctypes not found
39918 WARNING: Library user32 required via ctypes not found
39918 WARNING: Library dwmapi required via ctypes not found
40002 INFO: Analyzing run-time hooks ...
40014 INFO: Including run-time hook '/Users/expoem/Dev/BallonsTranslator/venv/lib/python3.11/site-packages/PyInstaller/hooks/rthooks/pyi_rth_inspect.py'
40015 INFO: Including run-time hook '/Users/expoem/Dev/BallonsTranslator/venv/lib/python3.11/site-packages/PyInstaller/hooks/rthooks/pyi_rth_pkgutil.py'
40016 INFO: Including run-time hook '/Users/expoem/Dev/BallonsTranslator/venv/lib/python3.11/site-packages/PyInstaller/hooks/rthooks/pyi_rth_multiprocessing.py'
40018 INFO: Including run-time hook '/Users/expoem/Dev/BallonsTranslator/venv/lib/python3.11/site-packages/PyInstaller/hooks/rthooks/pyi_rth_setuptools.py'
40019 INFO: Including run-time hook '/Users/expoem/Dev/BallonsTranslator/venv/lib/python3.11/site-packages/PyInstaller/hooks/rthooks/pyi_rth_pyqt6.py'
40020 INFO: Including run-time hook '/Users/expoem/Dev/BallonsTranslator/venv/lib/python3.11/site-packages/PyInstaller/hooks/rthooks/pyi_rth_pkgres.py'
40265 INFO: Looking for dynamic libraries
42562 INFO: Warnings written to /Users/expoem/Dev/BallonsTranslator/build/launch/warn-launch.txt
42700 INFO: Graph cross-reference written to /Users/expoem/Dev/BallonsTranslator/build/launch/xref-launch.html
42909 INFO: checking PYZ
42909 INFO: Building PYZ because PYZ-00.toc is non existent
42909 INFO: Building PYZ (ZlibArchive) /Users/expoem/Dev/BallonsTranslator/build/launch/PYZ-00.pyz
46454 INFO: Building PYZ (ZlibArchive) /Users/expoem/Dev/BallonsTranslator/build/launch/PYZ-00.pyz completed successfully.
46503 INFO: EXE target arch: arm64
46503 INFO: Code signing identity: None
46504 INFO: checking PKG
46504 INFO: Building PKG because PKG-00.toc is non existent
46504 INFO: Building PKG (CArchive) launch.pkg
46527 INFO: Building PKG (CArchive) launch.pkg completed successfully.
46528 INFO: Bootloader /Users/expoem/Dev/BallonsTranslator/venv/lib/python3.11/site-packages/PyInstaller/bootloader/Darwin-64bit/runw
46528 INFO: checking EXE
46528 INFO: Building EXE because EXE-00.toc is non existent
46528 INFO: Building EXE from EXE-00.toc
46528 INFO: Copying bootloader EXE to /Users/expoem/Dev/BallonsTranslator/build/launch/launch
46529 INFO: Converting EXE to target arch (arm64)
46555 INFO: Removing signature(s) from EXE
46574 INFO: Appending PKG archive to EXE
46592 INFO: Fixing EXE headers for code signing
46595 INFO: Re-signing the EXE
46667 INFO: Building EXE from EXE-00.toc completed successfully.
46777 INFO: checking COLLECT
46777 INFO: Building COLLECT because COLLECT-00.toc is non existent
46777 INFO: Building COLLECT COLLECT-00.toc
57280 INFO: Building COLLECT COLLECT-00.toc completed successfully.
57468 INFO: checking BUNDLE
57468 INFO: Building BUNDLE because BUNDLE-00.toc is non existent
57468 INFO: Building BUNDLE BUNDLE-00.toc
67691 INFO: Signing the BUNDLE...
76445 INFO: Building BUNDLE BUNDLE-00.toc completed successfully.
INFO: Copying app to Downloads folder...
INFO: ✅ The app is now in your Downloads folder.
INFO: Drag and drop the app icon into Applications folder to install it.
@hyrulelinks

**Comment by dmMaze** [comment]
> 感谢回复。 打包运行的，按照readme安装了相关组件和data，文件树与展示的一致，文件是否完好不确定没有md5校验，从说给mega下载。 使用的一件打包脚本，运行输出信息没有留存，现在也无法复现了，相关的环境和软件我都已经删除。 ui问题具体来说就是对于单个图片进行编辑时，右键功能失效，运行相应的翻译，ocr，和重绘没反应，sync直接卡死。 而且运行中，所有的窗口都不能移动，运行信息窗口置顶无法隐藏。 再次感谢您的回复，抱歉没法提供更详细的输出信息和日志。 @hyrulelinks

我手边正好有台mbp, 我试了下直接源码运行，你提到的这些功能基本是正常的，右键ocr日文推荐选manga_ocr。sync就是没用我也不知道当时为啥要合并这个pr待会删了。
macos上另外两个已知问题是某些字体竖排错位和ui大小位置乱了，有空我会修一下

**Comment by longyiqiang** [comment]
> > 感谢回复。 打包运行的，按照readme安装了相关组件和data，文件树与展示的一致，文件是否完好不确定没有md5校验，从说给mega下载。 使用的一件打包脚本，运行输出信息没有留存，现在也无法复现了，相关的环境和软件我都已经删除。 ui问题具体来说就是对于单个图片进行编辑时，右键功能失效，运行相应的翻译，ocr，和重绘没反应，sync直接卡死。 而且运行中，所有的窗口都不能移动，运行信息窗口置顶无法隐藏。 再次感谢您的回复，抱歉没法提供更详细的输出信息和日志。 @hyrulelinks
> 
> 我手边正好有台mbp, 我试了下直接源码运行，你提到的这些功能基本是正常的，右键ocr日文推荐选manga_ocr。sync就是没用我也不知道当时为啥要合并这个pr待会删了。 macos上另外两个已知问题是某些字体竖排错位和ui大小位置乱了，有空我会修一下 run的时候程序冻住是正常的

感谢🙏，顺便问下detection值只有三个，不能输入2048，正常吗？

**Comment by dmMaze** [comment]
> 2048

正常，这个不是越大越好，默认设置就是推荐配置
