### ISSUE TITLE
OCR替换的BUG》？

### ISSUE THREAD

**Issue by lhj5426** [dmMaze/BallonsTranslator#258]
https://github.com/dmMaze/BallonsTranslator/assets/30548000/6c7abd1f-a6f3-4402-9e93-34adb65586d7

大佬您好
如 视频您看到 想要把 某一句 背景拟声字替换 为空

![image](https://github.com/dmMaze/BallonsTranslator/assets/30548000/a0bb3fb7-1062-4928-8b78-e425cf01d158)

からせいえきふめ

整句 无法替换  3 4个字符无法替换 只能 一点点一点的 磨  
这个算不算是OCR 替换的BUG 这种问题 在替换的时候 有很多 

再比如

https://github.com/dmMaze/BallonsTranslator/assets/30548000/75cb657d-1d45-49e9-8675-b4621006b73f

这种一个数字

还有
のないてくたさい
てそモイムですき
いヤ~ほら。
てちだ』
くやすッくあゃ川
ひよ♡
せいネさ9「ゴめ
シム
す、？～♡そラ♡こわ及
ぁにせご…♡
はす…♡なにミれ♡
这种 都无法被 替换 
类似这种诸如此类的

![image](https://github.com/dmMaze/BallonsTranslator/assets/30548000/9f077166-2cc1-4629-b363-867f778714c8)
…年目…集県間しこ

另外如果可以的话 可以 在替换为空的时候
![image](https://github.com/dmMaze/BallonsTranslator/assets/30548000/b6d75f35-0f19-468e-b7d8-2690e6243044)
可以直接不在图上显示吗

![image](https://github.com/dmMaze/BallonsTranslator/assets/30548000/46bbe0b4-487c-46ed-a34e-9cf9064b17d2)

**Comment by bropines** [comment]
The neural network is not capable of sounds. At all. The sounds are too chaotic and dependent on the authors. And on the last pic there is a blur at the top left

**Comment by lhj5426** [comment]
> The neural network is not capable of sounds. At all. The sounds are too chaotic and dependent on the authors. And on the last pic there is a blur at the top left

So, while doing OCR, I manually add onomatopoeic words that are mistakenly recognized to the OCR replacement directory. This way, next time when encountering similar cases, they can be automatically replaced. As long as I collect enough of them, it will eventually reduce the workload in future comics.

**Comment by dmMaze** [comment]
我能替换成功啊，你没多打空格什么的吧
或者你方便的话发张原图（可以传压缩包）和待替换字符串

**Comment by lhj5426** [comment]
> くやすッくあゃ川

[新建文件夹.zip](https://github.com/dmMaze/BallonsTranslator/files/13068243/default.zip)
[新建文件夹 (2).zip](https://github.com/dmMaze/BallonsTranslator/files/13068245/2.zip)
[新建文件夹 (3).zip](https://github.com/dmMaze/BallonsTranslator/files/13068247/3.zip)
[新建文件夹 (4).zip](https://github.com/dmMaze/BallonsTranslator/files/13068248/4.zip)
[新建文件夹 (5).zip](https://github.com/dmMaze/BallonsTranslator/files/13068250/5.zip)
提供您5张  文档里都有不能替换的词条 都是复制粘贴的 不是手动输入的 
[config.zip](https://github.com/dmMaze/BallonsTranslator/files/13068261/config.zip)
这是我的配置 文件 D:\BL\BallonsTranslator\config 
因为都是不好的图片 还请您在自己一个人的情况下打开 对不起

**Comment by dmMaze** [comment]
替换bug修了，另外在设置ocr下面勾选Delete and restore region where OCR return empty string.可以过滤掉所有后处理后ocr结果为空的文本块

**Comment by lhj5426** [comment]
> 替换bug修了，另外在设置ocr下面勾选Delete and restore region where OCR return empty string.可以过滤掉所有后处理后ocr结果为空的文本块

大佬 好像还差一点
^\d$
![image](https://github.com/dmMaze/BallonsTranslator/assets/30548000/e694ff5f-02d3-4318-bfb1-84a297bcba20)

这样 单子数字3 没有被替换

\d 但是这样写可以替换 可这样是全部数字都会被替换 是我正则写的不对么 
问的GPT
![image](https://github.com/dmMaze/BallonsTranslator/assets/30548000/8936ed06-8e68-473b-a2ff-8f0a9d1707d6)
其他的 非常感谢您的修正

**Comment by lhj5426** [comment]
![image](https://github.com/dmMaze/BallonsTranslator/assets/30548000/ba1d02a5-4129-4602-b72d-50b09eaf13d2)
这种 时间 数字是可以被匹配上的

就单个数字不行

**Comment by dmMaze** [comment]
> 就单个数字不行

那个正则表达式只匹配单个数字不允许首尾出现空格的，你给的那个例子是"3 "有空格所以匹配失败了

**Comment by lhj5426** [comment]
> > 就单个数字不行
> 
> 那个正则表达式只匹配单个数字不允许首尾出现空格的，你给的那个例子是"3 "有空格所以匹配失败了

原来还有空格  抱歉复制的时候没有看到  非常感谢大佬您
