### ISSUE TITLE
我想问问翻译功能的问题

### ISSUE THREAD

**Issue by longfei796** [dmMaze/BallonsTranslator#259]
请问各位大佬
翻译进度一直不动，不能翻译，连接失败什么的
恳请指点一二

**Comment by dmMaze** [comment]
我记得除了百度和彩云其它在线翻译器国内用都是要翻墙的

**Comment by longfei796** [comment]
> 我记得除了百度和彩云其它在线翻译器国内用都是要翻墙的

谢谢大佬回复
就是翻墙也是这样
还有baidu也是显示连接失败什么的，明天我给您拍个照片吧

**Comment by dmMaze** [comment]
> 就是翻墙也是这样

用国内的翻译器最好把梯子关了，用国外的你得开全局代理。如果你是跑源码得满足依赖库urllib3==1.25.11，如果还是失败有可能就是你节点太脏所以一直被那些翻译器拒

**Comment by lhj5426** [comment]
其实不一定要开全局 我是用的这个 Proxifier
![image](https://github.com/dmMaze/BallonsTranslator/assets/30548000/30d57838-5283-4da7-9060-c2b6f9f27b88)
https://youtu.be/ZPi56hSm__E?t=465  youtube 有详细的教程

**Comment by longfei796** [comment]
> > 就是翻墙也是这样
> 
> 用国内的翻译器最好把梯子关了，用国外的你得开全局代理。如果你是跑源码得满足依赖库urllib3==1.25.11，如果还是失败有可能就是你节点太脏所以一直被那些翻译器拒

问题解决，就是您说的节点问题
请问软件可以宣传吗

**Comment by lhj5426** [comment]
> > > 就是翻墙也是这样
> > 
> > 
> > 用国内的翻译器最好把_梯子_关了，用国外的你得开全局_代理_。如果你是跑源码得满足依赖库urllib3==1.25.11，如果还是失败有可能就是你节点太脏所以一直被那些翻译器拒
> 
> 问题解决，就是您说的节点问题 请问软件可以宣传吗

B站 搜漫画翻译 播放量最高的前几个 你看看  早就宣传开了

**Comment by dmMaze** [comment]
> > > 就是翻墙也是这样
> > 
> > 
> > 用国内的翻译器最好把梯子关了，用国外的你得开全局代理。如果你是跑源码得满足依赖库urllib3==1.25.11，如果还是失败有可能就是你节点太脏所以一直被那些翻译器拒
> 
> 问题解决，就是您说的节点问题 请问软件可以宣传吗

谢谢~ 只要不打包到咸鱼淘宝卖钱就行
