### ISSUE TITLE
Font Size Settings

### ISSUE THREAD

**Issue by bropines** [dmMaze/BallonsTranslator#26]
When I try to change the font size, I enter one digit and... all. The cursor moves to a block of text, and sometimes erases everything I've been working on. Here's a gif

https://user-images.githubusercontent.com/57861007/186544474-4d8692dd-d71d-42cb-bb74-3a5b308529e8.mp4

**Comment by dmMaze** [comment]
> When I try to change the font size, I enter one digit and... all. The cursor moves to a block of text,

fixed 59f283a83f233d95ddb0f678f990506c4f5c5ee3 8f6b88170288e178de668019badaa8f30b6ea3ba, font size editor's changes will be applied after "Enter" or ```Return``` is pressed.  


> and sometimes erases everything I've been working on

It's not been erased, the block (with big font size) grew too long resulting in the centered text (changed to small font size) moving out of the scene.
