### ISSUE TITLE
蒙板的范围过窄

### ISSUE THREAD

**Issue by Petro-Rabbit** [dmMaze/BallonsTranslator#261]
同样内容图片修图在低分辨率的情况下比高分辨率要好，可能是因为字体带有白色描边，识别时只抠出了白边里的黑字，导致所有文本都残留了白底。而软件似乎完全不识别外部对Mask文件夹中的蒙板做的手动修改。
![1](https://github.com/dmMaze/BallonsTranslator/assets/58901739/13566f66-4239-4d09-8204-3ff70a551226) ![2](https://github.com/dmMaze/BallonsTranslator/assets/58901739/e40134f5-e4e2-47f8-9a03-adc7c014d8c2) ![3](https://github.com/dmMaze/BallonsTranslator/assets/58901739/9e1077dd-35be-449f-b61a-0068ba7ce702) ![5](https://github.com/dmMaze/BallonsTranslator/assets/58901739/5cddc9ec-41be-48f7-9f02-75432d38d28d) ![4](https://github.com/dmMaze/BallonsTranslator/assets/58901739/acd54ac0-e617-4780-be18-8ec47d23599c)

如果能有扩展蒙板范围的选项，或者允许使用手动改好的蒙板图片的功能会比较好。

**Comment by dmMaze** [comment]
<img width="322" alt="image" src="https://github.com/dmMaze/BallonsTranslator/assets/51270320/078454d1-7a62-4f33-8de3-ce9a623b83f2">

拉这个可以膨胀蒙版
其次对mask文件夹里面蒙版的修改是可以被识别的，只要你替换的时候这个蒙版在软件里不是被加载的状态就行了

**Comment by Petro-Rabbit** [comment]
> 拉这个可以膨胀蒙板 其次对mask文件夹里面蒙板的修改是可以被识别的，只要你替换的时候这个蒙板在软件里不是被加载的状态就行了

膨胀的确起效了，效果很好；
但手动修改蒙板不行，我测试了4种修复方式都没有效果，会覆盖掉修改的图片。在哪里能仅使用mask的图片？

**Comment by dmMaze** [comment]
> > 拉这个可以膨胀蒙板 其次对mask文件夹里面蒙板的修改是可以被识别的，只要你替换的时候这个蒙板在软件里不是被加载的状态就行了
> 
> 膨胀的确起效了，效果很好； 但手动修改蒙板不行，我测试了4种修复方式都没有效果，会覆盖掉修改的图片。在哪里能仅使用mask的图片？

哦如果你指run那程序直接重新算蒙版了所以没用手动修改的，现在也不支持

**Comment by dmMaze** [comment]
> > > 拉这个可以膨胀蒙板 其次对mask文件夹里面蒙板的修改是可以被识别的，只要你替换的时候这个蒙板在软件里不是被加载的状态就行了
> > 
> > 
> > 膨胀的确起效了，效果很好； 但手动修改蒙板不行，我测试了4种修复方式都没有效果，会覆盖掉修改的图片。在哪里能仅使用mask的图片？
> 
> 哦如果你指run那程序直接重新算蒙版了所以没用手动修改的，现在也不支持

好吧dev版其实是支持的，你换了蒙版后这里只启用修复再run一遍就行了
<img width="605" alt="image" src="https://github.com/dmMaze/BallonsTranslator/assets/51270320/32fc98fb-fac6-4414-b6ca-8084c0f74b9e">

**Comment by Petro-Rabbit** [comment]
> 
> 好吧dev版其实是支持的，你换了蒙板后这里只启用修复再run一遍就行了 蒙板是在text detction的时候算的所以启用这个会覆盖掉你手动修改的

好的，非常感谢，如果Dev版后续将发布的话那这个反馈可以关闭了。
顺便一提，我在1.3.0版中遇到了文本框偏移和最终结果中文本框带有矩形线的问题，似乎没有人提到过。在1.3.35中已经修复了吗？我没在新版测试过，如果没修复我新开一个反馈写一下。

**Comment by dmMaze** [comment]
> 在1.3.35中已经修复了吗？我没在新版测试过，如果没修复我新开一个反馈写一下。

修了
