### ISSUE TITLE
建议作者更新一下两个网盘里的data文件夹

### ISSUE THREAD

**Issue by wjz2001** [dmMaze/BallonsTranslator#263]
谷歌云盘里的data文件夹没有alphabet-all-v5.txt，因此无法使用lama_mpe；mega云盘里的data文件夹和core压缩包里的data文件夹没有opencv_world455.dll，因此无法使用patchmatch。
尤其是缺opencv_world455.dll特别坑爹，因为日志只会显示patchmatch_inpaint.dll或它的依赖不存在，还需要用软件才能发现问题关键。

**Comment by dmMaze** [comment]
已更新，另外alphabet-all-v5.txt本来就不需要放网盘里
