### ISSUE TITLE
嵌完字，五百mb变一个G，不是太想压缩画质，请问有无解决办法

### ISSUE THREAD

**Issue by longfei796** [dmMaze/BallonsTranslator#266]
是不是我有什么没操作好的

**Comment by dmMaze** [comment]
保存的是png格式所以一般会比jpg的图源大，你可以用个别的批量图片压缩软件搞成jpg的

**Comment by longfei796** [comment]
> 保存的是png格式所以一般会比jpg的图源大，你可以用个别的批量图片压缩软件搞成jpg的

希望您优化的
1，添加常用特殊符号，例如双感叹号，感叹问号，三感叹号，爱心之类，斜感叹号
2，♡等特殊符号竖排排列的时候是左偏，还有与字体大小不成正比

**Comment by dmMaze** [comment]
> ，♡等特殊符号竖排排列的时候是左偏，特殊符号及标点符号与字体大小不成正比，可以自己调，但是请问一下您

这是啥字体？

**Comment by longfei796** [comment]
> > ，♡等特殊符号竖排排列的时候是左偏，特殊符号及标点符号与字体大小不成正比，可以自己调，但是请问一下您
> 
> 这是啥字体？

方正大黑简体，请问有什么问题吗
这种字体看的清楚，所以一直在用

**Comment by dmMaze** [comment]
> 方正大黑简体

特殊符号居中问题已修
排字有问题需要告诉我是哪种字体我才好查错。所有特殊符号标点符号大小就是按给定字体大小渲染的，看起来大小不一可能是因为选定字体本身缺失这些特殊字符所以用默认字体的字符替换了

**Comment by longfei796** [comment]
> > 方正大黑简体
> 
> 特殊符号居中问题已修 排字有问题需要告诉我是哪种字体我才好查错。所有特殊符号标点符号大小就是按给定字体大小渲染的，看起来大小不一可能是因为选定字体本身缺失这些特殊字符所以用默认字体的字符替换了

也

> > 方正大黑简体
> 
> 特殊符号居中问题已修 排字有问题需要告诉我是哪种字体我才好查错。所有特殊符号标点符号大小就是按给定字体大小渲染的，看起来大小不一可能是因为选定字体本身缺失这些特殊字符所以用默认字体的字符替换了

谢谢您，大佬，请问是自己的更新data文件就行了？我看mega网盘里的文件日期还是旧的

**Comment by longfei796** [comment]
> > > 方正大黑简体
> > 
> > 
> > 特殊符号居中问题已修 排字有问题需要告诉我是哪种字体我才好查错。所有特殊符号标点符号大小就是按给定字体大小渲染的，看起来大小不一可能是因为选定字体本身缺失这些特殊字符所以用默认字体的字符替换了
> 
> 也
> 
> > > 方正大黑简体
> > 
> > 
> > 特殊符号居中问题已修 排字有问题需要告诉我是哪种字体我才好查错。所有特殊符号标点符号大小就是按给定字体大小渲染的，看起来大小不一可能是因为选定字体本身缺失这些特殊字符所以用默认字体的字符替换了
> 
> 谢谢您，大佬，请问是自己的更新data文件就行了？我看mega网盘里的文件日期还是旧的 彩云翻译被卡住了 ，是不是因为没有py环境或者命令终端运行导致？https://s1.locimg.com/2023/11/01/298e7ba999b69.jpg https://s1.locimg.com/2023/11/01/3b538bf2c2076.jpg https://s1.locimg.com/2023/11/01/298e7ba999b69.jpg

**Comment by longfei796** [comment]
> > 方正大黑简体
> 
> 特殊符号居中问题已修 排字有问题需要告诉我是哪种字体我才好查错。所有特殊符号标点符号大小就是按给定字体大小渲染的，看起来大小不一可能是因为选定字体本身缺失这些特殊字符所以用默认字体的字符替换了

请问该怎么操作，是自己在根据代码操作吗？我不是程序员，不太懂这个

**Comment by dmMaze** [comment]
> 请问该怎么操作，是自己在根据代码操作吗？我不是程序员，不太懂这个

你现在是怎么跑的？如果跑的是dev版：
https://github.com/dmMaze/BallonsTranslator/tree/dev code->Download Zip, 解压并覆盖到你现有程序的根目录

**Comment by longfei796** [comment]
> > 请问该怎么操作，是自己在根据代码操作吗？我不是程序员，不太懂这个
> 
> 你现在是怎么跑的？如果跑的是dev版： https://github.com/dmMaze/BallonsTranslator/tree/dev code->Download Zip, 解压并覆盖到你现有程序的根目录

什么都没弄，吧mega盘里的三个文件直接直接下载解压在电脑上就用了？没有py环境

**Comment by longfei796** [comment]
> > 是你讲的dev版吗
> 
> 用.exe启动的是旧版，launch.bat启动的是dev版，或者把启动时带的那个黑框复制给我看下也行

那就是旧版，后缀是exe
https://s1.locimg.com/2023/11/02/f2c1f5e495dca.jpg
https://s1.locimg.com/2023/11/02/988f4e3a066ee.jpg

**Comment by dmMaze** [comment]
> > > 是你讲的dev版吗
> > 
> > 
> > 用.exe启动的是旧版，launch.bat启动的是dev版，或者把启动时带的那个黑框复制给我看下也行
> 
> 那就是旧版，后缀是exe https://s1.locimg.com/2023/11/02/f2c1f5e495dca.jpg https://s1.locimg.com/2023/11/02/988f4e3a066ee.jpg

如果你还有心情折腾就参考https://github.com/dmMaze/BallonsTranslator/issues/160#issuecomment-1602064296 跑dev
我最早本周末打包一个新版

**Comment by longfei796** [comment]
> > > > 是你讲的dev版吗
> > > 
> > > 
> > > 用.exe启动的是旧版，launch.bat启动的是dev版，或者把启动时带的那个黑框复制给我看下也行
> > 
> > 
> > 那就是旧版，后缀是exe https://s1.locimg.com/2023/11/02/f2c1f5e495dca.jpg https://s1.locimg.com/2023/11/02/988f4e3a066ee.jpg
> 
> 如果你还有心情折腾就参考[#160 (comment)](https://github.com/dmMaze/BallonsTranslator/issues/160#issuecomment-1602064296) 跑dev 我最早本周末打包一个新版

不了不了，我自己专业的名词学的都头大
不过您愿意费心弄一个面向我这种非程序员傻瓜般的，真是太谢谢您了

**Comment by dmMaze** [comment]
从谷歌盘或者MEGA下载新上传的BallonsTranslator_dev_src_with_gitpython.7z，解压进去双击launch.bat等它安装完就启动了
双击scripts/local_gitpull.bat就能更新到最新代码，没问题旧的就可以删了
内地需要开全局代理
另外现在能在设置面板里调保存图片格式和质量了

**Comment by longfei796** [comment]
> 从谷歌盘或者MEGA下载新上传的BallonsTranslator_dev_src_with_gitpython.7z，解压进去双击launch.bat等它安装完就启动了 双击scripts/local_gitpull.bat就能更新到最新代码，没问题旧的就可以删了 内地需要开全局代理 另外现在能在设置面板里调保存图片格式和质量了

您好，谢谢开发者大佬，辛苦了
问问其他的问题，如果我想删除的话是不是，也是像旧版直接把文件夹删除就行了
我看下载了好多东西，电脑是64位，我看上面写32位的，请问您可以吗

**Comment by dmMaze** [comment]
@longfei796 你torch下载失败了，只能多试几次或者换个代理

**Comment by longfei796** [comment]
> @longfei796 你torch下载失败了，只能多试几次或者换个代理

再打扰您问问，可以用浏览器下载再拖到文件夹里面吗
可以的话拖到哪个文件夹里

**Comment by longfei796** [comment]
> > @longfei796 你torch下载失败了，只能多试几次或者换个代理
> 
> 再打扰您问问，可以用浏览器下载再拖到文件夹里面吗 可以的话拖到哪个文件夹里

或者说请人下载好，再打包发给我

**Comment by dmMaze** [comment]
@longfei796 OK我又往网盘里加了python库的压缩包, 仔细阅读readme里和网盘里的安装说明

**Comment by longfei796** [comment]
> @longfei796 OK我又往网盘里加了python库的压缩包, 仔细阅读readme里和网盘里的安装说明

[WARNING] launch:main:156 - Failed to load config file, using default config
[ERROR  ] launch:main:155 - [Errno 2] No such file or directory: 'D:\\下载\\BallonsTranslator_dev_src_with_gitpython\\config/config.json'
可以正常打开，但是有两个这显示

**Comment by wjz2001** [comment]
> 保存的是png格式所以一般会比jpg的图源大，你可以用个别的批量图片压缩软件搞成jpg的

不推荐，这连格式都换了。可以试试[https://www.iloveimg.com/zh-cn/compress-image](url)或者[https://www.zhangxinxu.com/sp/tinyimg/](url)，格式不变。

**Comment by dmMaze** [comment]
> > @longfei796 OK我又往网盘里加了python库的压缩包, 仔细阅读readme里和网盘里的安装说明
> 
> 导出word失败 [ERROR ] io_thread:handleRunTimeException:33 - Execution error: OpenCV(4.8.1) D:\a\opencv-python\opencv-python\opencv\modules\imgproc\src\resize.cpp:4062: error: (-215:Assertion failed) !ssize.empty() in function 'cv::resize'
> 
> Traceback (most recent call last): File "D:\下载\BallonsTranslator_dev_src_with_gitpython\ui\io_thread.py", line 25, in run self.job() File "D:\下载\BallonsTranslator_dev_src_with_gitpython\ui\io_thread.py", line 119, in _export_as_doc self.proj.dump_doc(fin_page_signal=self.fin_page) File "D:\下载\BallonsTranslator_dev_src_with_gitpython\ui\config_proj.py", line 331, in dump_doc cuts_path_list, cut_width_list = gen_ballon_cuts(cuts_dir, imgpath, blklist) File "D:\下载\BallonsTranslator_dev_src_with_gitpython\ui\config_proj.py", line 448, in gen_ballon_cuts resized = cv2.resize(bub, dim, interpolation = cv2.INTER_AREA) if resize else bub cv2.error: OpenCV(4.8.1) D:\a\opencv-python\opencv-python\opencv\modules\imgproc\src\resize.cpp:4062: error: (-215:Assertion failed) !ssize.empty() in function 'cv::resize'
> 
> 是不是跟这个有关，之前显示，现在不显示了 [WARNING] launch:main:156 - Failed to load config file, using default config [ERROR ] launch:main:155 - [Errno 2] No such file or directory: 'D:\下载\BallonsTranslator_dev_src_with_gitpython\config/config.json'

修了，再有问题另开
