### ISSUE TITLE
OCR and A buttons are missing?

### ISSUE THREAD

**Issue by BedrosBoost** [dmMaze/BallonsTranslator#267]
Hi, there used to be the 'OCR' and 'A' buttons in the bottom toolbar controls but they seem to be missing now?

![image](https://github.com/dmMaze/BallonsTranslator/assets/102727507/7b04e959-83d0-445d-860c-545c7567313f)

Thank you.

**Comment by dmMaze** [comment]
the ocr button was moved to titlebar-run-enable ocr, and the other missing button is useless and confusing

**Comment by BedrosBoost** [comment]
Thank you. I found it now.
