### ISSUE TITLE
 新版跑几十张就报错 

### ISSUE THREAD

**Issue by lhj5426** [dmMaze/BallonsTranslator#269]
py version:  3.10.11 (tags/v3.10.11:7d4cc5a, Apr  5 2023, 00:38:17) [MSC v.1929 64 bit (AMD64)]
py executable:  D:\BL\BallonsTranslator\ballontrans_pylibs_win\python.exe
version: 1.4.0
branch: dev
Commit hash: <none>
[INFO   ] launch:main:153 - QT_API: pyqt6, QT Version: 6.4.2
[INFO   ] launch:main:192 - set display language to zh_CN
[INFO   ] module_manager:on_finish_settranslator:792 - Translator set to ChatGPT
[INFO   ] module_manager:on_finish_setinpainter:784 - Inpainter set to aot
[INFO   ] module_manager:on_finish_setocr:777 - OCR set to mit48px_ctc
[INFO   ] module_manager:on_finish_setdetector:771 - Text detector set to ctd
Traceback (most recent call last):
  File "D:\BL\BallonsTranslator\ui\module_manager.py", line 464, in run
    self.job()
  File "D:\BL\BallonsTranslator\ui\module_manager.py", line 391, in _imgtrans_pipeline
    blk_mask, xyxy = get_block_mask(xywh, mask, blk.angle)
  File "D:\BL\BallonsTranslator\utils\imgproc_utils.py", line 395, in get_block_mask
    msk = cv2.bitwise_and(mask_array[y1: y2, x1: x2], itmsk)
cv2.error: OpenCV(4.7.0) D:\a\opencv-python\opencv-python\opencv\modules\core\src\arithm.cpp:214: error: (-209:Sizes of input arguments do not match) The operation is neither 'array op array' (where arrays have the same size and type), nor 'array op scalar', nor 'scalar op array' in function 'cv::binary_op'
请按任意键继续. . .

![image](https://github.com/dmMaze/BallonsTranslator/assets/30548000/f792994b-02f5-42a4-b081-799e48284029)

![image](https://github.com/dmMaze/BallonsTranslator/assets/30548000/4a4beb9f-b3ca-4e5a-9d07-0a358b0480dc)

刚才更新了 新版  然后跑 漫画 跑几十页就报错

**Comment by lhj5426** [comment]
然后关闭掉 之前增加的新功能呢  【如果 结果为空 就删除 空气泡】 之后 可以正常跑

**Comment by lhj5426** [comment]
感谢！

**Comment by dmMaze** [comment]
https://github.com/dmMaze/BallonsTranslator/commit/f63c779cf853d9657ad25764795b8dd6e7734f30 修了，其次没必要道歉，我个人并不care nsfw

**Comment by lhj5426** [comment]
> [f63c779](https://github.com/dmMaze/BallonsTranslator/commit/f63c779cf853d9657ad25764795b8dd6e7734f30) 修了，其次没必要道歉，我个人并不care nsfw

嗯 就是看到  
已关闭 in  f63c779 然后 运行更新
 之后重跑 发现没问题 了 所以才来回复
 
 总之 非常感谢 大佬
