### ISSUE TITLE
some unclear instruction about "saladict"

### ISSUE THREAD

**Issue by dhana-exe** [dmMaze/BallonsTranslator#272]
After checking it i had some confussion
on saladict tutorial is on https://github.com/dmMaze/BallonsTranslator/blob/dev/doc/saladict.md
on there said that we should change something to CTRL + S right?

but where we get that
![image](https://github.com/dmMaze/BallonsTranslator/assets/29838157/bccc4823-f7e4-4276-bc26-1e32fd3228bc)
no single setting that i search had those setting
can you tell me where it's?
or they already changed over time?

on my extension on /options.html?menuselected=SearchModes 
/options.html?menuselected=General
and other
i can't find where that setting

**Comment by lhj5426** [comment]
edge://extensions/shortcuts 
chrome//extensions/shortcuts

**Comment by dhana-exe** [comment]
AHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHH
fuccc XD i got confused far away lol
now it's works perfectly fine now

thanks alot bro

**Comment by dhana-exe** [comment]
yeah maybe it's just some dumbness from me....
thanks anyway
