### ISSUE TITLE
可以 把模型选择这里开放成手动输入的吗

### ISSUE THREAD

**Issue by lhj5426** [dmMaze/BallonsTranslator#275]
![image](https://github.com/dmMaze/BallonsTranslator/assets/30548000/a978fdd2-1cff-4a70-b826-db83970138ac)
这里大佬现在是写死的
![image](https://github.com/dmMaze/BallonsTranslator/assets/30548000/468f0e71-65a2-433f-98b1-48d4e19934c1)
如果可以做成这样
![image](https://github.com/dmMaze/BallonsTranslator/assets/30548000/6223dccf-7a71-40c6-bd76-ca7ceda16bee)
手动写入的话
![image](https://github.com/dmMaze/BallonsTranslator/assets/30548000/7238125b-b02d-4c17-85fe-5668717a174e)
用户自己就可以马上写入并使用最新的模型

**Comment by dmMaze** [comment]
45f5790 加了，往override model写东西就会覆盖选中模型
