### ISSUE TITLE
字体大小又。。。。

### ISSUE THREAD

**Issue by lhj5426** [dmMaze/BallonsTranslator#279]
https://github.com/dmMaze/BallonsTranslator/assets/30548000/2614c526-4007-4b8c-87c0-8483ec078bc5
https://github.com/dmMaze/BallonsTranslator/issues/202
 之前提到过  大佬您也修修了 不过 现在又 复现了。 ？

**Comment by lhj5426** [comment]
现在只运行OCR的时候 只会 改颜色 字体大小无变化

https://github.com/dmMaze/BallonsTranslator/assets/30548000/d4e1376d-da1e-4f15-9b85-3749211f0363

**Comment by dmMaze** [comment]
https://github.com/dmMaze/BallonsTranslator/commit/45f579072a9bfe521deaaa4a05557c008e3c61f9 应该修好了

**Comment by lhj5426** [comment]
> [45f5790](https://github.com/dmMaze/BallonsTranslator/commit/45f579072a9bfe521deaaa4a05557c008e3c61f9) 应该修好了

嗯 修复了 
谢谢

刚才更新的时候好像还增加了一个新的模型
![image](https://github.com/dmMaze/BallonsTranslator/assets/30548000/da84a92e-0a91-43ea-8df9-25a863a5a038)
