### ISSUE TITLE
ModuleNotFoundError: No module named 'qtpy'

### ISSUE THREAD

**Issue by num421337** [dmMaze/BallonsTranslator#28]
I tried building the program so I could try using sugoi translator with this, and I after about a day of it running (not sure why it was so slow) it finally finished but when I try and run the ballontranslator.exe it gives me this error

Traceback (most recent call last):
  File "H:\apps\BallonsTranslator\release\BallonTranslator.dist\__main__.py", line 44, in <module>
  File "H:\apps\BallonsTranslator\release\BallonTranslator.dist\__main__.py", line 19, in main
ModuleNotFoundError: No module named 'qtpy'

**Comment by dmMaze** [comment]
You don't need to build it to use sugoi.

**Comment by num421337** [comment]
Then what do I do?

**Comment by num421337** [comment]
I didn't have a few requirements installed in my python, but also running it through main.py was much better thank you
