### ISSUE TITLE
不知道是不是BUG  一个识别上的问题

### ISSUE THREAD

**Issue by lhj5426** [dmMaze/BallonsTranslator#282]
请大佬看视频

https://github.com/dmMaze/BallonsTranslator/assets/30548000/ad1bbb03-5aad-4e1e-b234-08100d610480

视频1 上的两张图 每个都有 一个空气泡
然后 我很肯定 并且仔细的检查了我的配置里
是没有过滤掉
疲れた……

なんだこれ
这2个被漏识别的词语的

然后

https://github.com/dmMaze/BallonsTranslator/assets/30548000/453cfc69-ba89-46d2-9a64-64543d9e9fc6

视频2 是我把配置文件删除之后 O 过滤 识别的 就正常 识别出文字内容了

然后 这个是我 配置文件

[Aconfig - 复制.zip](https://github.com/dmMaze/BallonsTranslator/files/13322893/Aconfig.-.zip)

这个是 视频里用来说明问题的图片原图
[OCR替换测试.zip](https://github.com/dmMaze/BallonsTranslator/files/13322915/OCR.zip)

还请烦劳 大佬看一下 这个问题 

我是非常的确定 我的配置文件里 确实没有过滤这2个词 出了问题之后我用记事本的搜索 和过滤都搜过了
但是使用这个配置文件 就确确实实会出现如视频1里的问题

**Comment by dmMaze** [comment]
是你自己正则把这些去掉了，

``` python
import json

# 待替换字符
text_list = ['なんだこれ', '疲れた……']

# buggyconfig.json是你自己程序的config.json
with open('buggyconfig.json', 'r', encoding='utf8') as f:
    config_dict = json.loads(f.read())

# 所有ocr替换的规则
sublist = config_dict['ocr_sublist']

for text in text_list:
    for ii, subpair in enumerate(sublist):
        k = subpair['keyword']
        if k == '':
            continue
        
        regexr = k
        flag = re.DOTALL
        if not subpair['case_sens']:
            flag |= re.IGNORECASE
        if not subpair['use_reg']:
            regexr = re.escape(regexr)

        text_after = re.sub(regexr, subpair['sub'], text)

        # 成功匹配发生替换
        if text_after != text:
            print(ii, subpair, f'{text} was replaced to {text_after}')
```

用上面脚本跑你配置替换发送的规则是:
2621 {'keyword': '^.....$', 'sub': '', 'use_reg': True, 'case_sens': True} なんだこれ was replaced to 
2621 {'keyword': '^.....$', 'sub': '', 'use_reg': True, 'case_sens': True} 疲れた…… was replaced to 

'^.....$'是匹配五字字符 （"……"算两个字符)
以后你正则有问题可以自行用上面代码查错

**Comment by lhj5426** [comment]
这这这 好吧 还是自己的锅 
感谢大佬提供的代码
我用gpt4 修改了下 改成了 
把JSON 拖拽到 .PY文件上然后在目录下生成一个TXT 
TXT里保护 正则结果 和正则

以后再遇到这种问题  我会先用大佬提供的脚本 排错

import json
import re
import sys

def process_text_with_config(text_list, config_dict):
    results = []
    sublist = config_dict['ocr_sublist']

    for text in text_list:
        for ii, subpair in enumerate(sublist):
            k = subpair['keyword']
            if k == '':
                continue
            
            regexr = k
            flag = re.DOTALL
            if not subpair['case_sens']:
                flag |= re.IGNORECASE
            if not subpair['use_reg']:
                regexr = re.escape(regexr)

            text_after = re.sub(regexr, subpair['sub'], text, flags=flag)

            # 成功匹配发生替换
            if text_after != text:
                result = f'Match #{ii}: "{text}" replaced with "{text_after}" using regex "{regexr}"'
                results.append(result)
    
    return results

if __name__ == "__main__":
    if len(sys.argv) < 2:
        print("Please drag a .json file onto this script.")
        sys.exit(1)

    json_file_path = sys.argv[1]
    with open(json_file_path, 'r', encoding='utf8') as f:
        config_dict = json.load(f)

    # 这里是待替换的字符列表
    text_list = ['なんだこれ', '疲れた……']

    # 处理文本并获取结果
    results = process_text_with_config(text_list, config_dict)

    # 将结果写入TXT文件
    with open('detailed_results.txt', 'w', encoding='utf8') as f:
        for line in results:
            f.write(line + '\n')
    
    print("Detailed results have been written to 'detailed_results.txt'")
