### ISSUE TITLE
The application does not open

### ISSUE THREAD

**Issue by ahraf1234** [dmMaze/BallonsTranslator#286]
![1](https://github.com/dmMaze/BallonsTranslator/assets/65016388/23baffe9-5728-4c9f-8689-9a4fc70b45b4)
![2](https://github.com/dmMaze/BallonsTranslator/assets/65016388/df5d1fed-afde-496d-a504-1b160cb3d805)

**Comment by dmMaze** [comment]
upgrade your gpu driver and run git pull

**Comment by ahraf1234** [comment]
![3](https://github.com/dmMaze/BallonsTranslator/assets/65016388/4329c018-9fcb-417d-b6de-1f056af0477e)

**Comment by ahraf1234** [comment]
> upgrade your gpu driver and run git pull

I done that but it still not working.

**Comment by ahraf1234** [comment]
Should I download the portable edition ?

**Comment by ahraf1234** [comment]
> I cannot help you without further information about the exact execution problem, your system, and the setup environment, even if I want to. You could run the source code.

Thanks a lot, I ran the code and it works perfectly.
