### ISSUE TITLE
Deepl free翻译器默认设置的延迟太低导致IP被封杀。Error: Too many requests, your IP has been blocked by DeepL temporarily, please don't request it frequently in a short time.

### ISSUE THREAD

**Issue by gsxgmpkt9020** [dmMaze/BallonsTranslator#287]
```
Traceback (most recent call last):
  File "D:\Applications\BallonTranslator\ui\module_manager.py", line 232, in _run_translate_pipeline
    self._translate_page(self.imgtrans_proj.pages, page_key, raise_exception=True, emit_finished=False)
  File "D:\Applications\BallonTranslator\ui\module_manager.py", line 203, in _translate_page
    raise e
  File "D:\Applications\BallonTranslator\ui\module_manager.py", line 195, in _translate_page
    self.translator.translate_textblk_lst(page)
  File "D:\Applications\BallonTranslator\modules\translators\base.py", line 196, in translate_textblk_lst
    _translations = self.translate(text_list)
  File "D:\Applications\BallonTranslator\modules\translators\base.py", line 145, in translate
    text_trans = self._translate([text_source])[0]
  File "D:\Applications\BallonTranslator\modules\translators\trans_deeplx.py", line 230, in _translate
    tl = translate(t,source,target)
  File "D:\Applications\BallonTranslator\modules\translators\trans_deeplx.py", line 153, in translate
    raise TooManyRequestsException
modules.translators.trans_deeplx.TooManyRequestsException: Error: Too many requests, your IP has been blocked by DeepL temporarily, please don't request it frequently in a short time.

```

**Comment by bropines** [comment]
> ```
> Traceback (most recent call last):
>   File "D:\Applications\BallonTranslator\ui\module_manager.py", line 232, in _run_translate_pipeline
>     self._translate_page(self.imgtrans_proj.pages, page_key, raise_exception=True, emit_finished=False)
>   File "D:\Applications\BallonTranslator\ui\module_manager.py", line 203, in _translate_page
>     raise e
>   File "D:\Applications\BallonTranslator\ui\module_manager.py", line 195, in _translate_page
>     self.translator.translate_textblk_lst(page)
>   File "D:\Applications\BallonTranslator\modules\translators\base.py", line 196, in translate_textblk_lst
>     _translations = self.translate(text_list)
>   File "D:\Applications\BallonTranslator\modules\translators\base.py", line 145, in translate
>     text_trans = self._translate([text_source])[0]
>   File "D:\Applications\BallonTranslator\modules\translators\trans_deeplx.py", line 230, in _translate
>     tl = translate(t,source,target)
>   File "D:\Applications\BallonTranslator\modules\translators\trans_deeplx.py", line 153, in translate
>     raise TooManyRequestsException
> modules.translators.trans_deeplx.TooManyRequestsException: Error: Too many requests, your IP has been blocked by DeepL temporarily, please don't request it frequently in a short time.
> ```

Enter a higher value in seconds here, such as 5 or 7

![image](https://github.com/dmMaze/BallonsTranslator/assets/57861007/2f46dea4-b370-4db2-906c-5d5407170bce)

**Comment by nyjah3007** [comment]
> 完成的

請問你最後是如何解決的呢？我用Deepl free遇到文字泡時一樣都會出現too many requests exception，即使我把 delay調高到50也改變不了
