### ISSUE TITLE
（功能）从当前页开始运行（翻译、渲染等等）以便处理新增文件避免从头部重复处理和覆盖

### ISSUE THREAD

**Issue by gsxgmpkt9020** [dmMaze/BallonsTranslator#288]
从当前页开始运行（翻译、渲染等等）以便处理新增文件避免重复处理和覆盖

<img width="422" alt="Snipaste_2023-11-14_14-30-30" src="https://github.com/dmMaze/BallonsTranslator/assets/2074641/84c4a4be-1727-4224-9e7c-98b1332e2149">

**Comment by bropines** [comment]
this can be done stupidly and easier. Select all the clouds of text, do ocr, click on translate page

**Comment by dmMaze** [comment]
按下T退出文本框创建模式就能拖拽选择了，或者alt+a全选当前页的文本框

**Comment by bropines** [comment]
> 按下T退出文本框创建模式就能拖拽选择了，或者ctrl+a全选当前页的文本框

I most likely think that he wants to immediately launch a full translation, recognition, and so on. At once, but on the same page. In the case of mit48, mi32, this helps significantly. and yes, for some reason mit48 does not work when selecting vertical text. Only horizontal, although if you run it through run, it recognizes it as it should.

**Comment by lhj5426** [comment]
其实不建议一起跑
先跑12 然后 手动修正 再跑3 
4 的话如果是自己看 其实完全没必要跑也行
而且主要出现闪退也是4 影响的 
![image](https://github.com/dmMaze/BallonsTranslator/assets/30548000/f8282df1-3ed6-436f-9fb2-f4b770fe6a16)
甚至 3可以单独导出文本去用设置更详细的翻译工具跑
然后导入  
闪退的主要原因 就是跑 4 显存爆了 
如果单独跑4 经常爆显存 的话
可以把图片复制一份然后分成多份 少量多次的跑
![image](https://github.com/dmMaze/BallonsTranslator/assets/30548000/d7c50573-bed2-4d27-a03b-db38ac91ccd0)

跑 完 再合并回inpainted  到原来整体文件的同名文件夹里

**Comment by lhj5426** [comment]
你按照 我这个说的去做一下 你会发现 会好用很多很多

**Comment by dmMaze** [comment]
> 显存直接就炸了

现在应该不会爆显存退出了，现在你用那个新修复模型和bf16应该没那么容易爆显存了，而且爆显存会回退cpu，倒是有可能爆内存。而且他是a卡所以应该不是这个问题。
异常处理确实一直挺拉的我有时间修一下。

**Comment by lhj5426** [comment]
> > 显存直接就炸了
> 
> 现在应该不会爆显存退出了，现在你用那个新修复模型和bf16应该没那么容易爆显存了，而且爆显存会回退cpu，倒是有可能爆内存。而且他是a卡所以应该不是这个问题。 异常处理确实一直挺拉的我有时间修一下。

嗯 好的 感谢指正说的不对地方

**Comment by lhj5426** [comment]
> > 其实不建议一起跑 先跑12 然后 手动修正 再跑3 因为软件 会把很多多余的非文字的部分也识别上 12跑完了可以手动清理这些 清理干净之后再继续 4 的话如果是自己看 其实完全没必要跑也行 而且主要出现闪退也是4 影响的 ![image](https://user-images.githubusercontent.com/30548000/282830246-f8282df1-3ed6-436f-9fb2-f4b770fe6a16.png) 甚至 3可以单独导出文本去用设置更详细的翻译工具跑 然后导入 闪退的主要原因 就是跑 4 显存爆了 如果单独跑4 经常爆显存 的话 可以把图片复制一份然后分成多份 少量多次的跑 ![image](https://user-images.githubusercontent.com/30548000/282830920-d7c50573-bed2-4d27-a03b-db38ac91ccd0.png)
> > 跑 完 再合并回inpainted 到原来整体文件的同名文件夹里
> > 我图里的文件夹就是 漫画有1000多页 我分成了一次200张一组 来跑 4 修复图像 因为一次跑一千张 显存直接就炸了 反倒更浪
> > 费时间 不如分开 确保 能跑完 软件不会炸显存 跑的少跑的也快
> 
> 1. 我这里主要是为了让项目文件在异常退出以后，在中断的地方继续跑，比如下面的错误导致的中断。
>    [Deepl free翻译器默认设置的延迟太低导致IP被封杀。Error: Too many requests, your IP has been blocked by DeepL temporarily, please don't request it frequently in a short time. #287](https://github.com/dmMaze/BallonsTranslator/issues/287)
> 
> 我想问下，比如你200页跑到100然后异常中断了（只是假设），是不是重新打开程序就只能从头开始跑？至少我这里是这样的。
> 
> 2. “运行”原来还有勾可以选用来分阶段处理，谢谢提醒。[能不能在有翻译的情况下 重新进行颜色识别 #189](https://github.com/dmMaze/BallonsTranslator/issues/189)
> 3. “导出文本”的脚本是这里的吗？我看了下你以前提的很多问题我都遇到了，经典实用，非常感谢。 [请问可以导出ocr的漫画原文吗 #232](https://github.com/dmMaze/BallonsTranslator/issues/232)
> 4. 更详细的翻译工具你用的是_gpt_-translator还是manga-image-translator？可以介绍下用的具体工具吗？
>    ![image](https://user-images.githubusercontent.com/2074641/282923952-c5044782-2b99-4408-ae56-fbc893b8bdad.png)
>    我看你以前用的是_GPT_ API，需要用到多个_GPT_账号轮询吗？否则好像大量连续翻译会超时。我听说过GAL翻译是需要轮询的。
> 5. 我看见你之前说和_GPT_小伙伴一起写了互转manga-image-translator和BallonsTranslator配置文件的脚本，我这边没有商业级别的_gpt_，只有网上一点点tokens的玩具。互转的脚本能分享下吗？谢谢
>    ![image](https://user-images.githubusercontent.com/2074641/282933527-500e2471-6f7f-4551-ac0d-2fdeaff47084.png)

支持轮训  支持设置 挺多东西的
https://github.com/NEKOparapa/AiNiee-chatgpt
这个 GPT翻译 工具

**Comment by lhj5426** [comment]
然后 你没发现么 如果运行出错 只能关闭重开 这时候 项目文件都不会保留任何刚才跑的东西所以也不存在 继续跑的可能 就目前为止
所以为了不出错一次性顺利的跑完 页数多做好是分开

**Comment by Mistermozg1** [comment]
> > Выделите все облака текста,
> 
> Как я могу «Выбрать все облака текста» на определенных страницах одновременно, например: со страницы 40-100? Мы, Люди, можем выделять облака текста только одно за другим, страницу за страницей. Я прошу выбрать пакет/пакет по страницам.

cntrl+A

**Comment by bropines** [comment]
in one of the posts, I already wrote a script to extract blocks of text or translation into a numbered txt file. I can forward it here, it's obviously easier than highlighting a hundred blocks on different pages
