### ISSUE TITLE
Icon

### ISSUE THREAD

**Issue by bropines** [dmMaze/BallonsTranslator#29]
I've been working on adding an icon here. Everything worked out, but I still don't understand how to change the icon in the Windows taskbar
![image](https://user-images.githubusercontent.com/57861007/187178130-9a36f952-0b03-4715-a8d8-eefb70fd428d.png)

We drew the icon from scratch with [Lavanette](https://github.com/HideriLavanette)

**Comment by bropines** [comment]
`self.setWindowTitle("My Window")
  self.setWindowIcon(QtGui.QIcon('test_icon.png'))`
used this module

**Comment by dmMaze** [comment]
Whoa, thanks in advance!  

Copy-paste following lines into ```ballontranslator/__main__.py```
``` python
    if sys.platform == 'win32':
        import ctypes
        myappid = u'BalloonsTranslator' # arbitrary string
        ctypes.windll.shell32.SetCurrentProcessExplicitAppUserModelID(myappid)
```
<img width="612" alt="image" src="https://user-images.githubusercontent.com/51270320/187196664-5c8d7f42-3dd3-46c0-a365-dab3a2e8f11d.png">

Besides, I would like to suggest using #697187 instead of pure black.  
And would you kindly make it a bit less like DeepL's?

**Comment by bropines** [comment]
> Besides, I would like to suggest using #697187 instead of pure black. And would you kindly make it a bit less like DeepL's?
1. I think we'll fix the color.  
2. The reference was just taken from DeepL)
I have already sent the files to the email address specified in your github profile. I'm just warning you. Now we will quickly make a redesign

**Comment by dmMaze** [comment]
I have made the pre-mentioned changes to master branch. You only need to modify the following line to specify the icon file path:
https://github.com/dmMaze/BallonsTranslator/blob/18a65651dce7700e24de9e17496173cc3d58cdfb/ballontranslator/ui/constants.py#L3

**Comment by bropines** [comment]
![image](https://user-images.githubusercontent.com/57861007/187214357-c658dd86-1b8e-4266-8def-8efb2279c308.png)
For some reason windows refuses to show the icon in the taskbar. Maybe it's because I have the Python microsoft store?

**Comment by dmMaze** [comment]
Did you update to 18a65651dce7700e24de9e17496173cc3d58cdfb? 
<img width="54" alt="image" src="https://user-images.githubusercontent.com/51270320/187224014-727030ee-f41f-4932-92d9-d90207e48019.png">

Run the following code, what's the output?
``` python
import sys
print(sys.platform)
```

**Comment by bropines** [comment]
![image](https://user-images.githubusercontent.com/57861007/187225840-e6fe4fae-60f0-4e84-be85-1b80237499a9.png)

**Comment by dmMaze** [comment]
hmm, it works on my set:  
```
Python 3.8.10 (tags/v3.8.10:3d8993a, May  3 2021, 11:48:03) [MSC v.1928 64 bit (AMD64)] on win32
PyQt: v 5.15.4  
```

try add ```app.setWindowIcon(QIcon(constants.ICON_PATH))``` following this line: https://github.com/dmMaze/BallonsTranslator/blob/18a65651dce7700e24de9e17496173cc3d58cdfb/ballontranslator/__main__.py#L42

**Comment by bropines** [comment]
![image](https://user-images.githubusercontent.com/57861007/187232186-f30ed9a1-94fa-4fcf-b3d7-5fb1a9f2fbd3.png)
Failure again. I think the fact is that I have a python version downloaded from the MIcrosoft Store and windows stupidly blocks any changes

**Comment by dmMaze** [comment]
Did the program's terminal spit out any unsual message on start-up?

**Comment by bropines** [comment]
> D:\ai\BallonsTranslator\ballontranslator>python __main__.py
[INFO   ] dl_manager:on_finish_setdetector:622 - Text detector set to ctd
[INFO   ] dl_manager:on_finish_settranslator:643 - Translator set to google
[INFO   ] dl_manager:on_finish_setinpainter:635 - Inpainter set to aot
[INFO   ] dl_manager:on_finish_setocr:628 - OCR set to mit48px_ctc

And nothing more

Maybe we should switch to some messenger (by the type of telegram) to communicate more conveniently?

**Comment by dmMaze** [comment]
You may send a telegram chat link to beneathlimbo@gmail.com

**Comment by bropines** [comment]
I send

**Comment by bropines** [comment]
I'll close the question for now. There is an updated icon in my fork, someday we will get to the icon, but not now.
