### ISSUE TITLE
“翻译本页”的翻译比起对话框单独翻译会不一样（deepl free）【使用方法提问】

### ISSUE THREAD

**Issue by gsxgmpkt9020** [dmMaze/BallonsTranslator#291]
是接口调用的API不同还是程序运行方式不同？还是说“翻译本页”是有特殊优化的。

比如我查了下deepl的网页翻译某句话中的“エルフ様”会翻译成“精灵大师”（三种候选都是一样的翻译）

![image](https://github.com/dmMaze/BallonsTranslator/assets/2074641/2eb8ee5d-2f71-4246-a300-6093a8479e72)

而[BallonsTranslator](https://github.com/dmMaze/BallonsTranslator)用deepl free对话框翻译和deepl的网页翻译一致。

但是“翻译本页”往往会出现不同的翻译（，难道翻译本页会进行特殊短句、结合上下文调用全文翻译API（然后再拆分成句）???  还是说“翻译本页”应用到了延迟效果，或者其他原因

还有一个例子：
ゴクンと静かな部屋にかの女の鳴らした音が響き渡りました．．．。

翻译本页（CTRL-A翻译一样效果）：女人的哭声在安静的房间里回荡着......
翻译框：潺潺的流水声在安静的房间里回荡......女人的铃声在房间里回荡......

顺便说一下，GPT的翻译是：咕咕地，寂静的房间里响起了那个女人发出的声音……。”
Google Bard：在静谧的房间里，那个女人发出的咕噜声响彻了整个房间……（我把性别改掉bard才很不情愿地同意翻译）

似乎确实就是单选翻译框，质量会比较差

**Comment by dmMaze** [comment]
翻译整页会所有对话一起送去翻译，语境更完整了，你让活人翻译也是一样的效果
