### ISSUE TITLE
有些区域翻译某个词会出现过高频率的重复（比如：不，不，不...(省略)...不，不，不。）

### ISSUE THREAD

**Issue by gsxgmpkt9020** [dmMaze/BallonsTranslator#292]
和翻译器没有强相关，换了还是一样有类似现象

![image](https://github.com/dmMaze/BallonsTranslator/assets/2074641/c3a2e616-2477-477a-bf5a-b315bfef040c)

![image](https://github.com/dmMaze/BallonsTranslator/assets/2074641/be32b8fc-7b6a-4ccb-ad92-36079c48e6d8)

「あっっおじいちゃっっもう、あっ、だめええっっ

哦，大井茶，哦，不，不，不，不，不，不，不，不，不，不，不，不，不，不，不，不。

严重的时候会占据半个屏幕

顺便放下正确翻译：“啊，爷爷，啊，不！

（试了Google Bard 被认为是违反风纪的不健全语气词，真是无语了）

**Comment by lhj5426** [comment]
这个问题是润色阶段的事情
给你个例子
![image](https://github.com/dmMaze/BallonsTranslator/assets/30548000/cd4b0667-bb95-40ed-887f-769c6d6dec15)

**Comment by lhj5426** [comment]
另外 如果你知道格式的话
![image](https://github.com/dmMaze/BallonsTranslator/assets/30548000/e88a28ae-bfab-4f21-922e-764b6c47e5b9)
可以通过 这个功能的正则 来翻译的时候自动修正

**Comment by lhj5426** [comment]
> > 为什么要_润色_就是为了修正 各种 _机翻_不合理的问题 和语句不通顺的 不是咔嚓 _机翻_跑一下就拉拉倒了 润完色之后是这样的 !这> 是翻译引擎的问题 _润色_是必要的
> 
> 你把图片去掉吧，有些没清理干净对社区和版主不好
> 
> ![image](https://user-images.githubusercontent.com/2074641/283238585-207b41e0-c38a-4c8f-bc02-a1ec08a5230b.png)
> 
> 我现在觉得应该是翻译器检测到内容敏感，所以故意打哈哈。网页字数少应该是它根据文本框长度主动调节的
> 
> ![image](https://user-images.githubusercontent.com/2074641/283241819-156aed52-357b-46db-8c5c-40fd483ad0ac.png)

这种时候就该轮到听译 朗读软件出场了
https://github.com/VOICEVOX/voicevox
首先听一下朗读 然后 短句 分开一部分 一部分去喂给各大翻译引擎
这里推荐同时使用 https://github.com/HIllya51/LunaTranslator
和划词翻译 或者沙拉查词 或者pot  https://github.com/pot-app/pot-desktop
来进行 一键多引起 调用
