### ISSUE TITLE
openai version error output when translating chatgpt

### ISSUE THREAD

**Issue by MIBIN12** [dmMaze/BallonsTranslator#294]
When I click the run button with "chatgpt", the message continues to repeat in the cmd window.

The operation continues to stop with the message repeated.

I tried with dev version "BallonsTranslator_dev_src_with_gitpython".

No other python installed.

[WARNING] trans_chatgpt:_translate:239 - Translation failed due to

You tried to access openai.ChatCompletion, but this is no longer supported in openai>=1.0.0 - see the README at https://github.com/openai/openai-python for the API.

You can run `openai migrate` to automatically upgrade your codebase to use the 1.0.0 interface.

Alternatively, you can pin your installation to the old version, e.g. `pip install openai==0.28`

A detailed migration guide is available here: https://github.com/openai/openai-python/discussions/742
. Attempt: 1, sleep for 15 secs...

**Comment by dmMaze** [comment]
run git pull (or double click scripts/local_gitpull.bat) and try if [c76ce33](https://github.com/dmMaze/BallonsTranslator/commit/c76ce3311fd13224ef351a64890e7010aea02e14) fixes the issue

**Comment by MIBIN12** [comment]
Thank you for answer. After searching on my own, I just solved the problem by fixing the openai version using the pip command. However, if you try to translate multiple photos at once, the following message is displayed.

If I proceed with the photos one by one, they are translated normally.

Traceback (most recent call last):
  File "C:\Users\SYJ\Downloads\BallonsTranslator_dev_src_with_gitpython\BallonsTranslator_dev_src_with_gitpython\ui\mainwindow.py", line 900, in on_pagtrans_finished
    blk.set_font_colors(fg_colors=gf.frgb)
TypeError: TextBlock.set_font_colors() missing 1 required positional argument: 'bg_colors'

**Comment by dmMaze** [comment]
> Thank you for answer. After searching on my own, I just solved the problem by fixing the openai version using the 'pip install openai==0.28' command.
> 
> However, if I try to translate multiple photos at once, the following message is displayed.
> 
> If I proceed with the photos one by one, they are translated normally.
> 
> Can I get some help on this?
> 
> Traceback (most recent call last): File "C:\Users\SYJ\Downloads\BallonsTranslator_dev_src_with_gitpython\BallonsTranslator_dev_src_with_gitpython\ui\mainwindow.py", line 900, in on_pagtrans_finished blk.set_font_colors(fg_colors=gf.frgb) TypeError: TextBlock.set_font_colors() missing 1 required positional argument: 'bg_colors'

fixed by https://github.com/dmMaze/BallonsTranslator/commit/1f2ad36b6d7dd023caa509f1cb793049c0ed1c9f

**Comment by MIBIN12** [comment]
It was resolved right away. Thank you for your reply.
