### ISSUE TITLE
Brazilian Portuguese(pt-BR) for DeepL Free target language.

### ISSUE THREAD

**Issue by wensleyoliv** [dmMaze/BallonsTranslator#295]
There's only Portuguese available, but the differences of Portuguese and Brazilian Portuguese are too much, i tried to add it modifying files, but i gives a Http error or something. If it's possible i would like you to add Brazilian Portuguese as a target language in DeepL Free. Thanks.

**Comment by dmMaze** [comment]
added by d0f431b
