### ISSUE TITLE
实用功能增强：搜索替换功能区，提供一键连续重复字符优化（译文区域）

### ISSUE THREAD

**Issue by gsxgmpkt9020** [dmMaze/BallonsTranslator#297]
对于这里出现的现象的一键优化，让连续重复字符上限小于置顶数目（删除多余字符）

https://github.com/dmMaze/BallonsTranslator/issues/292

翻译言情、热血运动的漫画这类现象出现比较频繁

**Comment by dmMaze** [comment]
这个正则都可以搞定

<img width="532" alt="image" src="https://github.com/dmMaze/BallonsTranslator/assets/51270320/789a83f5-40eb-4da5-83c4-b09e3f5d7bc0">

上面例子保证字符重复次数<=5
