### ISSUE TITLE
为什么同样是用的manga-image-translator的aot图像修复工具，会有差别呢？

### ISSUE THREAD

**Issue by fanglangxinghai** [dmMaze/BallonsTranslator#299]
原图：
![1](https://github.com/dmMaze/BallonsTranslator/assets/55346060/a6030979-a036-4420-a394-5fd0d1cf8096)

BallonsTranslator（使用的aot图像修复）：
![2](https://github.com/dmMaze/BallonsTranslator/assets/55346060/a1654a4a-cec6-4612-8247-6a89ca102293)

manga-image-translator的在线网站（https://cotrans.touhou.ai/）：
![3](https://github.com/dmMaze/BallonsTranslator/assets/55346060/e837101f-a2ad-4ea0-b929-d716961d616f)

**Comment by dmMaze** [comment]
其实分两步，抠字然后修复，修复模型只负责第二步。上图是抠字差别，你膨胀下掩膜也差不多了

**Comment by fanglangxinghai** [comment]
@dmMaze 
请问一下哪里进行“膨胀下掩膜”？

**Comment by dmMaze** [comment]
> @dmMaze 
> 请问一下哪里进行“膨胀下掩膜”？

#261

**Comment by fanglangxinghai** [comment]
@dmMaze 
非常感谢，现在这样效果就好多了，顺便问一下，那个图像修复的“方法1”和“方法2”有什么区别吗？我试了下，感觉好像没啥区别。

**Comment by dmMaze** [comment]
> 非常感谢，现在这样效果就好多了，顺便问一下，那个图像修复的“方法1”和“方法2”有什么区别吗？我试了下，感觉好像没啥区别。

基本没有，要是方法1不管用就试试方法2这样
