### ISSUE TITLE
Error when translating with Portuguese or Brazilian Portuguese on DeepL Free.

### ISSUE THREAD

**Issue by wensleyoliv** [dmMaze/BallonsTranslator#300]
Thanks for adding support for Brazilian Portuguese as i requested, but now both Portuguese and Brazilian Portuguese translations are not working, the following error appears:

![cmd error](https://github.com/dmMaze/BallonsTranslator/assets/14226926/5e2da596-7ed1-4ee9-b122-9f4d73edb7cc)

**Comment by dmMaze** [comment]
it seems the free one refuses the Brazilian language code https://www.deepl.com/docs-api/translate-text
you could try the api
