### ISSUE TITLE
增加 locker of translation of unselected boxes 防住自己精修翻译被刷新覆盖

### ISSUE THREAD

**Issue by gsxgmpkt9020** [dmMaze/BallonsTranslator#303]
### 现在的情况下：

很多时候需要用设置的机器翻译单独（或者同时批量）更新一个（或者几个）框中的译文，但是又需要保证他是结合该页上下文的翻译，所以这时候需要用到一键翻译（或者全选后翻译）。

但是如果此时已经有几个自己精修过翻译，那么就会被自动刷新覆盖

**希望能加一个锁，或者菜单勾。locker of translation of unselected boxes防住自己精修翻译被刷新覆盖**

### 增加功能后的情况下：
点击该状态的锁按钮（一种全局状态切换，锁按钮本身不指定对象）

选中一个或者几个需要机器翻译的框，然后点击“一键翻译”：效果是既保证了是结合该页上下文的翻译，同时又保住了未选中的框中的自己精修的翻译。

**Comment by dmMaze** [comment]
好绕啊，你为啥精修后还要跑机番，已翻译的内容对翻译器是不可见的啊，翻译器只能看到原文
除非你用chatgpt, 你可以直接拿现有有的翻译给它当例子

**Comment by lhj5426** [comment]
吐槽下 要么就只说中文 要么就只说英文
不要英文夹杂着 英文
而且这个逻辑。。我自己做漫画润色快2年了
全部作品在这里
https://exhentai.org/?f_search=uploader%3Allflzy+uploader%3A%E6%B7%AB%E4%B9%A6%E9%A6%86+uploader%3AL%E6%B7%AB%E4%B9%A6%E9%A6%86L+uploader%3A%E6%B7%AB%E6%9B%B8%E9%A6%86
 你这个逻辑
我就没有看明白 
机器翻译只翻一遍就够了
润色全都是手动 无须再机器翻译参与全程一个气泡一个破的润的话
也是用其他翻译来辅助
而不是用软件上的翻译再无意义的跑一边
