### ISSUE TITLE
翻页会导致抹字图层回档

### ISSUE THREAD

**Issue by didala083** [dmMaze/BallonsTranslator#308]
已经多次复现了该问题，已经将dev版更新到最新。

复现方法：
使用右键一键OCR+翻译+抹字后，保存更改，然后翻页后再回到这一页，OCR和翻译结果保存了，抹字图层的保存未更改！

但是，如果在一键操作后进行了手动抹字，抹字涂层的保存就会保留！应该是哪里的保存逻辑出了问题吧~

之前因为一键三连完后总有些没有抹干净的地方有手动抹字操作，最近有几页漫画抹得比较好才发现有这个问题~

另外，请愿在右键菜单中将抹字功能分离出来~这样更方便操作！

**Comment by dmMaze** [comment]
修了，抹字也单独开了
