### ISSUE TITLE
當有文字和符號的時候，符號會左歪無法置中

### ISSUE THREAD

**Issue by minimoonleaf** [dmMaze/BallonsTranslator#316]
當有文字和符號的時候，符號會左歪無法置中
![螢幕擷取畫面 2023-11-30 005504](https://github.com/dmMaze/BallonsTranslator/assets/90105166/f87ce3f8-9532-4310-8fbc-f43b7d27c027)

**Comment by dmMaze** [comment]
最新版是正常的，这是哪个版本啥系统啥字体，那个心unicode是啥 (不确定直接贴上来

**Comment by minimoonleaf** [comment]
這個符號 ♡

**Comment by dmMaze** [comment]
> > 最新版是正常的，这是哪个版本啥系统啥字体，那个心unicode是啥 (不确定直接贴上来
> 
> BallonTranslator_V1.3.35
> 系統: Windows 10
> 字體: Microsoft YaHei UI
> 符號: ♡
> 轉換unicode: \u2661

那直接用最新版吧，看readme安装

**Comment by minimoonleaf** [comment]
> > > 最新版是正常的，这是哪个版本啥系统啥字体，那个心unicode是啥 (不确定直接贴上来
> > 
> > 
> > BallonTranslator_V1.3.35
> > 系統: Windows 10
> > 字體: Microsoft YaHei UI
> > 符號: ♡
> > 轉換unicode: \u2661
> 
> 那直接用最新版吧，看readme安装

目前最新版的不是1.3.35嗎? 還有更新版的嗎?

**Comment by dmMaze** [comment]
> > > > 最新版是正常的，这是哪个版本啥系统啥字体，那个心unicode是啥 (不确定直接贴上来
> > > 
> > > 
> > > BallonTranslator_V1.3.35
> > > 系統: Windows 10
> > > 字體: Microsoft YaHei UI
> > > 符號: ♡
> > > 轉換unicode: \u2661
> > 
> > 那直接用最新版吧，看readme安装
> 
> 目前最新版的不是1.3.35嗎? 還有更新版的嗎?

不是，看下dev版本的readme
release 那个应该被mark as deprecated了
