### ISSUE TITLE
Add shortcuts for paint mode instruments

### ISSUE THREAD

**Issue by bropines** [dmMaze/BallonsTranslator#319]
Bind the buttons on the keyboard like this (except for the hand, it is not necessary, the middle button is there): 
![image](https://github.com/dmMaze/BallonsTranslator/assets/57861007/f1125a03-5ccc-4905-899c-0ed8923db0a3)

And it would be a cool feature to personally bind the keys of the keyboard to the desired functions, in the future

**Comment by Mistermozg1** [comment]
i do that with autohotkey! yeeeaaah!!
