### ISSUE TITLE
Moving the page when the middle mouse button is held down

### ISSUE THREAD

**Issue by bropines** [dmMaze/BallonsTranslator#32]
Figma has a pretty handy feature. When you press the middle mouse button, you can move the page (not the object). It would be convenient not to select a special drag tool, but just hold down the middle mouse button

**Comment by dmMaze** [comment]
Panning with middle button has been supported: 51d165dc6f8a1f7777ff05e3a1249f102083066e

**Comment by bropines** [comment]
Working
