### ISSUE TITLE
The latest update made saved images outputs blurrier

### ISSUE THREAD

**Issue by himouto** [dmMaze/BallonsTranslator#320]
Just noticed that the latest update made saved images blurrier... it wasn't like this last month

Try starting a new project then compare the image quality side-by-side between the RAW and the translated ones from the results folder

It wasn't like this last month because I have backlog of projects from then that don't have blurry image results

I tried re-installing completely also tried changing Inpainter from aot to lama_large_512px - same results

The Result Image format is PNG

**Comment by bropines** [comment]
it seems there is a quality parameter in the settings (for webm exactly). Can he help?

**Comment by bropines** [comment]
> > it seems there is a quality parameter in the settings (for webm exactly). Can he help?
> 
> I already tried webm - also blurry

Hmmmm, let's wait for dmaze, but I'll take a look at how the image system works there.

**Comment by dmMaze** [comment]
It is a serious problem and it's there for a month! Thanks for catching it!
