### ISSUE TITLE
result文件夹生成的结果图片稀奇古怪

### ISSUE THREAD

**Issue by didala083** [dmMaze/BallonsTranslator#322]
DEV版更新到最新，发现结果图片各种稀奇古怪的问题，大体上都是没有铺满画布范围。删除后重新保存生成也是一样的问题。
<img width="499" alt="屏幕截图 2023-11-30 215323" src="https://github.com/dmMaze/BallonsTranslator/assets/64563710/ede31401-93e4-4a72-938a-10351fe1668f">

**Comment by dmMaze** [comment]
https://github.com/dmMaze/BallonsTranslator/commit/5a465482cb51847f7e57fba0d22d2a62799b4334 这次应该没问题了
