### ISSUE TITLE
最新的ocr模型应该是mit48px吧，为什么默认模型不是这个呢？

### ISSUE THREAD

**Issue by fanglangxinghai** [dmMaze/BallonsTranslator#326]
mit48px的ocr效果应该是最好的吧，我觉得应该安装完后，默认的ocr模型是mit48px比较好，为什么现在是mit48px_ctc？

**Comment by bropines** [comment]
> mit48px的ocr效果应该是最好的吧，我觉得应该安装完后，默认的ocr模型是mit48px比较好，为什么现在是mit48px_ctc？

Because we may have forgotten to change the default config. As soon as you change to another one, the program will remember it and will only use it.
