### ISSUE TITLE
请问有了解过sakura翻译模型吗？效果可以达到chatgpt3.5的水平

### ISSUE THREAD

**Issue by fanglangxinghai** [dmMaze/BallonsTranslator#329]
[https://github.com/SakuraLLM/Sakura-13B-Galgame](https://github.com/SakuraLLM/Sakura-13B-Galgame)

这是一个可以本地离线运行的翻译模型，现在对于显卡要求还是比较高的，感觉可以先了解着，等它再更新优化下，可以考虑添加到ballonstranlator里。

现在lunatranslator里面已经添加有sakura的翻译接口。

**Comment by bropines** [comment]
> https://github.com/SakuraLLM/Sakura-13B-Galgame
> 
> 这是一个可以本地离线运行的翻译模型，现在对于显卡要求还是比较高的，感觉可以先了解着，等它再更新优化下，可以考虑添加到ballonstranlator里。
> 
> 现在lunatranslator里面已经添加有sakura的翻译接口。

We can add an API connection to LLM, and you will just need to launch the neural network through clients like text-generation-webui and analogues.....

**Comment by xuejianxianzun** [comment]
看了下，显存要求太大了，没几个普通用户用得起

**Comment by fanglangxinghai** [comment]
> 看了下，显存要求太大了，没几个普通用户用得起

确实没错，现在我能想到的解决办法就是通过白嫖kaggle来翻译。而txt源文件的获取，则使用脚本，通过对ballonstranslator的json文件转换。当翻译完后的txt，则再转回去json。

[https://github.com/SakuraLLM/Sakura-13B-Galgame/wiki/%E7%99%BD%E5%AB%96Kaggle%E5%B9%B3%E5%8F%B0%E9%83%A8%E7%BD%B2%E6%95%99%E7%A8%8B](url)

[https://github.com/dmMaze/BallonsTranslator/issues/141#issuecomment-1789345964](url)

**Comment by fanglangxinghai** [comment]
> 看了下，显存要求太大了，没几个普通用户用得起

确实如此，我现在能想到的办法就是，用kaggle来白嫖显卡进行翻译。而日文txt源文件的获取，则利用BallonsTranslator进行ocr后的json文件，用脚本对json文件转为txt文件。txt文件翻译完后，再用脚本把中文译文的txt文件转回json文件。

https://github.com/SakuraLLM/Sakura-13B-Galgame/wiki/%E7%99%BD%E5%AB%96Kaggle%E5%B9%B3%E5%8F%B0%E9%83%A8%E7%BD%B2%E6%95%99%E7%A8%8B

https://github.com/dmMaze/BallonsTranslator/issues/141#issuecomment-1787629711
