### ISSUE TITLE
Brush tool is missing an eraser

### ISSUE THREAD

**Issue by bropines** [dmMaze/BallonsTranslator#33]
Suppose I've drawn something, but I want to erase some extra pieces and there is no eraser. If click Right mouse button, it turns on permanent drawing mode altogether

The video shows how it just starts drawing all the time after right-clicking

https://user-images.githubusercontent.com/57861007/187884204-d7d9f69b-90a5-4a85-9185-ac018c553b7d.mp4

**Comment by dmMaze** [comment]
fixed e1645e083ccc1e152c6b3e7c5e9d94a5d4cc2235
