### ISSUE TITLE
书写方向无法更改

### ISSUE THREAD

**Issue by lhj5426** [dmMaze/BallonsTranslator#332]
![image](https://github.com/dmMaze/BallonsTranslator/assets/30548000/ad91a790-d309-4358-8fa5-a73f2b3c46ea)
如图 无论设置全局  还是程序自动 
书写方向 始终是横着的 无法进行竖排 转换
这是遇到BUG了吗
大佬

**Comment by dmMaze** [comment]
你可以先试试删掉config.json重新跑图，或者跑下别的图
如果是config.json的问题看看“替换翻译结果的关键字”里有没有加什么奇怪的东西

**Comment by lhj5426** [comment]
> 你可以先试试删掉config.json重新跑图，或者跑下别的图 如果是config.json的问题看看“替换翻译结果的关键字”里有没有加什么奇怪的东西

随便拿出来跑了几页就可以正常修改方向
![image](https://github.com/dmMaze/BallonsTranslator/assets/30548000/13ece1f6-9efc-45dd-9632-9c3d1191ffe4)
随便 拿几张图跑就是正常的 
![image](https://github.com/dmMaze/BallonsTranslator/assets/30548000/3a990fd7-7e3d-41b7-b25a-8d92aa7f4da6)
批量跑  就很奇怪 
  用更多是 相同 的 config.json

**Comment by lhj5426** [comment]
删掉了 配置文件重新启动软件自动生成一个新的
重新跑OCR还是一样
![image](https://github.com/dmMaze/BallonsTranslator/assets/30548000/aceb93cc-e397-4f16-9810-6c5ed70d2059)

[imgtrans_本篇.json](https://github.com/dmMaze/BallonsTranslator/files/13638291/imgtrans_.json)
这是出问题的 漫画jSON

**Comment by lhj5426** [comment]
不知道什么问题 删除漫画的JSON 重新oCR  重新 跑 GPT 现在 又正常了
![image](https://github.com/dmMaze/BallonsTranslator/assets/30548000/eb732bfd-4d75-4d76-9a55-1d0f6d9832db)

**Comment by lhj5426** [comment]
不好意思 给大佬添麻烦了
虽然不知道到底怎么回事 不过 
删除JSON 重新跑完翻译 并且 又重新设置 字大小 书写方式为 软件自动决定  
并重跑OCR  翻译的字幕也会跟着重新 设定了 这个 就先关闭了 
非常不好意思
