### ISSUE TITLE
problems about manga_ocr

### ISSUE THREAD

**Issue by Raiter123** [dmMaze/BallonsTranslator#333]
I don't know why I can't choose the manga_OCR type as running OCR function , it will appear this!
![IMG_20231212_102625_042.jpg](https://github.com/dmMaze/BallonsTranslator/assets/153535038/d1f536d6-6708-467c-b1f7-5ee29e55fa55)

Is that any way to solve it , thank you

**Comment by bropines** [comment]
> I don't know why I can't choose the manga_OCR type as running OCR function , it will appear this! ![IMG_20231212_102625_042.jpg](https://private-user-images.githubusercontent.com/153535038/289725869-d1f536d6-6708-467c-b1f7-5ee29e55fa55.jpg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDIzNTIwOTksIm5iZiI6MTcwMjM1MTc5OSwicGF0aCI6Ii8xNTM1MzUwMzgvMjg5NzI1ODY5LWQxZjUzNmQ2LTY3MDgtNDY3Yy1iMWY3LTVlZTI5ZTU1ZmE1NS5qcGc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBSVdOSllBWDRDU1ZFSDUzQSUyRjIwMjMxMjEyJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDIzMTIxMlQwMzI5NTlaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0yZWIxNTQxYjljYjllOGMyZTdmYzVjNGM5ZjBkOTg0YzhmMTU1NDZjMmNkMWUxODFlOWEzZmRiYmEzOTQyZTlkJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.57nRC6E79JUfMK31thdO7-atdw7pxIhXKSWSv-mumts)
> 
> Is that any way to solve it , thank you

How did you install python?

**Comment by bropines** [comment]
If anything was written about this in the readme
![image](https://github.com/dmMaze/BallonsTranslator/assets/57861007/fc3edd7c-f6b6-4608-b4b1-c2c67ef59ce2)

**Comment by Raiter123** [comment]
> > I don't know why I can't choose the manga_OCR type as running OCR function , it will appear this! ![IMG_20231212_102625_042.jpg](https://private-user-images.githubusercontent.com/153535038/289725869-d1f536d6-6708-467c-b1f7-5ee29e55fa55.jpg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDIzNTIwOTksIm5iZiI6MTcwMjM1MTc5OSwicGF0aCI6Ii8xNTM1MzUwMzgvMjg5NzI1ODY5LWQxZjUzNmQ2LTY3MDgtNDY3Yy1iMWY3LTVlZTI5ZTU1ZmE1NS5qcGc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBSVdOSllBWDRDU1ZFSDUzQSUyRjIwMjMxMjEyJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDIzMTIxMlQwMzI5NTlaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0yZWIxNTQxYjljYjllOGMyZTdmYzVjNGM5ZjBkOTg0YzhmMTU1NDZjMmNkMWUxODFlOWEzZmRiYmEzOTQyZTlkJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.57nRC6E79JUfMK31thdO7-atdw7pxIhXKSWSv-mumts)
> > 
> > Is that any way to solve it , thank you
> 
> How did you install python? MS store or python site?

MS store

**Comment by bropines** [comment]
Well, good luck reinstalling through the python website. Or you can use pyenv-win for Windows.

I explain why this is so.
All applications from the MS store have an "internal environment" to which they have access, but they simply put libraries on disk, so downloading executable libraries is extremely problematic on versions from the msstore. If you don't want to puzzle over how and what, you can just put the version from the auto-installer in my repository (it's just easy, not advertising -_-). Well, or as I said, put the python through python.org or [pyenv-win](https://github.com/pyenv-win/pyenv-win )

**Comment by Raiter123** [comment]
> Well, good luck reinstalling through the python website. Or you can use pyenv-win for Windows.
> 
> I explain why this is so. All applications from the MS store have an "internal environment" to which they have access, but they simply put libraries on disk, so downloading executable libraries is extremely problematic on versions from the msstore. If you don't want to puzzle over how and what, you can just use the version from the auto-installer in my repository (it's just easy, not advertising -_-). Well, or as I said, put the python through python.org or [pyenv-win](https://github.com/pyenv-win/pyenv-win)

fail to start
![image](https://github.com/dmMaze/BallonsTranslator/assets/153535038/ee3ead1a-e58a-4a79-aea9-92a2184d5b0d)
the software need me install python from MS store

**Comment by bropines** [comment]
> > Well, good luck reinstalling through the python website. Or you can use pyenv-win for Windows.
> > I explain why this is so. All applications from the MS store have an "internal environment" to which they have access, but they simply put libraries on disk, so downloading executable libraries is extremely problematic on versions from the msstore. If you don't want to puzzle over how and what, you can just use the version from the auto-installer in my repository (it's just easy, not advertising -_-). Well, or as I said, put the python through python.org or [pyenv-win](https://github.com/pyenv-win/pyenv-win)
> 
> fail to start ![image](https://private-user-images.githubusercontent.com/153535038/290053950-ee3ead1a-e58a-4a79-aea9-92a2184d5b0d.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDI0MzQyNDAsIm5iZiI6MTcwMjQzMzk0MCwicGF0aCI6Ii8xNTM1MzUwMzgvMjkwMDUzOTUwLWVlM2VhZDFhLWU1OGEtNGE3OS1hZWE5LTkyYTIxODRkNWIwZC5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBSVdOSllBWDRDU1ZFSDUzQSUyRjIwMjMxMjEzJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDIzMTIxM1QwMjE5MDBaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT05NGU3MmU0NTRhNWNkZWEwYWQwMTYzYTM1MjVhMjRmNDNjNTZjOGFlYmNmMzE0OTcxYWM3NmZmMzM5MmYyY2MzJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.BwZDUi5TLDJo6fq8sTBGntoGixr3DqXkqrkptU3hvMY) the software need me install python from MS store

I'm telling you that you need a NO PYTHON version of the Microsoft store

**Comment by bropines** [comment]
> the software need me install python from MS store

Briefly speaking. By default, Windows is promoting its app store, but you don’t need it. If you don’t want to deal with tapping potatoes on the table, take this [auto-installer](https://github.com/bropines/Ballon-translator-portable) and don’t waste your time

**Comment by Raiter123** [comment]
is ok now , thanks all

**Comment by bropines** [comment]
> is ok now , thanks all

Close issue?
