### ISSUE TITLE
为啥复制文本框这么难？

### ISSUE THREAD

**Issue by jsnxing** [dmMaze/BallonsTranslator#336]
大佬 我复制文本框好多时候半天没有反应，大部分时候一个文本框要我按Ctrl+v十几次它才复制文本框，有时候我要重启了它才管用。

另外，想问一下大佬，程序能新建文本框吗？我因为汉化的作品画面都比较简单，所有嵌字都直接在程序里完成的，但有时候需要自己添加文本框之类的。

**Comment by dmMaze** [comment]
你用的是啥版本？
你看不到readme里那些gif吗？如果是网络原因可以下载源码用本地markdown查看器看看readme里面有基本教学，包括拉框的，或者直接翻看doc/src下面那些gif

**Comment by didala083** [comment]
这个属于是基本操作不清楚
