### ISSUE TITLE
现在的字体样式功能不太好用

### ISSUE THREAD

**Issue by wjz2001** [dmMaze/BallonsTranslator#337]
之前的字体样式保存了就是保存了，即便我不小心把现在的字体样式修改地乱七八糟也能一键复原。
而现在的字体样式修改过于容易，比如有某个文本框需要临时调整字体大小，那我现在就必须调好字体大小后再手动调回默认，或者临时新建一个字体样式，不能像以前那样一键复原了。

**Comment by dmMaze** [comment]
你啥字体样式都不选就跟以前的行为一样了
