### ISSUE TITLE
google got new AI

### ISSUE THREAD

**Issue by Raiter123** [dmMaze/BallonsTranslator#338]
google got new AI Gemini, can you add in this ?

**Comment by bropines** [comment]
> google got new AI Gemini, can you add in this ?

Do you have api documentation for it? Or accesses? The problem is that we cannot add this product until it has documentation and at least some access

**Comment by bropines** [comment]
> > google got new AI Gemini, can you add in this ?
> 
> Do you have api documentation for it? Or accesses? The problem is that we cannot add this product until it has documentation and at least some access

Okay, I got a little excited, here's the api, I'll see what we can use

https://ai.google.dev/tutorials/python_quickstart

**Comment by didala083** [comment]
Anyone who have got a google developer account can use Gemini Pro and try the Gemini API.
But you should in US.

**Comment by dmMaze** [comment]
Please refer to https://github.com/dmMaze/BallonsTranslator/issues/561
