### ISSUE TITLE
Another block selection system

### ISSUE THREAD

**Issue by bropines** [dmMaze/BallonsTranslator#34]
The annoying thing is that when I'm about to edit a selected block on a page, I move the mouse to another block and everything flies off. And I also wanted the text blocks (on the right) to move the focus only when I click on the input box.

**Comment by bropines** [comment]
This is especially needed when zooming in, when you get close to one block, accidentally tap another text and move the page back

**Comment by dmMaze** [comment]
> Yes, it's better than hover-enter focus policy.

changed ab2533b17eb95e905f4e568fd30dec03a818e561
