### ISSUE TITLE
请问可以重新渲染全部图片到 result 文件夹里吗？（软件没识别到文字被修改，就没法重新保存图片）

### ISSUE THREAD

**Issue by xuejianxianzun** [dmMaze/BallonsTranslator#347]
因为我没有 ChatGPT 的 api key，所以先用软件内的谷歌翻译，然后提取文本，自行用 AI 聊天机器人翻译，再回填回去。但是我是直接编辑的 imgtrans_image.json。结果虽然确实替换了之前的文字，但是没法保存修改后的图片。

操作步骤：
1. 先正常批量处理，生成结果
2. 关闭软件
3. 编辑 imgtrans_image.json，提取了 OCR 识别后的日语和翻译的中文。并用 AI 翻译，然后回填回去，保存
4. 重新打开软件

这样操作后，软件里看到的文字确实是修改后的，但是这样软件不会检查到变化，按 ctrl + s 没用。
手动修改一下文字（比如在最后加个空格再删掉）可以触发变化，再次保存。但是图片多的话太麻烦了。
请问有办法单独将图片重新渲染到 result 文件夹里吗？
或者以后是否能考虑让 ctrl + s 始终渲染图片（即使软件没识别到变化）？

另外想问下大家怎么通过 OpenAI 的手机验证，国内的和虚拟的手机号都不能用，我还搜到了一些要付费收验证码的网站，但是看到有人说这些可能花了钱也收不到，或者是号码被太多人用，会被识别为滥用，也无法通过。不知道该怎么办。

**Comment by lhj5426** [comment]
用脚本提取JSON里的内容 翻译完再写回去
API 都是买别人的 很多人再卖 比如官方的5刀普通号几毛钱
10刀的第三方帐号几块钱
https://github.com/dmMaze/BallonsTranslator/issues/141
这样导出的还可以批量喂 也可以手动翻译 
然后再导入就行了

**Comment by xuejianxianzun** [comment]
> 用脚本提取JSON里的内容 翻译完再写回去 API 都是买别人的 很多人再卖 比如官方的5刀普通号几毛钱 10刀的第三方帐号几块钱 #141 这样导出的还可以批量喂 也可以手动翻译 然后再导入就行了

原来如此，可以直接买。
另外导入导出的我自己写脚本搞定了，就是有些图片的文字感觉不用调整，但是为了渲染到 result 还得手动改一下。

**Comment by lhj5426** [comment]
> > 用脚本提取JSON里的内容 翻译完再写回去 API 都是买别人的 很多人再卖 比如官方的5刀普通号几毛钱 10刀的第三方帐号几块钱 #141*  这样导出的还可以批量喂 也可以手动翻译 然后再导入就行了
> 
> 谢谢，原来可以直接买，我以后再试试。 另外导入导出的我自己写脚本搞定了，就是有些图片的文字感觉不用调整，但是为了渲染到 result 还得手动改一下。

完事了 你重新只运行oCR 
![image](https://github.com/dmMaze/BallonsTranslator/assets/30548000/8c0ccea0-5ae1-47fe-860f-51476f75c2d8)
 是会保存的

**Comment by xuejianxianzun** [comment]
懂了，感谢大佬！

**Comment by dmMaze** [comment]
只是渲染结果图可以不勾ocr

**Comment by xuejianxianzun** [comment]
> 只是渲染结果图可以不勾ocr

原来如此，谢谢！
