### ISSUE TITLE
Add Gemini Translator

### ISSUE THREAD

**Issue by Lowfeye** [dmMaze/BallonsTranslator#348]
https://ai.google.dev/tutorials/python_quickstart

https://github.com/MUTED64/GeminiTranslate

Thank you.

**Comment by fanglangxinghai** [comment]
gemini的问题是敏感词无法翻译

**Comment by bropines** [comment]
duplicate issue
https://github.com/dmMaze/BallonsTranslator/issues/338

**Comment by levanphuc342** [comment]
> gemini的问题是敏感词无法翻译

有没有可以不受敏感词限制翻译的AI？

**Comment by bropines** [comment]
> > gemini的问题是敏感词无法翻译
> 
> 有没有可以不受敏感词限制翻译的AI？

Search the Internet for GPT JailBreak

And also in your case, there are ready-made LLAMA models for local launch, but they are quite demanding. They also have “censorship” that can be bypassed

**Comment by levanphuc342** [comment]
> > > gemini的问题是敏感词无法翻译
> > 
> > 
> > 有没有可以不受敏感词限制翻译的AI？
> 
> Search the Internet for GPT JailBreak
> 
> And also in your case, there are ready-made LLAMA models for local launch, but they are quite demanding. They also have “censorship” that can be bypassed

I tried and it seems all the GPT JailBreak methods currently on the internet cannot bypass censorship
