### ISSUE TITLE
Add Gemini ai 🥺

### ISSUE THREAD

**Issue by ahraf1234** [dmMaze/BallonsTranslator#349]
Is there a way to add Google ai Gemini and make it do OCR and translating, like edit chatgpt code to fit Gemini.

**Comment by ahraf1234** [comment]
Here's the url to the AI ( https://ai.google.dev/tutorials/python_quickstart )

**Comment by bropines** [comment]
> Here's the url to the AI ( https://ai.google.dev/tutorials/python_quickstart )

I will add but only as a translator. And I think that it, like GPT, will not work with hentai and 18+ content.

**Comment by ahraf1234** [comment]
I don't intend to use it on hentai any way 😂

**Comment by bropines** [comment]
duplicate issue
https://github.com/dmMaze/BallonsTranslator/issues/338

**Comment by simonrule** [comment]
> > Here's the url to the AI ( https://ai.google.dev/tutorials/python_quickstart )
> 
> I will add but only as a translator. And I think that it, like GPT, will not work with hentai and 18+ content.

which translator works well with +18 contents ?

**Comment by bropines** [comment]
> > > Here's the url to the AI ( https://ai.google.dev/tutorials/python_quickstart )
> > 
> > 
> > I will add but only as a translator. And I think that it, like GPT, will not work with hentai and 18+ content.
> 
> which translator works well with +18 contents ?

https://github.com/dmMaze/BallonsTranslator/issues/405

**Comment by dmMaze** [comment]
please refer to #560
