### ISSUE TITLE
Cropped text on different font

### ISSUE THREAD

**Issue by yiannischoust** [dmMaze/BallonsTranslator#350]
Hi dmMaze, great program!
I wanted to report an issue. When using the popular CC Wild Words Roman font, the text gets cropped from the upper side and I have to manually expand the textbox to fix it. I tried looking for a text margin setting but I couldn't find any. Is there such an option in the script files?
Thanks in advance!

**Comment by bropines** [comment]
> Hi dmMaze, great program! I wanted to report an issue. When using the popular CC Wild Words Roman font, the text gets cropped from the upper side and I have to manually expand the textbox to fix it. I tried looking for a text margin setting but I couldn't find any. Is there such an option in the script files? Thanks in advance!

In theory, this is due to the fact that we have the Display Block customized for regular fonts. Could you provide your own font? I want to test it, in theory I'll fix it, but I don't know when dmmaze will accept the pool requester

**Comment by yiannischoust** [comment]
Thank you! This is where I downloaded the font from:
https://copyfonts.com/fonts/cc-wild-words-roman.html
