### ISSUE TITLE
BT MOD (set up like Photoshop) enhancement

### ISSUE THREAD

**Issue by Mistermozg1** [dmMaze/BallonsTranslator#353]
### **Hello everyone. I Modified a couple of files to improve the user interface**
**1.	Previously it was impossible to zoom more than 300%, changed to 600%, zoom works with (alt+wheel mouse)**
![zoom](https://github.com/dmMaze/BallonsTranslator/assets/119166991/f9ea8fa5-05a7-48a2-9029-a3b2ec6ea628)

**2. The "Grout" cursor used to have a purple colored stroke, and a dotted line, plus there was also a cross in the middle. I changed that:** 
![cursor](https://github.com/dmMaze/BallonsTranslator/assets/119166991/b32c5bd4-c2ae-4c88-8090-fcdfe4a45440)

**3. The problem with the "brush" was that the stroke color took on the color selected in the palette, so the cursor was lost on the white background if white was selected. I changed this for the brush as well**
![paint](https://github.com/dmMaze/BallonsTranslator/assets/119166991/a129cef2-82e7-4cfc-9f99-7cde1eb9f1f4)

**4. I also changed the scaling of the cursor. Previously it was scaled somewhere to the side (to the upper left corner) and the cursor disappeared at the moment of scaling, and when you release the PCM, the cursor is already in a completely different place, and this is very inconvenient. That's why I made centering from the center where the cursor was, and made the cursor stick to its original place until the RMB is released**

https://github.com/dmMaze/BallonsTranslator/assets/119166991/19b0dc94-452b-4654-b367-5e7fba514bed

https://github.com/dmMaze/BallonsTranslator/assets/119166991/06ed678c-b0a5-4c43-9a14-3d8487bf9140

**It's also worth noting that I couldn't reassign the keys I wanted in python, so I'm using AutoHotKey, which is a key reassignment program.**
I need this to use:
(ALT+Mouse scroll), to zoom the image
(ALT+RMB) to zoom the Brush and Trowel cursor.
(Space+LMB) to move the image
(Shift) to lock the mouse cursor, only for horizontal movement
**All of this is set up the way it is in Photoshop**

Instruction:

link to modified python files: 
[ui.zip](https://github.com/dmMaze/BallonsTranslator/files/13853303/ui.zip) **_Put them in the root folder of the program, in the "ui" folder_**

link to AHK script:
[BT HOT KEYS UPDATE.zip](https://github.com/dmMaze/BallonsTranslator/files/13853343/BT.HOT.KEYS.UPDATE.zip) **You can unzip it anywhere you want, it doesn't matter.**

To make it work you will also have to download the free AutoHotKey program from the official website https://www.autohotkey.com/ and install it, then just run BT HOT KEYS UPDATE.ahk

**Done!**

**Comment by bropines** [comment]
I suggest you move this "issue" in [discussions](https://github.com/dmMaze/BallonsTranslator/discussions) so as not to interfere with some more important issues. Thanks for your help.
