### ISSUE TITLE
Want to add thai language translation

### ISSUE THREAD

**Issue by SilencioPth** [dmMaze/BallonsTranslator#354]
Hi,
I want to add Thai language translation; how can I do that?
Thai language code : th_TH

**Comment by bropines** [comment]
> Hi, I want to add Thai language translation; how can I do that? Thai language code : th_TH

I'll come back from vacation, I'll do it, or dmmaze will do it. there is not much access to the PC right now.

**Comment by dmMaze** [comment]
Added to google and chatgpt, deepl seems don't support Thai.
I haven't checked other translators, to add yourself, you may check https://github.com/dmMaze/BallonsTranslator/issues/346#issuecomment-1880717188
