### ISSUE TITLE
右键选中翻译后文字选择删除并恢复被抹除文字不起作用

### ISSUE THREAD

**Issue by ge90114b** [dmMaze/BallonsTranslator#356]
有些拟声词的小气泡可以基本恢复，但是类似作者后记的文本就无法恢复

**Comment by dmMaze** [comment]
我试了下可以啊，你跑的是最新版吗，另外框要覆盖全原文字块

**Comment by Mistermozg1** [comment]
> 我试了下可以啊，你跑的是最新版吗，另外框要覆盖全原文字块

I have a question, not really on the topic, I just don't know how to write to you personally) in the program you can move a picture using "hand" but only when it is enlarged, I can't find in the code where this limitation is....

is it possible to make it possible to use panning, and drag the image even when there are no sliders yet, when the image is smaller than the workspace window?

**Comment by dmMaze** [comment]
> > 我试了下可以啊，你跑的是最新版吗，另外框要覆盖全原文字块
> 
> I have a question, not really on the topic, I just don't know how to write to you personally) in the program you can move a picture using "hand" but only when it is enlarged, I can't find in the code where this limitation is....
> 
> is it possible to make it possible to use panning, and drag the image even when there are no sliders yet, when the image is smaller than the workspace window?

No.

**Comment by Mistermozg1** [comment]
why?) it can't be done on qt?

**Comment by Mistermozg1** [comment]
> > > 我试了下可以啊，你跑的是最新版吗，另外框要覆盖全原文字块
> > 
> > 
> > I have a question, not really on the topic, I just don't know how to write to you personally) in the program you can move a picture using "hand" but only when it is enlarged, I can't find in the code where this limitation is....
> > is it possible to make it possible to use panning, and drag the image even when there are no sliders yet, when the image is smaller than the workspace window?
> 
> No.

Why?) It can't be done on QT?

**Comment by dmMaze** [comment]
> > > > 我试了下可以啊，你跑的是最新版吗，另外框要覆盖全原文字块
> > > 
> > > 
> > > I have a question, not really on the topic, I just don't know how to write to you personally) in the program you can move a picture using "hand" but only when it is enlarged, I can't find in the code where this limitation is....
> > > is it possible to make it possible to use panning, and drag the image even when there are no sliders yet, when the image is smaller than the workspace window?
> > 
> > 
> > No.
> 
> Why?) It can't be done on QT?

It's one of these features I find boring to implement and not very useful.

**Comment by bropines** [comment]
> It's one of these features I find boring to implement and not very useful.

I also don’t think it’s the most useful, because it’s stupid to copy the program for viewing pictures picasa. Also, is it possible to somehow deal with when a text block flies off the edges so far that you have to reduce it yourself (well, a bug with the font, let’s say it’s too big.) Is it possible to reset the size of a block if there is no text in it? I’m tired of seeing blocks of text (by my own mistake) the size of Mars

**Comment by Mistermozg1** [comment]
> > > > > 我试了下可以啊，你跑的是最新版吗，另外框要覆盖全原文字块
> > > > 
> > > > 
> > > > I have a question, not really on the topic, I just don't know how to write to you personally) in the program you can move a picture using "hand" but only when it is enlarged, I can't find in the code where this limitation is....
> > > > is it possible to make it possible to use panning, and drag the image even when there are no sliders yet, when the image is smaller than the workspace window?
> > > 
> > > 
> > > No.
> > 
> > 
> > Why?) It can't be done on QT?
> 
> It's one of these features I find boring to implement and not very useful.

and can i know what is the name of the "dropper" function? i couldn't find where in the code here about colorpicker.

**Comment by bropines** [comment]
> > It's one of these features I find boring to implement and not very useful.
> 
> I also don’t think it’s the most useful, because it’s stupid to copy the program for viewing pictures picasa. Also, is it possible to somehow deal with when a text block flies off the edges so far that you have to reduce it yourself (well, a bug with the font, let’s say it’s too big.) Is it possible to reset the size of a block if there is no text in it? I’m tired of seeing blocks of text (by my own mistake) the size of Mars

I'm a moron, I forgot that autolayout exists... Now I don't care

**Comment by bropines** [comment]
> and can i know what is the name of the "dropper" function? i couldn't find where in the code here about colorpicker.

If I read the documentation correctly, then there is a call to the system color selection. I can’t tell you where now

**Comment by ge90114b** [comment]
> 我试了下可以啊，你跑的是最新版吗，另外框要覆盖全原文字块

指的是文字框消失了但是原本的字没彻底恢复 有一些涂抹痕迹 不过倒是问题不大
另外还有个文件就是加载字体报错
<img width="385" alt="IMG_8182" src="https://github.com/dmMaze/BallonsTranslator/assets/111622870/20bc2c33-1bc3-4647-90b8-ab88f0f407e0">

**Comment by dmMaze** [comment]
> 指的是文字框消失了但是原本的字没彻底恢复 有一些涂抹痕迹 不过倒是问题不大

没抹掉的部分是不是都在框的边缘外，如果是删掉前把框拉到覆盖全



> 另外还有个文件就是加载字体报错

这个我也没问题啊，你把你的字体文件发我看看
<img width="430" alt="image" src="https://github.com/dmMaze/BallonsTranslator/assets/51270320/0b020a4b-8df3-406a-b8c0-7becc735c8e5">

**Comment by ge90114b** [comment]
> > 指的是文字框消失了但是原本的字没彻底恢复 有一些涂抹痕迹 不过倒是问题不大
> 
> 没抹掉的部分是不是都在框的边缘外，如果是删掉前把框拉到覆盖全
> 
懂了
> > 另外还有个文件就是加载字体报错
> 
> 这个我也没问题啊，你把你的字体文件发我看看 <img alt="image" width="430" src="https://private-user-images.githubusercontent.com/51270320/295850135-0b020a4b-8df3-406a-b8c0-7becc735c8e5.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDQ5NzkzNjgsIm5iZiI6MTcwNDk3OTA2OCwicGF0aCI6Ii81MTI3MDMyMC8yOTU4NTAxMzUtMGIwMjBhNGItOGRmMy00MDZhLWI4YzAtN2JlY2M3MzVjOGU1LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAxMTElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMTExVDEzMTc0OFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWNhMDY0YTM0MmIyYmNjZWI0MDBhYTVhNWVjZjRiNzBjYjE3ZGY0YWZkZmZiNTliZDY3NjE0YjMwODM5NDg2M2MmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.KQt_7Afhoy34WIloT7aYSrPtTeWeR0W-mq68PxGPqmE">

[华康方圆体W7.zip](https://github.com/dmMaze/BallonsTranslator/files/13903681/W7.zip)
这个压缩文件里面的ttf

**Comment by dmMaze** [comment]
> > > 指的是文字框消失了但是原本的字没彻底恢复 有一些涂抹痕迹 不过倒是问题不大
> > 
> > 
> > 没抹掉的部分是不是都在框的边缘外，如果是删掉前把框拉到覆盖全
> 
> 懂了
> 
> > > 另外还有个文件就是加载字体报错
> > 
> > 
> > 这个我也没问题啊，你把你的字体文件发我看看 <img alt="image" width="430" src="https://private-user-images.githubusercontent.com/51270320/295850135-0b020a4b-8df3-406a-b8c0-7becc735c8e5.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDQ5NzkzNjgsIm5iZiI6MTcwNDk3OTA2OCwicGF0aCI6Ii81MTI3MDMyMC8yOTU4NTAxMzUtMGIwMjBhNGItOGRmMy00MDZhLWI4YzAtN2JlY2M3MzVjOGU1LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAxMTElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMTExVDEzMTc0OFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWNhMDY0YTM0MmIyYmNjZWI0MDBhYTVhNWVjZjRiNzBjYjE3ZGY0YWZkZmZiNTliZDY3NjE0YjMwODM5NDg2M2MmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.KQt_7Afhoy34WIloT7aYSrPtTeWeR0W-mq68PxGPqmE">
> 
> [华康方圆体W7.zip](https://github.com/dmMaze/BallonsTranslator/files/13903681/W7.zip) 这个压缩文件里面的ttf

你是不是试着把这个字体拖进字体样式界面加载... 
字体只要放进那个fonts里然后在界面里选就行了...那些样式是一整套格式

**Comment by ge90114b** [comment]
> > > > 指的是文字框消失了但是原本的字没彻底恢复 有一些涂抹痕迹 不过倒是问题不大
> > > 
> > > 
> > > 没抹掉的部分是不是都在框的边缘外，如果是删掉前把框拉到覆盖全
> > 
> > 
> > 懂了
> > > > 另外还有个文件就是加载字体报错
> > > 
> > > 
> > > 这个我也没问题啊，你把你的字体文件发我看看 <img alt="image" width="430" src="https://private-user-images.githubusercontent.com/51270320/295850135-0b020a4b-8df3-406a-b8c0-7becc735c8e5.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDQ5NzkzNjgsIm5iZiI6MTcwNDk3OTA2OCwicGF0aCI6Ii81MTI3MDMyMC8yOTU4NTAxMzUtMGIwMjBhNGItOGRmMy00MDZhLWI4YzAtN2JlY2M3MzVjOGU1LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAxMTElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMTExVDEzMTc0OFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWNhMDY0YTM0MmIyYmNjZWI0MDBhYTVhNWVjZjRiNzBjYjE3ZGY0YWZkZmZiNTliZDY3NjE0YjMwODM5NDg2M2MmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.KQt_7Afhoy34WIloT7aYSrPtTeWeR0W-mq68PxGPqmE">
> > 
> > 
> > [华康方圆体W7.zip](https://github.com/dmMaze/BallonsTranslator/files/13903681/W7.zip) 这个压缩文件里面的ttf
> 
> 你是不是试着把这个字体拖进字体样式界面加载... 字体只要放进那个fonts里然后在界面里选就行了...那些样式是一整套格式

fonts文件夹吗？现在这个ttf我手动放进去过 但是在选的时候还是找不到

**Comment by ge90114b** [comment]
<img width="658" alt="屏幕截图 2024-01-12 004703" src="https://github.com/dmMaze/BallonsTranslator/assets/111622870/a1998ed0-e93f-48de-92dc-6ac9bea33109">
<img width="760" alt="屏幕截图 2024-01-12 004658" src="https://github.com/dmMaze/BallonsTranslator/assets/111622870/5971be5d-6c23-453a-875d-0af3be4e0290">
<img width="642" alt="屏幕截图 2024-01-12 004621" src="https://github.com/dmMaze/BallonsTranslator/assets/111622870/ecf18e55-1cd4-42d4-8356-5c8839c38cca">

**Comment by dmMaze** [comment]
> <img alt="屏幕截图 2024-01-12 004703" width="658" src="https://private-user-images.githubusercontent.com/111622870/295970355-a1998ed0-e93f-48de-92dc-6ac9bea33109.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDQ5OTA0NTgsIm5iZiI6MTcwNDk5MDE1OCwicGF0aCI6Ii8xMTE2MjI4NzAvMjk1OTcwMzU1LWExOTk4ZWQwLWU5M2YtNDhkZS05MmRjLTZhYzliZWEzMzEwOS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwMTExJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDExMVQxNjIyMzhaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT03MmZiMmQ4OGJiZjJiN2NmNjgyODFmNDcwNmJiM2VlMTZiNGE1NzU2MWRmZDZhOWYxMGY5Y2E2MDA1NDE2ZGEyJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.cZ_cDTusxInd3vNelpg08Akbu1E6nM0LBIeQHyDo7mk"> <img alt="屏幕截图 2024-01-12 004658" width="760" src="https://private-user-images.githubusercontent.com/111622870/295970383-5971be5d-6c23-453a-875d-0af3be4e0290.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDQ5OTA0NTgsIm5iZiI6MTcwNDk5MDE1OCwicGF0aCI6Ii8xMTE2MjI4NzAvMjk1OTcwMzgzLTU5NzFiZTVkLTZjMjMtNDUzYS04NzVkLTBhZjNiZTRlMDI5MC5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwMTExJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDExMVQxNjIyMzhaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT05NjFlNDQzOTI4YzgyMmI0YzY0ZjViNDZhZjNjY2QzOTA0NTIwODAwYzE2MzZhMTRiYzI3M2JlNmE1NWMyYzc5JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.UMzQI5dwgpg6UNB3UPfjI-QKBgcAH_4LWBgwncLqSZ0"> <img alt="屏幕截图 2024-01-12 004621" width="642" src="https://private-user-images.githubusercontent.com/111622870/295970398-ecf18e55-1cd4-42d4-8356-5c8839c38cca.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDQ5OTA0NTgsIm5iZiI6MTcwNDk5MDE1OCwicGF0aCI6Ii8xMTE2MjI4NzAvMjk1OTcwMzk4LWVjZjE4ZTU1LTFjZDQtNDJkNC04MzU2LTVjODgzOWMzOGNjYS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwMTExJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDExMVQxNjIyMzhaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1iMzdiYmM4YWI1MWFmNzA1M2Q5ODdiMTkxOWM4OWUzMzc4ZjFlZjZhOGFjMzQwYWY0ZGQyMWNlNzFkNDVhNDY1JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.2tG4V8NOYJYqPn2tVHij4CSQFa2XuirA051TAkOckUw">

打开你提供的字体文件出的字体名是这个
<img width="271" alt="image" src="https://github.com/dmMaze/BallonsTranslator/assets/51270320/25a3df92-34ed-47cd-a473-3e1605819d67">
放进fonts里在程序里就能看到了：
<img width="160" alt="image" src="https://github.com/dmMaze/BallonsTranslator/assets/51270320/fb3bd0e6-3ef8-4b7a-8c8d-0e8926b91987">

如果装进系统它字体名会显示为繁体。
另外我还是删掉你给的字体文件了，我不想关心它是啥license...

**Comment by ge90114b** [comment]
> > <img alt="屏幕截图 2024-01-12 004703" width="658" src="https://private-user-images.githubusercontent.com/111622870/295970355-a1998ed0-e93f-48de-92dc-6ac9bea33109.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDQ5OTA0NTgsIm5iZiI6MTcwNDk5MDE1OCwicGF0aCI6Ii8xMTE2MjI4NzAvMjk1OTcwMzU1LWExOTk4ZWQwLWU5M2YtNDhkZS05MmRjLTZhYzliZWEzMzEwOS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwMTExJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDExMVQxNjIyMzhaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT03MmZiMmQ4OGJiZjJiN2NmNjgyODFmNDcwNmJiM2VlMTZiNGE1NzU2MWRmZDZhOWYxMGY5Y2E2MDA1NDE2ZGEyJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.cZ_cDTusxInd3vNelpg08Akbu1E6nM0LBIeQHyDo7mk"> <img alt="屏幕截图 2024-01-12 004658" width="760" src="https://private-user-images.githubusercontent.com/111622870/295970383-5971be5d-6c23-453a-875d-0af3be4e0290.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDQ5OTA0NTgsIm5iZiI6MTcwNDk5MDE1OCwicGF0aCI6Ii8xMTE2MjI4NzAvMjk1OTcwMzgzLTU5NzFiZTVkLTZjMjMtNDUzYS04NzVkLTBhZjNiZTRlMDI5MC5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwMTExJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDExMVQxNjIyMzhaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT05NjFlNDQzOTI4YzgyMmI0YzY0ZjViNDZhZjNjY2QzOTA0NTIwODAwYzE2MzZhMTRiYzI3M2JlNmE1NWMyYzc5JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.UMzQI5dwgpg6UNB3UPfjI-QKBgcAH_4LWBgwncLqSZ0"> <img alt="屏幕截图 2024-01-12 004621" width="642" src="https://private-user-images.githubusercontent.com/111622870/295970398-ecf18e55-1cd4-42d4-8356-5c8839c38cca.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDQ5OTA0NTgsIm5iZiI6MTcwNDk5MDE1OCwicGF0aCI6Ii8xMTE2MjI4NzAvMjk1OTcwMzk4LWVjZjE4ZTU1LTFjZDQtNDJkNC04MzU2LTVjODgzOWMzOGNjYS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwMTExJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDExMVQxNjIyMzhaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1iMzdiYmM4YWI1MWFmNzA1M2Q5ODdiMTkxOWM4OWUzMzc4ZjFlZjZhOGFjMzQwYWY0ZGQyMWNlNzFkNDVhNDY1JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.2tG4V8NOYJYqPn2tVHij4CSQFa2XuirA051TAkOckUw">
> 
> 打开你提供的字体文件出的字体名是这个 <img alt="image" width="271" src="https://private-user-images.githubusercontent.com/51270320/295981062-25a3df92-34ed-47cd-a473-3e1605819d67.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDQ5OTUxNTgsIm5iZiI6MTcwNDk5NDg1OCwicGF0aCI6Ii81MTI3MDMyMC8yOTU5ODEwNjItMjVhM2RmOTItMzRlZC00N2NkLWE0NzMtM2UxNjA1ODE5ZDY3LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAxMTElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMTExVDE3NDA1OFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWMyMGI2MTBjMmQ3YjcwYjg5ZDA2YzZhYTJlZDJhMDYxOGIwYjQ3YzBjMDFlYTBlMzAzMDBmMDExOWNlNDFlYjUmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.EPI-I-e_PUJ_JwvM3aRa5X9DiF_T7e8o4aiklZtBzKA"> 放进fonts里在程序里就能看到了： <img alt="image" width="160" src="https://private-user-images.githubusercontent.com/51270320/295981217-fb3bd0e6-3ef8-4b7a-8c8d-0e8926b91987.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDQ5OTUxNTgsIm5iZiI6MTcwNDk5NDg1OCwicGF0aCI6Ii81MTI3MDMyMC8yOTU5ODEyMTctZmIzYmQwZTYtM2VmOC00YjdhLThjOGQtMGU4OTI2YjkxOTg3LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAxMTElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMTExVDE3NDA1OFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTFmOTAyZDk1YWZmODg1NmI3ZDM4YWQ3OGFhNTQwZWExYzIxYWE2NjgwZGQ3ZDAxZWQ1MTRiYzk2NzY0N2QzZjYmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.XSnwdAveg0qtVXW72roJS9iDvsh44-G2ONA7NApzYM4">
> 
> 如果装进系统它字体名会显示为繁体。 另外我还是删掉你给的字体文件了，我不想关心它是啥license...

好的 感谢解答
