### ISSUE TITLE
latin text wrapping is wrong

### ISSUE THREAD

**Issue by gezzerlol** [dmMaze/BallonsTranslator#357]
I would love to fix the text wrapping functionality myself but I'm not sure which module or piece of code is responsible for text rendering, I would appreciate if you could point me to that code. I'm not really used to work on multi file projects, I only code single file programs.

![image](https://github.com/dmMaze/BallonsTranslator/assets/156261427/6a122e65-fdd8-4ce6-a3aa-132dc56de005)
Basically I want the line ends to not split words, if the feature is already implemented I would love help on activating that.

**Comment by bropines** [comment]
Same on Cyrillic
