### ISSUE TITLE
Crash dumps eating up space.2GB every time it crashes.

### ISSUE THREAD

**Issue by DA-NAV** [dmMaze/BallonsTranslator#36]
Every time the app crashes it takes 2GB of memory. It dumps the crash files in AppData/local/Crash_dumps folder.

**Comment by dmMaze** [comment]
This app doesn't create dump files, it's on windows side, did you get python from microsoft store?

**Comment by DA-NAV** [comment]
I did once but I uninstalled it and installed back it from the official website (python 3.9.11). Thanks, I'll close this issue then
