### ISSUE TITLE
大伙的字体加粗能用吗

### ISSUE THREAD

**Issue by Killua223** [dmMaze/BallonsTranslator#369]
最早版本的正常，前短时间更新到最新版之后就没效果了

**Comment by bropines** [comment]
> 最早版本的正常，前短时间更新到最新版之后就没效果了

Send logs

**Comment by dmMaze** [comment]
你用的是啥系统啥字体？之前的版本是哪个？
我简单试了下最新版 454fa05 Windows 下字体都可以加粗, macos下只有少部分字体可以. 
另外确实有个 bug 设加粗会崩溃, 已在 454fa05 修复

**Comment by Killua223** [comment]
我是win10，我不知道怎么看版本号。启动页显示的Commit hash: bdbbae9885f47a8de81d4049ac4df54410df491a，和你发的这个好像不一样，不知道自己现在这个是不是最新版。我是Google Drive下载BallonsTranslator_dev_src_with_gitpython这个文件解压复制到目录 这样升级的。之前的版本我不太记得了，应该是去年十一月的吧。
目前是所有中英文字体都没办法加粗，但是其他功能都正常。

**Comment by dmMaze** [comment]
> 我是win10，我不知道怎么看版本号。启动页显示的Commit hash: [bdbbae9](https://github.com/dmMaze/BallonsTranslator/commit/bdbbae9885f47a8de81d4049ac4df54410df491a)，和你发的这个好像不一样，不知道自己现在这个是不是最新版。我是Google Drive下载BallonsTranslator_dev_src_with_gitpython这个文件解压复制到目录 这样升级的。之前的版本我不太记得了，应该是去年十一月的吧。 目前是所有中英文字体都没办法加粗，但是其他功能都正常。

找到scripts/local_gitpull.bat 双击一下就更新了

**Comment by Killua223** [comment]
不知道是不是我节点有问题，上面显示
F:\download\BallonsTranslator_dev_src_with_gitpython>git config http.sslVerify false

F:\download\BallonsTranslator_dev_src_with_gitpython>git pull
fatal: unable to access 'https://github.com/dmMaze/BallonsTranslator/': Failed to connect to github.com port 443 after 21081 ms: Couldn't connect to server

F:\download\BallonsTranslator_dev_src_with_gitpython>pause
请按任意键继续. . .

**Comment by dmMaze** [comment]
<img width="965" alt="截屏2024-01-29 21 33 36" src="https://github.com/dmMaze/BallonsTranslator/assets/51270320/80625114-9db1-4c52-ac14-0936a964ced9">

那你就只能自己下代码覆盖了

**Comment by Killua223** [comment]
谢谢了，更新完现在可以正常加粗了
