### ISSUE TITLE
Help me with Sugoi translator integration (RuntimeError: Unable to open file 'model.bin' in model 'data/models/sugoi_translator')

### ISSUE THREAD

**Issue by DA-NAV** [dmMaze/BallonsTranslator#37]
Traceback (most recent call last):
  File "C:\Users\n\DOWNLO~1\COMPRE~1\BALLON~1\BALLON~1.0-C\BALLON~1\dl\translators\__init__.py", line 81, in __init__
  File "C:\Users\n\DOWNLO~1\COMPRE~1\BALLON~1\BALLON~1.0-C\BALLON~1\dl\translators\__init__.py", line 106, in setup_translator
  File "C:\Users\n\DOWNLO~1\COMPRE~1\BALLON~1\BALLON~1.0-C\BALLON~1\dl\translators\__init__.py", line 374, in _setup_translator
RuntimeError: Unable to open file 'model.bin' in model 'data/models/sugoi_translator'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\n\DOWNLO~1\COMPRE~1\BALLON~1\BALLON~1.0-C\BALLON~1\ui\dl_manager.py", line 161, in _set_translator
  File "C:\Users\n\DOWNLO~1\COMPRE~1\BALLON~1\BALLON~1.0-C\BALLON~1\dl\translators\__init__.py", line 86, in __init__
dl.translators.exceptions.TranslatorSetupFailure: Unable to open file 'model.bin' in model 'data/models/sugoi_translator'

(strike down was unintended it had '~' symbol  in it)

**Comment by bropines** [comment]
> Traceback (most recent call last):
>   File "C:\Users\n\DOWNLO~1\COMPRE~1\BALLON~1\BALLON~1.0-C\BALLON~1\dl\translators\__init__.py", line 81, in __init__
>   File "C:\Users\n\DOWNLO~1\COMPRE~1\BALLON~1\BALLON~1.0-C\BALLON~1\dl\translators\__init__.py", line 106, in setup_translator
>   File "C:\Users\n\DOWNLO~1\COMPRE~1\BALLON~1\BALLON~1.0-C\BALLON~1\dl\translators\__init__.py", line 374, in _setup_translator
> RuntimeError: Unable to open file 'model.bin' in model 'data/models/sugoi_translator'
> 
> During handling of the above exception, another exception occurred:
> 
> Traceback (most recent call last):
>   File "C:\Users\n\DOWNLO~1\COMPRE~1\BALLON~1\BALLON~1.0-C\BALLON~1\ui\dl_manager.py", line 161, in _set_translator
>   File "C:\Users\n\DOWNLO~1\COMPRE~1\BALLON~1\BALLON~1.0-C\BALLON~1\dl\translators\__init__.py", line 86, in __init__
> dl.translators.exceptions.TranslatorSetupFailure: Unable to open file 'model.bin' in model 'data/models/sugoi_translator'
> 
> 
> 
> (strike down was unintended it had '~' symbol  in it)

Have you downloaded the translation model files?

**Comment by DA-NAV** [comment]
Yes I downloaded the files from the drive link in description for Sugoi translator.I am using the app version in windows

**Comment by bropines** [comment]
> Yes I downloaded the files from the drive link in description for Sugoi translator.I am using the app version in windows
> 

There is a screenshot of the folder h can be found on the path ballontranslator/data/

**Comment by DA-NAV** [comment]
> > Yes I downloaded the files from the drive link in description for Sugoi translator.I am using the app version in windows
> 
> Take me is a screenshot of the folder h can be found on the path ballontranslator/data/
Where?

**Comment by bropines** [comment]
> > > Yes I downloaded the files from the drive link in description for Sugoi translator.I am using the app version in windows
> > 
> > Take me is a screenshot of the folder h can be found on the path ballontranslator/data/
> Where?
> 

(Yandex translate is bad)

attach a screenshot here where the sugoi folder is shown and where you inserted it. I think the problem is in the folder paths

**Comment by DA-NAV** [comment]
![Capture](https://user-images.githubusercontent.com/99066383/189316505-376a1313-5f43-4078-b124-92f2d8173e90.PNG)
![Capture](https://user-images.githubusercontent.com/99066383/189316634-7fe37fd0-abe1-434a-8c01-f2bd3aa2649f.PNG)

**Comment by dmMaze** [comment]
move ```sugoi_translator``` into ```models```, its a mistake in doc

**Comment by DA-NAV** [comment]
thanks, it's working now. I'm closing this issue.
