### ISSUE TITLE
is_causal parameter does not work in transformer_encoder_forward ( mit48px model )

### ISSUE THREAD

**Issue by freelze** [dmMaze/BallonsTranslator#371]
It seems like [657f18a](https://github.com/dmMaze/BallonsTranslator/commit/657f18af602b738c88495f7aaf6078f0139eaae6) fixed [mit48px_ctc.py](https://github.com/dmMaze/BallonsTranslator/commit/657f18af602b738c88495f7aaf6078f0139eaae6#diff-fbcb17e234ff99fe54efa3649aa6b1ea8366d4cfa33063f666ffe300be499644) `is_causal` parameter problem

but the newer [mit48px.py](https://github.com/dmMaze/BallonsTranslator/blob/dev/modules/ocr/mit48px.py#L331) has not fixed yet.

[mit48px.py#L331](https://github.com/dmMaze/BallonsTranslator/blob/dev/modules/ocr/mit48px.py#L331)
```python
def transformer_encoder_forward(
    self,
    src: torch.Tensor,
    src_mask: Optional[torch.Tensor] = None,
    src_key_padding_mask: Optional[torch.Tensor] = None,
    is_causal: bool = False) -> torch.Tensor:
    x = src
    if self.norm_first:
        x = x + self._sa_block(self.norm1(x), src_mask, src_key_padding_mask, is_causal=is_causal)
        x = x + self._ff_block(self.norm2(x))
    else:
        x = self.norm1(x + self._sa_block(x, src_mask, src_key_padding_mask, is_causal=is_causal))
        x = self.norm2(x + self._ff_block(x))

    return x

``` 

If `is_causal=is_causal` is deleted then it will work.

 
```python
x = x + self._sa_block(self.norm1(x), src_mask, src_key_padding_mask)
``` 

My torch version: 1.13.1+cu116

Error log:

(BallonsTranslator) E:\#Github\BallonsTranslator>E:/miniconda/envs/BallonsTranslator/python.exe e:/#Github/BallonsTranslator/launch.py
py version:  3.9.16 (main, May 17 2023, 17:49:16) [MSC v.1916 64 bit (AMD64)]
py executable:  E:\miniconda\envs\BallonsTranslator\python.exe
version: 1.4.0
branch: dev
Commit hash: ae9916a920027caa31ebd600ae25667e8776a6dd
[INFO   ] config:load_textstyle_from:176 - Text style loaded from e:\#Github\BallonsTranslator\config/textstyles\default.json
[INFO   ] launch:main:172 - QT_API: pyqt6, QT Version: 6.4.2
[INFO   ] launch:main:200 - set display language to en_US
[INFO   ] module_manager:on_finish_settranslator:814 - Translator set to ChatGPT
[INFO   ] module_manager:on_finish_setinpainter:806 - Inpainter set to lama_large_512px
[INFO   ] module_manager:on_finish_setdetector:793 - Text detector set to ctd
[INFO   ] module_manager:on_finish_setocr:799 - OCR set to mit48px
[INFO   ] config:save_config:211 - Config saved
Traceback (most recent call last):
  File "e:\#Github\BallonsTranslator\ui\module_manager.py", line 467, in run
    self.job()
  File "e:\#Github\BallonsTranslator\ui\module_manager.py", line 370, in _imgtrans_pipeline
    self.ocr.run_ocr(img, blk_list)
  File "e:\#Github\BallonsTranslator\modules\ocr\__init__.py", line 41, in run_ocr
    self._ocr_blk_list(img, blk_list)
  File "e:\#Github\BallonsTranslator\modules\ocr\__init__.py", line 237, in _ocr_blk_list
    return self.model(img, blk_list)
  File "e:\#Github\BallonsTranslator\modules\ocr\mit48px.py", line 176, in __call__
    ret = self.model.infer_beam_batch(image_tensor, widths, beams_k = 5, max_seq_length = 255)
  File "e:\#Github\BallonsTranslator\modules\ocr\mit48px.py", line 620, in infer_beam_batch
    memory = layer(layer, src = memory, src_key_padding_mask = input_mask)
  File "E:\miniconda\envs\BallonsTranslator\lib\site-packages\torch\nn\modules\module.py", line 1194, in _call_impl
    return forward_call(*input, **kwargs)
  File "e:\#Github\BallonsTranslator\modules\ocr\mit48px.py", line 331, in transformer_encoder_forward
    x = x + self._sa_block(self.norm1(x), src_mask, src_key_padding_mask, is_causal=None)
TypeError: _sa_block() got an unexpected keyword argument 'is_causal'

**Comment by dmMaze** [comment]
I haven't tested on torch 1.13, does change
https://github.com/dmMaze/BallonsTranslator/blob/704aca60b693cce00ae91f9eab84f8021ae1f284/modules/ocr/mit48px_ctc.py#L111-L112
to 
``` python
    def _sa_block(self, x: torch.Tensor,
                  attn_mask: Optional[torch.Tensor], key_padding_mask: Optional[torch.Tensor], is_causal = None) -> torch.Tensor:
```
solve the problem?

**Comment by freelze** [comment]
No. It still throw the same error.
`TypeError: _sa_block() got an unexpected keyword argument 'is_causal'`

**Comment by freelze** [comment]
https://github.com/zyddnys/manga-image-translator/commit/5be14508c80fee902cf36c30c7f968e5ae9b58ae
I found that zyddnys just delete `is_causal=is_causal` to solve the same [issue](https://github.com/zyddnys/manga-image-translator/issues/503#issue-1989320402) FYI.
