### ISSUE TITLE
Suggestion for improvement. The program should not crash with TooManyRequestsException exception for DeepL Free.

### ISSUE THREAD

**Issue by rossetero** [dmMaze/BallonsTranslator#374]
It is not very pleasant when the program crashes and loses unsaved changes after unsuccessful attempt to translate via DeepL. It would be much better if the program would not crash,  the user would get some notification about it, and the translation button for DeepL Free option would be blocked for 5 minutes until the service unblocks the IP.

**Comment by bropines** [comment]
We are aware of the problem. I am currently writing a new translator method that will work adequately and quickly. The interface remains to understand how qt works

**Comment by dmMaze** [comment]
Translation failure will not crash the program since 840c428f27cb98be6c2a649fbd6452e02b1e69e1
