### ISSUE TITLE
Cannot switch to CUDA

### ISSUE THREAD

**Issue by Toisoi** [dmMaze/BallonsTranslator#375]
I have rtx 4060 (laptop version, 8GB) inside, but, when inside settings i change any device to cuda it just stands oc cpu. How I can change to cuda, maybe I need download something?

And yeah, sorry for issue tag, idk how set question tag

**Comment by bropines** [comment]
> I have rtx 4060 (laptop version, 8GB) inside, but, when inside settings i change any device to cuda it just stands oc cpu. How I can change to cuda, maybe I need download something?
> 
> And yeah, sorry for issue tag, idk how set question tag

You install PyTorch?

**Comment by bropines** [comment]
Open console and write `python`

```python
import torch
```
and 
```python 
torch.cuda.is_available()
```

**Comment by Toisoi** [comment]
> Open console and write `python`
> 
> ```python
> import torch
> ```
> 
> and
> 
> ```python
> torch.cuda.is_available()
> ```

the second line of code writes False, apparently my video card does not support it (although I may need to install something)

**Comment by bropines** [comment]
> > Open console and write `python`
> > ```python
> > import torch
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > and
> > ```python
> > torch.cuda.is_available()
> > ```
> 
> the second line of code writes False, apparently my video card does not support it (although I may need to install something)

```cmd
pip3 install torch torchvision torchaudio --index-url https://download.pytorch.org/whl/cu118
```

**Comment by Toisoi** [comment]
> > > Open console and write `python`
> > > ```python
> > > import torch
> > > ```
> > > 
> > > 
> > >     
> > >       
> > >     
> > > 
> > >       
> > >     
> > > 
> > >     
> > >   
> > > and
> > > ```python
> > > torch.cuda.is_available()
> > > ```
> > 
> > 
> > the second line of code writes False, apparently my video card does not support it (although I may need to install something)
> 
> Activate venv and :
> 
> ```batchfile
> pip3 install torch torchvision torchaudio --index-url https://download.pytorch.org/whl/cu118
> ```

already done. Not working

**Comment by bropines** [comment]
> > > > Open console and write `python`
> > > > ```python
> > > > import torch
> > > > ```
> > > > 
> > > > 
> > > >     
> > > >       
> > > >     
> > > > 
> > > >       
> > > >     
> > > > 
> > > >     
> > > >   
> > > > and
> > > > ```python
> > > > torch.cuda.is_available()
> > > > ```
> > > 
> > > 
> > > the second line of code writes False, apparently my video card does not support it (although I may need to install something)
> > 
> > 
> > Activate venv and :
> > ```batchfile
> > pip3 install torch torchvision torchaudio --index-url https://download.pytorch.org/whl/cu118
> > ```
> 
> already done. Not working

write `pip freeze > pip.txt`

**Comment by Toisoi** [comment]
[pip.txt](https://github.com/dmMaze/BallonsTranslator/files/14233936/pip.txt)

**Comment by bropines** [comment]
Try this
```
pip3 install -U torch torchvision torchaudio --index-url https://download.pytorch.org/whl/cu118
```

**Comment by Toisoi** [comment]
> Try this
> 
> ```
> pip3 install -U torch torchvision torchaudio --index-url https://download.pytorch.org/whl/cu118
> ```

Now everything changes to cuda, except that it does not change for text recognition. crashes with an error
```
File "C:\Users\timga\Downloads\BallonsTranslator\ui\module_manager.py", line 872, in on_textdetectorparam_edited
    self.updateModuleSetupParam(self.textdetector, param_key, param_content)
  File "C:\Users\timga\Downloads\BallonsTranslator\ui\module_manager.py", line 884, in updateModuleSetupParam
    module.updateParam(param_key, param_content)
  File "C:\Users\timga\Downloads\BallonsTranslator\modules\textdetector\__init__.py", line 94, in updateParam
    self.setup_detector()
  File "C:\Users\timga\Downloads\BallonsTranslator\modules\textdetector\__init__.py", line 35, in setup_detector
    raise NotImplementedError
NotImplementedError
```

**Comment by bropines** [comment]
Если не поможет, то Будем выяснять

> > Try this
> > ```
> > pip3 install -U torch torchvision torchaudio --index-url https://download.pytorch.org/whl/cu118
> > ```
> 
> Now everything changes to cuda, except that it does not change for text recognition. crashes with an error
> 
> ```
> File "C:\Users\timga\Downloads\BallonsTranslator\ui\module_manager.py", line 872, in on_textdetectorparam_edited
>     self.updateModuleSetupParam(self.textdetector, param_key, param_content)
>   File "C:\Users\timga\Downloads\BallonsTranslator\ui\module_manager.py", line 884, in updateModuleSetupParam
>     module.updateParam(param_key, param_content)
>   File "C:\Users\timga\Downloads\BallonsTranslator\modules\textdetector\__init__.py", line 94, in updateParam
>     self.setup_detector()
>   File "C:\Users\timga\Downloads\BallonsTranslator\modules\textdetector\__init__.py", line 35, in setup_detector
>     raise NotImplementedError
> NotImplementedError
> ```

try to remove config file

**Comment by Toisoi** [comment]
> Если не поможет, то Будем выяснять
> 
> > > Try this
> > > ```
> > > pip3 install -U torch torchvision torchaudio --index-url https://download.pytorch.org/whl/cu118
> > > ```
> > 
> > 
> > Now everything changes to cuda, except that it does not change for text recognition. crashes with an error
> > ```
> > File "C:\Users\timga\Downloads\BallonsTranslator\ui\module_manager.py", line 872, in on_textdetectorparam_edited
> >     self.updateModuleSetupParam(self.textdetector, param_key, param_content)
> >   File "C:\Users\timga\Downloads\BallonsTranslator\ui\module_manager.py", line 884, in updateModuleSetupParam
> >     module.updateParam(param_key, param_content)
> >   File "C:\Users\timga\Downloads\BallonsTranslator\modules\textdetector\__init__.py", line 94, in updateParam
> >     self.setup_detector()
> >   File "C:\Users\timga\Downloads\BallonsTranslator\modules\textdetector\__init__.py", line 35, in setup_detector
> >     raise NotImplementedError
> > NotImplementedError
> > ```
> 
> try to remove config file `config/config.json`

now everything works! Thank you very much!

**Comment by bropines** [comment]
No problem). Next time (if you are reinstalling) you can use my auto-install script https://github.com/bropines/Ballon-translator-portable
