### ISSUE TITLE
chatgpt翻译频繁报错！

### ISSUE THREAD

**Issue by didala083** [dmMaze/BallonsTranslator#379]
这个bug多次复现，说不清是什么原因，表现就是明明原文和chatgpt返回的翻译句数是对得上的，但是总是判定为数量和原文对不上，然后就反复请求，token耗费很多很受伤呢！

如下面例子：原文和翻译都是7句，但是却说数量对不上

[WARNING] trans_chatgpt:_translate:234 - number of translations does not match to source:
prompt:
    Please help me to translate the following text from a manga to Simplified Chinese (if it's already in Simplified Chinese or looks like gibberish you have to output it as it is instead):
<|1|>お母さん
<|2|>じゃ なかった…リーア…
<|3|>ははは
<|4|>お母さんって！
<|5|>時々聞く間違いだけど妖精相手にあるかぁ！
<|6|>ユウもかわいいとこあるねえ！あっはっはっは
<|7|>間違えちゃったはは…
translations:
  ['妈妈\n不是……莉亚……\n哈哈哈\n叫人妈妈！\n虽然偶尔会听到这种误会，但对妖精来说也是有可能的嘛！\n优也有可爱的一面呢！啊哈哈哈哈\n弄错了啊哈……']
openai response:
  妈妈
不是……莉亚……
哈哈哈
叫人妈妈！
虽然偶尔会听到这种误会，但对妖精来说也是有可能的嘛！
优也有可爱的一面呢！啊哈哈哈哈
弄错了啊哈……
Restarting request. Attempt: 1

**Comment by dmMaze** [comment]
试试[3e945a5](https://github.com/dmMaze/BallonsTranslator/commit/3e945a547943d8890798d35f68cfe50fe337ff96)

**Comment by didala083** [comment]
感谢修正！试了几次没出现类似报错了，但是偶尔会把行号之类的带到翻译中

**Comment by dmMaze** [comment]
> 感谢修正！试了几次没出现类似报错了，但是偶尔会把行号之类的带到翻译中

[ccdc90b](https://github.com/dmMaze/BallonsTranslator/commit/ccdc90b00f1a331f65375fd294a5d72811bcc318) 会试着把行号去掉了
