### ISSUE TITLE
想请教如何卸载

### ISSUE THREAD

**Issue by asumi2001** [dmMaze/BallonsTranslator#381]
纯小白 从其他站的推介帖子看到的 如果这是一个蠢问题非常抱歉！因为电脑之后可能需要清掉一些软件和文件来腾出空间，想要请问一下ballons translator要如何卸载呢？在根目录好像没有看到类似于uninstall之类的快捷程序，电脑系统里面也检测不到这个软件无法通过系统路径卸载，请问是把整个文件夹直接删除就可以了吗？
非常感谢创作者的付出！辛苦了！

**Comment by dmMaze** [comment]
对，删掉整个文件夹，如果你只是为了这个软件装了python可以把它也卸了
