### ISSUE TITLE
1.4.0 无法加粗字体

### ISSUE THREAD

**Issue by Sawtooth-IT** [dmMaze/BallonsTranslator#385]
https://github.com/dmMaze/BallonsTranslator/assets/126060127/df1680be-8544-484b-aae4-27a809dcb08f

**Comment by dmMaze** [comment]
这ui看着像是macos的? 我试过macos上只有少部分字体(比如Microsoft YaHei)可以加粗, windows上大部分字体都可以

**Comment by Sawtooth-IT** [comment]
> 这ui看着像是macos的？我试过macos上只有少部分字体（比如Microsoft YaHei）可以加粗， windows上大部分字体都可以

Win11，换了其他字体也加粗不了
之前用1.3.35的时候正常

**Comment by dmMaze** [comment]
@Sawtooth-IT 是最新版 ccdc90b00f1a331f65375fd294a5d72811bcc318 吗，如果不是拉一下源码，或者下网盘里的.7z解压覆盖一下

**Comment by Sawtooth-IT** [comment]
> @Sawtooth-IT 是最新版 [ccdc90b](https://github.com/dmMaze/BallonsTranslator/commit/ccdc90b00f1a331f65375fd294a5d72811bcc318) 吗，如果不是拉一下源码，或者下网盘里的.7z解压覆盖一下

已解决问题
