### ISSUE TITLE
经常报错退出

### ISSUE THREAD

**Issue by huimieba** [dmMaze/BallonsTranslator#390]
内容：
[WARNING] module_manager:inpaint:633 - Waiting for inpainting to finish
QPixmap::scaled: Pixmap is a null pixmap
Traceback (most recent call last):
  File "D:\GAL\BallonsTranslator-1.4.0\ui\canvas.py", line 751, in on_create_contextmenu
    self.on_paste(pos.toPointF())
                  ^^^^^^^^^^^^
AttributeError: 'QPoint' object has no attribute 'toPointF'

这个怎么解决

**Comment by dmMaze** [comment]
操作系统, pyqt和程序版本是啥

**Comment by huimieba** [comment]
win11x64，python-3.11.4-amd64，版本是1.4.0

**Comment by huimieba** [comment]
> 操作系统, pyqt和程序版本是啥
win11x64，python-3.11.4-amd64，版本是1.4.0

**Comment by huimieba** [comment]
> win11x64，python-3.11.4-amd64，版本是1.4.0

win11x64，python-3.11.4-amd64，版本是1.4.0

**Comment by huimieba** [comment]
> 操作系统， pyqt和程序版本是啥

win11x64，python-3.11.4-amd64，版本是1.4.0

**Comment by dmMaze** [comment]
> > 操作系统， pyqt和程序版本是啥
> 
> win11x64，python-3.11.4-amd64，版本是1.4.0

我是说pyqt版本...还是把启动时的完整log贴上来吧

**Comment by huimieba** [comment]
> > > 操作系统， pyqt和程序版本是啥
> > 
> > 
> > win11x64，python-3.11.4-amd64，版本是1.4.0
> 
> 我是说pyqt版本...还是把启动时的完整log贴上来吧

D:\GAL\BallonsTranslator-1.4.0>cd D:\GAL\BallonsTranslator-1.4.0\
py version:  3.11.4 (tags/v3.11.4:d2340ef, Jun  7 2023, 05:45:37) [MSC v.1934 64 bit (AMD64)]
py executable:  D:\python\python.exe
version: 1.4.0
branch: dev
Commit hash: <none>
[INFO   ] config:load_textstyle_from:174 - Text style loaded from D:\GAL\BallonsTranslator-1.4.0\config/textstyles\default.json
[INFO   ] launch:main:172 - QT_API: pyqt5, QT Version: 5.15.2
[INFO   ] launch:main:200 - set display language to zh_CN
[INFO   ] module_manager:on_finish_settranslator:801 - Translator set to ChatGPT
[INFO   ] module_manager:on_finish_setinpainter:793 - Inpainter set to aot
[INFO   ] module_manager:on_finish_setocr:786 - OCR set to mit48px_ctc
[INFO   ] module_manager:on_finish_setdetector:780 - Text detector set to ctd

**Comment by dmMaze** [comment]
> [INFO ] launch:main:172 - QT_API: pyqt5, QT Version: 5.15.2

目前windows上只推荐pyqt==6.4.2: 
pip install PyQt6==6.4.2

**Comment by huimieba** [comment]
> > [INFO ] launch:main:172 - QT_API: pyqt5, QT Version: 5.15.2
> 
> 目前windows上只推荐pyqt==6.4.2: pip install PyQt6==6.4.2

好，我到时候看看还有没有问题

**Comment by huimieba** [comment]
> > [INFO ] launch:main:172 - QT_API: pyqt5, QT Version: 5.15.2
> 
> 目前windows上只推荐pyqt==6.4.2: pip install PyQt6==6.4.2

他说我安装了，但是我打开还是pyqt5，是要在哪个文件切换吗

**Comment by dmMaze** [comment]
> > > [INFO ] launch:main:172 - QT_API: pyqt5, QT Version: 5.15.2
> > 
> > 目前windows上只推荐pyqt==6.4.2: pip install PyQt6==6.4.2
> 
> 他说我安装了，但是我打开还是pyqt5，是要在哪个文件切换吗

那你把它卸载试试

**Comment by huimieba** [comment]
> > > > [INFO ] launch:main:172 - QT_API: pyqt5, QT Version: 5.15.2
> > > 
> > > 
> > > 目前windows上只推荐pyqt==6.4.2: pip install PyQt6==6.4.2
> > 
> > 
> > 他说我安装了，但是我打开还是pyqt5，是要在哪个文件切换吗
> 
> 那你把它卸载试试

好了，删除之后确实是显示使用pyqt6

**Comment by huimieba** [comment]
> > > > [INFO ] launch:main:172 - QT_API: pyqt5, QT Version: 5.15.2
> > > 
> > > 
> > > 目前windows上只推荐pyqt==6.4.2: pip install PyQt6==6.4.2
> > 
> > 
> > 他说我安装了，但是我打开还是pyqt5，是要在哪个文件切换吗
> 
> 那你把它卸载试试

谢谢大佬

**Comment by dmMaze** [comment]
> > > > > [INFO ] launch:main:172 - QT_API: pyqt5, QT Version: 5.15.2
> > > > 
> > > > 
> > > > 目前windows上只推荐pyqt==6.4.2: pip install PyQt6==6.4.2
> > > 
> > > 
> > > 他说我安装了，但是我打开还是pyqt5，是要在哪个文件切换吗
> > 
> > 
> > 那你把它卸载试试
> 
> 还有个问题，就是那个图像修复的脚本放在哪里，我想顺便看看他们有什么区别

如果你是说源码在 modules/inpaint/base.py，如果是程序里在那个画板界面

**Comment by huimieba** [comment]
> > > > > > [INFO ] launch:main:172 - QT_API: pyqt5, QT Version: 5.15.2
> > > > > 
> > > > > 
> > > > > 目前windows上只推荐pyqt==6.4.2: pip install PyQt6==6.4.2
> > > > 
> > > > 
> > > > 他说我安装了，但是我打开还是pyqt5，是要在哪个文件切换吗
> > > 
> > > 
> > > 那你把它卸载试试
> > 
> > 
> > 还有个问题，就是那个图像修复的脚本放在哪里，我想顺便看看他们有什么区别
> 
> 如果你是说源码在 modules/inpaint/base.py，如果是程序里在那个画板界面

好的

**Comment by huimieba** [comment]
> > > > > > [INFO ] launch:main:172 - QT_API: pyqt5, QT Version: 5.15.2
> > > > > 
> > > > > 
> > > > > 目前windows上只推荐pyqt==6.4.2: pip install PyQt6==6.4.2
> > > > 
> > > > 
> > > > 他说我安装了，但是我打开还是pyqt5，是要在哪个文件切换吗
> > > 
> > > 
> > > 那你把它卸载试试
> > 
> > 
> > 还有个问题，就是那个图像修复的脚本放在哪里，我想顺便看看他们有什么区别
> 
> 如果你是说源码在 modules/inpaint/base.py，如果是程序里在那个画板界面

Traceback (most recent call last):
  File "D:\GAL\BallonsTranslator-1.4.0\ui\scenetext_manager.py", line 880, in onTransWidgetHoverEnter
    blk_item = self.textblk_item_list[idx]
               ~~~~~~~~~~~~~~~~~~~~~~^^^^^
IndexError: list index out of range

但是换了pyqt6还是会报错

**Comment by dmMaze** [comment]
> > > > > > > [INFO ] launch:main:172 - QT_API: pyqt5, QT Version: 5.15.2
> > > > > > 
> > > > > > 
> > > > > > 目前windows上只推荐pyqt==6.4.2: pip install PyQt6==6.4.2
> > > > > 
> > > > > 
> > > > > 他说我安装了，但是我打开还是pyqt5，是要在哪个文件切换吗
> > > > 
> > > > 
> > > > 那你把它卸载试试
> > > 
> > > 
> > > 还有个问题，就是那个图像修复的脚本放在哪里，我想顺便看看他们有什么区别
> > 
> > 
> > 如果你是说源码在 modules/inpaint/base.py，如果是程序里在那个画板界面
> 
> Traceback (most recent call last): File "D:\GAL\BallonsTranslator-1.4.0\ui\scenetext_manager.py", line 880, in onTransWidgetHoverEnter blk_item = self.textblk_item_list[idx] ~~~~~~~~~~~~~~~~~~~~~~^^^^^ IndexError: list index out of range
> 
> 但是换了pyqt6还是会报错

你用的是最新版吗, 你用的好像是没.git的, 这里下载代码覆盖一下
<img width="606" alt="截屏2024-03-03 17 25 24" src="https://github.com/dmMaze/BallonsTranslator/assets/51270320/7d67422b-e50a-4e89-a655-24e4a82580b7">

**Comment by huimieba** [comment]
> > > > > > > > [INFO ] launch:main:172 - QT_API: pyqt5, QT Version: 5.15.2
> > > > > > > 
> > > > > > > 
> > > > > > > 目前windows上只推荐pyqt==6.4.2: pip install PyQt6==6.4.2
> > > > > > 
> > > > > > 
> > > > > > 他说我安装了，但是我打开还是pyqt5，是要在哪个文件切换吗
> > > > > 
> > > > > 
> > > > > 那你把它卸载试试
> > > > 
> > > > 
> > > > 还有个问题，就是那个图像修复的脚本放在哪里，我想顺便看看他们有什么区别
> > > 
> > > 
> > > 如果你是说源码在 modules/inpaint/base.py，如果是程序里在那个画板界面
> > 
> > 
> > Traceback (most recent call last): File "D:\GAL\BallonsTranslator-1.4.0\ui\scenetext_manager.py", line 880, in onTransWidgetHoverEnter blk_item = self.textblk_item_list[idx] ~~~~~~~~~~~~~~~~~~~~~~^^^^^ IndexError: list index out of range
> > 但是换了pyqt6还是会报错
> 
> 你用的是最新版吗, 你用的好像是没.git的, 这里下载代码覆盖一下 <img alt="截屏2024-03-03 17 25 24" width="606" src="https://private-user-images.githubusercontent.com/51270320/309539377-7d67422b-e50a-4e89-a655-24e4a82580b7.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDk0NTkwNjQsIm5iZiI6MTcwOTQ1ODc2NCwicGF0aCI6Ii81MTI3MDMyMC8zMDk1MzkzNzctN2Q2NzQyMmItZTUwYS00ZTg5LWE2NTUtMjRlNGE4MjU4MGI3LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAzMDMlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMzAzVDA5MzkyNFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTU1YjE1MmZkODQ2MTk4NjljYjY5YTMzZjM5MDcxNmU4ZWFiMGZlNjAxZGIyMWE3ZjYwMWIzMGI3MmY1OWY1NDUmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.KurpeR_9CMwysoiPimHze443FWYciTlyk6rbJctqrtc">

好的，我试试

**Comment by huimieba** [comment]
> > > > > > > > > [INFO ] launch:main:172 - QT_API: pyqt5, QT Version: 5.15.2
> > > > > > > > 
> > > > > > > > 
> > > > > > > > 目前windows上只推荐pyqt==6.4.2: pip install PyQt6==6.4.2
> > > > > > > 
> > > > > > > 
> > > > > > > 他说我安装了，但是我打开还是pyqt5，是要在哪个文件切换吗
> > > > > > 
> > > > > > 
> > > > > > 那你把它卸载试试
> > > > > 
> > > > > 
> > > > > 还有个问题，就是那个图像修复的脚本放在哪里，我想顺便看看他们有什么区别
> > > > 
> > > > 
> > > > 如果你是说源码在 modules/inpaint/base.py，如果是程序里在那个画板界面
> > > 
> > > 
> > > Traceback (most recent call last): File "D:\GAL\BallonsTranslator-1.4.0\ui\scenetext_manager.py", line 880, in onTransWidgetHoverEnter blk_item = self.textblk_item_list[idx] ~~~~~~~~~~~~~~~~~~~~~~^^^^^ IndexError: list index out of range
> > > 但是换了pyqt6还是会报错
> > 
> > 
> > 你用的是最新版吗, 你用的好像是没.git的, 这里下载代码覆盖一下 <img alt="截屏2024-03-03 17 25 24" width="606" src="https://private-user-images.githubusercontent.com/51270320/309539377-7d67422b-e50a-4e89-a655-24e4a82580b7.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDk0NTkwNjQsIm5iZiI6MTcwOTQ1ODc2NCwicGF0aCI6Ii81MTI3MDMyMC8zMDk1MzkzNzctN2Q2NzQyMmItZTUwYS00ZTg5LWE2NTUtMjRlNGE4MjU4MGI3LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAzMDMlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMzAzVDA5MzkyNFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTU1YjE1MmZkODQ2MTk4NjljYjY5YTMzZjM5MDcxNmU4ZWFiMGZlNjAxZGIyMWE3ZjYwMWIzMGI3MmY1OWY1NDUmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.KurpeR_9CMwysoiPimHze443FWYciTlyk6rbJctqrtc">
> 
> 好的，我试试

大佬我这里很奇怪，我手动框选文本编辑后点击ocr抹字并翻译，但是只有抹字启动并且成功，其他两个好像都没有启动（run的时候倒是有动，但是难免有些没有提取到）

**Comment by huimieba** [comment]
> > > > > > > > [信息] launch：main：172 - QT_API： pyqt5， QT 版本： 5.15.2
> > > > > > > 
> > > > > > > 
> > > > > > > 目前windows上只推荐pyqt==6.4.2： pip install PyQt6==6.4.2
> > > > > > 
> > > > > > 
> > > > > > 他说我安装了，但是我打开还是pyqt5，是要在哪个文件切换吗
> > > > > 
> > > > > 
> > > > > 那你把它卸载试试
> > > > 
> > > > 
> > > > 还有个问题，就是那个图像修复的脚本放在哪里，我想顺便看看他们有什么区别
> > > 
> > > 
> > > 如果你是说源码在 modules/inpaint/base.py，如果是程序里在那个画板界面
> > 
> > 
> > 回溯（最近一次调用）：文件“D：\GAL\BallonsTranslator-1.4.0\ui\scenetext_manager.py”，第 880 行，在 onTransWidgetHoverEnter blk_item = self.textblk_item_list[idx] ~~~~~~~~~~~~~~~~~~~~~~^^^^^ IndexError：列出索引超出范围
> > 但是换了pyqt6还是会报错
> 
> 你用的是最新版吗， 你用的好像是没.git的， 这里下载代码覆盖一下 <img alt="截屏2024-03-03 17 25 24" width="606" src="https://private-user-images.githubusercontent.com/51270320/309539377-7d67422b-e50a-4e89-a655-24e4a82580b7.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDk1NjU4NTQsIm5iZiI6MTcwOTU2NTU1NCwicGF0aCI6Ii81MTI3MDMyMC8zMDk1MzkzNzctN2Q2NzQyMmItZTUwYS00ZTg5LWE2NTUtMjRlNGE4MjU4MGI3LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAzMDQlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMzA0VDE1MTkxNFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWU1MjQ1ZmNiYjI3ZTdkYjdkNTg3ODYyZDlhZmJlNmNhNmQ0ODNmZGYxNmY0OTBkOTdkZWI3NjQ1Yjg0MzYzOTkmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.oUgJbwt017tBi8EAoRbmhY-V6LN7TugqHcIoQJoar9c">

大佬我这里很奇怪，我手动框选文本编辑后点击ocr抹字并翻译，但是只有抹字启动并且成功，其他两个好像都没有启动（run的时候倒是有动，但是难免有几个没有提取到）

**Comment by dmMaze** [comment]
> 大佬我这里很奇怪，我手动框选文本编辑后点击ocr抹字并翻译，但是只有抹字启动并且成功，其他两个好像都没有启动（run的时候倒是有动，但是难免有几个没有提取到）

框选的话OCR只建议用manga_ocr

**Comment by huimieba** [comment]
> > 大佬我这里很奇怪，我手动框选文本编辑后点击ocr抹字并翻译，但是只有抹字启动并且成功，其他两个好像都没有启动（run的时候倒是有动，但是难免有几个没有提取到）
> 
> 框选的话OCR只建议用manga_ocr

好的，换了manga_ocr确实能识别并翻译了

**Comment by huimieba** [comment]
> > 大佬我这里很奇怪，我手动框选文本编辑后点击ocr抹字并翻译，但是只有抹字启动并且成功，其他两个好像都没有启动（run的时候倒是有动，但是难免有几个没有提取到）
> 
> 框选的话OCR只建议用manga_ocr

Traceback (most recent call last):
  File "D:\GAL\BallonsTranslator-dev\ui\scenetext_manager.py", line 874, in onTransWidgetHoverEnter
    blk_item = self.textblk_item_list[idx]
               ~~~~~~~~~~~~~~~~~~~~~~^^^^^
IndexError: list index out of range
还是会有这种报错
