### ISSUE TITLE
關於安裝python3

### ISSUE THREAD

**Issue by Raiter123** [dmMaze/BallonsTranslator#392]
雖然有提示別安裝store裏的，但是我安裝網頁下載版的卻沒被系統測有安裝就是使用這個 python3 --version去查， 該怎麽辦， 不過我有試試與store版的，這兩種有什麽差別嗎一定要安裝網頁下載版的嗎？

**Comment by dmMaze** [comment]
store版能用就用，出了问题我不排查。可以卸载store版再自己重装，或者用网盘里那个python环境launch_win.bat启动
