### ISSUE TITLE
i have a Issues cause me cant start the new download software

### ISSUE THREAD

**Issue by Raiter123** [dmMaze/BallonsTranslator#393]
during start 
![image](https://github.com/dmMaze/BallonsTranslator/assets/153535038/08b1f707-591b-493c-97c5-75b8427394ca)
what it this and how to solve it

**Comment by dmMaze** [comment]
#392 说了别用微软商店，**py版本<3.12**，要是整不好环境直接用网盘里的包

**Comment by Raiter123** [comment]
> #392 说了别用微软商店，**py版本<3.12**，要是整不好环境直接用网盘里的包

沒用哦， 已經卸載掉了哦，這是我重新安裝網頁版的
