### ISSUE TITLE
i have a Issues cause me cant start the new download software

### ISSUE THREAD

**Issue by Raiter123** [dmMaze/BallonsTranslator#394]
我沒用微软商店版的，早已經完全卸載掉了，你都説有商店問題所以我就卸載了，這是我重新安裝網頁版的再打開軟件的發生的
![image](https://github.com/dmMaze/BallonsTranslator/assets/153535038/1300f3ce-4e84-42aa-8902-a8ea4e7326cc)

**Comment by Raiter123** [comment]
> readme里写了python 版本要求<3.12
我的本版不對嗎 要3.11的嗎
![image](https://github.com/dmMaze/BallonsTranslator/assets/153535038/24818ef8-4c4a-49fa-b5eb-144467ed8d98)

**Comment by bropines** [comment]
> > readme里写了python 版本要求<3.12
> > 我的本版不對嗎 要3.11的嗎
> > ![image](https://private-user-images.githubusercontent.com/153535038/310470725-24818ef8-4c4a-49fa-b5eb-144467ed8d98.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDk3MjU3NzQsIm5iZiI6MTcwOTcyNTQ3NCwicGF0aCI6Ii8xNTM1MzUwMzgvMzEwNDcwNzI1LTI0ODE4ZWY4LTRjNGEtNDlmYS1iNWViLTE0NDQ2N2VkOGQ5OC5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwMzA2JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDMwNlQxMTQ0MzRaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1mZTc3ZDJjZTBiYzcwOWFkYjMwYzJmMjE4MDg4ZDY0Y2YyMWI4ZTgwYWYxNzFjOGZmMDZmOTY5M2JiNDJkZTBiJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.ywdbF9zUAPDy0pQGE_7VsEHa_yDqBoaJWpiCiXetMrQ)

How you install python?

**Comment by Raiter123** [comment]
> 版本要求<3.12

成功打開，謝謝
![image](https://github.com/dmMaze/BallonsTranslator/assets/153535038/158d2b85-09df-4cc7-b978-afde2e9a7222)

**Comment by Raiter123** [comment]
> How you install python?

download from the web https://www.python.org/downloads/ 
choose the 3.11 version

**Comment by bropines** [comment]
> > How you install python?
> 
> download from the web https://www.python.org/downloads/ choose the 3.11 version

Write in CMD 
`where python`

**Comment by bropines** [comment]
@dmMaze  I will answer him here and help him, we will not open a new issue

**Comment by bropines** [comment]
I love GitHub, he decided not to update my story even after a forced update -_-
