### ISSUE TITLE
Line spacing problem

### ISSUE THREAD

**Issue by sinsw0000** [dmMaze/BallonsTranslator#396]
https://github.com/dmMaze/BallonsTranslator/assets/132151202/d510808f-68ab-472b-b8e2-58137ad05806

If I write Korean horizontally and increase the font size to emphasize a word in a sentence, the line spacing of the sentence becomes too wide because it fits the font size larger. It would be nice if the line spacing was adjusted to match the smaller font size.

**Comment by dmMaze** [comment]
![图片](https://github.com/dmMaze/BallonsTranslator/assets/51270320/030d2dd9-13ec-4217-85b0-90a9cb41b48e)
You can insert line breaks manually

**Comment by dmMaze** [comment]
> You can insert line breaks manually

No need to insert line breaks since [e77ed40](https://github.com/dmMaze/BallonsTranslator/commit/e77ed406a7640409cf74f6ab1784a68fc79dd83e)

**Comment by bropines** [comment]
> > You can insert line breaks manually
> 
> No need to insert line breaks since [e77ed40](https://github.com/dmMaze/BallonsTranslator/commit/e77ed406a7640409cf74f6ab1784a68fc79dd83e)

I dug into the code a little here. How difficult would it be to add this as a tick in the settings?

It’s just that when working with h-manga you have to pervert it in order to feed it chatgpt because it skips and confuses lines, and this numbering prevents this.

Mainwindow.py stroke 1130 - 1145

```python
    def on_copy_src(self):
        blks = self.canvas.selected_text_items()
        if len(blks) == 0:
            return
            
        if isinstance(self.module_manager.translator, GPTTranslator):
            src_list = [self.st_manager.pairwidget_list[blk.idx].e_source.toPlainText() for blk in blks]
            src_txt = ''
            for (prompt, num_src) in self.module_manager.translator._assemble_prompts(src_list, max_tokens=4294967295):
                src_txt += prompt
            src_txt = src_txt.strip()
        else:
            src_list = [f"{idx + 1}. " + self.st_manager.pairwidget_list[blk.idx].e_source.toPlainText().strip().replace('\n', ' ') for idx, blk in enumerate(blks)]
            src_txt = '\n'.join(src_list)

        self.st_manager.app_clipborad.setText(src_txt, QClipboard.Mode.Clipboard)
```
