### ISSUE TITLE
有幾個疑問和請求增加功能

### ISSUE THREAD

**Issue by Raiter123** [dmMaze/BallonsTranslator#397]
请问下如果已经做过ocr的漫画当我选其他翻译方法重新翻译时软件会再次做ocr吗

有办法在软件运作时停止吗，因爲有時候發現操作失誤但是軟件又停不下來，如果可以的话请加个停止按键

最新版的有时候会用到一半时自动关掉，通常是在編輯完页面后换页时， 请问这有什么问题吗，我可以自己解决吗

**Comment by Raiter123** [comment]
> > 请问下如果已经做过ocr的漫画当我选其他翻译方法重新翻译时软件会再次做ocr吗
> 
> 标题栏-运行 可以选阶段运行，readme里也说了
> 
> > 有办法在软件运作时停止吗，因爲有時候發現操作失誤但是軟件又停不下來，如果可以的话请加个停止按键
> 
> windows可以在任务栏右键关闭或者关掉那个cmd窗口
> 
> > 最新版的有时候会用到一半时自动关掉，通常是在編輯完页面后换页时， 请问这有什么问题吗，我可以自己解决吗
> 
> 需要给完整的报错信息


查报错信息時我才發現發到我的bat無法正常啓動，好像我的python的安裝方式有問題，之前我是直接點launch。py的
![image](https://github.com/dmMaze/BallonsTranslator/assets/153535038/d1f9c0ab-b76f-4587-b91d-5ad38a7d3bdc)

**Comment by bropines** [comment]
> 查报错信息時我才發現發到我的bat無法正常啓動，好像我的python的安裝方式有問題，之前我是直接點launch。py的

Is python fixed now?

**Comment by Raiter123** [comment]
> > 查报错信息時我才發現發到我的bat無法正常啓動，好像我的python的安裝方式有問題，之前我是直接點launch。py的
> 
> Is python fixed now?

no, try now

**Comment by Raiter123** [comment]
thanks
