### ISSUE TITLE
最新版的有时候会用到一半时自动关掉

### ISSUE THREAD

**Issue by Raiter123** [dmMaze/BallonsTranslator#398]
通常是在編輯完页面時后换页时，有時候是在改設定時， 请问这有什么问题吗，我可以自己解决吗
换设定时的
![image](https://github.com/dmMaze/BallonsTranslator/assets/153535038/ad452b08-7f6e-451e-9bd6-90b54f0eaaf3)

![image](https://github.com/dmMaze/BallonsTranslator/assets/153535038/87601a1e-a9a3-4148-a591-afd584671fea)

编辑后换页时
![image](https://github.com/dmMaze/BallonsTranslator/assets/153535038/c1078e83-74c4-4d5f-87cd-f058a3af58e8)

运行时强制停止时
![image](https://github.com/dmMaze/BallonsTranslator/assets/153535038/c06220a7-4781-4a89-a653-4c6f57de0a15)

**Comment by dmMaze** [comment]
Commit hash是版本, 6fda20fe52da844f5708d40bc3ab8f3013b27ee8 修了

**Comment by Raiter123** [comment]
> Commit hash

我該重新下載？

**Comment by dmMaze** [comment]
> > Commit hash
> 
> 我該重新下載？

README里说了怎么更新：
 运行 scripts/local_gitpull.bat 获取更新。
