### ISSUE TITLE
can't import project json file

### ISSUE THREAD

**Issue by Snowad14** [dmMaze/BallonsTranslator#4]
```
Traceback (most recent call last):
  File "E:\dev2\BallonsTranslator-master\ui\mainwindowbars.py", line 265, in onOpenProj
    self.open_dir.emit()
TypeError: LeftBar.open_dir[str] signal has 1 argument(s) but 0 provided
```

Maybe you just haven't implemented it yet but as there are no Exeptions that show it so I wanted to be sure

**Comment by Snowad14** [comment]
I just noticed that the opening via the folder works very well so it's not very important but I'll mention it anyway

**Comment by dmMaze** [comment]
Yes, it's not implemented. I would not turn back to the GUI stuff before I finish something like comic-textd-detector-v2 except for some serious bugfix, so I'll leave it as it is for now.
