### ISSUE TITLE
開始運行時軟件直接關掉了

### ISSUE THREAD

**Issue by Raiter123** [dmMaze/BallonsTranslator#403]
開始運行時軟件直接關掉了
![image](https://github.com/dmMaze/BallonsTranslator/assets/153535038/d8254d14-5b03-4baa-b2ed-b6d637f2de7e)
**順便提下，如果自己跑“launch.py”則沒有問題

**Comment by bropines** [comment]
> 開始運行時軟件直接關掉了 ![image](https://private-user-images.githubusercontent.com/153535038/313224206-d8254d14-5b03-4baa-b2ed-b6d637f2de7e.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTA1MTQ0NDksIm5iZiI6MTcxMDUxNDE0OSwicGF0aCI6Ii8xNTM1MzUwMzgvMzEzMjI0MjA2LWQ4MjU0ZDE0LTViMDMtNGJhYS1iMmVkLWI2ZDYzN2YyZGU3ZS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwMzE1JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDMxNVQxNDQ5MDlaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0wNmMwOWVlZDlmNmVmYzAwOWVmNWJjN2U2Mjg4ZjgyMmFkMGQ2MzMxNDhjMGEyZGE4NmY4MWY1ZmU2Njc2MjgyJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.UPQZL7RentDYNAh72ELSfaRGhhHDdfEPFSEzqacwi38) **順便提下，如果自己跑“launch.py”則沒有問題

install Python not from Microsoft store

**Comment by bropines** [comment]
> 開始運行時軟件直接關掉了 ![image](https://private-user-images.githubusercontent.com/153535038/313224206-d8254d14-5b03-4baa-b2ed-b6d637f2de7e.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTA1MTQ1MzUsIm5iZiI6MTcxMDUxNDIzNSwicGF0aCI6Ii8xNTM1MzUwMzgvMzEzMjI0MjA2LWQ4MjU0ZDE0LTViMDMtNGJhYS1iMmVkLWI2ZDYzN2YyZGU3ZS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwMzE1JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDMxNVQxNDUwMzVaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT02NWZkODI1MzA4NjBiYzllNDkyZGNjMDA5YzZjNWQ1OTY1ZTFjZTM0MThmZmJiMzA5NjRjNzFkODRlZDYxYzBmJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.MNgBSf-f6x23CSmu6cLk6LfAYpxpB1WIZAeqlRxHNWI) **順便提下，如果自己跑“launch.py”則沒有問題

still, yes, install Python not from Microsoft Store, and it looks like you have installed libraries crookedly.

**Comment by bropines** [comment]
Why is that? It says here https://github.com/kha-white/manga-ocr#troubleshooting

If you want a normal Python, then I advise you to do it, but it's better to put something on the example of pyenv-win

**Comment by bropines** [comment]
> 開始運行時軟件直接關掉了 ![image](https://private-user-images.githubusercontent.com/153535038/313224206-d8254d14-5b03-4baa-b2ed-b6d637f2de7e.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTA1MTkwMzQsIm5iZiI6MTcxMDUxODczNCwicGF0aCI6Ii8xNTM1MzUwMzgvMzEzMjI0MjA2LWQ4MjU0ZDE0LTViMDMtNGJhYS1iMmVkLWI2ZDYzN2YyZGU3ZS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwMzE1JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDMxNVQxNjA1MzRaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT00ZWQ1ZjQzNWEyNjUzODVjODg2NWNlOWEwNmNhOTQ2M2NmNjNkMTA2YTJjYzQ0ZDNiOTEzYTViNTQyYzhlYWQzJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.FBHfWuy-zqqbK4EZS2j9PWf3gdOI3Wsyn9rlePZCwaM) **順便提下，如果自己跑“launch.py”則沒有問題

Did you solve the problem or i help you?

**Comment by Raiter123** [comment]
> If you want a normal Python, then I advise you to do it, but it's better to put something on the example of pyenv-win

wait let me try first

**Comment by Raiter123** [comment]
> still, yes, install Python not from Microsoft Store, and it looks like you have installed libraries crookedly.
install Python 3.10 only noww
![image](https://github.com/dmMaze/BallonsTranslator/assets/153535038/4350279a-3a1e-4b6b-94f0-3123fd151e5d)

when run .bat
![image](https://github.com/dmMaze/BallonsTranslator/assets/153535038/86cc16fa-f360-4889-bd96-0fcf22732421)
It can't run due dont know why 
![image](https://github.com/dmMaze/BallonsTranslator/assets/153535038/f434050c-534a-4de9-a768-9cff71fcf11d)

**Comment by bropines** [comment]
> > still, yes, install Python not from Microsoft Store, and it looks like you have installed libraries crookedly.
> > install Python 3.10 only noww
> > ![image](https://private-user-images.githubusercontent.com/153535038/313408373-4350279a-3a1e-4b6b-94f0-3123fd151e5d.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTA1OTgwMTQsIm5iZiI6MTcxMDU5NzcxNCwicGF0aCI6Ii8xNTM1MzUwMzgvMzEzNDA4MzczLTQzNTAyNzlhLTNhMWUtNGI2Yi05NGYwLTMxMjNmZDE1MWU1ZC5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwMzE2JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDMxNlQxNDAxNTRaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1mOTFhZjA5NDIzZTkwOTU5NWU1MWI1YTY3NjEzZjkyZjhkNmVjMTdlM2E2MTA3MDk3OTU0MmNjOTQxYTExYWJjJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.U9OwXsOtzlQsBAPuiqukOMJ6L52ar2TlKn7zpWFrdLc)
> 
> when run .bat ![image](https://private-user-images.githubusercontent.com/153535038/313408410-86cc16fa-f360-4889-bd96-0fcf22732421.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTA1OTgwMTQsIm5iZiI6MTcxMDU5NzcxNCwicGF0aCI6Ii8xNTM1MzUwMzgvMzEzNDA4NDEwLTg2Y2MxNmZhLWYzNjAtNDg4OS1iZDk2LTBmY2YyMjczMjQyMS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwMzE2JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDMxNlQxNDAxNTRaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT01OWE1MGYxYzg1ZTRlMDk2MjViMjE5NmU0NWFiNTBhYjNlN2U4Y2ZmNGRmNzU5OWZlZWYyNTZhMmY4ZDk5Y2UwJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.1JHKOEJ3ayeVGmve3ucwXVyrK9lPLigiiHa_kYpi2NE) It can't run due dont know why ![image](https://private-user-images.githubusercontent.com/153535038/313408473-f434050c-534a-4de9-a768-9cff71fcf11d.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTA1OTgwMTQsIm5iZiI6MTcxMDU5NzcxNCwicGF0aCI6Ii8xNTM1MzUwMzgvMzEzNDA4NDczLWY0MzQwNTBjLTUzNGEtNGRlOS1hNzY4LTljZmY3MWZjZjExZC5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwMzE2JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDMxNlQxNDAxNTRaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0yNTY4ZDRkMmVjYzU0ZmZmNDBjNGJmZjU3Y2VmY2ViZmRjZGJhOGJhMzY4ZmI0OGY4NjgwM2Q5MDRkOTA1NWJkJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.mNM_illxL7gJgejGwwip7TJuFIz3065iAo7KtfQtvU0)


![image](https://github.com/dmMaze/BallonsTranslator/assets/57861007/77b69a23-2573-4a02-b32a-acadcd9ed88e)

pyhton3?

Delete all python's. Now let's do it differently, and it's better if you write to me in [telegram](t.me/bropines) (if possible).

**Comment by Raiter123** [comment]
> > > still, yes, install Python not from Microsoft Store, and it looks like you have installed libraries crookedly.
> > > install Python 3.10 only noww
> > > ![image](https://private-user-images.githubusercontent.com/153535038/313408373-4350279a-3a1e-4b6b-94f0-3123fd151e5d.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTA1OTgwMTQsIm5iZiI6MTcxMDU5NzcxNCwicGF0aCI6Ii8xNTM1MzUwMzgvMzEzNDA4MzczLTQzNTAyNzlhLTNhMWUtNGI2Yi05NGYwLTMxMjNmZDE1MWU1ZC5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwMzE2JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDMxNlQxNDAxNTRaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1mOTFhZjA5NDIzZTkwOTU5NWU1MWI1YTY3NjEzZjkyZjhkNmVjMTdlM2E2MTA3MDk3OTU0MmNjOTQxYTExYWJjJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.U9OwXsOtzlQsBAPuiqukOMJ6L52ar2TlKn7zpWFrdLc)不过，是的，不是从 Microsoft Store 安装 Python，看起来您安装的库歪歪扭扭。
> > > 现在只安装 Python 3.10w
> > 
> > 
> > when run .bat ![image](https://private-user-images.githubusercontent.com/153535038/313408410-86cc16fa-f360-4889-bd96-0fcf22732421.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTA1OTgwMTQsIm5iZiI6MTcxMDU5NzcxNCwicGF0aCI6Ii8xNTM1MzUwMzgvMzEzNDA4NDEwLTg2Y2MxNmZhLWYzNjAtNDg4OS1iZDk2LTBmY2YyMjczMjQyMS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwMzE2JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDMxNlQxNDAxNTRaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT01OWE1MGYxYzg1ZTRlMDk2MjViMjE5NmU0NWFiNTBhYjNlN2U4Y2ZmNGRmNzU5OWZlZWYyNTZhMmY4ZDk5Y2UwJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.1JHKOEJ3ayeVGmve3ucwXVyrK9lPLigiiHa_kYpi2NE) It can't run due dont know why ![image](https://private-user-images.githubusercontent.com/153535038/313408473-f434050c-534a-4de9-a768-9cff71fcf11d.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTA1OTgwMTQsIm5iZiI6MTcxMDU5NzcxNCwicGF0aCI6Ii8xNTM1MzUwMzgvMzEzNDA4NDczLWY0MzQwNTBjLTUzNGEtNGRlOS1hNzY4LTljZmY3MWZjZjExZC5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwMzE2JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDMxNlQxNDAxNTRaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0yNTY4ZDRkMmVjYzU0ZmZmNDBjNGJmZjU3Y2VmY2ViZmRjZGJhOGJhMzY4ZmI0OGY4NjgwM2Q5MDRkOTA1NWJkJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.mNM_illxL7gJgejGwwip7TJuFIz3065iAo7KtfQtvU0)运行时.bat 由于不知道为什么，它无法运行
> 
> ![image](https://private-user-images.githubusercontent.com/57861007/313409185-77b69a23-2573-4a02-b32a-acadcd9ed88e.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTA1OTg5ODEsIm5iZiI6MTcxMDU5ODY4MSwicGF0aCI6Ii81Nzg2MTAwNy8zMTM0MDkxODUtNzdiNjlhMjMtMjU3My00YTAyLWIzMmEtYWNhZGNkOWVkODhlLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAzMTYlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMzE2VDE0MTgwMVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWJlYTAzN2YxN2Q2NDMwMjE3MGY5NTc1YzNjMzg0MTFmMWM3NmQxMjA2NjhlMjk0Zjk0ODlhNDNlNDE1OGMxMGUmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.XBgOmwPcs7MGydyFrTfPbfLvN3mtc_XywdgnpbmewiM)
> 
> pyhton3? 皮顿3？
> 
> Delete all python's. Now let's do it differently, and it's better if you write to me in [telegram](t.me/bropines) (if possible).删除所有 python。现在让我们以不同的方式做，最好是你用电报给我写信（如果可能的话）。

i am uninstall all python already , now only install the python 3.10

**Comment by bropines** [comment]
And

> i am uninstall all python already , now only install the python 3.10

Dont install. Install this

https://github.com/pyenv-win/pyenv-win?ysclid=ltu6fhcgqp455019785

**Comment by Raiter123** [comment]
> > > > still, yes, install Python not from Microsoft Store, and it looks like you have installed libraries crookedly.
> > > > install Python 3.10 only noww
> > > > ![image](https://private-user-images.githubusercontent.com/153535038/313408373-4350279a-3a1e-4b6b-94f0-3123fd151e5d.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTA1OTgwMTQsIm5iZiI6MTcxMDU5NzcxNCwicGF0aCI6Ii8xNTM1MzUwMzgvMzEzNDA4MzczLTQzNTAyNzlhLTNhMWUtNGI2Yi05NGYwLTMxMjNmZDE1MWU1ZC5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwMzE2JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDMxNlQxNDAxNTRaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1mOTFhZjA5NDIzZTkwOTU5NWU1MWI1YTY3NjEzZjkyZjhkNmVjMTdlM2E2MTA3MDk3OTU0MmNjOTQxYTExYWJjJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.U9OwXsOtzlQsBAPuiqukOMJ6L52ar2TlKn7zpWFrdLc)不过，是的，不是从 Microsoft Store 安装 Python，看起来您安装的库歪歪扭扭。
> > > > 现在只安装 Python 3.10w
> > > 
> > > 
> > > when run .bat ![image](https://private-user-images.githubusercontent.com/153535038/313408410-86cc16fa-f360-4889-bd96-0fcf22732421.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTA1OTgwMTQsIm5iZiI6MTcxMDU5NzcxNCwicGF0aCI6Ii8xNTM1MzUwMzgvMzEzNDA4NDEwLTg2Y2MxNmZhLWYzNjAtNDg4OS1iZDk2LTBmY2YyMjczMjQyMS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwMzE2JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDMxNlQxNDAxNTRaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT01OWE1MGYxYzg1ZTRlMDk2MjViMjE5NmU0NWFiNTBhYjNlN2U4Y2ZmNGRmNzU5OWZlZWYyNTZhMmY4ZDk5Y2UwJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.1JHKOEJ3ayeVGmve3ucwXVyrK9lPLigiiHa_kYpi2NE) It can't run due dont know why ![image](https://private-user-images.githubusercontent.com/153535038/313408473-f434050c-534a-4de9-a768-9cff71fcf11d.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTA1OTgwMTQsIm5iZiI6MTcxMDU5NzcxNCwicGF0aCI6Ii8xNTM1MzUwMzgvMzEzNDA4NDczLWY0MzQwNTBjLTUzNGEtNGRlOS1hNzY4LTljZmY3MWZjZjExZC5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwMzE2JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDMxNlQxNDAxNTRaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0yNTY4ZDRkMmVjYzU0ZmZmNDBjNGJmZjU3Y2VmY2ViZmRjZGJhOGJhMzY4ZmI0OGY4NjgwM2Q5MDRkOTA1NWJkJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.mNM_illxL7gJgejGwwip7TJuFIz3065iAo7KtfQtvU0)运行时.bat 由于不知道为什么，它无法运行
> > 
> > 
> > ![image](https://private-user-images.githubusercontent.com/57861007/313409185-77b69a23-2573-4a02-b32a-acadcd9ed88e.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTA1OTg5ODEsIm5iZiI6MTcxMDU5ODY4MSwicGF0aCI6Ii81Nzg2MTAwNy8zMTM0MDkxODUtNzdiNjlhMjMtMjU3My00YTAyLWIzMmEtYWNhZGNkOWVkODhlLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAzMTYlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMzE2VDE0MTgwMVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWJlYTAzN2YxN2Q2NDMwMjE3MGY5NTc1YzNjMzg0MTFmMWM3NmQxMjA2NjhlMjk0Zjk0ODlhNDNlNDE1OGMxMGUmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.XBgOmwPcs7MGydyFrTfPbfLvN3mtc_XywdgnpbmewiM)
> > pyhton3? 皮顿3？
> > Delete all python's. Now let's do it differently, and it's better if you write to me in [telegram](t.me/bropines) (if possible).删除所有 python。现在让我们以不同的方式做，最好是你用电报给我写信（如果可能的话）。Delete all python's. Now let's do it differently, and it's better if you write to me in telegram (if possible).删除所有 python。 现在让我们以不同的方式做，最好是你用电报给我写信（如果可能的话）。
> 
> i am uninstall all python already , now only install the python 3.10我已经卸载了所有python，现在只安装python 3.10

ok i, Uninstall again

**Comment by Raiter123** [comment]
> And
> 
> > i am uninstall all python already , now only install the python 3.10
> 
> Dont install. Install this
> 
> https://github.com/pyenv-win/pyenv-win?ysclid=ltu6fhcgqp455019785

OK i will uninstall python again , than install this ??
