### ISSUE TITLE
DeepL pro account

### ISSUE THREAD

**Issue by simonrule** [dmMaze/BallonsTranslator#406]
Do you think you could add support to use email and pass my friend shared with me his deepl pro account, i checked for api key but couldnt fond anything about it.

**Comment by bropines** [comment]
> Do you think you could add support to use email and pass my friend shared with me his deepl pro account, i checked for api key but couldnt fond anything about it.

https://www.deepl.com/ru/account/summary

![translated (2)](https://github.com/dmMaze/BallonsTranslator/assets/57861007/af48de47-c0dc-4ee5-8ea5-e3a70892446c)

**Comment by simonrule** [comment]
> > Do you think you could add support to use email and pass my friend shared with me his deepl pro account, i checked for api key but couldnt fond anything about it.
> 
> https://www.deepl.com/en/account/summary
> 
> ![translated (2)](https://private-user-images.githubusercontent.com/57861007/313469099-af48de47-c0dc-4ee5-8ea5-e3a70892446c.jpg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTA2OTgwMDEsIm5iZiI6MTcxMDY5NzcwMSwicGF0aCI6Ii81Nzg2MTAwNy8zMTM0NjkwOTktYWY0OGRlNDctYzBkYy00ZWU1LThlYTUtZTNhNzA4OTI0NDZjLmpwZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAzMTclMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMzE3VDE3NDgyMVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWFkNjk2YTEyMjU4YmViZDAyMGY2NTBlNzM0MTE3OTNiZGUxYmU5NWVlNmQ5NDZhN2Q2OWZjNDRiYjc0YWYxOWEmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.7bM7eSvMtlcWM5bxubT209xmKO5GZZY2oRERrNI4sq4)

i didnt find anything related i guess because the account subscription status is DeepL Pro not DeepL API.

![Screenshot 2024-03-17 114958](https://github.com/dmMaze/BallonsTranslator/assets/23766323/4c05a159-3b40-4ac9-9779-9809d5e3b558)

**Comment by bropines** [comment]
> > > Do you think you could add support to use email and pass my friend shared with me his deepl pro account, i checked for api key but couldnt fond anything about it.
> > 
> > 
> > https://www.deepl.com/en/account/summary
> > ![translated (2)](https://private-user-images.githubusercontent.com/57861007/313469099-af48de47-c0dc-4ee5-8ea5-e3a70892446c.jpg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTA2OTgwMDEsIm5iZiI6MTcxMDY5NzcwMSwicGF0aCI6Ii81Nzg2MTAwNy8zMTM0NjkwOTktYWY0OGRlNDctYzBkYy00ZWU1LThlYTUtZTNhNzA4OTI0NDZjLmpwZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAzMTclMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMzE3VDE3NDgyMVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWFkNjk2YTEyMjU4YmViZDAyMGY2NTBlNzM0MTE3OTNiZGUxYmU5NWVlNmQ5NDZhN2Q2OWZjNDRiYjc0YWYxOWEmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.7bM7eSvMtlcWM5bxubT209xmKO5GZZY2oRERrNI4sq4)
> 
> i didnt find anything related i guess because the account subscription status is DeepL Pro not DeepL API.
> 
> ![Screenshot 2024-03-17 114958](https://private-user-images.githubusercontent.com/23766323/313494128-4c05a159-3b40-4ac9-9779-9809d5e3b558.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTA3MDU4MjUsIm5iZiI6MTcxMDcwNTUyNSwicGF0aCI6Ii8yMzc2NjMyMy8zMTM0OTQxMjgtNGMwNWExNTktM2I0MC00YWM5LTk3NzktOTgwOWQ1ZTNiNTU4LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAzMTclMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMzE3VDE5NTg0NVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTcyNzNhOTZmMDY3NzBkOWU1ZWUxN2RkODk4NzA5MDQyYjBjOGQ2ZDMxNDBmZjljZGZhNDc3NzU0YTBjMWYxNjImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.qeIu9iTQV5DKjXosqiIzvjT6feQ-JB6j81K9LQSVTho)

and stop, yes, you need an API, I even thought that you had an API PRO

**Comment by simonrule** [comment]
> > > > Do you think you could add support to use email and pass my friend shared with me his deepl pro account, i checked for api key but couldnt fond anything about it.
> > > 
> > > 
> > > https://www.deepl.com/en/account/summary
> > > ![translated (2)](https://private-user-images.githubusercontent.com/57861007/313469099-af48de47-c0dc-4ee5-8ea5-e3a70892446c.jpg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTA2OTgwMDEsIm5iZiI6MTcxMDY5NzcwMSwicGF0aCI6Ii81Nzg2MTAwNy8zMTM0NjkwOTktYWY0OGRlNDctYzBkYy00ZWU1LThlYTUtZTNhNzA4OTI0NDZjLmpwZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAzMTclMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMzE3VDE3NDgyMVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWFkNjk2YTEyMjU4YmViZDAyMGY2NTBlNzM0MTE3OTNiZGUxYmU5NWVlNmQ5NDZhN2Q2OWZjNDRiYjc0YWYxOWEmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.7bM7eSvMtlcWM5bxubT209xmKO5GZZY2oRERrNI4sq4)
> > 
> > 
> > i didnt find anything related i guess because the account subscription status is DeepL Pro not DeepL API.
> > ![Screenshot 2024-03-17 114958](https://private-user-images.githubusercontent.com/23766323/313494128-4c05a159-3b40-4ac9-9779-9809d5e3b558.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTA3MDU4MjUsIm5iZiI6MTcxMDcwNTUyNSwicGF0aCI6Ii8yMzc2NjMyMy8zMTM0OTQxMjgtNGMwNWExNTktM2I0MC00YWM5LTk3NzktOTgwOWQ1ZTNiNTU4LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAzMTclMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMzE3VDE5NTg0NVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTcyNzNhOTZmMDY3NzBkOWU1ZWUxN2RkODk4NzA5MDQyYjBjOGQ2ZDMxNDBmZjljZGZhNDc3NzU0YTBjMWYxNjImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.qeIu9iTQV5DKjXosqiIzvjT6feQ-JB6j81K9LQSVTho)
> 
> and stop, yes, you need an API, I even thought that you had an API PRO

ok ill have to buy my own api pro.
Thank you :)

**Comment by bropines** [comment]
> ok ill have to buy my own api pro.
> Thank you :)

Firstly, you need to close the issue. Secondly, you can sign up for a free one (it only includes a card) and there are 500k symbols free per month

**Comment by simonrule** [comment]
> > ok ill have to buy my own api pro.
> > Thank you :)
> 
> Firstly, you need to close the issue. Secondly, you can sign up for a free one (it only includes a card) and there are 500k symbols free per month

thank you or letting me know :)
