### ISSUE TITLE
MacOS app build ERROR

### ISSUE THREAD

**Issue by Heathcliff-Ng** [dmMaze/BallonsTranslator#408]
https://raw.githubusercontent.com/dmMaze/BallonsTranslator/dev/scripts/macos-build-script.sh 这个网址好像已经失效了。有最新的 app build bash 吗？

**Comment by dmMaze** [comment]
好像被重命名成了macos-build-script-arm64.sh

**Comment by Heathcliff-Ng** [comment]
> 好像被重命名成了macos-build-script-arm64.sh

感谢。只需要把 scripts 里面的 macos-build-script-arm64.sh 移动到文件夹外面然后运行就可以了。
