### ISSUE TITLE
Translation failed due to 'str' object has no attribute 'usage'.

### ISSUE THREAD

**Issue by daxuquan** [dmMaze/BallonsTranslator#415]
![2024-03-27_14-28-00](https://github.com/dmMaze/BallonsTranslator/assets/70622093/409b4ca4-0210-4478-9fff-f962e3c05e61)

请问这该如何处理呢

**Comment by dmMaze** [comment]
这个第三方api返回的不是标准格式

**Comment by daxuquan** [comment]
换直连api搞定了，谢谢

**Comment by bropines** [comment]
> 换直连api搞定了，谢谢

Close issue. <3
