### ISSUE TITLE
好像不支持图片还原？

### ISSUE THREAD

**Issue by lhj5426** [dmMaze/BallonsTranslator#42]
![image](https://user-images.githubusercontent.com/30548000/190694464-2ad73396-2d99-49f0-8834-81aa6691765e.png)
![image](https://user-images.githubusercontent.com/30548000/190694579-3c510679-4a59-40d9-b3a1-dbec9f6407bb.png)
您好 这个 拟声词 被自动识别并且翻译了 实际上是没必要的
然后删除之后这里就空白了 然后在 掩码的部分没有看到反向涂抹修复？

**Comment by lhj5426** [comment]
![image](https://user-images.githubusercontent.com/30548000/190695634-3af16b61-883e-4461-9f4b-db8822298a08.png)
 掩膜这里没有找到涂抹反向还原

**Comment by lhj5426** [comment]
然后 竖排的时候 叹号是横着的
![image](https://user-images.githubusercontent.com/30548000/190696906-0bec8f59-3d90-436e-9bbc-b9538a4b7740.png)

**Comment by bropines** [comment]
唉，这是文字，会被识别出来的，这还是取决于文字检测器。 如果教导得当，他就不会碰触到声音。

**Comment by bropines** [comment]
背景中的漫画是什么？ (我知道这是什么样的内容)

**Comment by dmMaze** [comment]
> ![image](https://user-images.githubusercontent.com/30548000/190695634-3af16b61-883e-4461-9f4b-db8822298a08.png)
>  掩膜这里没有找到涂抹反向还原 

矩形工具或者修复画笔按下右键就是还原

**Comment by dmMaze** [comment]
> 您好 这个 拟声词 被自动识别并且翻译了 实际上是没必要的

现在这个检测模型会尽可能找出所有文字，不会对免翻译内容做过滤，我没有日语/日漫翻译经验也不能决定哪些是免翻内容

**Comment by dmMaze** [comment]
> 然后 竖排的时候 叹号是横着的

半角会转全角不会，竖排规则见https://github.com/dmMaze/BallonsTranslator/pull/30

**Comment by lhj5426** [comment]
> > 然后 竖排的时候 叹号是横着的
> 
> 半角会转全角不会，竖排符号规则见#30

我说没看懂你会不理我么
这个30 的动图怎么看也没看到 标点符号转过来呀 
![image](https://user-images.githubusercontent.com/30548000/190843388-80642c67-8adc-4ff7-bb8e-25a2862b649e.png)
自始至终这个标点一直是躺着的 

> > 您好 这个 拟声词 被自动识别并且翻译了 实际上是没必要的
> 
> 现在这个检测模型会尽可能找出所有文字，不会对免翻译内容做过滤，我没有日语/日漫翻译经验也不能决定哪些是免翻内容

好像也不支持手动选择内容 全部交给了 那个软件处理 就是假如 有没被识别的内容 无法手动进行2次干预 进行手动框选识别

**Comment by dmMaze** [comment]
> 我说没看懂你会不理我么
> 这个30 的动图怎么看也没看到 标点符号转过来呀

中文竖排规范就是部分半角符号旋转九十度的，这里可以用全角代替。

> 好像也不支持手动选择内容 全部交给了 那个软件处理 就是假如 有没被识别的内容 无法手动进行2次干预 进行手动框选识别

现在确实没这个功能，我可能会在下一轮模型训练完加

> 但是 左键框选 没有勾自动 框选之后 程序整体就卡住了

点下修复就行了，或者删除，这是生成一个预览看掩膜是否生成正确再做决定

**Comment by lhj5426** [comment]
> > 我说没看懂你会不理我么
> > 这个30 的动图怎么看也没看到 标点符号转过来呀
> 
> _中文_竖排规范就是部分半角符号旋转九十度的，这里可以用全角代替。
> 
> > 好像也不支持手动选择内容 全部交给了 那个软件处理 就是假如 有没被识别的内容 无法手动进行2次干预 进行手动框选识别
> 
> 现在确实没这个功能，我可能会在下一轮模型训练完加
> 
> > 但是 左键框选 没有勾自动 框选之后 程序整体就卡住了
> 
> 点下修复就行了，或者删除，这是生成一个预览看掩膜是否生成正确再做决定

我了去 您回复的也太快了我这还没编辑完
还有一个问题 有的漫画 一句话会有3个或者2个叹号强调重点 这个目前也没有吧

**Comment by lhj5426** [comment]
> > 我说没看懂你会不理我么
> > 这个30 的动图怎么看也没看到 标点符号转过来呀
> 
> _中文_竖排规范就是部分半角符号旋转九十度的，这里可以用全角代替。
> 
> > 好像也不支持手动选择内容 全部交给了 那个软件处理 就是假如 有没被识别的内容 无法手动进行2次干预 进行手动框选识别
> 
> 现在确实没这个功能，我可能会在下一轮模型训练完加
> 
> > 但是 左键框选 没有勾自动 框选之后 程序整体就卡住了
> 
> 点下修复就行了，或者删除，这是生成一个预览看掩膜是否生成正确再做决定

是卡住 不是点删除 或者点 修复的问题 我上一个视频

https://user-images.githubusercontent.com/30548000/190844082-f52e48fe-7879-4c13-94e8-889b1d0d3a46.mp4

**Comment by dmMaze** [comment]
> 还有一个问题 有的漫画 一句话会有3个或者2个叹号强调重点 这个目前也没有吧

'⁇', '⁉', '⁈', '‼'这几个都是独立字符可以直接输进去，两个以上可能要像ps那样做竖排内横排，这功能实现起来会非常麻烦现阶段暂时不打算做

**Comment by lhj5426** [comment]
> > 还有一个问题 有的漫画 一句话会有3个或者2个叹号强调重点 这个目前也没有吧
> 
> '⁇', '⁉', '⁈', '‼'这几个都是独立字符可以直接输进去，两个以上可能要像ps那样做竖排内横排，这功能实现起来会非常麻烦现阶段暂时不打算做

嗯 那个 题外话您录制GIF的工具是什么呀 又有鼠标点击的提示又有按键的提示 还有在什么程序里执行的 看着好棒呀

**Comment by dmMaze** [comment]
> 是卡住 不是点删除 或者点 修复的问题 我上一个视频

我没法复现这个bug，终端里有报什么错吗，方便的话传下原图

> 嗯 那个 题外话您录制GIF的工具是什么呀 又有鼠标点击的提示又有按键的提示 还有在什么程序里执行的 看着好棒呀

录屏是https://github.com/NickeManarin/ScreenToGif
按键显示是https://github.com/bfritscher/carnac

**Comment by lhj5426** [comment]
> > 是卡住 不是点删除 或者点 修复的问题 我上一个_视频_
> 
> 我没法复现这个bug，终端里有报什么错吗，方便的话传下原图
> 
> > 嗯 那个 题外话您录制GIF的工具是什么呀 又有鼠标点击的提示又有按键的提示 还有在什么程序里执行的 看着好棒呀
> 
> 录屏是https://github.com/NickeManarin/ScreenToGif 按键显示是https://github.com/bfritscher/carnac

我第一次左键框选然后删除 然后第二次左键框选 什么都没点软件就卡住了 每次都可以复现。。。。 我也不知道为什么

**Comment by lhj5426** [comment]
> > 是卡住 不是点删除 或者点 修复的问题 我上一个_视频_
> 
> 我没法复现这个bug，终端里有报什么错吗，方便的话传下原图
> 
> > 嗯 那个 题外话您录制GIF的工具是什么呀 又有鼠标点击的提示又有按键的提示 还有在什么程序里执行的 看着好棒呀
> 
> 录屏是https://github.com/NickeManarin/ScreenToGif 按键显示是https://github.com/bfritscher/carnac

![image](https://user-images.githubusercontent.com/30548000/190844703-e8e78840-dee0-4cf2-8576-fe81a5ed997a.png)
卡住之后黑框是这样的

**Comment by lhj5426** [comment]
[#0019.zip](https://github.com/dmMaze/BallonsTranslator/files/9591186/0019.zip)
如果您 要原图的话 这张 测试用的

**Comment by dmMaze** [comment]
> 是卡住 不是点删除 或者点 修复的问题 我上一个视频

应该修好了，已更新至网盘
另外加了个掩膜膨胀应对描边
<img width="491" alt="dilate" src="https://user-images.githubusercontent.com/51270320/190855212-c91ae1eb-e0a7-4b3b-bc2f-ab517c26d3d1.png">

**Comment by lhj5426** [comment]
> > 是卡住 不是点删除 或者点 修复的问题 我上一个_视频_
> 
> 应该修好了，已更新至网盘 另外加了个掩膜膨胀应对描边，注意这同样会应用到一键翻译 <img alt="dilate" width="491" src="https://user-images.githubusercontent.com/51270320/190855212-c91ae1eb-e0a7-4b3b-bc2f-ab517c26d3d1.png">

修好了 刚试过没有在触发哈哈  还挺苦恼这个 全彩识别完是白边呢 现在好像不需要烦恼了
