### ISSUE TITLE
can you add support for arabic please?

### ISSUE THREAD

**Issue by aymanharrawi** [dmMaze/BallonsTranslator#422]
can you add support for arabic please?, or at least give me modify to config file that use arabic translation please

**Comment by bropines** [comment]
If you tell me what your language looks like in code (like RU, EN, ZH), I will help you add it locally

**Comment by bropines** [comment]
Add this line to these blocks in the required translator files `\modules\translators`. DeepL, Yandex, Google work, the rest have not been tested
![image](https://github.com/dmMaze/BallonsTranslator/assets/57861007/0374d471-41f5-4f4f-93ca-b3fd20ef623d)
```python
self.lang_map['Arabic'] = 'ar'
```

**Comment by aymanharrawi** [comment]
it worked! thank you very much!

**Comment by bropines** [comment]
@aymanharrawi update the program (if you are using launch from source) and clean up your changes.
