### ISSUE TITLE
我是使用sakura翻譯的，最近出現問題了，無法翻譯

### ISSUE THREAD

**Issue by Raiter123** [dmMaze/BallonsTranslator#424]
我是使用sakura翻译的最近出现问题了，无法翻译
![image](https://github.com/dmMaze/BallonsTranslator/assets/153535038/ac55cbd1-180c-4a5e-90ee-607ad8ccc4d7)
不知道为何会连上openai,总之我无法ballon无法和Sakura链接

**Comment by dmMaze** [comment]
你自己 url 和 token 没贴错吧
贴下完整启动 log

**Comment by Raiter123** [comment]
> 你自己 url 和 token 没贴错吧 贴下完整启动 log

這個嗎
![image](https://github.com/dmMaze/BallonsTranslator/assets/153535038/2d8511f6-a48d-4346-b911-fbfe82be4204)

還是這個？
![image](https://github.com/dmMaze/BallonsTranslator/assets/153535038/5091ee10-f414-4101-a5ab-1160709a0a9f)

**Comment by Raiter123** [comment]
,等下，解决了吗？

**Comment by galickery** [comment]
Even with your fix #424, the same error is still occurring for me. Error message: "Sakura server error. Returning original text".

**Comment by dmMaze** [comment]
@galickery Can you confirm whether 00e4c9f143971b8541eb54050a620a9a0a53678a is working
