### ISSUE TITLE
翻譯中一半時卡著

### ISSUE THREAD

**Issue by Raiter123** [dmMaze/BallonsTranslator#425]
用Sakura翻译到一半是卡着，然后log里出现重复的码，请问这是正常的吗，之前好像沒方式過
![image](https://github.com/dmMaze/BallonsTranslator/assets/153535038/711d6903-3e52-431e-94ea-c08586e0208c)

还是我的设定有问题呢
![image](https://github.com/dmMaze/BallonsTranslator/assets/153535038/0893fc76-bbd5-408b-b362-b3a7fdd35bb9)

还有我发现在正常运行时如果把加载栏关掉后软件还是在运行的，虽然关掉加载栏后我可以编辑图片但是当软件完成运行下一页时会强制跳页，如果软件本来就卡着就没有这个问题

还有希望可以增加可以在指定页数内运行的功能，比如只運行第15頁到30頁

**Comment by dmMaze** [comment]
第一张图从 traceback 开始贴完整

**Comment by Raiter123** [comment]
> 第一张图从 traceback 开始贴完整

這樣？
![image](https://github.com/dmMaze/BallonsTranslator/assets/153535038/da73379a-f746-49f5-ac0b-8955a062aaad)

**Comment by dmMaze** [comment]
@Raiter123  我是说像第一张图那样，你卡住的时候命令行下面有打印 Traceback，把那个完整的 log 复制或者截图贴上来

**Comment by Raiter123** [comment]
這樣？

![image](https://github.com/dmMaze/BallonsTranslator/assets/153535038/6541d688-391c-4703-88a8-db7f53cbdf81)

**Comment by dmMaze** [comment]
你是不是按了 Ctrl+C 才卡住的

**Comment by Raiter123** [comment]
沒有沒有，現在那一頁保持日文的狀態，目前可以我用“翻譯本頁”一頁一頁翻譯，拿一頁雖然發現不會卡住但是會運行很久然後會翻譯失敗還原成日語

**Comment by Raiter123** [comment]
> 你是不是按了 Ctrl+C 才卡住的

沒有沒有，現在那一頁保持日文的狀態，目前可以我跳過那一頁用“翻譯本頁”一頁一頁翻譯，拿一頁雖然發現不會卡住但是會運行很久然後會翻譯失敗還原成日語

**Comment by 2394079412** [comment]
我用Sakura翻译也差不多有这个情况，我一直觉得是我vpn的问题，只要一波动，基本上那页就翻译不出来了

**Comment by 2394079412** [comment]
![image](https://github.com/dmMaze/BallonsTranslator/assets/163848426/8e803030-64b9-450a-ba9d-96ef98517edc)

**Comment by 2394079412** [comment]
![image](https://github.com/dmMaze/BallonsTranslator/assets/163848426/4a0126b1-ebdb-41ee-8f80-26354588a885)
chabud
差不多都是这个样子，然后下面有极低的几率翻译成功，大概率翻译失败原文覆盖

**Comment by 2394079412** [comment]
![image](https://github.com/dmMaze/BallonsTranslator/assets/163848426/67913229-0b4b-4d2c-8b10-468bae05a4bd)
差不多都是这个样子，然后下面有极低的几率翻译成功，大概率翻译失败原文覆盖

**Comment by 2394079412** [comment]
![image](https://github.com/dmMaze/BallonsTranslator/assets/163848426/ffc83e9a-aa08-48ff-8668-0a02c2afef96)
差不多都是这个样子

**Comment by Raiter123** [comment]
> 我用Sakura翻译也差不多有这个情况，我一直觉得是我vpn的问题，只要一波动，基本上那页就翻译不出来了

你的sakura 不是自己连接自己电脑多的吗？

**Comment by Raiter123** [comment]
> 我用Sakura翻译也差不多有这个情况，我一直觉得是我vpn的问题，只要一波动，基本上那页就翻译不出来了
我的也是，有時候會卡的很多次
![image](https://github.com/dmMaze/BallonsTranslator/assets/153535038/9a38a320-ced3-43a1-bfe5-c585e6784862)
