### ISSUE TITLE
TGW read time out

### ISSUE THREAD

**Issue by paul0728** [dmMaze/BallonsTranslator#429]
我使用text-generation-webui並且使用sakura-13b-lnovel-v0.9-Q4_K_M.gguf 模型,但會產生以下錯誤訊息
![螢幕擷取畫面 2024-04-10 200946](https://github.com/dmMaze/BallonsTranslator/assets/44644609/b0645009-a106-4dcb-8da8-7247de5f5c6e)

Traceback (most recent call last):
  File "C:\Users\paul\.conda\envs\translator\lib\site-packages\urllib3\connectionpool.py", line 426, in _make_request
    six.raise_from(e, None)
  File "<string>", line 3, in raise_from
  File "C:\Users\paul\.conda\envs\translator\lib\site-packages\urllib3\connectionpool.py", line 421, in _make_request
    httplib_response = conn.getresponse()
  File "C:\Users\paul\.conda\envs\translator\lib\http\client.py", line 1375, in getresponse
    response.begin()
  File "C:\Users\paul\.conda\envs\translator\lib\http\client.py", line 318, in begin
    version, status, reason = self._read_status()
  File "C:\Users\paul\.conda\envs\translator\lib\http\client.py", line 279, in _read_status
    line = str(self.fp.readline(_MAXLINE + 1), "iso-8859-1")
  File "C:\Users\paul\.conda\envs\translator\lib\socket.py", line 705, in readinto
    return self._sock.recv_into(b)
TimeoutError: timed out

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\paul\.conda\envs\translator\lib\site-packages\requests\adapters.py", line 486, in send
    resp = conn.urlopen(
  File "C:\Users\paul\.conda\envs\translator\lib\site-packages\urllib3\connectionpool.py", line 726, in urlopen
    retries = retries.increment(
  File "C:\Users\paul\.conda\envs\translator\lib\site-packages\urllib3\util\retry.py", line 410, in increment
    raise six.reraise(type(error), error, _stacktrace)
  File "C:\Users\paul\.conda\envs\translator\lib\site-packages\urllib3\packages\six.py", line 735, in reraise
    raise value
  File "C:\Users\paul\.conda\envs\translator\lib\site-packages\urllib3\connectionpool.py", line 670, in urlopen
    httplib_response = self._make_request(
  File "C:\Users\paul\.conda\envs\translator\lib\site-packages\urllib3\connectionpool.py", line 428, in _make_request
    self._raise_timeout(err=e, url=url, timeout_value=read_timeout)
  File "C:\Users\paul\.conda\envs\translator\lib\site-packages\urllib3\connectionpool.py", line 335, in _raise_timeout
    raise ReadTimeoutError(
urllib3.exceptions.ReadTimeoutError: HTTPConnectionPool(host='127.0.0.1', port=5000): Read timed out. (read timeout=30)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\translator\BallonsTranslator_dev_src_with_gitpython\ui\module_manager.py", line 203, in _translate_page
    self.translator.translate_textblk_lst(page)
  File "C:\translator\BallonsTranslator_dev_src_with_gitpython\modules\translators\base.py", line 199, in translate_textblk_lst
    _translations = self.translate(text_list)
  File "C:\translator\BallonsTranslator_dev_src_with_gitpython\modules\translators\base.py", line 146, in translate
    text_trans = self._translate(text_source)
  File "C:\translator\BallonsTranslator_dev_src_with_gitpython\modules\translators\trans_tgw.py", line 138, in _translate
    response = requests.post(url, timeout=self.params['timeout'], json=payload, headers=headers)
  File "C:\Users\paul\.conda\envs\translator\lib\site-packages\requests\api.py", line 115, in post
    return request("post", url, data=data, json=json, **kwargs)
  File "C:\Users\paul\.conda\envs\translator\lib\site-packages\requests\api.py", line 59, in request
    return session.request(method=method, url=url, **kwargs)
  File "C:\Users\paul\.conda\envs\translator\lib\site-packages\requests\sessions.py", line 589, in request
    resp = self.send(prep, **send_kwargs)
  File "C:\Users\paul\.conda\envs\translator\lib\site-packages\requests\sessions.py", line 703, in send
    r = adapter.send(request, **kwargs)
  File "C:\Users\paul\.conda\envs\translator\lib\site-packages\requests\adapters.py", line 532, in send
    raise ReadTimeout(e, request=request)
requests.exceptions.ReadTimeout: HTTPConnectionPool(host='127.0.0.1', port=5000): Read timed out. (read timeout=30)

同樣的模型我拿去翻譯遊戲沒有問題但是用在這裡會報錯
希望作者大大能幫忙解決一下謝謝~

**Comment by dmMaze** [comment]
建议直接 Translator 选 Sakura

**Comment by paul0728** [comment]
> 建议直接 Translator 选 Sakura
好的謝謝!

**Comment by bropines** [comment]
> 我使用text-generation-webui並且使用sakura-13b-lnovel-v0.9-Q4_K_M.gguf 模型,但會產生以下錯誤訊息 ![螢幕擷取畫面 2024-04-10 200946](https://private-user-images.githubusercontent.com/44644609/321232599-b0645009-a106-4dcb-8da8-7247de5f5c6e.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTU3MTEwNTYsIm5iZiI6MTcxNTcxMDc1NiwicGF0aCI6Ii80NDY0NDYwOS8zMjEyMzI1OTktYjA2NDUwMDktYTEwNi00ZGNiLThkYTgtNzI0N2RlNWY1YzZlLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA1MTQlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNTE0VDE4MTkxNlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTE2N2ExZTAyYzc1MjdlMGE3NjJjZjY0YzcyM2U2YjllMWFiYjI2ODkyOGQ4MjY0MTkxYTNiZmYwZDM3ODkyN2QmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.ssupVVu24HY9znc1cT2aAfE5zd8J-BZx3BdgxlqhMVg)
> 
> Traceback (most recent call last): File "C:\Users\paul.conda\envs\translator\lib\site-packages\urllib3\connectionpool.py", line 426, in _make_request six.raise_from(e, None) File "", line 3, in raise_from File "C:\Users\paul.conda\envs\translator\lib\site-packages\urllib3\connectionpool.py", line 421, in _make_request httplib_response = conn.getresponse() File "C:\Users\paul.conda\envs\translator\lib\http\client.py", line 1375, in getresponse response.begin() File "C:\Users\paul.conda\envs\translator\lib\http\client.py", line 318, in begin version, status, reason = self._read_status() File "C:\Users\paul.conda\envs\translator\lib\http\client.py", line 279, in _read_status line = str(self.fp.readline(_MAXLINE + 1), "iso-8859-1") File "C:\Users\paul.conda\envs\translator\lib\socket.py", line 705, in readinto return self._sock.recv_into(b) TimeoutError: timed out
> 
> During handling of the above exception, another exception occurred:
> 
> Traceback (most recent call last): File "C:\Users\paul.conda\envs\translator\lib\site-packages\requests\adapters.py", line 486, in send resp = conn.urlopen( File "C:\Users\paul.conda\envs\translator\lib\site-packages\urllib3\connectionpool.py", line 726, in urlopen retries = retries.increment( File "C:\Users\paul.conda\envs\translator\lib\site-packages\urllib3\util\retry.py", line 410, in increment raise six.reraise(type(error), error, _stacktrace) File "C:\Users\paul.conda\envs\translator\lib\site-packages\urllib3\packages\six.py", line 735, in reraise raise value File "C:\Users\paul.conda\envs\translator\lib\site-packages\urllib3\connectionpool.py", line 670, in urlopen httplib_response = self._make_request( File "C:\Users\paul.conda\envs\translator\lib\site-packages\urllib3\connectionpool.py", line 428, in _make_request self._raise_timeout(err=e, url=url, timeout_value=read_timeout) File "C:\Users\paul.conda\envs\translator\lib\site-packages\urllib3\connectionpool.py", line 335, in _raise_timeout raise ReadTimeoutError( urllib3.exceptions.ReadTimeoutError: HTTPConnectionPool(host='127.0.0.1', port=5000): Read timed out. (read timeout=30)
> 
> During handling of the above exception, another exception occurred:
> 
> Traceback (most recent call last): File "C:\translator\BallonsTranslator_dev_src_with_gitpython\ui\module_manager.py", line 203, in _translate_page self.translator.translate_textblk_lst(page) File "C:\translator\BallonsTranslator_dev_src_with_gitpython\modules\translators\base.py", line 199, in translate_textblk_lst _translations = self.translate(text_list) File "C:\translator\BallonsTranslator_dev_src_with_gitpython\modules\translators\base.py", line 146, in translate text_trans = self._translate(text_source) File "C:\translator\BallonsTranslator_dev_src_with_gitpython\modules\translators\trans_tgw.py", line 138, in _translate response = requests.post(url, timeout=self.params['timeout'], json=payload, headers=headers) File "C:\Users\paul.conda\envs\translator\lib\site-packages\requests\api.py", line 115, in post return request("post", url, data=data, json=json, **kwargs) File "C:\Users\paul.conda\envs\translator\lib\site-packages\requests\api.py", line 59, in request return session.request(method=method, url=url, **kwargs) File "C:\Users\paul.conda\envs\translator\lib\site-packages\requests\sessions.py", line 589, in request resp = self.send(prep, **send_kwargs) File "C:\Users\paul.conda\envs\translator\lib\site-packages\requests\sessions.py", line 703, in send r = adapter.send(request, **kwargs) File "C:\Users\paul.conda\envs\translator\lib\site-packages\requests\adapters.py", line 532, in send raise ReadTimeout(e, request=request) requests.exceptions.ReadTimeout: HTTPConnectionPool(host='127.0.0.1', port=5000): Read timed out. (read timeout=30)
> 
> 同樣的模型我拿去翻譯遊戲沒有問題但是用在這裡會報錯 希望作者大大能幫忙解決一下謝謝~

Do you happen to have VPN or proxy enabled? I'll install the TGW now and check, but it will take a little time.

**Comment by paul0728** [comment]
> > 我使用text-generation-webui並且使用sakura-13b-lnovel-v0.9-Q4_K_M.gguf 模型,但會產生以下錯誤訊息 ![螢幕擷取畫面 2024-04-10 200946](https://private-user-images.githubusercontent.com/44644609/321232599-b0645009-a106-4dcb-8da8-7247de5f5c6e.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTU3MTEwNTYsIm5iZiI6MTcxNTcxMDc1NiwicGF0aCI6Ii80NDY0NDYwOS8zMjEyMzI1OTktYjA2NDUwMDktYTEwNi00ZGNiLThkYTgtNzI0N2RlNWY1YzZlLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA1MTQlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNTE0VDE4MTkxNlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTE2N2ExZTAyYzc1MjdlMGE3NjJjZjY0YzcyM2U2YjllMWFiYjI2ODkyOGQ4MjY0MTkxYTNiZmYwZDM3ODkyN2QmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.ssupVVu24HY9znc1cT2aAfE5zd8J-BZx3BdgxlqhMVg)
> > Traceback (most recent call last): File "C:\Users\paul.conda\envs\translator\lib\site-packages\urllib3\connectionpool.py", line 426, in _make_request six.raise_from(e, None) File "", line 3, in raise_from File "C:\Users\paul.conda\envs\translator\lib\site-packages\urllib3\connectionpool.py", line 421, in _make_request httplib_response = conn.getresponse() File "C:\Users\paul.conda\envs\translator\lib\http\client.py", line 1375, in getresponse response.begin() File "C:\Users\paul.conda\envs\translator\lib\http\client.py", line 318, in begin version, status, reason = self._read_status() File "C:\Users\paul.conda\envs\translator\lib\http\client.py", line 279, in _read_status line = str(self.fp.readline(_MAXLINE + 1), "iso-8859-1") File "C:\Users\paul.conda\envs\translator\lib\socket.py", line 705, in readinto return self._sock.recv_into(b) TimeoutError: timed out
> > During handling of the above exception, another exception occurred:
> > Traceback (most recent call last): File "C:\Users\paul.conda\envs\translator\lib\site-packages\requests\adapters.py", line 486, in send resp = conn.urlopen( File "C:\Users\paul.conda\envs\translator\lib\site-packages\urllib3\connectionpool.py", line 726, in urlopen retries = retries.increment( File "C:\Users\paul.conda\envs\translator\lib\site-packages\urllib3\util\retry.py", line 410, in increment raise six.reraise(type(error), error, _stacktrace) File "C:\Users\paul.conda\envs\translator\lib\site-packages\urllib3\packages\six.py", line 735, in reraise raise value File "C:\Users\paul.conda\envs\translator\lib\site-packages\urllib3\connectionpool.py", line 670, in urlopen httplib_response = self._make_request( File "C:\Users\paul.conda\envs\translator\lib\site-packages\urllib3\connectionpool.py", line 428, in _make_request self._raise_timeout(err=e, url=url, timeout_value=read_timeout) File "C:\Users\paul.conda\envs\translator\lib\site-packages\urllib3\connectionpool.py", line 335, in _raise_timeout raise ReadTimeoutError( urllib3.exceptions.ReadTimeoutError: HTTPConnectionPool(host='127.0.0.1', port=5000): Read timed out. (read timeout=30)
> > During handling of the above exception, another exception occurred:
> > Traceback (most recent call last): File "C:\translator\BallonsTranslator_dev_src_with_gitpython\ui\module_manager.py", line 203, in _translate_page self.translator.translate_textblk_lst(page) File "C:\translator\BallonsTranslator_dev_src_with_gitpython\modules\translators\base.py", line 199, in translate_textblk_lst _translations = self.translate(text_list) File "C:\translator\BallonsTranslator_dev_src_with_gitpython\modules\translators\base.py", line 146, in translate text_trans = self._translate(text_source) File "C:\translator\BallonsTranslator_dev_src_with_gitpython\modules\translators\trans_tgw.py", line 138, in _translate response = requests.post(url, timeout=self.params['timeout'], json=payload, headers=headers) File "C:\Users\paul.conda\envs\translator\lib\site-packages\requests\api.py", line 115, in post return request("post", url, data=data, json=json, **kwargs) File "C:\Users\paul.conda\envs\translator\lib\site-packages\requests\api.py", line 59, in request return session.request(method=method, url=url, **kwargs) File "C:\Users\paul.conda\envs\translator\lib\site-packages\requests\sessions.py", line 589, in request resp = self.send(prep, **send_kwargs) File "C:\Users\paul.conda\envs\translator\lib\site-packages\requests\sessions.py", line 703, in send r = adapter.send(request, **kwargs) File "C:\Users\paul.conda\envs\translator\lib\site-packages\requests\adapters.py", line 532, in send raise ReadTimeout(e, request=request) requests.exceptions.ReadTimeout: HTTPConnectionPool(host='127.0.0.1', port=5000): Read timed out. (read timeout=30)
> > 同樣的模型我拿去翻譯遊戲沒有問題但是用在這裡會報錯 希望作者大大能幫忙解決一下謝謝~
> 
> Do you happen to have VPN or proxy enabled? I'll install the TGW now and check, but it will take a little time.

NO. I didn't use VPN or proxy
