### ISSUE TITLE
A small addition to the interface of the text block editor

### ISSUE THREAD

**Issue by bropines** [dmMaze/BallonsTranslator#43]
To begin with, there is no way to copy existing text blocks to the clipboard. 
I did a little design of how it might look in the interface. Plus I added dragging the order of the blocks (I'm missing that)

| Enabled checkbox | Disabled checkbox |
:-------------------------:|:-------------------------:
![Frame 34](https://user-images.githubusercontent.com/57861007/190833676-d3258103-437a-4590-95f9-ec852831f47c.png)  | ![Frame 34 (1)](https://user-images.githubusercontent.com/57861007/190833671-6e02240b-79b8-4eb1-bd27-a739b917e988.png)

You can also do when inserting text Ctrl+V, a text block was created with text inserted into it from the clipboard.

https://www.figma.com/file/sxMxIJnU30vwtoJFjOYsvg/Test
Link to figma (icons)

**Comment by bropines** [comment]
Update figma design)

**Comment by dmMaze** [comment]
what does the checkbox do? it suggests this text has been translated and revised?

**Comment by bropines** [comment]
This checkbox allows you to select multiple blocks. (I just don't know how else to show that this block was selected for something)

**Comment by bropines** [comment]
I can just explain everything with a screenshot with arrows)
