### ISSUE TITLE
第六步脚本的链接显示404

### ISSUE THREAD

**Issue by ok-y** [dmMaze/BallonsTranslator#437]
https://raw.githubusercontent.com/dmMaze/BallonsTranslator/dev/scripts/macos-build-script.sh
<img width="921" alt="截屏2024-04-17 18 58 09" src="https://github.com/dmMaze/BallonsTranslator/assets/90232106/f87668c7-71b0-4c99-9edb-881439457cf9">

**Comment by dmMaze** [comment]
不知道什么时候改成了 https://github.com/dmMaze/BallonsTranslator/blob/dev/scripts/macos-build-script-arm64.sh

@hyrulelinks 另外我看这个脚本内容和 readme 里的步骤有部分是重合的，比如下载模型哈希校对实际上第一次运行是会做的，脚本另外下载有什么必要吗

**Comment by hyrulelinks** [comment]
源头上来说，主要是不知道什么原因，运行python主程序自行下载模型虽然速度顶格，但总是会失败报错，无法下载成功，非常磨人，最后只能从错误信息中提取下载链接到浏览器下载，然后按照错误信息提示放到正确的路径下，可能python下载的模块需要更新或替换成其他更好的软件包来解决下载的问题

**Comment by hyrulelinks** [comment]
这两天比较忙，我空点重新写过这个脚本

**Comment by hyrulelinks** [comment]
已更新readme，不需要脚本了，按照步骤打包APP即可，建议close该议题
