### ISSUE TITLE
無法運行

### ISSUE THREAD

**Issue by uramungai** [dmMaze/BallonsTranslator#442]
G:\BallonsTranslator>cd G:\BallonsTranslator\
py version:  3.10.11 (tags/v3.10.11:7d4cc5a, Apr  5 2023, 00:38:17) [MSC v.1929 64 bit (AMD64)]
py executable:  G:\Python310\python.exe
version: 1.4.0
branch: dev
Commit hash: 26efe38e97596056d25f73eabf2342db73417728
[INFO   ] config:load_config:188 - G:\BallonsTranslator\config/config.json does not exist, new config file will be created.
Traceback (most recent call last):
  File "G:\BallonsTranslator\launch.py", line 285, in <module>
    main()
  File "G:\BallonsTranslator\launch.py", line 174, in main
    from qtpy.QtWidgets import QApplication
  File "G:\Python310\lib\site-packages\qtpy\QtWidgets.py", line 38, in <module>
    from PyQt6 import QtWidgets
ImportError: DLL load failed while importing QtGui: 找不到指定的程序。
[INFO   ] utils:dump_compile_times:320 - TorchDynamo compilation metrics:
Function, Runtimes (s)
[INFO   ] utils:dump_compile_times:320 - TorchDynamo compilation metrics:
Function, Runtimes (s)
I0426 06:20:11.278000 13928 torch\_dynamo\utils.py:320] TorchDynamo compilation metrics:
I0426 06:20:11.278000 13928 torch\_dynamo\utils.py:320] Function, Runtimes (s)
請按任意鍵繼續 . . .

-----------------------------------------------------------------------
不管是運行BallonsTranslator_dev_src_with_gitpython.7z
還是手動解壓縮的，點了launch_win.bat後都是一樣的情況

**Comment by dmMaze** [comment]
试试 
pip install PyQt6==6.6.1 PyQt6-Qt6==6.6.2

**Comment by uramungai** [comment]
謝謝作者...自己不知道怎麼弄的，可以運行了。用的不是MEGA的檔案，是發行區那的BallonsTranslator-1.4.0.zip
中途自己做過的變更: pip uninstall了PyQt6==6.6.1 PyQt6-Qt6==6.6.2，重新pip install PyQt6==6.6.1 PyQt6-Qt6==6.6.1。
BallonsTranslator-1.4.0裡的launch_win.bat展開時看見PyQt6與PyQt6-Qt6有自動安裝成6.6.2。

**Comment by dmMaze** [comment]
> py executable: G:\BallonsTranslator_dev_src_with_gitpython\ballontrans_pylibs_win\python.exe

第二条 log 这里显示的是调用的 ballontrans_pylibs_win 下面的 python, 而 pip install 应该装到了第一条 log 显示的  G:\Python310 下面，所以你可以直接把 ballontrans_pylibs_win 删掉试试
另外 release 页面那个包其实有点老了，不如直接下载现在的源码

**Comment by uramungai** [comment]
> > py executable: G:\BallonsTranslator_dev_src_with_gitpython\ballontrans_pylibs_win\python.exe
> 
> 第二条 log 这里显示的是调用的 ballontrans_pylibs_win 下面的 python, 而 pip install 应该装到了第一条 log 显示的 G:\Python310 下面，所以你可以直接把 ballontrans_pylibs_win 删掉试试 另外 release 页面那个包其实有点老了，不如直接下载现在的源码

對，刪除ballontrans_pylibs_win資料夾後最新版的也可以運行了，十分感謝
