### ISSUE TITLE
关于气泡排序功能的的提议

### ISSUE THREAD

**Issue by lie245407163** [dmMaze/BallonsTranslator#445]
![image](https://github.com/dmMaze/BallonsTranslator/assets/75011081/34cf0be8-68f6-4472-a340-1f02a0c8c5e3)
正常来说，应该是摁W激活文本块创建模式，长摁文本编辑框大概是序号的下方，可以实现拖动文本编辑框从而实现气泡排序功能。
但不知道为什么，有时候会失灵？
也不算失灵，我一般是开关t和w多次后才能使用此功能。
可能是因为我直接切换图片并没有关闭T和W导致此功能使用失灵？
希望能修改此功能的方式，如可以直接编辑文本编辑框前的序号来实现气泡排序功能；
或者告知一下如何能正确正常的开启此功能的方式。

**Comment by lie245407163** [comment]
好像不开W也可以进行排序，但还是有不响应的问题存在。等一段事件后才能使用排序...

**Comment by lie245407163** [comment]
经过反复的测试，发现一个解决方法：
稍微拉伸变形一下图片上的任意一个文本框，然后就可以拖动右侧的文本编辑框进行排序了...

**Comment by dmMaze** [comment]
选中了后在拖拽试试

**Comment by lie245407163** [comment]
问题是我切换新的图片，不进行任何操作，直接点击文本编辑框(右边的那列文本框)并不能拖拽它进行排序。
我之前也尝试对里面的文字进行增删操作，发现并不能确保一定奏效。
而且新打开程序自动打开的项目是可以对当前页面的文本框进行拖拽排序，但切换图片后又失灵了。

感觉是我只有对这个文本编辑框所对应图片上的进行变形操作，程序才能判定我真正选中了它。
其他进行的操作程序并不能及时判定我选中那个文本编辑框。。。

**Comment by dmMaze** [comment]
> 问题是我切换新的图片，不进行任何操作，直接点击文本编辑框(右边的那列文本框)并不能拖拽它进行排序。

选中状态下也不能拖拽吗？你是啥系统

**Comment by dmMaze** [comment]
现在能编辑了，拖拽应该也修好了
