### ISSUE TITLE
替换机翻/ocr结果中的关键字没有效果耶

### ISSUE THREAD

**Issue by 2394079412** [dmMaze/BallonsTranslator#451]
![FX(RV9QBMD883BL6T9U 8OB](https://github.com/dmMaze/BallonsTranslator/assets/163848426/2c81e1d6-5eb3-4619-bd28-dd608424dc95)
有时候系统会把一条一条的马赛克识别成单个英文字母比如H，我想让他识别到了的时候直接清空掉，这个样子好像不行诶，正常按运行翻译是不会改的，需要一条一条的点进去再按对应的翻译才会清空，这个是bug还是原本就不支持呢，有点麻烦

**Comment by dmMaze** [comment]
你改了这个重跑 OCR 了吗

**Comment by 2394079412** [comment]
> > > 你修改了这个重跑 OCR 了吗
> > 
> > 
> > 我把大写小写英文字母全部单独交换去，ocr是可以了，替换机翻的还是不行，替换关键字中文换中文可以，英文字母换空白没效果，用谷歌翻译和樱花ocr用的话日译中倒是可以了，英译中就用不了了
> 
> 我尝试一下还是可以啊，你是最新版吗
> 
> 另外如果是替换字母可以写正则使用一个输出： <img alt="截屏2024-05-07 23 09 47" width="698" src="https://private-user-images.githubusercontent.com/51270320/328577119-132f3fb0-4634-431a-888b-390a090c5992.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTUwOTUzNDgsIm5iZiI6MTcxNTA5NTA0OCwicGF0aCI6Ii81MTI3MDMyMC8zMjg1NzcxMTktMTMyZjNmYjAtNDYzNC00MzFhLTg4OGItMzkwYTA5MGM1OTkyLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA1MDclMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNTA3VDE1MTcyOFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTIwNDI2NzRiYmY1NjkyODI2MDczNGQ0OTIzNmM4MDViOTE2NzQxZjkxYTIyYTQ1M2E4OTcxMDUyZTNiYTgwYjMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.SvmUo10kON6rj0fklyIFeJ4eiFJ6mO-zvldh2NcKKaQ">

用你这个就可以了，感谢大佬救我狗命啊，几千张图一张一张马赛克识别出的英文实在是太辛苦了，这就好了

**Comment by 2394079412** [comment]
> > > 你修改了这个重跑 OCR 了吗
> > 
> > 
> > 我把大写小写英文字母全部单独放进去，ocr是可以了，但是替换机翻的还是不行，替换关键字中文换中文可以，英文字母换空白没效果，用的Google翻译和sakura ocr可以用的话日译中倒是可以了，英译中就用不了了
> 
> 我试了一下还是可以啊，你是最新版吗
> 
> 另外如果是替换字母可以写正则不用一个个输： <img alt="截屏2024-05-07 23 09 47" width="698" src="https://private-user-images.githubusercontent.com/51270320/328577119-132f3fb0-4634-431a-888b-390a090c5992.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTUxMjg2OTEsIm5iZiI6MTcxNTEyODM5MSwicGF0aCI6Ii81MTI3MDMyMC8zMjg1NzcxMTktMTMyZjNmYjAtNDYzNC00MzFhLTg4OGItMzkwYTA5MGM1OTkyLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA1MDglMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNTA4VDAwMzMxMVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTc3ZjU0YjY4MzI3NTMyODI0ZTJjNzFkMzlkYzE4YTliZWMyYzE4OTVhYWNhYjAxYTBlMjFhMzdhMzQ4NmQxZGQmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.hCSjLDfZRrlOXf-F_2tXkO1B4AdtwCj3Y5YHMqJIdUQ">

我又尝试了一下，google里韩译中没法使用，有些画师的作品包含韩语和英文，刚好google选择韩语翻译也包含了英文翻译，这个时候选韩译中就没有用了，只能用在英译中

**Comment by dmMaze** [comment]
> 我又尝试了一下，google里韩译中没法使用，有些画师的作品包含韩语和英文，刚好google选择韩语翻译也包含了英文翻译，这个时候选韩译中就没有用了，只能用在英译中

你看下翻译结果英文字符是全角的吗

**Comment by 2394079412** [comment]
> > 我又尝试了一下，google里韩译中不能用，有些画师的作品包含韩语和英文，正好google选择韩语翻译也包含了英文翻译，这个时候选韩译中就没有用了，只能用在英译中
> 
> 你看下翻译结果英文字符是全角的吗

我不太清楚您说的这个意思是什么，但是他翻译完是这个样子的，我选的韩译中
![image](https://github.com/dmMaze/BallonsTranslator/assets/163848426/97a6e9fb-d11f-4336-9974-d0aee2b5eb48)
![image](https://github.com/dmMaze/BallonsTranslator/assets/163848426/38f044b4-94c2-4b3c-8dc1-df5f15e0038e)

**Comment by dmMaze** [comment]
> > > 我又尝试了一下，google里韩译中不能用，有些画师的作品包含韩语和英文，正好google选择韩语翻译也包含了英文翻译，这个时候选韩译中就没有用了，只能用在英译中
> > 
> > 
> > 你看下翻译结果英文字符是全角的吗
> 
> 我不太清楚您说的这个意思是什么，但是他翻译完是这个样子的，我选的韩译中 ![image](https://private-user-images.githubusercontent.com/163848426/329131959-97a6e9fb-d11f-4336-9974-d0aee2b5eb48.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTUyNzIyNTksIm5iZiI6MTcxNTI3MTk1OSwicGF0aCI6Ii8xNjM4NDg0MjYvMzI5MTMxOTU5LTk3YTZlOWZiLWQxMWYtNDMzNi05OTc0LWQwYWVlMmI1ZWI0OC5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNTA5JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDUwOVQxNjI1NTlaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT00NTkxMjZlZWRhYzAyMDAyNGE4YzUyYjA0ODVjMjMxMDQ5NmI0Y2E5YzZkY2YwOGI3NzY0MDJmNDQzYTA3MTljJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.s6RuDrdYMo9Sjh02eza9udWrAyeTEPrcaLuLbIZQz00) ![image](https://private-user-images.githubusercontent.com/163848426/329131984-38f044b4-94c2-4b3c-8dc1-df5f15e0038e.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTUyNzIyNTksIm5iZiI6MTcxNTI3MTk1OSwicGF0aCI6Ii8xNjM4NDg0MjYvMzI5MTMxOTg0LTM4ZjA0NGI0LTk0YzItNGIzYy04ZGMxLWRmNWYxNWUwMDM4ZS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNTA5JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDUwOVQxNjI1NTlaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT01MzNlNjI2YTMxZWQ3NDQ3YzQxYzQ0MWMwZjI3Y2RiOTRkNWM5ZDhiODk4MzExYzM4YjY0ZDcyNjlhYTg5OTU5JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.kpD4l8qtaBWwZNboEjZ2xE4T9H9JuCzXc3vNoLa_YoI)

这就是翻译器给你转全角了,
在替换窗口再加一栏
[ａｂｃｄｅｆｇｈｉｊｋｌｍｎｏｐｑｒｓｔｕｖｗｘｙｚＡＢＣＤＥＦＧＨＩＪＫＬＭＮＯＰＱＲＳＴＵＶＷＸＹＺ]
勾上正则就行了

**Comment by 2394079412** [comment]
> > > > 我又尝试了一下，google里韩译中不能用，有些画师的作品包含韩语和英文，正好google选择韩语翻译也包含英文翻译，这个时候选韩译中就没有用了，只能用在英译中
> > > 
> > > 
> > > 你看下翻译结果英文字符是全角的吗
> > 
> > 
> > 我不太清楚你说的这个意思是什么，但是他翻译完就是这个样子的，我选的韩译中![图像](https://private-user-images.githubusercontent.com/163848426/329131959-97a6e9fb-d11f-4336-9974-d0aee2b5eb48.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTUyNzIyNTksIm5iZiI6MTcxNTI3MTk1OSwicGF0aCI6Ii8xNjM4NDg0MjYvMzI5MTMxOTU5LTk3YTZlOWZiLWQxMWYtNDMzNi05OTc0LWQwYWVlMmI1ZWI0OC5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNTA5JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDUwOVQxNjI1NTlaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT00NTkxMjZlZWRhYzAyMDAyNGE4YzUyYjA0ODVjMjMxMDQ5NmI0Y2E5YzZkY2YwOGI3NzY0MDJmNDQzYTA3MTljJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.s6RuDrdYMo9Sjh02eza9udWrAyeTEPrcaLuLbIZQz00) ![图像](https://private-user-images.githubusercontent.com/163848426/329131984-38f044b4-94c2-4b3c-8dc1-df5f15e0038e.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTUyNzIyNTksIm5iZiI6MTcxNTI3MTk1OSwicGF0aCI6Ii8xNjM4NDg0MjYvMzI5MTMxOTg0LTM4ZjA0NGI0LTk0YzItNGIzYy04ZGMxLWRmNWYxNWUwMDM4ZS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNTA5JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDUwOVQxNjI1NTlaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT01MzNlNjI2YTMxZWQ3NDQ3YzQxYzQ0MWMwZjI3Y2RiOTRkNWM5ZDhiODk4MzExYzM4YjY0ZDcyNjlhYTg5OTU5JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.kpD4l8qtaBWwZNboEjZ2xE4T9H9JuCzXc3vNoLa_YoI)
> 
> 这就是翻译器给你转全角了， 在替换窗口加上一栏 [abcdefghhiｊkklｍnopｑrstuvwoxyｚＡＢＣＤＥＦＧHIJKＬＭＮＯＰＱＲＳＴＵＶＷＸＹＺ] 勾上正则就行了

感谢大佬指点迷津
