### ISSUE TITLE
Text layer addition feature request

### ISSUE THREAD

**Issue by Horangye2** [dmMaze/BallonsTranslator#454]
When using BallonsTranslator, there are times when there is no way to add a separate text layer, so I have to switch to Photoshop to do the work.
When the text cannot be successfully recognized during the process of OCR, I have to add a separate text layer to work on it. However, BallonsTranslator does not have such a feature, causing inconvenience.
So, I would appreciate it if the text layer addition feature could be added.

**Comment by dmMaze** [comment]
Please take a look at https://github.com/dmMaze/BallonsTranslator/blob/dev/doc/src/textedit.gif
it's around end of it
