### ISSUE TITLE
重新打开程序如何让他继续下载而不是要我重新跑一边

### ISSUE THREAD

**Issue by 2394079412** [dmMaze/BallonsTranslator#455]
目前有这个功能吗，我好想没有找到耶，有时候一次性导入几千张图，一次性没翻译完的话就得把翻译完的全部移掉，每次都要这样搞非常的麻烦啊，要是运气不好一点有些图的名字是乱码，windows的按名称排序好像还和软件的不太一样，不小心崩掉的话只能全部重跑一遍了，太麻烦了。

如果有大佬知道的话麻烦给鄙人解个惑，万分感谢

**Comment by dmMaze** [comment]
参考 https://github.com/dmMaze/BallonsTranslator/issues/463#issuecomment-2119006152
