### ISSUE TITLE
买来试了一下新加的星河云（团子漫画OCR）文本检测

### ISSUE THREAD

**Issue by 2394079412** [dmMaze/BallonsTranslator#456]
![image](https://github.com/dmMaze/BallonsTranslator/assets/163848426/a1583805-0d18-4032-a7d3-3f0c59e8e2af)
这个文本检测是有最大限制的，写着是5m，实际上5-9m他是有几率接着检测的，10以上就基本上直接不行了
![image](https://github.com/dmMaze/BallonsTranslator/assets/163848426/d065eee1-c149-42eb-9dea-e60a53567f63)
而且他检测出来的文本配合sakura翻译的非常奇怪，感觉可能是有什么地方不兼容，有些句子你需要单独再点击一下翻译翻出来的才会是正常的
![image](https://github.com/dmMaze/BallonsTranslator/assets/163848426/ed4f4d45-23a4-464f-9b0b-25d9984385a8)
而且很喜欢用这个
![image](https://github.com/dmMaze/BallonsTranslator/assets/163848426/6da2938f-2c12-44e1-9a5e-bdffabfa790e)
并且速度非常慢，跟性能好像没有什么关系应该是要上传服务器等响应

可能是目前还有bug，感觉绝大多数情况下都不如原本的ctd，而且还只能翻译5m以下的，基本上fanbox和patreon上的画师原图都比这个大，翻译不了

文本检测倒是比ctd好不少，他会比ctd检测的全一些，但是就目前的情况好像你只能先单独选择文本检测，全搞完了然后再选择ocr翻译和修复

要是只用来翻译短篇小图片倒是可以买一下

我是这么选择的不知道是不是我自己的问题
![image](https://github.com/dmMaze/BallonsTranslator/assets/163848426/d302e990-73c1-4369-a908-c2e94694eb30)

**Comment by didala083** [comment]
团子我用过几次，感觉识别率太低就放弃了

**Comment by 2394079412** [comment]
> 团子我用过几次，感觉识别率太低就放弃了

他能识别的确实比ctd的多，但是太慢了，而且同时用sakura翻译的话出来的东西莫名其妙

**Comment by didala083** [comment]
我是去年买来用过的，好多字都识别不出，一气之下不用了，现在有很大进步吗？

**Comment by 2394079412** [comment]
> 我是去年买来用过的，好多字都识别不出，一气之下不用了，现在有很大进步吗？

识别程度比ctd好一些但是只能5m以下的图片

**Comment by C4a15Wh** [comment]
关于识别图片大小上限的问题，已于5.17晚间的热更新调整至20M，详见：
https://www.bilibili.com/read/cv34598061

**Comment by dmMaze** [comment]
@PiDanShouRouZhouXD 你要是乐意维护这个 OCR/检测模块我可以给个仓库读写权限
其实可以设定一个最长边限制，图片尺寸超过了就按比例把长边缩到这个值，你不缩服务器终端进模型前还是会帮你缩放，返回坐标也做相应调整

**Comment by PiDanShouRouZhouXD** [comment]
> @PiDanShouRouZhouXD 你要是乐意维护这个 OCR/检测模块我可以给个仓库读写权限 其实可以设定一个最长边限制，图片尺寸超过了就按比例把长边缩到这个值，你不缩服务器终端进模型前还是会帮你缩放，返回坐标也做相应调整 或者短边，条漫最好是短边

作者最近还更新了token过期，可能确实需要更新一下了，我今天晚上看看。

**Comment by PiDanShouRouZhouXD** [comment]
> 关于识别图片大小上限的问题，已于5.17晚间的热更新调整至20M，详见： https://www.bilibili.com/read/cv34598061

请问您是团子的开发者吗？服务器实际上会把边长缩到多少以内？我照着这个改吧……

**Comment by C4a15Wh** [comment]
已于群内回复
