### ISSUE TITLE
BUG：当前页面的result图与实际图发生错位

### ISSUE THREAD

**Issue by didala083** [dmMaze/BallonsTranslator#457]
https://github.com/dmMaze/BallonsTranslator/assets/64563710/1cf57503-8d3f-4e1e-8461-6fa98d42de99

如上面录屏演示的一样，新建工程后完成OCR和部分页面的抹字和翻译后，关闭软件，再次打开后，第2张或第三张图大概率出现result图与实际文件名所对应的图片不符的情况，显示原图会发现这个显示的result图实际应该是后一张图片的。

已更新到最新开发版，之前还没有出现这个问题。

**Comment by didala083** [comment]
几乎每次都可以复现这个bug，对于页数多的漫画工程简直是灾难，一旦关软件之前做的大概率全部出问题

**Comment by dmMaze** [comment]
方便的话打包出问题的几张图传上来，发我 email 也行

**Comment by didala083** [comment]
已经打包到网盘里了，还有工程的JSON文件
[https://disk90.top/s/WA6H4](url)

**Comment by dmMaze** [comment]
@didala083 我无法复现... 就单跑这几张原图再开顺序是对的，能讲讲你具体触发 bug 步骤吗?

**Comment by dmMaze** [comment]
另外这个 bug 是概率触发的还是稳定触发的？
另外你可以尝试用
git reset --hard HEAD 回滚之前的版本，HEAD就从 https://github.com/dmMaze/BallonsTranslator/commits/dev/ 复制

![图片](https://github.com/dmMaze/BallonsTranslator/assets/51270320/4ad133c8-aca9-4946-a1a1-d9783699077d)

如果确定了是从哪个版本开始的顺便把 HEAD 告诉我一声

**Comment by dmMaze** [comment]
而且我没看懂你视频 4s 左右是怎么翻页的，快捷键？但是左边目录高亮怎么没变

**Comment by didala083** [comment]
我这边是每次都能复现的，4s那个地方不是翻页是更改图层显示，也就是说原图图层和result的图层错位了

**Comment by didala083** [comment]
好吧，我回滚一下试试

**Comment by dmMaze** [comment]
另外你开头提到的部分页面是什么意思？自己挑几页抹字翻译？

**Comment by dmMaze** [comment]
我知道了... https://github.com/dmMaze/BallonsTranslator/commit/6577793b3ec770e42a2b69f085c93deabefa8524 应该修好了
