### ISSUE TITLE
Can I limit the CPU usage?

### ISSUE THREAD

**Issue by edmar229** [dmMaze/BallonsTranslator#458]
I'm currently running in headless mode with only text detection and OCR enabled in the config.json file. However, my hardware is limited (Intel integrated graphics) and CPU usage can reach up to 80%. Is it possible to configure CPU usage limitations? I don't mind if it gets slower.

**Comment by dmMaze** [comment]
no, there's no direct in this program, you could search for some 3rd party apps

**Comment by edmar229** [comment]
Ok, thank you!
