### ISSUE TITLE
求加入最新模型GPT-4o

### ISSUE THREAD

**Issue by paul0728** [dmMaze/BallonsTranslator#459]
現在時下最新模型GPT-4o, 相比於GPT-4 Turbo，速度快了兩倍、成本以及價格為一半，而API速率限制、即用戶可發出的請求數量則提高了五倍
希望大大能將其加入

**Comment by bropines** [comment]
> 現在時下最新模型GPT-4o, 相比於GPT-4 Turbo，速度快了兩倍、成本以及價格為一半，而API速率限制、即用戶可發出的請求數量則提高了五倍
> 希望大大能將其加入

![image](https://github.com/dmMaze/BallonsTranslator/assets/57861007/3fc7a1c4-8ef1-413e-bc1a-30f2125edc97)

**Comment by lhj5426** [comment]
甚至还可以直接用claude 3 只要中转支持 OEPENAI格式的 而且大部分中转都支持CLAUD3使用 openai 格式的aip

**Comment by paul0728** [comment]
> 甚至还可以直接用claude 3 只要中转支持 OEPENAI格式的 而且大部分中转都支持CLAUD3使用 openai 格式的aip

可以請教大佬如何操作嗎?

**Comment by bropines** [comment]
> 甚至还可以直接用claude 3 只要中转支持 OEPENAI格式的 而且大部分中转都支持CLAUD3使用 openai 格式的aip

The problem is that the endpoint is not defined in the interface and it has to be defined in the program code. I can do the addition of api claude and google on condition that I will be given documentation and a paid endpoint (alas in russia we go far and long with api services).

**Comment by bropines** [comment]
> > 甚至还可以直接用claude 3 只要中转支持 OEPENAI格式的 而且大部分中转都支持CLAUD3使用 openai 格式的aip
> 
> 可以請教大佬如何操作嗎?

Purely theoretically here, but I haven't tested it to see if it works. 

![image](https://github.com/dmMaze/BallonsTranslator/assets/57861007/4e05aa18-1c1c-4d24-b24f-fd4032f8f7cb)

The service you use to access neural networks should tell you what api endpoints to use

**Comment by lhj5426** [comment]
> > 甚至还可以直接用_claude_ 3 只要中转支持 OEPENAI格式的 而且大部分中转都支持CLAUD3使用 openai 格式的aip
> 
> 可以請教大佬如何操作嗎?

图2不是给你 提示了 么自定义模型 你代理 支持 OPENAI格式 你直接写代理的模型就行了比如
直接在模型里填写 claude-3-opus-20240229 就可以用了

**Comment by bropines** [comment]
> > > 甚至还可以直接用_claude_ 3 只要中转支持 OEPENAI格式的 而且大部分中转都支持CLAUD3使用 openai 格式的aip
> > 
> > 
> > 可以請教大佬如何操作嗎?
> 
> 图2不是给你 提示了 么自定义模型 你代理 支持 OPENAI格式 你直接写代理的模型就行了比如 直接在模型里填写 claude-3-opus-20240229 就可以用了

Doesn't it need to specify a 3rd party url to work with the claude api?

**Comment by lhj5426** [comment]
> > > > 甚至还可以直接用__claude__ 3 只要中转支持 OEPENAI格式的 而且大部分中转都支持CLAUD3使用 openai 格式的aip
> > > 
> > > 
> > > 可以請教大佬如何操作嗎?
> > 
> > 
> > 图2不是给你 提示了 么自定义模型 你_代理_ 支持 OPENAI格式 你直接写_代理_的模型就行了比如 直接在模型里填写 _claude_-3-opus-20240229 就可以用了
> 
> Doesn't it need to specify a 3rd party url to work with the _claude_ api?

兼容格式的  AI中转API 是直接 兼容 claude 3的

**Comment by lhj5426** [comment]
> Well, I think you can figure it out for yourselves. If something needs to be corrected in the code in the translators, it's not hard to find me.

嗯  很早之前增加的 可以自定义模型 就可以用  所以不需要增加和改动代码 这个是 API 代理商们的问题

而且 还有题外话 GPT4O 可以直接翻译漫画
![image](https://github.com/dmMaze/BallonsTranslator/assets/30548000/da242fae-31ab-4d19-98a4-0246b0a78c7b)
虽然会串行 但是 真的可以直接 丢图片翻译漫画!!!!

**Comment by paul0728** [comment]
> > > 甚至还可以直接用_claude_ 3 只要中转支持 OEPENAI格式的 而且大部分中转都支持CLAUD3使用 openai 格式的aip
> > 
> > 
> > 可以請教大佬如何操作嗎?
> 
> 图2不是给你 提示了 么自定义模型 你代理 支持 OPENAI格式 你直接写代理的模型就行了比如 直接在模型里填写 claude-3-opus-20240229 就可以用了

了解!順便好奇請問一下,他跟chatgpt翻譯效果比較起來您覺得哪個好?

**Comment by lhj5426** [comment]
> > > > 甚至还可以直接用__claude__ 3 只要中转支持 OEPENAI格式的 而且大部分中转都支持CLAUD3使用 openai 格式的aip
> > > 
> > > 
> > > 可以請教大佬如何操作嗎?
> > 
> > 
> > 图2不是给你 提示了 么自定义模型 你_代理_ 支持 OPENAI格式 你直接写_代理_的模型就行了比如 直接在模型里填写 _claude_-3-opus-20240229 就可以用了
> 
> 了解!順便好奇請問一下,他跟_chatgpt_翻譯效果比較起來您覺得哪個好?

我全都都用 我每个AI都会翻译一边然后放在一起 对比 润色

**Comment by paul0728** [comment]
@bropines 
Although it's not related to this issue, could you please fix the TGW usage problem?
I have posted [this issue](https://github.com/dmMaze/BallonsTranslator/issues/429) before but the problem is not solved.
If you can fix this problem, there will be many more offline models to choose from.
Thank you for your help.

**Comment by paul0728** [comment]
> > > > > 甚至还可以直接用__claude__ 3 只要中转支持 OEPENAI格式的 而且大部分中转都支持CLAUD3使用 openai 格式的aip
> > > > 
> > > > 
> > > > 可以請教大佬如何操作嗎?
> > > 
> > > 
> > > 图2不是给你 提示了 么自定义模型 你_代理_ 支持 OPENAI格式 你直接写_代理_的模型就行了比如 直接在模型里填写 _claude_-3-opus-20240229 就可以用了
> > 
> > 
> > 了解!順便好奇請問一下,他跟_chatgpt_翻譯效果比較起來您覺得哪個好?
> 
> 我全都都用 我每个AI都会翻译一边然后放在一起 对比 润色

哇是大老呀!
但我錢不夠沒辦法每個都花錢去買,所以想說問問看哪個比較推薦?
