### ISSUE TITLE
mit系列的OCR无法识别英文

### ISSUE THREAD

**Issue by QionghuaGit** [dmMaze/BallonsTranslator#460]
是设置问题吗？可是也没有语言设置呀？
![image](https://github.com/dmMaze/BallonsTranslator/assets/64454888/000abcbe-ed46-4b97-ae23-b8e19cbd1963)

**Comment by bropines** [comment]
> 是设置问题吗？可是也没有语言设置呀？ ![image](https://private-user-images.githubusercontent.com/64454888/331428691-000abcbe-ed46-4b97-ae23-b8e19cbd1963.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTU5NDQzNzYsIm5iZiI6MTcxNTk0NDA3NiwicGF0aCI6Ii82NDQ1NDg4OC8zMzE0Mjg2OTEtMDAwYWJjYmUtZWQ0Ni00Yjk3LWFlMjMtYjhlMTljYmQxOTYzLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA1MTclMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNTE3VDExMDc1NlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTFhZTJkZTAxOTAwMmY3MWJjZDU2N2VmMDRhMTJjYTI5NDVlYWY5ZGJhNzEwNjlkNTczYThjMWY4YjAzMWQ0MDAmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.M9NXnu-kvbyyZbNPVDS5krSL-0habnMnzb7sMApcMao)

- 所有 mit 模型来自 manga-image-translator，支持日英汉识别和颜色提取

**Comment by dmMaze** [comment]
我都可以啊
<img width="1350" alt="截屏2024-05-19 04 57 47" src="https://github.com/dmMaze/BallonsTranslator/assets/51270320/48c71248-88ef-48b5-8095-77ac8fb4286f">

**Comment by sqx626** [comment]
重新测试了一下，发现是单独选中文本框右键OCR的时候无法识别，即使是RUN时候能识别的再右键OCR也识别不了了；以及有的框RUN也识别不出来，比如这个：
![image](https://github.com/dmMaze/BallonsTranslator/assets/64454888/ea33ccbd-0d0d-42b3-bfe8-c7e9d92adf37)
