### ISSUE TITLE
关于星河云漫画OCR <skip> 标签的说明

### ISSUE THREAD

**Issue by C4a15Wh** [dmMaze/BallonsTranslator#462]
对于返回的text_block对象内，识别文本结果为 **\<skip\>** 的对象，表明该段文本由于一些原因（例如score过低、是拟声词），被标记用于跳过填涂和渲染了。这些文本块的蒙版部分已经在服务端进行文本识别时被自动消除，但在调用渲染时应当过滤/忽略这部分文本块。

如要识别拟声词，应将filtrate参数设为false。该接口的相关参数如下：

|参数|类型|必填|默认值|版本|说明|
|--|--|--|--|--|--|
|token|string|是| - |stream-20230716093903+|星河云Token|
|image|string|是| - |stream-20230716093903+|原始图像base64编码后的字符串|
|mask|bool|否|false|stream-20230716093903+|是否获取图像遮罩|
|refine|bool|否|true|stream-20230716093903+|是否进行遮罩增强，该选项会影响inpaint结果|
|filtrate|bool|否|true|stream-20230716093903+|是否过滤误识别的气泡字体|
|detect_scale|int|否|1|stream-20230716093903+|检测的放大倍率，计费时该接口计为detect_scale的二次方，例如detect_scale=3时，有请求1次计为9次。|
|merge_threshold|float64|否|5.0|stream-20230716093903+|定义文本框合并为文本块的距离，越小文本越能独立成块，越大文本越能合并到一起。|
|disable_skip_area|bool|否|true|stream-20230716093903+|是否在蒙版(mask)上抹除标签为\<skip\>的内容。该选项可以防止~~机霸被消除~~特殊场景下的误消除现象。|
|low_accuracy_mode|bool|否|false|stream-20230821031114+|低精度模式。该模式会主动降低缩放大小，提高识别速度，适合对手动框选文字的识别。|
|force_expand|bool|否|false|stream-20240207160110+|是否强制扩展图片像素，**会导致识别速度下降**|

**Comment by PiDanShouRouZhouXD** [comment]
这个其实已经处理过了。
https://github.com/dmMaze/BallonsTranslator/blob/6577793b3ec770e42a2b69f085c93deabefa8524/modules/textdetector/__init__.py#L267

**Comment by C4a15Wh** [comment]
好的，感谢适配。
