### ISSUE TITLE
請求增加可以選指定中間頁數開始的功能

### ISSUE THREAD

**Issue by Raiter123** [dmMaze/BallonsTranslator#463]
有時候跑到一半時不知道爲啥會停下來
但是每次重新翻譯時又會從第一頁開始
可以增加增加可以選指定中間頁數開始的功能嗎

**Comment by bropines** [comment]
Duplicate, can't remember which one)

**Comment by dmMaze** [comment]
首先你需要确保版本在 6577793b3ec770e42a2b69f085c93deabefa8524 及之后
然后退出软件，在项目目录里新建一个文件夹，把你已经翻译完的图移入这个文件夹，打开软件，跑完剩下的，退出软件，把新建文件夹里的图挪回原位置，再打开软件，所有图和文字块都会正确加载

**Comment by bropines** [comment]
> 首先你需要确保版本在 [6577793](https://github.com/dmMaze/BallonsTranslator/commit/6577793b3ec770e42a2b69f085c93deabefa8524) 及之后 然后退出软件，在项目目录里新建一个文件夹，把你不需要再翻译的 **原图** 移入这个文件夹，打开软件，跑完剩下的，退出软件，把新建文件夹里的图挪回原位置，再打开软件，所有图和文字块都会正确加载

Sounds like a very wild crutch. Although I’m already used to manually selecting text, it’s stupidly faster than fixing text detector bugs

**Comment by Raiter123** [comment]
> 退出软件，在项目目录里新建一个文件夹，把你不需要再翻译的 **原图** 移入这个文件夹，打开软件，跑完剩下的，退出软件，把新建文件夹里的图挪回原位置，再打开软件，所有图和文字块都会正确加载

原來可以這樣啊，不會出問題嗎？

**Comment by dmMaze** [comment]
> > > 退出软件，在项目目录里新建一个文件夹，把你不需要再翻译的 **原图** 移入这个文件夹，打开软件，跑完剩下的，退出软件，把新建文件夹里的图挪回原位置，再打开软件，所有图和文字块都会正确加载
> > 
> > 
> > 原來可以這樣啊，不會出問題嗎？
> 
> 對呀，而且不是應該要把第二次翻譯的.json複製回去?所有翻譯紀錄都在.json檔裡面，感覺圖複製回去應該沒有作用?沒有斷掉翻譯過不太確定。

你们自己试一下就知道了。第二次翻译的 json 文件是在第一次翻译的基础上**更新**而不是覆盖
