### ISSUE TITLE
今天更新完星河云无法启动

### ISSUE THREAD

**Issue by 2394079412** [dmMaze/BallonsTranslator#464]
刚开始想双开，发现第二个文本检测启动不了了
![image](https://github.com/dmMaze/BallonsTranslator/assets/163848426/e8e6d811-60d4-4dbf-9fb3-bf7fa1357112)
![image](https://github.com/dmMaze/BallonsTranslator/assets/163848426/e647c006-f137-4d89-a0aa-80df769940f8)
然后我不管怎么重启翻译器（单开）都会有这个提示，这个选项就再也选不了了
launch.py如果用在这个启动翻译器在文本检测选择这个ocr还会直接闪退

**Comment by dmMaze** [comment]
d171c33a96db1dba818246a2dff576bb324d379c 应该修好了
我 32g 内存双开选项可以显示啊，你不会内存炸了吧

**Comment by 2394079412** [comment]
> [d171c33](https://github.com/dmMaze/BallonsTranslator/commit/d171c33a96db1dba818246a2dff576bb324d379c) 应该修好了 我 32g 内存双开选项可以显示啊，你不会内存炸了吧

我64g的，我刚才试了一下，有了个新的更新，好了
