### ISSUE TITLE
Inpaint Segmentation fault

### ISSUE THREAD

**Issue by Samurai-Kyo** [dmMaze/BallonsTranslator#468]
Select an inpainter from the inpainter dropdown menu.
Scroll the list with your mouse wheel.
Crashes with a segmentation fault.
![image](https://github.com/dmMaze/BallonsTranslator/assets/46701588/89a70012-fc35-49fa-8e1b-861d80685c56)

**Comment by bropines** [comment]
> Select an inpainter from the inpainter dropdown menu. Scroll the list with your mouse wheel. Crashes with a segmentation fault. ![image](https://private-user-images.githubusercontent.com/46701588/334144049-89a70012-fc35-49fa-8e1b-861d80685c56.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTY4MjM1NDAsIm5iZiI6MTcxNjgyMzI0MCwicGF0aCI6Ii80NjcwMTU4OC8zMzQxNDQwNDktODlhNzAwMTItZmMzNS00OWZhLThlMWItODYxZDgwNjg1YzU2LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA1MjclMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNTI3VDE1MjA0MFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTE3NWY5MGI4ZTAwNWIyMDlmN2VmNDZjZTZjODRkZjBiN2FmNzE4ZmZiNWYwMzY4NjBmNmVjYzU1NmI3OGE5MjAmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.3MPlI_nZhEfG9t4aTcV7EBoBIKxtnZ77YZrPVsnd9gQ)

Can you send console log of this error?

**Comment by Samurai-Kyo** [comment]
[INFO   ] modeling_utils:_load_pretrained_model:3992 - All model checkpoint weights were used when initializing VisionEncoderDecoderModel.

[INFO   ] modeling_utils:_load_pretrained_model:3992 - All model checkpoint weights were used when initializing VisionEncoderDecoderModel.

All model checkpoint weights were used when initializing VisionEncoderDecoderModel.

[INFO   ] modeling_utils:_load_pretrained_model:4000 - All the weights of VisionEncoderDecoderModel were initialized from the model checkpoint at data/models/manga-ocr-base.
If your task is similar to the task the model of the checkpoint was trained on, you can already use VisionEncoderDecoderModel for predictions without further training.
[INFO   ] modeling_utils:_load_pretrained_model:4000 - All the weights of VisionEncoderDecoderModel were initialized from the model checkpoint at data/models/manga-ocr-base.
If your task is similar to the task the model of the checkpoint was trained on, you can already use VisionEncoderDecoderModel for predictions without further training.
All the weights of VisionEncoderDecoderModel were initialized from the model checkpoint at data/models/manga-ocr-base.
If your task is similar to the task the model of the checkpoint was trained on, you can already use VisionEncoderDecoderModel for predictions without further training.
[INFO   ] modeling_utils:from_pretrained:3544 - Generation config file not found, using a generation config created from the model config.
[INFO   ] modeling_utils:from_pretrained:3544 - Generation config file not found, using a generation config created from the model config.
Generation config file not found, using a generation config created from the model config.
[INFO   ] module_manager:on_finish_setocr:844 - OCR set to manga_ocr
[INFO   ] config:save_config:211 - Config saved
[WARNING] module_manager:setInpainter:814 - Terminating a running inpaint thread.
[WARNING] module_manager:setInpainter:814 - Terminating a running inpaint thread.
[WARNING] module_manager:setInpainter:814 - Terminating a running inpaint thread.
[WARNING] module_manager:setInpainter:814 - Terminating a running inpaint thread.
[WARNING] module_manager:setInpainter:814 - Terminating a running inpaint thread.
[WARNING] module_manager:setInpainter:814 - Terminating a running inpaint thread.
[WARNING] module_manager:setInpainter:814 - Terminating a running inpaint thread.
[WARNING] module_manager:setInpainter:814 - Terminating a running inpaint thread.
[WARNING] module_manager:setInpainter:814 - Terminating a running inpaint thread.
[WARNING] module_manager:setInpainter:814 - Terminating a running inpaint thread.
[WARNING] module_manager:setInpainter:814 - Terminating a running inpaint thread.

**Comment by bropines** [comment]
First of all, don’t drag the list with the wheel.
Secondly, the bug is related to the “quick” change of the painter. I think it’s stupid to set a limit on the speed of list changes.

**Comment by dmMaze** [comment]
@Samurai-Kyo It doesn't cause segmentation fault on my device, but it did lead to another problem: several inpainter threads running in the background forever even if qthread.terminate() is called. I don't know the source of this bug yet, maybe I'll put some restrictions on the user end.

**Comment by bropines** [comment]
> @Samurai-Kyo It doesn't cause segmentation fault on my device, but it did lead to another problem: several inpainter threads running in the background forever even if qthread.terminate() is called. I don't know the source of this bug yet, maybe I'll put some restrictions on the user end.

I had the bug repeated, but instead of the usual work, the program just crashed without an error. only with warning
