### ISSUE TITLE
请问使用sakura翻译是否支持OPENAI交互并设定翻译限制？

### ISSUE THREAD

**Issue by kumakumakichi** [dmMaze/BallonsTranslator#471]
目前sakura翻译存在乱加主语的情况，你我不分。manga-image-translator使用sakura翻译的时候会先和sakura交互限制人称代词乱用，请问下本项目也支援此功能吗?

**Comment by PiDanShouRouZhouXD** [comment]
如果你是指system prompt，那么我可以确定两个项目的实现是一样的（基本上只有同步和异步的区别，核心代码基本上就是复制粘贴）。
乱加主语的问题在翻译漫画时因为缺少上下文，基本无法避免。
你可以用不同版本的sakura模型进行尝试，也许会有更好的效果。

**Comment by kumakumakichi** [comment]
> 如果你是指system prompt，那么我可以确定两个项目的实现是一样的（基本上只有同步和异步的区别，核心代码基本上就是复制粘贴）。 乱加主语的问题在翻译漫画时因为缺少上下文，基本无法避免。 你可以用不同版本的sakura模型进行尝试，也许会有更好的效果。

感谢
