### ISSUE TITLE
有沒有方法一口氣更換字體的大小

### ISSUE THREAD

**Issue by Raiter123** [dmMaze/BallonsTranslator#472]
有沒有方法一口氣更換全部頁面的字體的大小的方法嗎
有時候發現設定錯誤的字型時超崩潰的說

**Comment by dmMaze** [comment]
标题栏->运行，去掉所有勾，在设置里把字体改成 总是使用全局设置

**Comment by Raiter123** [comment]
> 标题栏->运行，去掉所有勾，在设置里把字体改成 总是使用全局设置

成功
