### ISSUE TITLE
[ERROR] module_manager:handleRunTimeException:876 Failed to set ctd: ctd

### ISSUE THREAD

**Issue by Shi-49-94-444-4444** [dmMaze/BallonsTranslator#476]
Traceback (most recent call last): File "D:\Ballons Translator_dev_src_with_gitpython\ui\module_manager.py", line 50, in _set_module = self.module_register.module_dict[module_name] KeyError: 'ctd'
![image](https://github.com/dmMaze/BallonsTranslator/assets/90235020/5ed232e0-13c0-4c16-89aa-903b654c02a3)

**Comment by dmMaze** [comment]
Can you confirm ```modules\textdetector\detector_ctd.py``` exist?
Try ```scripts\local_gitpull.bat``` to update to the latest.

**Comment by Shi-49-94-444-4444** [comment]
> Can you confirm `modules\textdetector\detector_ctd.py` exist? Try `scripts\local_gitpull.bat` to update to the latest.

yeah, i don't have file detector_ctd.py
