### ISSUE TITLE
请问 text-generatrion-webui 的参数应该如何填写？

### ISSUE THREAD

**Issue by hhucchenyixiao** [dmMaze/BallonsTranslator#480]
我想使用 Qwen2-7B-Instruc 进行翻译，所以在 app-url 填了 text-generatrion-webui 的 API URL

![image](https://github.com/dmMaze/BallonsTranslator/assets/96377023/abf435ca-0c13-4c9d-a603-b99c5c20ab60)
![image](https://github.com/dmMaze/BallonsTranslator/assets/96377023/0cb810f9-bfbc-44e2-94bb-55f81c916811)

但是会出现报错
```
 File "C:\software\miniconda3\envs\BallonsTranslator\Lib\site-packages\requests\models.py", line 435, in prepare_url
    raise InvalidURL(*e.args)
requests.exceptions.InvalidURL: Failed to parse: http://127.0.0.1:5000v1/chat/completions
```

请问是哪里搞错了呢？

**Comment by PiDanShouRouZhouXD** [comment]
> requests.exceptions.InvalidURL: Failed to parse: http://127.0.0.1:5000v1/chat/completions

应该为`http://127.0.0.1:5000/`
少了一个“/”，tgw翻译器的作者可能没做防呆设计。

**Comment by hhucchenyixiao** [comment]
> > requests.exceptions.InvalidURL: Failed to parse: http://127.0.0.1:5000v1/chat/completions
> 
> 应该为`http://127.0.0.1:5000/` 少了一个“/”，tgw翻译器的作者可能没做防呆设计。

多谢大佬
