### ISSUE TITLE
重新识别？

### ISSUE THREAD

**Issue by lhj5426** [dmMaze/BallonsTranslator#49]
![image](https://user-images.githubusercontent.com/30548000/195078631-7f149231-8c13-4a04-9fea-92ba99b35335.png)
相同的文本框
![image](https://user-images.githubusercontent.com/30548000/195078778-c6cb38f8-75ef-4a83-a4ea-03a3e09dccba.png)
一页有3个 有一个没被识别出来 这种情况狠多
可否考虑增加右键菜单 对单一选中的框选区域进行重新审查识别？
还有这种整页都没有识别的
是否可以增加一个
![image](https://user-images.githubusercontent.com/30548000/195079263-7c692d34-2347-41cd-8606-7203313c2b26.png)
![image](https://user-images.githubusercontent.com/30548000/195079312-0bc434c4-c720-495f-b2c3-8ddfe8259ce0.png)
运行仅限于本页的单次 运行重新审查识别 现在的运行=整本漫画全部重来一遍

**Comment by dmMaze** [comment]
> 可否考虑增加右键菜单 对单一选中的框选区域进行重新审查识别？
有这打算，不过要到我整完新的检测和识别模型之后了

> 还有这种整页都没有识别的
按理来说现在的模型对规矩的文本检测成功率已经非常高了，方便的话这种图片可以发给我分析一下改进模型

**Comment by lhj5426** [comment]
> > 可否考虑增加右键菜单 对单一选中的框选区域进行重新审查识别？
> 
> 有这打算，不过要到我整完新的检测和识别模型之后了
> 
> > 还有这种整页都没有识别的
> 
> 按理来说现在的模型对规矩的文本检测成功率已经非常高了，方便的话这种图片可以发给我分析一下改进模型

就是很规则正常的图 就是漏网之鱼了
[0002.zip](https://github.com/dmMaze/BallonsTranslator/files/9761547/0002.zip)
这是出问题的图片

**Comment by dmMaze** [comment]
> 就是很规则正常的图 就是漏网之鱼了
> [0002.zip](https://github.com/dmMaze/BallonsTranslator/files/9761547/0002.zip)
> 这是出问题的图片

这几张图主要是后处理算法的问题, 刚传到网盘的v1.3.13.3可以成功识别

**Comment by lhj5426** [comment]
![image](https://user-images.githubusercontent.com/30548000/195834380-b41b2b32-92b7-4815-9269-1e666d0f95f6.png)
运行几张就直接卡死闪退了

**Comment by lhj5426** [comment]
卡死的位置刚好是 那个1312 读取不出来的图片题位置

**Comment by lhj5426** [comment]
有没有旧版本 先给我一个 降级 接着用的机会 以后 升级先备份。。。

**Comment by lhj5426** [comment]
![image](https://user-images.githubusercontent.com/30548000/195836010-aa3f7e8f-a27a-4218-b9c7-272195108b08.png)
用CMD启动 软件卡死 3个窗口一个都没留下 我也不知道怎么提供错误数据。。。

**Comment by lhj5426** [comment]
┭┮﹏┭┮ 现在随便跑一个都闪退 完全不能用的状态。。。

**Comment by dmMaze** [comment]
> 这个1313 又跟之前好早的版本一样了直接卡死 3个窗口全部闪退消失

只有这一个错误吗

**Comment by lhj5426** [comment]
> > 这个1313 又跟之前好早的版本一样了直接卡死 3个窗口全部闪退消失
> 
> 只有这一个错误吗

是啊  任何漫画 任何数量的图片只要点击RUN 运行就闪退 可以给我一个降级的版本先用着嘛 球球大佬了

**Comment by dmMaze** [comment]
> > > 这个1313 又跟之前好早的版本一样了直接卡死 3个窗口全部闪退消失
> > 
> > 
> > 只有这一个错误吗
> 
> 是啊 任何漫画 任何数量的图片只要点击RUN 运行就闪退 可以给我一个降级的版本先用着嘛 球球大佬了

请更新到1.3.13.5(见网盘)

**Comment by lhj5426** [comment]
> > > > 这个1313 又跟之前好早的版本一样了直接卡死 3个窗口全部闪退消失
> > > 
> > > 
> > > 只有这一个错误吗
> > 
> > 
> > 是啊 任何漫画 任何数量的图片只要点击RUN 运行就闪退 可以给我一个降级的版本先用着嘛 球球大佬了
> 
> 请更新到1.3.13.5(见网盘)

好滴 我去更新

**Comment by lhj5426** [comment]
> > > > 这个1313 又跟之前好早的版本一样了直接卡死 3个窗口全部闪退消失
> > > 
> > > 
> > > 只有这一个错误吗
> > 
> > 
> > 是啊 任何漫画 任何数量的图片只要点击RUN 运行就闪退 可以给我一个降级的版本先用着嘛 球球大佬了
> 
> 请更新到1.3.13.5(见网盘)

![image](https://user-images.githubusercontent.com/30548000/195855326-34666fa2-1cc2-469a-a5d9-384d5f1f5c97.png)
可以正常使用了 而且速度还变快了！感谢 大佬！！！
