### ISSUE TITLE
Unable to find .btrans_cache

### ISSUE THREAD

**Issue by nhhalc** [dmMaze/BallonsTranslator#491]
Mac Intel 2019 Sonoma
<img width="567" alt="SCR-20240618-m7d" src="https://github.com/dmMaze/BallonsTranslator/assets/86941854/a9a1f2e0-9ea0-46e9-a2aa-f3052d4a5810">
I got this notice in the end, couldn't see the packaged app though it have created the BallonsTranslator file

**Comment by dmMaze** [comment]
The program doesn't have write permission for the target directory. If can't resolve it by yourself, just run the source code.
