### ISSUE TITLE
Is it possible to provide a button for a full update?

### ISSUE THREAD

**Issue by chou18194766xx** [dmMaze/BallonsTranslator#498]
For example, if I make changes to the content of imgtrans_XXX.json and replace the font for all translations, the content of the result folder will not be updated. As a result, I need a one-click button to update the result folder. Can you provide such a feature?

**Comment by dmMaze** [comment]
After you make changes to the project file, reopen the app, top bar->Run, uncheck all and click run

**Comment by chou18194766xx** [comment]
> After you make changes to the project file, reopen the app, top bar->Run, uncheck all and click run

I used your method to update the "result" folder today, but I found that my carefully crafted formatting was messed up. For example, some of the fonts in the comics had different outlines, so I clicked to run the update to ensure that all modifications were saved, only to find that there was an issue with the font outlines, and I had to reformat everything again.

**Comment by dmMaze** [comment]
@chou18194766xx 
Sorry, should have mentioned the text style will follow "Lettering" settings in the config panel. And there is no "leave as it is" option for now. I'll implement it later.

**Comment by chou18194766xx** [comment]
> @chou18194766xx Sorry, should have mentioned the text style will follow "Lettering" settings in the config panel. And there is no "leave as it is" option for now. I'll implement it later.

Looking forward to your update. Thank you

**Comment by dmMaze** [comment]
It has been implemented in [a6b4636](https://github.com/dmMaze/BallonsTranslator/commit/a6b4636979090021a89d5dfb12ced1f8c4599a50) via titlebar->run without update text styles

**Comment by chou18194766xx** [comment]
> It has been implemented in [a6b4636](https://github.com/dmMaze/BallonsTranslator/commit/a6b4636979090021a89d5dfb12ced1f8c4599a50) via titlebar->run without update text styles

After testing, I found that the new button works fine in most cases. But there is still a bug. For example, there are two different text formats in the same bubble. If you run "run without updating text styles", the text format will become one kind. Please see the attachment.
![now](https://github.com/dmMaze/BallonsTranslator/assets/150505840/f65bf3a4-3966-4c45-bbe1-736490813cd0)
![origin](https://github.com/dmMaze/BallonsTranslator/assets/150505840/4184d2e7-3ac9-4d80-87b2-0ca3f9f0f976)

**Comment by dmMaze** [comment]
> > It has been implemented in [a6b4636](https://github.com/dmMaze/BallonsTranslator/commit/a6b4636979090021a89d5dfb12ced1f8c4599a50) via titlebar->run without update text styles
> 
> After testing, I found that the new button works fine in most cases. But there is still a bug. For example, there are two different text formats in the same bubble. If you run "run without updating text styles", the text format will become one kind. Please see the attachment. ![now](https://private-user-images.githubusercontent.com/150505840/342703084-f65bf3a4-3966-4c45-bbe1-736490813cd0.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTk1MDQ5MjcsIm5iZiI6MTcxOTUwNDYyNywicGF0aCI6Ii8xNTA1MDU4NDAvMzQyNzAzMDg0LWY2NWJmM2E0LTM5NjYtNGM0NS1iYmUxLTczNjQ5MDgxM2NkMC5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNjI3JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDYyN1QxNjEwMjdaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT04MDBkZWY1ZGQ5OGY4NTcxNDFlYzM3ZTlhMjJjZWE4OGRkMGNiN2Q5YjE3ODcxMjNmOWUwOGMwNjcyNzk0OGY4JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.MYvTxeKquI5aanm197s1eKg8Rp0xvYgSg9YiROkHOpY) ![origin](https://private-user-images.githubusercontent.com/150505840/342703090-4184d2e7-3ac9-4d80-87b2-0ca3f9f0f976.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTk1MDQ5MjcsIm5iZiI6MTcxOTUwNDYyNywicGF0aCI6Ii8xNTA1MDU4NDAvMzQyNzAzMDkwLTQxODRkMmU3LTNhYzktNGQ4MC04N2IyLTBjYTNmOWYwZjk3Ni5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNjI3JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDYyN1QxNjEwMjdaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1hY2QyN2JmMWYwYTJiNTQwM2RkNTY2MmU5OGIzYjMwZWFlMmZhYzRhYTYxZDY2ODY5MzM4NTlkMDk1MGIzOTgwJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.pUYoM5gj-NdzUhl9bCdoatr_w7d6R698MUnFifTIYFQ)

It is fixed by [319c0d4](https://github.com/dmMaze/BallonsTranslator/commit/319c0d445454f0efbbcfc50bf1adcfe4d7633261)
