### ISSUE TITLE
请问字体是否可以任意匹配

### ISSUE THREAD

**Issue by curacfyh** [dmMaze/BallonsTranslator#504]
漫画嵌字用的字体很多，所以搜索会高效点。但如附件所示，只能从头匹配，譬如字体“DFPLiHei-Lt”，只能输入“DFP”这样的，输入“lihei”就不行。

![搜狗截图20240701184632](https://github.com/dmMaze/BallonsTranslator/assets/38342089/9f9dcefb-e93e-46b5-a1a1-e62c6fc8854c)

**Comment by dmMaze** [comment]
现在确实不行，我看看怎么实现吧

**Comment by curacfyh** [comment]
> 现在确实不行，我看看怎么实现吧

好的，辛苦大佬。

另外问一下，result文件夹更新好像有点BUG，譬如移动文字块的位置，然后Ctrl+S，看软件里是被保存了，但result偶尔出现不更新的情况，尤其是一些微小的修改，失败率还挺高的。

**Comment by dmMaze** [comment]
@curacfyh 我试了一下正常啊，能提供能稳定复现的现细节吗

**Comment by curacfyh** [comment]
> @curacfyh 我试了一下正常啊，能提供能稳定复现的现细节吗

我试了下，可以重现，但不能稳定复现。主要是文字块位置的细微调整。
后面能复现了我再来。多谢

**Comment by dmMaze** [comment]
> > @curacfyh 我试了一下正常啊，能提供能稳定复现的现细节吗
> 
> 我试了下，可以重现，但不能稳定复现。主要是文字块位置的细微调整。 后面能复现了我再来。多谢

这个 [85a825e](https://github.com/dmMaze/BallonsTranslator/commit/85a825e57fbdffc9bf9b53240a1987bda0507a4e) 应该已经修好了
