### ISSUE TITLE
Good Translator Offline (Gemini-Gemma2, OpenAI-chatGPT)

### ISSUE THREAD

**Issue by snakeotakon** [dmMaze/BallonsTranslator#513]
**With Gemma 2**
A family of lightweight, state-of-the art open models built from the same research and technology used to create the Gemini models.  INFO: [https://ai.google.dev/gemma](https://ai.google.dev/gemma)

**INSTALLATION**
1. [Download the installer and install the program ollama ](https://ollama.com/) _Compatible clients ChatGPT_
2. Run prompt cmd "ollama run gemma2" 
 ` C:\Users\myuser>  ollama run gemma2`  _(Automatic Download Model  Gemma2 5GB)_
3. Configure your Translator ChatGPT
    - **Override Model**: gemma2
    - **3rd party api url**: http://localhost:11434/v1/

![ChatGPT Gemma](https://github.com/dmMaze/BallonsTranslator/assets/112669188/2bdebd0a-a6fc-44bc-93a9-9a7143af60f7)

Works with the CPU, but is highly recommended with nvidia cards. RTX-3060

_Ollama, a platform that makes local development with open-source large language models a breeze. With Ollama, everything you need to run an LLM—model weights and all of the config—is packaged into a single Modelfile_

There are a large number of models that can be tried
Meta Llama 3: The most capable openly available LLM to date
[deepseek-coder-v2](https://ollama.com/library/deepseek-coder-v2) An open-source Mixture-of-Experts code language model that achieves performance comparable to GPT4-Turbo in code-specific tasks.

https://ollama.com/library

**Comment by dmMaze** [comment]
Thanks for the intro. I suggest moving this thread to the discussion section and I'll add a link direct to it in readme.

**Comment by gickass** [comment]
you can use with koboldcpp from this way too if you don't have ollama since koboldcpp support openai api url
