### ISSUE TITLE
命令行模式输出的图像中的字符都是方框

### ISSUE THREAD

**Issue by caiweihan** [dmMaze/BallonsTranslator#519]
我使用 GUI 翻译漫画时能够正确地将日文翻译成中文，但当我使用命令行模式时，本应该是文字的地方变成了方框，这是什么问题？

**Comment by caiweihan** [comment]
![1](https://github.com/user-attachments/assets/5cbe6e9b-d1a8-4962-b368-ce9352330e33)

**Comment by caiweihan** [comment]
补充信息：
inpainted 文件夹，mask 文件夹 都输出了正确的结果，json 文件也将每个日文翻译成了对应的中文，只是最后 result 文件夹的图片有问题

**Comment by caiweihan** [comment]
补充信息：
我修改了 mainwindow.py 中的几行代码：
```
        if shared.HEADLESS:
            self.run_batch(**exec_args)
        else: # CHANGED!!!
            self.run_batch(**exec_args)
```
然后运行指令 `python launch.py --exec_dirs "[DIR_1],[DIR_2]..."`
就能够批量处理地址了，只是会打开窗口。此时输出的图片是正确的。
这说明问题出在 --headless 相关的代码中

**Comment by dmMaze** [comment]
出方块字的时候开界面的时候右上显示的全局字体是什么？换个更全的字体比如微软雅黑再跑 headless 结果怎么样？

**Comment by caiweihan** [comment]
> 出方块字的时候开界面的时候右上显示的全局字体是什么？换个更全的字体比如微软雅黑再跑 headless 结果怎么样？

只要打开了界面，就没有方块字。只要没有打开界面（也就是命令行有 --headless）就会有方块字。所以看不到右上显示的全局字体。

**Comment by dmMaze** [comment]
> > 出方块字的时候开界面的时候右上显示的全局字体是什么？换个更全的字体比如微软雅黑再跑 headless 结果怎么样？
> 
> 只要打开了界面，就没有方块字。只要没有打开界面（也就是命令行有 --headless）就会有方块字。所以看不到右上显示的全局字体。

我就是问打开界面的时候全局字体是啥，headless 会用同样的字体

**Comment by caiweihan** [comment]
> > > 出方块字的时候开界面的时候右上显示的全局字体是什么？换个更全的字体比如微软雅黑再跑 headless 结果怎么样？
> > 
> > 
> > 只要打开了界面，就没有方块字。只要没有打开界面（也就是命令行有 --headless）就会有方块字。所以看不到右上显示的全局字体。
> 
> 我就是问打开界面的时候全局字体是啥，headless 会用同样的字体

Microsoft YaHei UI
大小24，行间距1.2

**Comment by dmMaze** [comment]
windows 上 qt 指定 qpa offscreen 的时候不会加载系统字体，linux 没问题，macos 我记得也行
他们似乎修了 mac 没修 win: https://bugreports.qt.io/browse/QTBUG-72335
https://github.com/dmMaze/BallonsTranslator/commit/82d2df2735933070fcfa245d7773619b9a227005 已修
