### ISSUE TITLE
运行launch_win.bat后显示找不到指定模块

### ISSUE THREAD

**Issue by Stasert39** [dmMaze/BallonsTranslator#524]
运行launch_win.bat后显示
OSError: [WinError 126] 找不到指定的模块。 Error loading "C:\Users\poemc\Downloads\BallonsTranslator_dev_src_with_gitpython\ballontrans_pylibs_win\lib\site-packages\torch\lib\fbgemm.dll" or one of its dependencies.
请按任意键继续. . .

**Comment by dmMaze** [comment]
用网盘里那个 ballontrans_pylibs_win 包，或者自己重装一下 torch:
pip install torch==2.2.2 torchvision==0.17.2 --index-url https://download.pytorch.org/whl/cu118 --disable-pip-version-check

**Comment by Stasert39** [comment]
试过了，依然显示找不到指定模块
