### ISSUE TITLE
windows 第一次源码安装

### ISSUE THREAD

**Issue by cat799** [dmMaze/BallonsTranslator#525]
![image](https://github.com/user-attachments/assets/7f3f7538-63a3-4940-8452-b2915ce6577f)
更新windows python版本 并且下载mega的data文件和ballontrans_pylibs_win 依赖均解决不了这个问题 找不到指定的模块 
 torch\lib\fbgemm.dll 怀疑是工作的电脑显卡不支持？ 我是ntel UHD Graphics 630 显卡 win10系统

**Comment by dmMaze** [comment]
不要从 release 页面下源码，那个是旧的，从项目主页->code->download zip 或者下网盘里那个
