### ISSUE TITLE
希望能够彻底还原抹字图层

### ISSUE THREAD

**Issue by StudyingPy** [dmMaze/BallonsTranslator#532]
在一些情况下，AI会误将部分性器官遮罩识别为文字并抹除，但手动删除并不能完全还原原图，而是保留了部分涂抹。希望能够加入工具将图片某些部分彻底还原。

样例在您无法理解描述后再提交，以避免版权问题和NSFW内容暴露，希请理解。

**Comment by dmMaze** [comment]
拉一下右下角掩膜透明度会显示哪些部分被涂抹过，然后画板矩形工具，右键拉矩形框就能把这些部分恢复

**Comment by StudyingPy** [comment]
多谢您了，我再试一下。没有想到右键呢…

**Comment by dmMaze** [comment]
> 多谢您了，我再试一下。没有想到右键呢…

那些 gif 演示里有一张就是这个

**Comment by StudyingPy** [comment]
#按下鼠标左键拖动矩形框抹除框内文字，按下右键拉框清除框内修复结果。

对不起对不起打扰了，是我没有好好看说明……
