### ISSUE TITLE
求助:竖向日文排版出现问题,挤在一个方块字格中

### ISSUE THREAD

**Issue by TwilightHome20** [dmMaze/BallonsTranslator#54]
### 运行后出现文字挤在一起的情况,切换横向文字是正常的
![image](https://user-images.githubusercontent.com/101049847/204145060-168a7f6c-b079-4f66-9774-d02c4627d2f3.png)

### 横向文字:
![image](https://user-images.githubusercontent.com/101049847/204145252-3074318a-4171-49b3-979c-62bc21543bc4.png)

### mask识别是正常的:
![image](https://user-images.githubusercontent.com/101049847/204145163-6e8db4df-a0c2-4b6c-8591-9b88131501a8.png)

### 设置为全部程序决定:
![image](https://user-images.githubusercontent.com/101049847/204145274-b46a85c9-bec5-4095-8627-1db1fe5a50db.png)

### 目录里没找到log文件,不知道控制台这个输出是否正常:
![image](https://user-images.githubusercontent.com/101049847/204145370-54d29431-d0d5-4bc4-a73e-981caa74c03a.png)

### 原图:
![20221127_145108_W2xEX_jpg_waifu2x_2x_png](https://user-images.githubusercontent.com/101049847/204145074-5caf7a6a-f500-4ce8-95e6-35b2c51a46dd.png)

**Comment by dmMaze** [comment]
<img width="256" alt="image" src="https://user-images.githubusercontent.com/51270320/204148457-a072f404-6966-41bf-8482-b7b662ff6ee8.png">
字间距调小了吧...那个一键机翻是按全局字体样式来填的

**Comment by TwilightHome20** [comment]
哦的确...不知何时变成了0...现在正常了x,谢谢大佬解惑
