### ISSUE TITLE
Font size bug?

### ISSUE THREAD

**Issue by andy-julot** [dmMaze/BallonsTranslator#541]
When I set typesetting to "Use global setting", the font size result is very strange.
The generated json file for font size seems to be bigger than what I selected in font style.
But the generated font size in the result image is much smaller.
I'm really confused here.

**Comment by dmMaze** [comment]
The font size shown in GUI is point size, and it is stored as pixel size for cross-platform compatibility. Here's the convert function, note  ```shared.LDPI```  is assigned to the right value (usually bigger than 72) once app is launched: 
https://github.com/dmMaze/BallonsTranslator/blob/cad1ff4cba035e31bb2bce237cf11fea74056f32/utils/fontformat.py#L6-L10


As for the smaller font size in the generated image, is the stroke width > 0?

**Comment by andy-julot** [comment]
> The font size shown in GUI is point size, and it is stored as pixel size for cross-platform compatibility. Here's the convert function, note `shared.LDPI` is assigned to the right value (usually bigger than 72) once app is launched:

I see, so that's why they're different.

> As for the smaller font size in the generated image, is the stroke width > 0?

Oh yes, I use 0.2 for stroke.
But I think that's not a problem.
Let me illustrate what I means.

Here is my setting:

![Global Font Format](https://github.com/user-attachments/assets/1a7a93cd-3137-40d8-a750-69027fc92deb)

![Typesetting](https://github.com/user-attachments/assets/38b1883a-d82d-40d8-a3dc-57e2f0312495)

After I click Run this is the result:

![Generated Result](https://github.com/user-attachments/assets/0828adcc-8dd5-49f0-940b-14c28539f13f)

Because the generated text is outside of the balloon boundary, I adjust it:

![Adjusted Boundaries](https://github.com/user-attachments/assets/ed7ac2a6-5b23-4829-8d84-97edb77024a4)

Because I think I can still increase the font size I try to change the font size, that's when I realize something strange. After I change the size to other than 20 and back to 20, the generated text seems bigger like this:

![Manual Font Size](https://github.com/user-attachments/assets/ca367e52-9500-4a66-9fd8-d1343cdb63f4)

Wasn't it supposed to be the same size?

**Comment by dmMaze** [comment]
> After I click Run this is the result:
> 
> ![Generated Result](https://private-user-images.githubusercontent.com/178530383/358470719-0828adcc-8dd5-49f0-940b-14c28539f13f.jpg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjM3ODQ1ODcsIm5iZiI6MTcyMzc4NDI4NywicGF0aCI6Ii8xNzg1MzAzODMvMzU4NDcwNzE5LTA4MjhhZGNjLThkZDUtNDlmMC05NDBiLTE0YzI4NTM5ZjEzZi5qcGc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwODE2JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDgxNlQwNDU4MDdaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1iZWIyNWU4MzQyMGRkZTNmYjUwMjhmYzEyYjY1MTUyOTVmMjI2MTQxN2JjY2Q5MmRmMGQ1Yzg2NTcwNjliZWMwJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.wm1C4rJcUzqYBIAyT2WlR4NwopO7rAKwCDBNzhlibUI)

Double click this text block, the font size displayed in the font menu should be less than 20. It is adjusted so that font size + stroke size = target size, it is meaningful for automatic mode (to match the source text size) but not for ```use global setting, it should be fixed by [66d191e](https://github.com/dmMaze/BallonsTranslator/commit/66d191ea2a240f4b4ce9d768a80efeaab870e29d)

**Comment by andy-julot** [comment]
It fixed now, thank you.
