### ISSUE TITLE
哥，这什么情况

### ISSUE THREAD

**Issue by heiyanmaster** [dmMaze/BallonsTranslator#545]
![image](https://github.com/user-attachments/assets/125ea1b6-5c1c-459d-b7bb-9b381d81f40d)
哥这个怎么全是白的？？？我好像无法调试翻译的那个py文件，我尝试改了没效果
![image](https://github.com/user-attachments/assets/ce61fe3a-08f9-410b-80da-fc9b0bacabfa)
我这个是exe版本的什么情况我醉了

**Comment by dmMaze** [comment]
别用旧版

**Comment by heiyanmaster** [comment]
> 别用旧版

哥们能不能来个完整版，包括环境和各种所需要的组件打包成zip啊求个完整版下载地址，我们更新一下模块很费劲的
