### ISSUE TITLE
塗白失敗

### ISSUE THREAD

**Issue by wagannan** [dmMaze/BallonsTranslator#552]
不知道是哪個步驟或是檔案出了問題
沒有辦法塗白

可以塗白的頁似乎圖片太長,下半節就無法辨識 
請幫我看看 如果需要原圖或是還需要甚麼資料請在聯繫我
![image_373](https://github.com/user-attachments/assets/2542353a-89c4-42ed-8e34-398001148dd4)
![image_374](https://github.com/user-attachments/assets/01289e02-43a9-4a8d-a08f-8436bfe1e59d)
![image_375](https://github.com/user-attachments/assets/ed21fe7e-1815-46fe-b17a-192e546de2c1)
![image_376](https://github.com/user-attachments/assets/df751d93-89d6-428d-b94c-5f9d5c9c3376)

再來我的 翻譯也沒有成功過
所以我只使用塗白功能

**Comment by lhj5426** [comment]
涂白有4个工具你换换其他的呢
![image](https://github.com/user-attachments/assets/60a79670-d972-48bc-835b-7f82d8b1e62d)
个人常用 这2个 
翻译器 也是很多个 不要捏着谷歌不放啊
![image](https://github.com/user-attachments/assets/8bceebf0-f0b9-470c-84cc-410f7807b76f)

**Comment by lhj5426** [comment]
对于韩漫这种另类的 长条 处理的效果不是很好 因为太长了 可以把图裁切一下

**Comment by dmMaze** [comment]
方便的话给下原图，你点了 run 出现这个弹窗？



> 对于韩漫这种另类的 长条 处理的效果不是很好 因为太长了 可以把图裁切一下

实际上软件里会在检测前自动切

**Comment by wagannan** [comment]
> 塗白有4個工具你換換其他的呢 個人常用這2個 翻譯器也是很多不要捏著谷歌不放啊 ![影像](https://private-user-images.githubusercontent.com/30548000/360737966-60a79670-d972-48bc-835b-7f82d8b1e62d.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjQzOTk5MjQsIm5iZiI6MTcyNDM5OTYyNCwicGF0aCI6Ii8zMDU0ODAwMC8zNjA3Mzc5NjYtNjBhNzk2NzAtZDk3Mi00OGJjLTgzNWItN2Y4MmQ4YjFlNjJkLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA4MjMlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwODIzVDA3NTM0NFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTIyMDU0NmU5YjIzYjY1ZjljM2FiMWUxMTY4N2MzN2E1N2UxMGMzNWE2OWNiNTE0NmVlNzVkNzRkOGYwMzRmOTAmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.7my2ugeciJyuIKAzazvT1VRVG_jnQQFlMuSzG4gVHbo) ![影像](https://private-user-images.githubusercontent.com/30548000/360738144-8bceebf0-f0b9-470c-84cc-410f7807b76f.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjQzOTk5MjQsIm5iZiI6MTcyNDM5OTYyNCwicGF0aCI6Ii8zMDU0ODAwMC8zNjA3MzgxNDQtOGJjZWViZjAtZjBiOS00NzBjLTg0Y2MtNDEwZjc4MDdiNzZmLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA4MjMlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwODIzVDA3NTM0NFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWRkMDU2MGQ5NWZlNGY5MDg3YmE4Y2VkYjk0YTJhYWQxMDg2ZGVmODcyNWUxZTY5MmQyZjQ5ZjI1ZDI5NjE2YjkmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.kzLGqh2WxUcFK3d0iE74i_2VBFwfKEsF3TUyzPAdPzc)

我沒有捏著谷歌不放 能用翻譯器我都嘗試過一遍了
至於塗白 選擇那個模式是因為 我覺得他白框塗得最乾淨
再來 我試過如果不用文本檢測是無法使用"修復工具"的
所以 跟修復工具選擇哪一個因該是沒有太大關西
 
 文本檢測那關我就先過不了了

**Comment by wagannan** [comment]
@dmMaze  已把原圖發您郵件了~~

**Comment by dmMaze** [comment]
> @dmMaze 已把原圖發您郵件了~~

没有，垃圾邮件里也没有，你没发错吧。你可以贴到一些在线图床，比如https://imgur.com ，实在不行你给个来源和页码我自己下

**Comment by wagannan** [comment]
> > @dmMaze把原圖發給您已郵件了~~
> 
> [沒有，垃圾郵件裡](https://imgur.com)也沒有，你沒發錯吧。

8/24  pm：08：08分 有再傳一次了

**Comment by dmMaze** [comment]
https://github.com/dmMaze/BallonsTranslator/commit/baba06ae10a19c6036e76f3c7072bf0a452ea66d 修好了
