### ISSUE TITLE
全局字体勾选加粗run后没有加粗效果

### ISSUE THREAD

**Issue by popcion** [dmMaze/BallonsTranslator#555]
勾选了加粗，实际没效果，fontconfig文件里的bold确认为true，run之后生成的imgtrans_XXX.json中的bold却一直为false，实际上并没加粗。翻译后需要选择文本框，将加粗按钮取消再重新勾选才能加粗，并且发现将加粗按钮关闭后字体会稍稍变粗一点（可能关闭加粗按钮正确的字体才会显示？YaHei和YaHei UI都出现这种情况），第二次点击加粗按钮后才会真正加粗，再次关闭加粗按钮后翻译后的细字体便不再出现。对于其他字体则不会出现细小字体，但不会被加粗。而且CTRL+A全选再加粗只能用作于单页，是否可以支持多选页面对多页进行同时修正。
![image](https://github.com/user-attachments/assets/1daf9aff-2a28-42ff-b68f-744c1edfc6bf)
翻译后的：
![image](https://github.com/user-attachments/assets/f94f854d-258b-436b-a985-51a590f11f04)
关闭加粗按钮：
![image](https://github.com/user-attachments/assets/1816c733-673a-4900-b4bd-2294d7fa0935)
点击加粗按钮：
![image](https://github.com/user-attachments/assets/83b09c48-6896-4da8-803e-ac4ff5b56f24)
再次关闭加粗按钮：
![image](https://github.com/user-attachments/assets/1816c733-673a-4900-b4bd-2294d7fa0935)

**Comment by popcion** [comment]
另外能否在多页面中仅对单独几页进行run操作，例如500页中有十来页需要ocr识别一遍，想直接在UI中选择对应页数仅对选择的部分进行批量操作。把需要识别的在本地重新挑出来再单独跑一遍挺麻烦的，若需要进一步识别又要单独拿出来几页，要是500页全部跑一遍时间就更长了。不知增加多选选项的可行性如何

**Comment by dmMaze** [comment]
> 另外能否在多页面中仅对单独几页进行run操作，例如500页中有十来页需要ocr识别一遍，想直接在UI中选择对应页数仅对选择的部分进行run操作。把需要识别的在内容在本地重新挑出来再单独跑一遍挺麻烦的，若需要进一步识别又要单独拿出来几页，要是500页全部跑一遍时间太长了。不知增加多选选项的可行性如何

可以在漫画目录里新建一个文件夹，把这次不翻译的挪进去，重新打开软件就只加载剩下的图片。翻译完了再把图挪回来，重新打开软件可以正确加载所有图和翻译结果



> 勾选了加粗，实际没效果，fontconfig文件里的bold确认为true，run之后生成的imgtrans_XXX.json中的bold却一直为false，实际上并没加粗。翻译后需要选择文本框，将加粗按钮取消再重新勾选才能加粗，并且发现将加粗按钮关闭后字体会稍稍变粗一点（可能关闭加粗按钮正确的字体才会显示？YaHei和YaHei UI都出现这种情况

字体变细的问题，如果 run 前不勾选加粗还存在吗？
另外还没有 run 的时候应用全局加粗/斜体/下划线这种设置

**Comment by dmMaze** [comment]
字体变细的问题 [c7d5207](https://github.com/dmMaze/BallonsTranslator/commit/c7d52079b6bed2c610b0ed3fd847e053b522230a) 修好了

**Comment by popcion** [comment]
感谢更新

**Comment by dmMaze** [comment]
字体变细是 qt6 和 qt5 字体权重规范不匹配的问题。2debb6d573670d4ab521f33ec0c8f345fea68b34 后重新打开旧的项目有问题 (过细) 的权重会被修复，可以去掉顶部栏->Run下的所有勾，点 RUN 重新渲染所有文本

**Comment by dmMaze** [comment]
现在全局加粗会应用到 RUN 了
