### ISSUE TITLE
lama_large_512px修复问题，出现大量灰框

### ISSUE THREAD

**Issue by jenffrey** [dmMaze/BallonsTranslator#557]
![微信图片_20240825145051](https://github.com/user-attachments/assets/c32269b6-e9e0-4a72-b73f-f0027106c5ae)

用批量运行修复时出现，之前好好的，不知道怎么突然变成这样，求大佬

**Comment by dmMaze** [comment]
你怎么跑的批量，只勾了修复然后点 run 吗？
给个设置界面截图，方便的话原图发一下

**Comment by jenffrey** [comment]
![1](https://github.com/user-attachments/assets/35a2befd-bfd3-47f3-9a80-2dbbcb693999)
![2](https://github.com/user-attachments/assets/2834ad09-27b7-460d-80ea-135bac318838)
运行里面勾选：启用文本检测，启用OCR，启用修复，然后点运行

**Comment by popcion** [comment]
画板里面把膨胀关掉再跑

**Comment by dmMaze** [comment]
@jenffrey 你画板膨胀滑条是不是拉满了

**Comment by jenffrey** [comment]
解决了，感谢
