### ISSUE TITLE
[Feature request] Replace all newline characters with one space each

### ISSUE THREAD

**Issue by notimp** [dmMaze/BallonsTranslator#558]
Google lens OCR is one of the best free OCR options out there, Google translate is also one of the most popular free translators used by many in here but if you use it (even with the "handling newline" setting turned to remove in the Google lens module), there will still be linebreaks in every recognized text bubble - which are fine if you dont plan on doing a manual quality assurance pass (editing all text in the comic), but become the most time intensive step as you have to remove them manually during a quality control pass, if you plan on reflowing the text afterwards. (Using a different font size, or changing the size of the rectangle, both count as reflowing the text. :) )

Please add an option for a text parser to remove every non breaking space (\s) and every newline (\n) from all text in one text bubble (recognized and handed forward as "one text box" by the ocr, and translated as "one text box" by the translator module) and replace it with one space exactly. So all the text we get back in the translation box for one text bubble in a comic by default will be an endless line, and only limited by the text boxes boundaries.

Here are some examples to illustrate the issue.

All images are "as google lens OCR, google translate and BallonsTranslator filled out those bubbles in auto mode, after hitting run". None of the results were modified manually.

![Screenshot 2024-08-26 071354](https://github.com/user-attachments/assets/4f50b686-8f10-4a2c-8ad7-7469867c7b76)

In all the examples in this image, you see the same behavior, after the first word, there is a newline break in the text.

```
Ich
werde sie sofort anrufen!
```

```
Eine
Woche später...
```

```
Eva
die Zeitungen sprechen von
```

```
Hören, 
die Brauttoilette ist aus sehr feinem Goldfasermaterial
```

If you plan on reflowing those bubbles (changing their size, or their font size) you have to always remove that newline break manually, as it still will be honored after reflowing the text.

Here is a more outrageous example:

![Screenshot 2024-08-26 071442](https://github.com/user-attachments/assets/0cfe4083-b6fb-4ee5-9f84-e3b69b279aee)

```
Warten sie eine Minute! Sie hätten die Drogen ins Meer
werfen
können. Bevor wir sie gehen lassen, werfen wir noch einen
Blick
unter Wasser. Meine beiden Agenten sind ausgezeichnete
Taucher...
```

So what I'm proposing is this: Give us an optional feature that parses the text and removes all newline breaks (soft and hard), and replaces them with one space each, for the text in every recognized speachbubble.

So this:

![Bildschirmfoto 2024-08-26 um 07 54 05](https://github.com/user-attachments/assets/645eb136-7752-4727-9a9a-f3ef1abd6d35)

which will give the following result:

![Bildschirmfoto 2024-08-26 um 07 54 43](https://github.com/user-attachments/assets/9bb93c79-b96e-497c-bbc4-2b7fe7bdb498)

==
```
Warten sie eine Minute! Sie hätten die Drogen ins Meer werfen können. Bevor wir sie gehen lassen, werfen wir noch einen Blick unter Wasser. Meine beiden Agenten sind ausgezeichnete Taucher...
```

-- so that the text within a text bubble will be limited by the boundries of the the textbox only, and not by linebreaks that were in the text already.

Make it available as an optional feature (many people will prefer the current behavior, as it gives you better results if you dont plan on doing a quality control pass afterwards).

Having such an optional feature would make reflowing text, much less time consuming in an optional manual quality control pass afterwards, where you'll be touching close to every textbox and resizing it anyhow..

I'm currently unsure if google lens (unlikely, see textboxes), or google translate add those newlines (new line characters), or its actually the way BallonsTranslator handles reflowing the text, please make it an optional feature to not have those linebreaks occur though.

If you know if google lens, or google translator, or BallonsTranslator itself add those newline characters, please tell us (/me).

Any help would be appreciated. :)

Thank you,

notimp

edit: I'll also post the uncleaned test images, give me a sec.

**Comment by notimp** [comment]
Here are the unedited images for you to test on. Source language is Dutch (Netherlands).

![s120 0023](https://github.com/user-attachments/assets/5c70de8e-9dde-4635-85d0-49a1f6f25041)

![s120 0014](https://github.com/user-attachments/assets/144c3458-8f8f-4616-9d0f-ff397847d777)

**Comment by dmMaze** [comment]
In the config panel, Typesetting, uncheck Autolayout and there will be no extra line breaks inserted into the translated text.
Besides you can write regexper in Titlebar->Edit->Keyword subtition for OCR & translated text.

**Comment by notimp** [comment]
> In the config panel, Typesetting, uncheck Autolayout and there will be no extra line breaks inserted into the translated text. Besides you can write regexper in Titlebar->Edit->Keyword subtition for OCR & translated text.

Thank you very much. I'll close the ticket once I had the chance to confim it. :)

Thank you!

**Comment by notimp** [comment]
Unchecking that checkbox solved all my problems. Thank you. I'm closing this ticket now.

**Comment by dmMaze** [comment]
Commented in the wrong issue, so I'll post it here:

<img width="1149" alt="截屏2024-09-04 21 32 58" src="https://github.com/user-attachments/assets/0be30a9a-9b89-4c11-bb00-7cd2fedf2abe">

The automatic mode should perform better now, the original algorithm was mostly for the scenario of manga. 
You may want to try it with that checkbox checked and set the font size to use the global setting. Tune the line spacing may also affect the results.
