### ISSUE TITLE
文字粘贴在右侧文本编辑区时,图片上只会显示最后一个字符,但在图片上的文本框粘贴没有问题

### ISSUE THREAD

**Issue by TwilightHome20** [dmMaze/BallonsTranslator#56]
[20221128204018.webm](https://user-images.githubusercontent.com/101049847/204280469-5c5af7ae-86b5-4e89-9093-8c476a4a0f41.webm)
如视频演示,log如下:
![image](https://user-images.githubusercontent.com/101049847/204280795-134402e6-7772-4c91-bc96-8cd413ae7b93.png)

**Comment by dmMaze** [comment]
[v1.3.15](https://github.com/dmMaze/BallonsTranslator/releases/tag/v1.3.15)应该已经修好了
