### ISSUE TITLE
提几个功能，望作者大大采纳

### ISSUE THREAD

**Issue by chou18194766xx** [dmMaze/BallonsTranslator#564]
现在的软件已经十分强大了，比用PS能节省至少70%的嵌字时间，堪称嵌字神器。
提几个功能，望大大能考虑下，不胜感激。

1. 文本的顺序调整（涉及到批量翻译的顺序）
    如图所示，这个文本排列顺序时常会有些错乱，毕竟漫画中的顺序不是机械式的顺序排列的，而是随着阅读目光前进的。这就需要调整顺序。
    首先，调整顺序有个BUG，如果点击左侧主界面的文本框，右侧的文本框也会被选中，但拖动它会没有反应。只有直接点击右侧文本块才能进行拖动。
    其次，请问是否可以增加主界面上文本框显示序号，并双击修改？现在改序号只能在右侧改，有时候想知道它是几号，还是得从主界面上先数好是第几个，再去修改。如果文本框一多起来，就低效了。
![image](https://github.com/user-attachments/assets/322fd500-d126-4f24-a3c3-5850e1c458d2)

2. 多重符号问题
    原文如下图
![image](https://github.com/user-attachments/assets/ac1d8834-bef0-4244-9804-e0534b02d59c)
    这里有3个感叹号。如果是PS，PS带这个功能可以让选定的字符竖排框中横排。
    目前我是用2个文本框，如下图
![image](https://github.com/user-attachments/assets/b09cbfff-81c6-43b3-82e7-1b995cbb26e1)
    要做成竖排内横排可能比较花时间，大大否则可以考虑下增加一个标尺功能方便对齐？或者提供一个对齐功能。

3. 文本框内文字回车换行后，如果文本框过窄，会出现再次双击编辑文本框时，无法按鼠标位置进行光标定位的BUG
    譬如下图
![image](https://github.com/user-attachments/assets/2bd03ff4-8f92-43bf-a24b-ef7ef1fcf533)
    然后我断句后，文本框大小会自动扩展，然后按ESC使得文本框非编辑状态，如下图
![image](https://github.com/user-attachments/assets/c814cfe0-533d-4992-abdb-8c3a38a4c95a)
    然后，我双击文本的最末尾，想添加一个问号，光标位置只能在最前面，如图的红色箭头处
![image](https://github.com/user-attachments/assets/1c5bc262-bdd2-43ef-a0b4-3ec83c09a218)
    只有重新调整文本框大小，BUG才解除。

有劳大大百忙之中看一下，谢谢！

**Comment by dmMaze** [comment]
光标定位和拖拽的问题修好了。
ps 竖排内横排如果超过列宽会换行吗

**Comment by chou18194766xx** [comment]
> 光标定位和拖拽的问题修好了。 ps 竖排内横排如果超过所在列宽会换行吗？

大佬神速！

PS中竖排内横排不会换行，会扩展宽度。不过一般都会调整符号的宽度，让它变窄。
![image](https://github.com/user-attachments/assets/af970497-ee27-4366-87b5-4dbe34067c76)

调整后
![image](https://github.com/user-attachments/assets/f351003a-35fa-45b8-a565-e329fde05541)

调整的文本框比最开始的文本框要宽

**Comment by chou18194766xx** [comment]
补充一个小BUG，新增加的Alt+WSAD或箭头的快捷键，只有主界面选中文本框有效，右侧样式栏选择无效

**Comment by chou18194766xx** [comment]
再补充一个小BUG，同文本框如果中间有不一样大小的文字，左右间距不一样
![image](https://github.com/user-attachments/assets/cb46c06e-0752-4ba2-b3a5-87ba3e539e45)
