### ISSUE TITLE
Keyword substitution for machine translation not working?

### ISSUE THREAD

**Issue by andy-julot** [dmMaze/BallonsTranslator#567]
I want to substitute some kanji for name to it's romaji like this:

![Keyword Substitution for Machine Translation](https://github.com/user-attachments/assets/8eba4c52-30f7-4407-897c-82128ca2cb66)

But it seems not working, and I can't see the substitution in the log:

![Terminal](https://github.com/user-attachments/assets/4e0ff6f5-152f-4dd6-ac26-eba24f66bc72)

Or did I miss something?

Thanks in advance.

**Comment by dmMaze** [comment]
It's for translated text. If you're trying to replace the original text, it's Keyword substitution for OCR result.

**Comment by andy-julot** [comment]
I see.

Thank you for the explanation.
