### ISSUE TITLE
Can't Start-up after update

### ISSUE THREAD

**Issue by Raiter123** [dmMaze/BallonsTranslator#575]
Can't Start-up after update
![image](https://github.com/user-attachments/assets/8df28d19-90d6-432a-88d6-7f6a455249a4)

**Comment by bropines** [comment]
> Can't Start-up after update ![image](https://private-user-images.githubusercontent.com/153535038/364004154-8df28d19-90d6-432a-88d6-7f6a455249a4.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjUzNzYwMDMsIm5iZiI6MTcyNTM3NTcwMywicGF0aCI6Ii8xNTM1MzUwMzgvMzY0MDA0MTU0LThkZjI4ZDE5LTkwZDYtNDMyYS04OGQ2LTdmNmE0NTUyNDlhNC5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwOTAzJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDkwM1QxNTAxNDNaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1lNzE3OWM4MDMzZjFlODQwZmFkZGNkODAwNmM0ZDRiOTJmZmNhNTNkZjgyNDM3ZTcxY2MxODBhM2I4NTdjMGNmJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.ybLTq7hGrtO-HQEBX3gHunna3lsJ2P88CT-OOVNTSWc)

```python
pip install httpx_socks
```

**Comment by bropines** [comment]
https://github.com/dmMaze/BallonsTranslator/pull/574#issuecomment-2325974933

If it complains when recognized, do it
