### ISSUE TITLE
用pyinstaller将本项目打包成standalone macOS app的方法

### ISSUE THREAD

**Issue by ghost** [dmMaze/BallonsTranslator#58]
之前版本能够在M1 Max Mac上启动了，但后来电脑重装了，有些库都变过了，就重新来了一遍，新版本在maxOS上又无法启动了

requirements_macOS.txt 中的cocoa库没有找到，去PyPI也没有，我猜是不是pycocoa？改成pycocoa后requirements_macOS安装成功，然后运行python ballontranslator

报错如下，虽然using pyqt6，但还是提示找不到pyqt5

```
❯ python ballontranslator
/Users/usr/.pyenv/versions/3.9.12/lib/python3.9/site-packages/qtpy/__init__.py:267: RuntimeWarning: Selected binding "pyqt5" could not be found, using "pyqt6"
  warnings.warn('Selected binding "{}" could not be found, '
Traceback (most recent call last):
  File "/Users/usr/.pyenv/versions/3.9.12/lib/python3.9/runpy.py", line 197, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/Users/usr/.pyenv/versions/3.9.12/lib/python3.9/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "/Users/usr/Downloads/BallonsTranslator/ballontranslator/__main__.py", line 60, in <module>
    main()
  File "/Users/usr/Downloads/BallonsTranslator/ballontranslator/__main__.py", line 52, in main
    from ui.mainwindow import MainWindow
  File "/Users/usr/Downloads/BallonsTranslator/ballontranslator/ui/mainwindow.py", line 22, in <module>
    from .mainwindowbars import TitleBar, LeftBar, BottomBar
  File "/Users/usr/Downloads/BallonsTranslator/ballontranslator/ui/mainwindowbars.py", line 11, in <module>
    from .framelesswindow import startSystemMove
  File "/Users/usr/Downloads/BallonsTranslator/ballontranslator/ui/framelesswindow/__init__.py", line 6, in <module>
    from .fw_qt6.utils import startSystemMove
  File "/Users/usr/Downloads/BallonsTranslator/ballontranslator/ui/framelesswindow/fw_qt6/__init__.py", line 8, in <module>
    from .mac import AcrylicWindow
  File "/Users/usr/Downloads/BallonsTranslator/ballontranslator/ui/framelesswindow/fw_qt6/mac/__init__.py", line 8, in <module>
    from .window_effect import MacWindowEffect
  File "/Users/usr/Downloads/BallonsTranslator/ballontranslator/ui/framelesswindow/fw_qt6/mac/window_effect.py", line 5, in <module>
    from ..utils.mac_utils import getNSWindow
  File "/Users/usr/Downloads/BallonsTranslator/ballontranslator/ui/framelesswindow/fw_qt6/utils/__init__.py", line 7, in <module>
    from .mac_utils import MacMoveResize as MoveResize
  File "/Users/usr/Downloads/BallonsTranslator/ballontranslator/ui/framelesswindow/fw_qt6/utils/mac_utils.py", line 6, in <module>
    from PyQt5.QtCore import QT_VERSION_STR
ModuleNotFoundError: No module named 'PyQt5.QtCore'
```

**Comment by dmMaze** [comment]
你试下这里try from PyQt5... except: from PyQt6... 一下，如果可以就开个pr，其它类似的异常也一样处理

**Comment by blacklein** [comment]
/BallonsTranslator/ballontranslator/ui/framelesswindow/fw_qt6/utils/mac_utils.py
```
# coding:utf-8
from ctypes import c_void_p

import Cocoa
import objc
try from PyQt5... except: from PyQt6...
```
这样吗，还是会报错

**Comment by dmMaze** [comment]
> /BallonsTranslator/ballontranslator/ui/framelesswindow/fw_qt6/utils/mac_utils.py
> 
> ```
> # coding:utf-8
> from ctypes import c_void_p
> 
> import Cocoa
> import objc
> try from PyQt5... except: from PyQt6...
> ```
> 
> 这样吗，还是会报错

<img width="325" alt="image" src="https://user-images.githubusercontent.com/51270320/205018770-ddd32784-636f-475a-9e00-997bed52390b.png">

这样，其它类似的异常也如法炮制

**Comment by dmMaze** [comment]
> /BallonsTranslator/ballontranslator/ui/framelesswindow/fw_qt6/utils/mac_utils.py
> 
> ```
> # coding:utf-8
> from ctypes import c_void_p
> 
> import Cocoa
> import objc
> try from PyQt5... except: from PyQt6...
> ```
> 
> 这样吗，还是会报错

哦不用try except, 把这个fw_qt6里面所有的PyQt5都换成PyQt6

**Comment by blacklein** [comment]
```
❯ python __main__.py
/Users/usr/.pyenv/versions/3.9.12/lib/python3.9/site-packages/qtpy/__init__.py:267: RuntimeWarning: Selected binding "pyqt5" could not be found, using "pyqt6"
  warnings.warn('Selected binding "{}" could not be found, '
[ERROR  ] configpanel:__init__:281 - [Errno 2] No such file or directory: '/Users/usr/Downloads/BallonsTranslator/ballontranslator/data/config/config.json'
Traceback (most recent call last):
  File "/Users/usr/Downloads/BallonsTranslator/ballontranslator/ui/configpanel.py", line 277, in __init__
    with open(CONFIG_PATH, 'r', encoding='utf8') as f:
FileNotFoundError: [Errno 2] No such file or directory: '/Users/usr/Downloads/BallonsTranslator/ballontranslator/data/config/config.json'
[WARNING] configpanel:__init__:282 - Failed to load config file, using default config
[INFO   ] dl_manager:on_finish_setdetector:634 - Text detector set to ctd
[INFO   ] dl_manager:on_finish_settranslator:655 - Translator set to google
[INFO   ] dl_manager:on_finish_setocr:640 - OCR set to mit32px
[INFO   ] dl_manager:on_finish_setinpainter:647 - Inpainter set to lama_mpe
```
可以启动了，但有提示error，这个有影响吗？

**Comment by dmMaze** [comment]
> ```
> ❯ python __main__.py
> /Users/usr/.pyenv/versions/3.9.12/lib/python3.9/site-packages/qtpy/__init__.py:267: RuntimeWarning: Selected binding "pyqt5" could not be found, using "pyqt6"
>   warnings.warn('Selected binding "{}" could not be found, '
> [ERROR  ] configpanel:__init__:281 - [Errno 2] No such file or directory: '/Users/usr/Downloads/BallonsTranslator/ballontranslator/data/config/config.json'
> Traceback (most recent call last):
>   File "/Users/usr/Downloads/BallonsTranslator/ballontranslator/ui/configpanel.py", line 277, in __init__
>     with open(CONFIG_PATH, 'r', encoding='utf8') as f:
> FileNotFoundError: [Errno 2] No such file or directory: '/Users/usr/Downloads/BallonsTranslator/ballontranslator/data/config/config.json'
> [WARNING] configpanel:__init__:282 - Failed to load config file, using default config
> [INFO   ] dl_manager:on_finish_setdetector:634 - Text detector set to ctd
> [INFO   ] dl_manager:on_finish_settranslator:655 - Translator set to google
> [INFO   ] dl_manager:on_finish_setocr:640 - OCR set to mit32px
> [INFO   ] dl_manager:on_finish_setinpainter:647 - Inpainter set to lama_mpe
> ```
> 可以启动了，但有提示error，这个有影响吗？

没有，这个应该搞成warning的

**Comment by blacklein** [comment]
可以运行，我在试着打包成独立的macOS app，方便使用，不知道能不能成，如果能成，我把spec内容贴上来

**Comment by blacklein** [comment]
翻译失败，是谷歌翻译失效了吗
```
Traceback (most recent call last):
  File "/Users/usr/Downloads/BallonsTranslator/ballontranslator/ui/dl_manager.py", line 187, in _translate_page
    self.translator.translate_textblk_lst(page)
  File "/Users/usr/Downloads/BallonsTranslator/ballontranslator/dl/translators/__init__.py", line 153, in translate_textblk_lst
    translations = self.translate(text_list)
  File "/Users/usr/Downloads/BallonsTranslator/ballontranslator/dl/translators/__init__.py", line 126, in translate
    text_trans = self._translate(text_source)
  File "/Users/usr/Downloads/BallonsTranslator/ballontranslator/dl/translators/__init__.py", line 213, in _translate
    translations = self.googletrans.translate(text)
  File "/Users/usr/Downloads/BallonsTranslator/ballontranslator/dl/translators/google_trans.py", line 193, in translate
    raise RequestError()
dl.translators.exceptions.RequestError: Request exception can happen due to an api connection error. Please check your connection and try again
```

另外打包用sudo pyinstaller --add-data "data:." -p ./dl -p ./scripts -p ./tests -p ./ui -p utils -F -w __main__.py
打出来1.43GB的app，但双击闪退，也没有跳出来报错信息

**Comment by dmMaze** [comment]
> 翻译失败，是谷歌翻译失效了吗
> ```
> Traceback (most recent call last):
>   File "/Users/usr/Downloads/BallonsTranslator/ballontranslator/ui/dl_manager.py", line 187, in _translate_page
>     self.translator.translate_textblk_lst(page)
>   File "/Users/usr/Downloads/BallonsTranslator/ballontranslator/dl/translators/__init__.py", line 153, in translate_textblk_lst
>     translations = self.translate(text_list)
>   File "/Users/usr/Downloads/BallonsTranslator/ballontranslator/dl/translators/__init__.py", line 126, in translate
>     text_trans = self._translate(text_source)
>   File "/Users/usr/Downloads/BallonsTranslator/ballontranslator/dl/translators/__init__.py", line 213, in _translate
>     translations = self.googletrans.translate(text)
>   File "/Users/usr/Downloads/BallonsTranslator/ballontranslator/dl/translators/google_trans.py", line 193, in translate
>     raise RequestError()
> dl.translators.exceptions.RequestError: Request exception can happen due to an api connection error. Please check your connection and try again
> ```
> 
> 另外打包用sudo pyinstaller --add-data "data:." -p ./dl -p ./scripts -p ./tests -p ./ui -p utils -F -w __main__.py
> 打出来1.43GB的app，但双击闪退，也没有跳出来报错信息

设置页面把谷歌的url换掉，启用全局代理，那个.cn被谷歌扬了
我win是nuitka 打包的，不是很熟mac怎么用pyinstaller，一般问题是缺包直接把py装的拷过去就行了

另外#59是不是缺了PyQt5替换成PyQt6的提交...

**Comment by blacklein** [comment]
换翻译器就好了，ui界面和嵌字效果比以前好不少，以前ui字和图标特别大

**Comment by blacklein** [comment]
看了下nuitka仓库介绍，和pyinstaller使用方法差不多，我回去再试试

可以发一下nuitka打包windows应用的命令参考下吗

**Comment by dmMaze** [comment]
> 看了下nuitka仓库介绍，和pyinstaller使用方法差不多，我回去再试试
> 
> 可以发一下nuitka打包windows应用的命令参考下吗

见scripts/build_win.bat
这条打包指令会跳过三方库的编译（不然打包时间会很长），完了你还得手动把三方库拷过去...
以后更新再打包就只更新可执行文件和其它图标模型资源（需要的话）

**Comment by blacklein** [comment]
nuitka 在mac上打包比我预想还要复杂，还是选择用pyinstaller打吧
目前跳出来找不到module，网上搜了好几个办法都解决不了
```
❯ ./__main__
qtpy/__init__.py:267: RuntimeWarning: Selected binding "pyqt5" could not be found, using "pyqt6"
Traceback (most recent call last):
  File "ballontranslator/__main__.py", line 60, in <module>
  File "ballontranslator/__main__.py", line 30, in main
ModuleNotFoundError: No module named 'ui'
[45035] Failed to execute script '__main__' due to unhandled exception!
```

**Comment by blacklein** [comment]
> > 此处有坑，本项目非常、非常、非常吃内存，16GB内存不一定hold住，内存溢出启动应用会闪退，我16GB的intel mac启动应用闪退，但32GB M1 Mac启动应用不闪退
> 
> 跑模型前windows上占用内存不到400M, 跑后不到4G...
> macOS上跑打包的程序和源码都占那么大内存吗...
> 
源码和app都占这么大内存，动辄20g内存，可能跟mac内存机制有关
> 
> > 找网络素材随便组了个图标，比较丑，希望作者能提供个官方图标
> 
> 本来有意试下用最近的一些diffusion来搞不过一直搁了
> 
sd ai画图入门挺难的
> 
> > 运行翻译的时候，有时候（是有时候）到翻译环节会闪退，报错类型的官方解释如下
> 
> 这个问题是打包的有还是在mac上跑源码也有? 
> 如果是打包程序闪退，用终端启动，闪退了可以看到报错信息然后搜那个...我没mac感觉也帮不上啥
> 
> 最后感谢折腾~
> 
我明天试试，ctypes是cpython的一部分，我明天安装cpython看看
