### ISSUE TITLE
软件的result导出的图片和源文件图片的大小不一样

### ISSUE THREAD

**Issue by l2959414766** [dmMaze/BallonsTranslator#581]
问一下大佬，为什么完成的导出的图片png 和源文件jpg 的大小不一样（导出的图片比原图片要小）但是像素都是一样大小的，导出的无字图却和原图片差不多大小

**Comment by dmMaze** [comment]
你用的是哪个版本软件？如果不是新版照 readme 用新版，如果是方便的话发一下原图（发我邮件也行
另外什么叫像素是一样大小的？标题的大小指的不是像素（长宽）大小？

**Comment by l2959414766** [comment]
![局部截取_20240909_080031](https://github.com/user-attachments/assets/6c25b515-81df-48dc-9e51-a40fddd37480)
![局部截取_20240909_080133](https://github.com/user-attachments/assets/bb51140d-5f78-481a-bfb8-52f074732fa8)
![局部截取_20240909_080337](https://github.com/user-attachments/assets/4da63882-4a0e-46a7-9d21-8ec6beaa2c23)
我也不知道在哪里看版本，你看看我的版本对吗。
最后那个图就jpg的是原图png是汉化完的图，一个5mb一个4mb。是这个意思

**Comment by bropines** [comment]
> 我也不知道在哪里看版本，你看看我的版本对吗。
> 最后那个图就jpg的是原图png是汉化完的图，一个5mb一个4mb。是这个意思

It's better to copy the top part from the console, in this form.

```bat
"Ya zapustil venv"
py version:  3.10.9 (tags/v3.10.9:1dd9be6, Dec  6 2022, 20:01:21) [MSC v.1934 64 bit (AMD64)]
py executable:  G:\Ballon-translator-portable-main\venv\Scripts\python.exe
version: 1.4.0
branch: dev
Commit hash: 77d18dc770b151553df8c2facf68cc64847498a7
[INFO   ] launch:main:184 - QT_API: pyqt6, QT Version: 6.6.1
```

In fact, we only need this line:
Commit hash: 77d18dc770b151553df8c2facf68cc64847498a7

**Comment by dmMaze** [comment]
> ![局部截取_20240909_080031](https://private-user-images.githubusercontent.com/45125219/365476290-6c25b515-81df-48dc-9e51-a40fddd37480.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjU4NDA4NDcsIm5iZiI6MTcyNTg0MDU0NywicGF0aCI6Ii80NTEyNTIxOS8zNjU0NzYyOTAtNmMyNWI1MTUtODFkZi00OGRjLTllNTEtYTQwZmRkZDM3NDgwLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA5MDklMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwOTA5VDAwMDkwN1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWQ3NzkwMjcwYjIxYTFhYWVlYWQ0YzVlZjVlMjEyNDVlMjAxZjBlYzRhYjliYjYzOGQxOWY3OThlOWYzN2Q2MGYmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.mx2evLNBbOdA-EhowfvAhzMJ343a7W0Wn7bSDwNc2PM) ![局部截取_20240909_080133](https://private-user-images.githubusercontent.com/45125219/365476292-bb51140d-5f78-481a-bfb8-52f074732fa8.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjU4NDA4NDcsIm5iZiI6MTcyNTg0MDU0NywicGF0aCI6Ii80NTEyNTIxOS8zNjU0NzYyOTItYmI1MTE0MGQtNWY3OC00ODFhLWJmYjgtNTJmMDc0NzMyZmE4LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA5MDklMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwOTA5VDAwMDkwN1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWQ1OTY4YmM2OGRiNmQ3MzVkYmIyOGRjOTZlOWMwMjdmOTA5M2MxYzJlYzBmYWI4ZDBiOTI0ZjdlNTI2ZGJlMTEmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.A6bWhVhHJkdntsJEsonBPd4ntaEAC_dDKKSi27wMcuY) ![局部截取_20240909_080337](https://private-user-images.githubusercontent.com/45125219/365476293-4da63882-4a0e-46a7-9d21-8ec6beaa2c23.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjU4NDA4NDcsIm5iZiI6MTcyNTg0MDU0NywicGF0aCI6Ii80NTEyNTIxOS8zNjU0NzYyOTMtNGRhNjM4ODItNGEwZS00NmE3LTlkMjEtOGVjNmJlYWEyYzIzLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA5MDklMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwOTA5VDAwMDkwN1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTBiYjU0MDEzNzNiMjU4OTkyNTk1YzI4M2I5NmM1YzJmMjA2ZmI5OTc2MjllZGNiNGE1YzFjMDlmYmM1ZmYyNWMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0._EdfVfO4HaQ9hKL7kMD6xtd30EF1CywjqpsQwg5d_QA) 我也不知道在哪里看版本，你看看我的版本对吗。 最后那个图就jpg的是原图png是汉化完的图，一个5mb一个4mb。是这个意思

图变小了不是坏事吧。png 就是和 jpg 不同的图像压缩算法，少数情况下（比如色彩很少）可能会得到更小的图，详情自行谷歌
