### ISSUE TITLE
求各位大佬能不能来个压缩包一次到位我受不鸟了

### ISSUE THREAD

**Issue by heiyanmaster** [dmMaze/BallonsTranslator#583]
求各位大佬能不能来个压缩包一次到位我受不鸟了求个zip压缩包所有环境一次到位我受不鸟了！！！！！！！！！！！！！！！！！！！！！！！

**Comment by bropines** [comment]
https://github.com/bropines/Ballon-translator-portable

**Comment by bropines** [comment]
Apparently you didn't really want to look

**Comment by heiyanmaster** [comment]
> Apparently you didn't really want to look

I'm a little crazy

**Comment by bropines** [comment]
> > Apparently you didn't really want to look
> 
> I'm a little crazy

If I helped you, close ISSUE)
