### ISSUE TITLE
 Font size issues (again)

### ISSUE THREAD

**Issue by howcare1** [dmMaze/BallonsTranslator#584]
Last week there was a report about font size (Issues #576). And this morning (Sep 10) there was an update to fix the issue. But the issues I mentioned still exists. Here is the video where I want to demonstrate the issue.
https://www.youtube.com/watch?v=_5P_kD1ZXks
In the Typesetting tab I adjusted Font size: use global setting. then I set Global Font Format to size 28, but when I RUN the specified font size of the speech bubble is bigger maybe 33-34. the same happens when I point at another number for example 12 it is always bigger like 18. or 40 to 56. 
This has never happened before. And my version is: github clone September 10.
English is not my native language sorry if my expression is not correct.
P/s: Thanks for creating this amazing software.

**Comment by bropines** [comment]
> Last week there was a report about font size (Issues #576). And this morning (Sep 10) there was an update to fix the issue. But the issues I mentioned still exists. Here is the video where I want to demonstrate the issue.
> [youtube.com/watch?v=_5P_kD1ZXks](https://www.youtube.com/watch?v=_5P_kD1ZXks)
> In the Typesetting tab I adjusted Font size: use global setting. then I set Global Font Format to size 28, but when I RUN the specified font size of the speech bubble is bigger maybe 33-34. the same happens when I point at another number for example 12 it is always bigger like 18. or 40 to 56.
> This has never happened before. And my version is: github clone September 10.
> English is not my native language sorry if my expression is not correct.
> P/s: Thanks for creating this amazing software.

~Are font settings enabled as global in settings?~ And create a temporary test block using the new settings after changing the parameters. It should help.
![image](https://github.com/user-attachments/assets/48447c7a-85ce-469d-a3a6-62448f0af5f5)

Our config may change a little strangely. If after the temporary initial block everything is fixed, then I think I know what the problem is

**Comment by howcare1** [comment]
> > Tuần trước có một báo cáo về cỡ chữ (Sự cố #576 ). Và sáng nay (ngày 10 tháng 9) đã có bản cập nhật để khắc phục sự cố. Nhưng các sự cố tôi đã đề cập vẫn tồn tại. Đây là video mà tôi muốn chứng minh sự cố. 
> > [youtube.com/watch?v=_5P_kD1ZXks](https://www.youtube.com/watch?v=_5P_kD1ZXks) 
> > Trong tab Typesetting, tôi đã điều chỉnh cỡ chữ: sử dụng cài đặt chung. sau đó tôi đặt Định dạng phông chữ chung thành cỡ 28, nhưng khi tôi CHẠY, cỡ chữ được chỉ định của bong bóng lời thoại lớn hơn, có thể là 33-34. điều tương tự cũng xảy ra khi tôi trỏ vào một số khác, ví dụ 12, nó luôn lớn hơn như 18. hoặc 40 đến 56. 
> > Điều này chưa bao giờ xảy ra trước đây. Và phiên bản của tôi là: github clone ngày 10 tháng 9. 
> > Tiếng Anh không phải là ngôn ngữ mẹ đẻ của tôi, xin lỗi nếu cách diễn đạt của tôi không chính xác. 
> > P/s: Cảm ơn bạn đã tạo ra phần mềm tuyệt vời này.
> 
> Cài đặt phông chữ có được bật là toàn cục trong cài đặt không? Và tạo một khối thử nghiệm tạm thời bằng cách sử dụng cài đặt mới sau khi thay đổi các tham số. Nó sẽ giúp ích. ![hình ảnh](https://private-user-images.githubusercontent.com/57861007/366178457-48447c7a-85ce-469d-a3a6-62448f0af5f5.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjU5OTUwOTgsIm5iZiI6MTcyNTk5NDc5OCwicGF0aCI6Ii81Nzg2MTAwNy8zNjYxNzg0NTctNDg0NDdjN2EtODVjZS00NjlkLWEzYTYtNjI0NDhmMGFmNWY1LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA5MTAlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwOTEwVDE4NTk1OFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWRmYjNiNWEzYmJhZjgwNWJjZjgwMDE1MWQ5ZjAzNGJlMDBmYTdjNDZmODUzNjcyMDY5OTNkZjAwYTdlMGYxYzEmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.xdSZHx94tN5pLgABB4lhYiymtKwkwkohW8GBtJHFDw4)

Of course i have it set to "use global setting" as i showed at the beginning of the video
![Screenshot 2024-09-11 020039](https://github.com/user-attachments/assets/1db0fa87-7dd1-4fd5-8d87-af3d5c73b121)

**Comment by bropines** [comment]
Is your size a little larger after running `RUN`? I just start it away. I have global 8, but all blocks are 14.2

**Comment by howcare1** [comment]
I noticed that the imgtrans_*.json file has "font_size" set: 28.0, which means the font size preview in the main interface is showing incorrectly.
![Uploading Screenshot 2024-09-11 020359.png…]()

**Comment by howcare1** [comment]
So every time I preview the font size I have to estimate that their size will increase by 18% @@

**Comment by howcare1** [comment]
I noticed that the imgtrans_*.json file has "font_size" set: 37.333333333333339, which means the font size preview in the main interface is showing incorrectly. If it was a previous version, it would be "font_size":28.333333333339
![Screenshot 2024-09-11 021551](https://github.com/user-attachments/assets/28c2663c-e726-4756-ae28-5eb3f87a9adb)

**Comment by bropines** [comment]
Yes, this is some kind of bug, and for me it is also growing by strictly N percent. It doesn't matter what settings.

**Comment by howcare1** [comment]
i don't know if this issue is will be resolve or not. So do you know any way to clone github commits file on specific date (Sep 3) the day before the text layout update is posted?

**Comment by bropines** [comment]
> i don't know if this issue is resolved or not. So do you know any way to clone github commits file on specific date (Sep 3) the day before the text layout update is posted?

You can use GIT commands to roll back to a specific commit knowing its HASH.

```bash
git checkout -b <new-branch-name> <commit the hash of that old commit>
```

If you want to go back, write 
```bash
git switch dev
```

**Comment by howcare1** [comment]
i really don't know how to use the command can you help me get the hash of that update? I would appreciate it.

**Comment by bropines** [comment]
![image](https://github.com/user-attachments/assets/9ad8fe48-5798-4e54-83d8-10f711dfa23b)

I don’t know which one you need, so here is a button that copies HASH

**Comment by howcare1** [comment]
> ![image](https://private-user-images.githubusercontent.com/57861007/366190447-9ad8fe48-5798-4e54-83d8-10f711dfa23b.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjU5OTgwMTUsIm5iZiI6MTcyNTk5NzcxNSwicGF0aCI6Ii81Nzg2MTAwNy8zNjYxOTA0NDctOWFkOGZlNDgtNTc5OC00ZTU0LTgzZDgtMTBmNzExZGZhMjNiLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA5MTAlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwOTEwVDE5NDgzNVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTFmNWUwODhhOWY4YTM5OGUxZmFiMjIxMGI5NzZiZTUzZTUwNjUzMmRhNzlkMGUzZWU5ZjYxMDMzMmRhYjI1MWQmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.c19CR9dR0Fc6Dae38sz_1P25aZy5okvUoyMxfX7usSA)
> 
> I don’t know which one you need, so here is a button that copies HASH

Oh very thanks it work, I rollback Sep 3 and my issues has solved.

**Comment by dmMaze** [comment]
@howcare1 [d96e1ef](https://github.com/dmMaze/BallonsTranslator/commit/d96e1ef00899b49468b36977418e5fe69a9ae362) should fix it. It is generally a bad idea to roll back. 
Besides, font_size in imgtrans_*.json should be consistent with the one displayed in UI, which is different from the previous version, such changes are expected and should not affect your actual usage.
