### ISSUE TITLE
自动去除v1/斜杠后会向/v1chat/completions发送请求

### ISSUE THREAD

**Issue by popcion** [dmMaze/BallonsTranslator#587]
以前不带/v1出错，/v1/正常，现在自动删除末尾斜杠后会出错
`[DEBUG  ] trans_chatgpt:api_url:349 - Removed trailing slash after 'v1': https://xxx.com/v1
[INFO   ] _base_client:_retry_request:1007 - Retrying request to /chat/completions in 0.880331 seconds
[INFO   ] _base_client:_retry_request:1007 - Retrying request to /chat/completions in 0.880331 seconds
[INFO   ] _client:_send_single_request:1013 - HTTP Request: POST https://xxx.com/v1chat/completions "HTTP/1.1 404 Not Found"
[WARNING] trans_chatgpt:_translate:261 - Translation failed due to Error code: 404 - {'error': {'message': 'Invalid URL (POST /v1chat/completions)', 'type': 'invalid_request_error', 'param': '', 'code': ''}}. Attempt: 1, sleep for 10 secs...`
去除以下检查后正常
`  # 移除末尾的斜杠
        if url.endswith('v1/'):
            url = url[:-1]
            self.logger.debug(f"Removed trailing slash after 'v1': {url}")`

**Comment by popcion** [comment]
另外不知道是不是卡bug了，CTRL+A会选择右侧栏全体，没选择左侧图上的框，而且在图上点击滑动光标也无法出现框，只有手指光标，需要点击右侧的内容才能在左侧显示对应的框，并且无法拖动文字框。重启几次恢复了，暂时没能复现。

另外，是否能增加ctd检测精度，mangaimagetranslator的文本扫描应该能到更高，现在气球的上限是1280，完全不够用，或者如何手动调高，ctd检测出来是一坨，OCR无法识别得到非常多的空白结果，在处理上百页的漫画时还会出现部分整页原文都是空白的情况，已经影响正常使用了。曾经使用mangaimagetranslator时，这个精度会严重影响翻译效果，基于数十本漫画翻译效果，基于相同模型的最终翻译结果，我认为1536px到2048px之间检测精度差距极大，1024会出现严重错误识别，个人一般拉到2048或2560这样，inpainting就调低一些节省内存，因为翻译已经较为准确了，嵌的时候反而不需要那么高了，或者说在不追求极致清晰度的情况下个人使用没什么必要，1024已经非常足够了。现在气球反倒是inpainting能调很高，仅作建议，我不清楚其他人用气球是否遇到这种现象。

**Comment by xyjandyyk** [comment]
我目前也是，不加斜杠就会缺失一个斜杠，如果加了就会多一个斜杠出来

**Comment by dmMaze** [comment]
再更新一下应该就好了
