### ISSUE TITLE
 cuDNN error: CUDNN_STATUS_NOT_INITIALIZED Text Detection Failed

### ISSUE THREAD

**Issue by mxsry** [dmMaze/BallonsTranslator#590]
upon press RUN it appear a window show this text :

"cuDNN error: CUDNN_STATUS_NOT_INITIALIZED
Text Detection Failed."

Is there any download file that i missing or is that any error that you guys can help me fix?
Thanks for take a look at this and hope u guys can response me asap

**Comment by bropines** [comment]
Try this
```bash
# CUDA 11.8
pip install -U torch==2.2.2 torchvision==0.17.2 torchaudio==2.2.2 --index-url https://download.pytorch.org/whl/cu118
# CUDA 12.1
pip install -U torch==2.2.2 torchvision==0.17.2 torchaudio==2.2.2 --index-url https://download.pytorch.org/whl/cu121
```

**Comment by mxsry** [comment]
It said this:

Found GPU0 Quadro K4200 which is of cuda capability 3.0.
PyTorch no longer supports this GPU because it is too old.
The minimum cuda capability supported by this library is 3.7.

Is there any way for me to still run the apps without cuda ?
