### ISSUE TITLE
dots problem in arabic

### ISSUE THREAD

**Issue by abasameer** [dmMaze/BallonsTranslator#592]
Hello,

I am experiencing an issue when translating text into Arabic. The problem is that certain parts of the characters, especially the dots (Niqkat), become unclear or disappear unless I increase the size of the text box. This makes it difficult to read the translated text properly.

I have attached two screenshots to demonstrate the issue:

- In the first screenshot, you can see that the text is clear when the text box is larger.
- In the second screenshot, the text becomes unclear and some dots are missing when the text box is smaller.

I believe this issue is related to how the program handles Arabic font rendering in smaller text boxes.

Could you please look into this issue? I would greatly appreciate any help or advice you can provide.

Thank you for your assistance.

![Screenshot 2024-09-19 213516](https://github.com/user-attachments/assets/e1929c19-46ed-4a6b-b10d-21eae543fc66)
![Screenshot 2024-09-19 213511](https://github.com/user-attachments/assets/8fab085c-93ce-4d91-9ef1-df1bc119366f)

**Comment by dmMaze** [comment]
What is the font you're using?

**Comment by abasameer** [comment]
> What is the font you're using?

Hayah font

https://arbfonts.com/hayah-font-download.html

**Comment by abasameer** [comment]
> What is the font you're using?

Hayah font

https://arbfonts.com/hayah-font-download.html

**Comment by abasameer** [comment]
> What is the font you're using?

Hayah font

https://arbfonts.com/hayah-font-download.html

**Comment by dmMaze** [comment]
I can't reproduce it using the font. There is a new change trying to fix it, you could try to update the program to see if the problem gets resolved.

**Comment by abasameer** [comment]
> I can't reproduce it using the font. There is a new change trying to fix it, you could try to update the program to see if the problem gets resolved.

yes, thanks
