### ISSUE TITLE
关于文字方向的问题

### ISSUE THREAD

**Issue by XVX415** [dmMaze/BallonsTranslator#600]
![123](https://github.com/user-attachments/assets/6d1d0e7a-6e8e-4059-bf4d-01995df1b5c7)
大佬，我想问一下有什么方法可以把右边框里竖排文字里的数字和字母单独改变方向吗？就像左边的文字那样
我在教程里没有看到方法
现在改变方向只能单独再拉一个框，还要单独改排版

**Comment by dmMaze** [comment]
现在暂时只能把右边的字符转成全角，全角字符不会被旋转。
你要是会 python 的话可以自己 parse 项目文件转一下

**Comment by XVX415** [comment]
> 现在暂时只能把右边的字符转成全角，全角字符不会被旋转。 你要是会 python 的话可以自己 parse 项目文件转一下

谢谢你的方法，虽然我不会python，但是输入法可以切换全角输入，也算是解决了，比左边那样方便多了。
