### ISSUE TITLE
.

### ISSUE THREAD

**Issue by Figurecollection** [dmMaze/BallonsTranslator#601]
.

**Comment by bropines** [comment]
In terms of. How does this “prefill” work and why does it allow GPT to write r18?

**Comment by Figurecollection** [comment]
> In terms of. How does this “prefile” work and why does it allow GPT to write r18?

I don't know because I'm not a programmer. However, for those with the necessary knowledge, analyzing the source code of that program might help them understand how it works.

**Comment by bropines** [comment]
> I don't know because I'm not a programmer. However, for those with the necessary knowledge, analyzing the source code of that program might help them understand how it works.

I've already looked. Another question is, what do you put in there that it doesn’t check censorship? You can write to me on Telegram (link in profile) if you don’t want this to end up on GitHub. It’s just that it actually works as a system industrial program, but as part of the GPT knowledge base, which is not particularly clear to me
