### ISSUE TITLE
这是bug吗还是正常的？

### ISSUE THREAD

**Issue by huimieba** [dmMaze/BallonsTranslator#603]
打“又”字时字体会偏左
<img width="66" alt="屏幕截图 2024-09-29 225000" src="https://github.com/user-attachments/assets/c9965020-65dd-4fe3-ae31-66618fa55c4b">
<img width="217" alt="屏幕截图 2024-09-29 225024" src="https://github.com/user-attachments/assets/bb40679b-78cc-4ac5-aacc-8ba3ca3e0fbe">
会偏左

**Comment by dmMaze** [comment]
不正常
你是啥系统，在跑哪个版本，这是啥字体

**Comment by huimieba** [comment]
> 不是 你是啥系统，在跑哪个版本，这是啥字体

操作系统还是pyqt？操作系统是win11，pyqqts6.6.1，版本是最新的，字体的话是幼圆

**Comment by dmMaze** [comment]
我打这段是正常的
你这段文本贴上来我试试

**Comment by huimieba** [comment]
> 我打这段是正常的 你这段文本贴上来我试试

刚刚重进之后又显示正常了，大佬

**Comment by aqssxlzc** [comment]
这个我遇到过。感觉是前面有一个非打印字符造成的，一般往前删除一部分字符，然后重新输入可以解决。

**Comment by huimieba** [comment]
> 这个我遇到过。 感觉是前面有一个非打印字符造成的，一般往前删除一部分字符，然后重新输入可以解决。

删过了，但是好像没用，重进之后好像才没事，应该就是一些问题不大的bug
