### ISSUE TITLE
CUDA Device Precision Error

### ISSUE THREAD

**Issue by ghost** [dmMaze/BallonsTranslator#607]
Error Message: 

[ERROR] base:_inpaint:363 - Current CUDA Device does not support bfloat16. Please switch dtype to float16.
[ERROR] base:_inpaint:364 - torch.bfloat16 inference is not supported for this device, use fp32 instead.

When attempting to run the inpainting function, I encountered an error indicating that the current CUDA device does not support bfloat16 precision. The system suggests switching to float16, but it appears that mixed-precision inference with float16 may also not be fully supported. Could you please provide guidance on how to modify the code to handle precision switching effectively? Specifically, I'd like to ensure that the model can fall back to float32 gracefully if float16 is unsupported, while attempting to use float16 where possible for performance improvements.

Thank you for your help!

**Comment by bropines** [comment]
What kind of video card do you have?

**Comment by ghost** [comment]
Nvidia MX 150 and also I noticed that at first it works perfectly fine with no problem but then this error shows up.

**Comment by bropines** [comment]
You're using antiquity. Torch probably doesn't work well with him

**Comment by ghost** [comment]
Thanks, I guess I need to change the GPU that will work well with this project.

**Comment by bropines** [comment]
> Thanks, I guess I need to change the GPU that will work well with this project.

I've been testing on 
1050TI - OK, but not enough memory
1650 6GB is plenty.
3050 4GB - Works great, but not enough memory
3060 12GB - Everything works perfectly in BF16
