### ISSUE TITLE
I want to set the detect_size larger than 1280. Is it possible to do that?

### ISSUE THREAD

**Issue by KorawitP** [dmMaze/BallonsTranslator#608]
![สกรีนช็อต 2024-10-06 135740](https://github.com/user-attachments/assets/4efdef15-f6b7-449a-9cba-092bd0b998ce)

**Comment by KorawitP** [comment]
I have fixed it now. 
![สกรีนช็อต 2024-10-06 141422](https://github.com/user-attachments/assets/a3122f08-834c-44cc-a63e-3f378dad0010)

**Comment by bropines** [comment]
Are you sure that the model can handle this size?
