### ISSUE TITLE
可以添加插入文本框的功能吗

### ISSUE THREAD

**Issue by asdaragon** [dmMaze/BallonsTranslator#617]
现在只有OCR后自动产生的文本框里填内容，有时候想添加一些备注说明只能另外PS，很不方便，能不能在画板里添加插入文本框的功能？

**Comment by dmMaze** [comment]
https://github.com/dmMaze/BallonsTranslator/blob/dev/doc/src/textedit.gif

**Comment by asdaragon** [comment]
明白了，感谢，原来是拖动右键拉出文本框
