### ISSUE TITLE
横竖排变换

### ISSUE THREAD

**Issue by nisumoly** [dmMaze/BallonsTranslator#625]
我用英语原本去转换，结果的文字是横排的，好像没找到变为竖排的地方。不知道是我初心还是这个功能暂且没有？

**Comment by bropines** [comment]
![python_m4xkYwHoIr](https://github.com/user-attachments/assets/6a79bbdc-6112-4833-9150-234c83c23384)
I understand Chinese very poorly, but try this, it will change the writing direction to vertical

![python_xMIjYvWR9r](https://github.com/user-attachments/assets/abc88d93-c610-438e-b88b-a7ae45c0795b)
![python_69CerDJwB7](https://github.com/user-attachments/assets/5a4b11fa-e47c-4ab8-bd3f-01971cf26a33)

**Comment by dmMaze** [comment]
输入法用全角字符

**Comment by nisumoly** [comment]
Thanks very much
