### ISSUE TITLE
OCR google lenc (When you turn on this scanner. Doesn't want to translate certain pages)

### ISSUE THREAD

**Issue by 0Over0** [dmMaze/BallonsTranslator#627]
For example, out of 100 pages, 12 may not be translated. Moreover, if I try to translate these pages separately, the result will be the same. There are no translation problems on other scanners. (If anything, I speak Russian)

![Безымянный 132214](https://github.com/user-attachments/assets/2fd3c086-2dfc-4a10-adf5-d57433df00b3)
![Безымянный 213441242](https://github.com/user-attachments/assets/ee3430fb-1993-44e6-9820-67082f34a75d)

**Comment by bropines** [comment]
Напиши мне в тг. Так будет быстрее.
@bropines

**Comment by 0Over0** [comment]
Я отправил приглашение. Я раньше никогда телеграмом не пользовался

**Comment by bropines** [comment]
@dmMaze Google translator died, I also get an error. 
```python
[ERROR  ] base:translate:165 - This translator seems to messed up the translation which resulted in inconsistent translated line count.
                              Set concate_text to False or change textblk_break in the source code may solve the problem.
Traceback (most recent call last):
  File "G:\Ballon-translator-portable-main\ui\module_manager.py", line 486, in run
    self.job()
  File "G:\Ballon-translator-portable-main\ui\module_manager.py", line 310, in <lambda>
    self.job = lambda : self._blktrans_pipeline(blk_list, tgt_img, mode, blk_ids, tgt_mask)
  File "G:\Ballon-translator-portable-main\ui\module_manager.py", line 322, in _blktrans_pipeline
    self.translate_thread.module.translate_textblk_lst(blk_list)
  File "G:\Ballon-translator-portable-main\modules\translators\base.py", line 205, in translate_textblk_lst
    _translations = self.translate(text_list)
  File "G:\Ballon-translator-portable-main\modules\translators\base.py", line 163, in translate
    assert len(text_trans) == len(text)
AssertionError

```

**Comment by dmMaze** [comment]
@bropines 
It's not dead:

> ```python
> base:translate:165 - This translator seems to messed up the translation which resulted in inconsistent translated line count.
>                               Set concate_text to False or change textblk_break in the source code may solve the problem.
> ```

**Comment by bropines** [comment]
>It's not dead:
> 
> >

Well, it’s different for me. In 2 mangas the effect is the same, in the third everything is fine. He doesn't give out the data clearly. I can add logs and see what went wrong

**Comment by bropines** [comment]
> @bropines It's not dead:
> 
> > ```python
> > base:translate:165 - This translator seems to messed up the translation which resulted in inconsistent translated line count.
> >                               Set concate_text to False or change textblk_break in the source code may solve the problem.
> > ```

Короче. Решил я потестить что и как. Это была какая-то вчерашная приколюха от гугла. Потому что сейчас он работает на любом кол-ве текста без нареканий. Либо гугл сломали фронтенд, либо мы просто вовремя пришли на их баги. Сейчас я прогнал с десяток комиксов, все великолепно работает (правда долго)

---
Briefly speaking. I decided to test what and how. It was some kind of yesterday's prank from Google. Because now it works on any amount of text without any complaints. Either Google broke the frontend, or we just caught their bugs in time. Now I've run about a dozen comics, everything works great (though it takes a long time)
