### ISSUE TITLE
批量导入翻译

### ISSUE THREAD

**Issue by tohsakrat** [dmMaze/BallonsTranslator#630]
生成式ai发展太快，内置的接口有点跟不上了
现在的工作流是用内置百度翻译粗翻，然后在shell窗口的debug信息里把漫画从头到尾全文复制，复制到生成式ai比如claude和kimi里面翻译（chatgpt太贵而且体感虽然它逻辑能力更强，但文学能力完全不如Claude ，kimi豆包等则胜在不要钱）然后再一句一句粘贴回文本框，有点重复搬运工作了。
要是能一次性复制一整夜回翻译器，回车两下把行对齐，就能去搬运下一页就好了。

**Comment by tohsakrat** [comment]
因为这个需求的存在，同时还希望一个工程内部可以存在多套翻译，互相核对

**Comment by dmMaze** [comment]
现在可以批量导入了，和导出在同一个下拉单下。需要保证导入文件的结构和导出原文的一致。

**Comment by tohsakrat** [comment]
请问可以支持txt导入和导出吗，大部分对上下文理解能力良好的ai翻译工具貌似对doc文档支持都较差

**Comment by dmMaze** [comment]
> 请问可以支持txt导入和导出吗，大部分对上下文理解能力良好的ai翻译工具貌似对doc文档支持都较差

![图片](https://github.com/user-attachments/assets/deaff685-8dd9-44c8-b98a-a76041c20ed3)
最新版支持导入导出 txt 啊

**Comment by tohsakrat** [comment]
感谢提醒，去fetch了一下最新的dev分支，可以了。
之前应该git设置有点问题
