### ISSUE TITLE
如何将图的一部分替换成原图？

### ISSUE THREAD

**Issue by mercury233** [dmMaze/BallonsTranslator#636]
OCR可能将背景中某些元素错误地识别成了文字，此时即使“删除并恢复抹除文字”，也可能留下一些涂抹的痕迹，想要手动恢复成原图

**Comment by bropines** [comment]
Select the "inpaint" tool and right-click. The eraser for all grout and brushes works on RMB

https://github.com/user-attachments/assets/c7506ac4-f24c-45d8-9bc2-f068fce9f233

There is also a Mask opacity mode that shows where the inpaint mask was applied
![image](https://github.com/user-attachments/assets/7b2caaa2-0818-44f4-8d69-ce8c9fb53b35)
