### ISSUE TITLE
自动生成的文本框里的字体太小，嵌字的字体大小设定成“使用全局设置”无效

### ISSUE THREAD

**Issue by madokazz** [dmMaze/BallonsTranslator#64]
跑完ocr后，自动生成的文本框，里面的字体变得很小。
就算全局字体设定成26了，设置里的嵌字也设置成“使用全局设置”了，字体也总是变得很小，需要每个都手动点击应用字体格式

**Comment by dmMaze** [comment]
我自己的图没问题，方便的话可以给我原图复现

**Comment by madokazz** [comment]
重启软件后似乎又可以了。
好像是因为设置没有生效的原因
还有以下的报错：
[INFO   ] dl_manager:on_finish_setocr:640 - OCR set to mit32px
[INFO   ] dl_manager:on_finish_setinpainter:647 - Inpainter set to lama_mpe
[INFO   ] dl_manager:on_finish_setdetector:634 - Text detector set to ctd
DirectWrite: CreateFontFaceFromHDC() failed (指示输入文件 (例如字体文件) 中的错误。) for QFontDef(Family="MS Serif", pointsize=16, pixelsize=21, styleHint=5, weight=50, stretch=100, hintingPreference=0) LOGFONT("MS Serif", lfWidth=0, lfHeight=-21) dpi=120
DirectWrite: CreateFontFaceFromHDC() failed (指示输入文件 (例如字体文件) 中的错误。) for QFontDef(Family="Small Fonts", pointsize=16, pixelsize=13, styleHint=5, weight=50, stretch=100, hintingPreference=0) LOGFONT("Small Fonts", lfWidth=0, lfHeight=-13) dpi=120
DirectWrite: CreateFontFaceFromHDC() failed (指示输入文件 (例如字体文件) 中的错误。) for QFontDef(Family="System", pointsize=16, pixelsize=20, styleHint=5, weight=50, stretch=100, hintingPreference=0) LOGFONT("System", lfWidth=0, lfHeight=-20) dpi=120
DirectWrite: CreateFontFaceFromHDC() failed (指示输入文件 (例如字体文件) 中的错误。) for QFontDef(Family="Terminal", pointsize=16, pixelsize=20, styleHint=5, weight=50, stretch=100, hintingPreference=0) LOGFONT("Terminal", lfWidth=0, lfHeight=-20) dpi=120
DirectWrite: CreateFontFaceFromHDC() failed (指示输入文件 (例如字体文件) 中的错误。) for QFontDef(Family="Terminal", pointsize=16, pixelsize=20, styleHint=5, weight=50, stretch=100, hintingPreference=0) LOGFONT("Terminal", lfWidth=0, lfHeight=-20) dpi=120

**Comment by dmMaze** [comment]
> 

这个是 qt读字体的报错，我也管不着，程序里没问题就不用管

**Comment by madokazz** [comment]
应该是配置的保存上面有某些bug。改完配置后，config.json 文件里的
 
"global_fontformat": {"family": "SourceHanSansCN-Medium", "size": 11.0, " 并不会跟着更新

**Comment by madokazz** [comment]
直接使用1.3.0-core 没有问题，将1.3.16 的文件复盖过去后，就会出现这个问题

**Comment by dmMaze** [comment]
> 直接使用1.3.0-core 没有问题，将1.3.16 的文件复盖过去后，就会出现这个问题，
> 不管怎么设置，就算手动改配置文件，设置成：
> 	"let_fntsize_flag": 1,
> 	"let_fntstroke_flag": 1,
> 	"let_fntcolor_flag": 1,
> 	"let_fnteffect_flag": 1,
> 	"let_alignment_flag": 1,
> 	"let_autolayout_flag": false,
> 	"let_uppercase_flag": false,
> 除了字体不变，其他样式都会自己变化

我试了下没问题
确认一下你改的是“全局字体格式”
然后你在程序里改了不会立刻写进config.json, 要正常退出后（点X）才会保存更改的设置

**Comment by madokazz** [comment]
终于找到问题了，只要设置了轮廓大小就会这样。
轮廓是0的时候不会出现问题。设置 轮廓>0的时候，字体就会变小

**Comment by dmMaze** [comment]
> 终于找到问题了，只要设置了轮廓大小就会这样。 轮廓是0的时候不会出现问题。设置 轮廓>0的时候，字体就会变小

你的意思是单纯字变小了还是出现上面说的大小调节失效的情况...
如果是后者我这边还是无法复现，一切正常

**Comment by madokazz** [comment]
![屏幕截图 2022-12-14 203623](https://user-images.githubusercontent.com/96102332/207598622-99056ffd-7323-4eb0-885d-2729b85cdb14.png)
![屏幕截图 2022-12-14 203643](https://user-images.githubusercontent.com/96102332/207598639-7005d330-fdcc-47ed-a435-f164110b0c12.png)
其他好像没问题，就是设置轮廓后才会出现大小失调的问题。
配置的问题重新安装之后，每次修改都重启软件就没再出现了

**Comment by dmMaze** [comment]
你可以先看样子调好一个样式，然后保存这个样式加载到全局字体样式，然后再跑程序
