### ISSUE TITLE
使用部分中转报错:gpt 'NoneType' object has no attribute 'total_tokens'

### ISSUE THREAD

**Issue by gamp26** [dmMaze/BallonsTranslator#640]
![4b6122347c4bf6fed577c49f478c062e](https://github.com/user-attachments/assets/4d954d12-64e2-414a-87e6-6adb5d48e669)
![a2754c9a13dac4c111496f64e6d39af2](https://github.com/user-attachments/assets/22097754-a8dd-40f8-8cc0-e5886a6d81d6)
![3c26945609b9fb6fe7f01f599961dd39](https://github.com/user-attachments/assets/66129369-9c5c-47d1-9f33-f21ab4af901d)
中转记录显示已经请求到，但是BallonsTranslator会报错
不清楚是不是因为这家中转的原因，但是用别的程序，api是可以正常使用的，您能否帮忙看一下是什么问题？

**Comment by popcion** [comment]
佬友用的公益站很可能是逆向，可以去查一查是否存在余额
https://github.com/zyddnys/manga-image-translator/issues/724
https://github.com/QAbot-zh/query-key

> 可用额度为: 无法计算剩余额度 已用额度为: NaN $ 总额度为: 无法获得额度信息

**Comment by dmMaze** [comment]
[3a40429](https://github.com/dmMaze/BallonsTranslator/commit/3a404293d1aeaff6e75a766bce5c735af4ac5fe2) 修了

**Comment by gamp26** [comment]
> 佬友用的公益站很可能是逆向，可以去查一查是否存在余额 [zyddnys/manga-image-translator#724](https://github.com/zyddnys/manga-image-translator/issues/724) https://github.com/QAbot-zh/query-key
> 
> > 可用额度为: 无法计算剩余额度 已用额度为: NaN $ 总额度为: 无法获得额度信息



> [3a40429](https://github.com/dmMaze/BallonsTranslator/commit/3a404293d1aeaff6e75a766bce5c735af4ac5fe2) 修了

原来是逆向的原因，感谢两位！
