### ISSUE TITLE
中文字体渲染错位

### ISSUE THREAD

**Issue by tohsakrat** [dmMaze/BallonsTranslator#641]
如题，更新之前没有这个问题，今天fetch到最新版之后，发现一些字错位了。
重新渲染解决不了，而且只要是这个字就会错位。
![image](https://github.com/user-attachments/assets/429b1c14-70bd-4b51-97f5-84a24af2d152)

**Comment by dmMaze** [comment]
这是啥字体，你能找到之前正常的 hash 吗

**Comment by tohsakrat** [comment]
宋体，微软雅黑等系统自带字体都有，且出错的往往是同一个字，不论位置。
雅黑ui有问题的字少一些，但不能完全解决。
有更新之前的启动录像录到了hash
version: 3.9.12 (main,Apr 4 2822, 95:22:27) [MSC v.1916 64
py executable:
version:1.4.8
C:\ProgramData\Anaconda3\python.exe
branch: dev
Comnit hash: f37813c19725a4560e81cb992b1da958bc03f963
[INFO ] launch:main:184 - QT_API: pyqt6, QT Version:6.7.8

**Comment by dmMaze** [comment]
没有这个 hash，而且你这个 qt 版本官方 pip 历史里也没有啊，试着装一下6.6.1

**Comment by tohsakrat** [comment]
谢谢！降级了pyqt导6.6.1，解决了！

**Comment by tohsakrat** [comment]
不对！问题好像还是存在！
目前hash
f78d6a9c99690f1bbeca78950c75ce668ebeee3a

**Comment by tohsakrat** [comment]
比较离奇的是这个bug似乎和字体大小有关，虽然不知道是什么回事倒是有办法绕过去了
![image](https://github.com/user-attachments/assets/a449481e-9414-4c7b-bcd2-3f3957d6fe1e)
![image](https://github.com/user-attachments/assets/58860953-3e2b-455c-98b7-f8c8f3b0e49a)
![image](https://github.com/user-attachments/assets/34fc8e3e-429a-4658-b8b3-0d3dc6de766a)
![image](https://github.com/user-attachments/assets/aca751f5-37f0-4204-94f7-535f9cdcce41)

**Comment by tohsakrat** [comment]
好像找到原因了，是因为巨首有空格，没有好好识别为竖版排版，而是把第一个字横向位移了
删除空格后更换字体可以修复，但是如果不更换字体，会有缓存，造成这个字一直错位
![image](https://github.com/user-attachments/assets/48a9dd86-5769-407f-bd24-3cec531b53a8)

**Comment by dmMaze** [comment]
@tohsakrat 我用微软雅黑 light 也复现了，不需要插空格。这个 bug 好像更多和字体有关，你插空格错位的是哪些字体

**Comment by tohsakrat** [comment]
系统自带的、华康系列、汉仪系列、方正系列都遇到了。体感和字体没有关系。切换字体只起到了一个重新渲染的作用，如果字符前面有空格，还是会错位

**Comment by dmMaze** [comment]
8c408b14bfab66065b4917840f6c0862dfc045c2 应该修好了

**Comment by tohsakrat** [comment]
试了一下，真的修好了！！！特别特别伟大~！！！！！！！！！
大大你就是！我的！神！
