### ISSUE TITLE
安装后找不到exe文件

### ISSUE THREAD

**Issue by soraniconico** [dmMaze/BallonsTranslator#644]
如题，电脑小白按安装说明自动安装成功了，程序运行正常。但是后续找不到装好的文件和运行程序在哪里。已善用搜索，求大佬教教安装路径的位置；；

**Comment by bropines** [comment]
> 如题，电脑小白按安装说明自动安装成功了，程序运行正常。但是后续找不到装好的文件和运行程序在哪里。已善用搜索，求大佬教教安装路径的位置；；

![image](https://github.com/user-attachments/assets/e1a21246-5c39-411c-bb91-e30a76ac58e0)


Our program does not have a normal installation. It simply runs via a bat file depending on how you downloaded it

Just launch `launch_win.bat` or `launch_win_venv.bat`

**Comment by soraniconico** [comment]
thanks a lot!!it works!

**Comment by bropines** [comment]
Ok, don't forget to close ISSUE
