### ISSUE TITLE
这是因为什么，方正大黑字体错位

### ISSUE THREAD

**Issue by longfei796** [dmMaze/BallonsTranslator#645]
因为是竖排的文本框，所以70也是竖排，我就把70删去空格后，想再添加个70的横排文本框就这样了，之后这个文本框的分始终是这样
其他的文本框也有这种情况，我用的是方正大黑
![mmexport1731118911151](https://github.com/user-attachments/assets/98132a52-1256-4109-9089-142cfdfe6f81)

**Comment by longfei796** [comment]
![mmexport1731118734032](https://github.com/user-attachments/assets/692ee90a-f602-4491-a032-c22923ea1317)

**Comment by longfei796** [comment]
INFO] launch:main:223 - set display language to zh_CN
[DEBUG] trans_chatgpt_exp:_setup_translator:45 - Setting up translator with initial parameters.
[DEBUG] trans_chatgpt_exp:_setup_translator:72 - Translator setup completed.
[INFO] module_manager:on_finish_settranslator:917 - Translator set to ChatGPT_exp
[INFO] module_manager:on_finish_setinpainter:909 - Inpainter set to patchmatch
[INFO] module_manager:on_finish_setdetector:896 - Text detector set to ctd
[INFO] module_manager:on_finish_setocr:902 - OCR set to manga_ocr
[DEBUG] config_proj:save:213 - project saved to C:/Users/DELL/Desktop/新建文件夹 (6)/新建文件夹/[Bai Asuka] Mama Koubi [Digital]\imgtrans_[Bai Asuka] Mama Koubi [Digital].json
[DEBUG] config_proj:save:213 - project saved to C:/Users/DELL/Desktop/新建文件夹 (6)/新建文件夹/[Bai Asuka] Mama Koubi [Digital]\imgtrans_[Bai Asuka] Mama Koubi [Digital].json
[DEBUG] config_proj:save:213 - project saved to C:/Users/DELL/Desktop/新建文件夹 (6)/新建文件夹/[Bai Asuka] Mama Koubi [Digital]\imgtrans_[Bai Asuka] Mama Koubi [Digital].json
[DEBUG] config_proj:save:213 - project saved to C:/Users/DELL/Desktop/新建文件夹 (6)/新建文件夹/[Bai Asuka] Mama Koubi [Digital]\imgtrans_[Bai Asuka] Mama Koubi [Digital].json
[DEBUG] config_proj:save:213 - project saved to C:/Users/DELL/Desktop/新建文件夹 (6)/新建文件夹/[Bai Asuka] Mama Koubi [Digital]\imgtrans_[Bai Asuka] Mama Koubi [Digital].json
[DEBUG] config_proj:save:213 - project saved to C:/Users/DELL/Desktop/新建文件夹 (6)/新建文件夹/[Bai Asuka] Mama Koubi [Digital]\imgtrans_[Bai Asuka] Mama Koubi [Digital].json
[DEBUG] config_proj:save:213 - project saved to C:/Users/DELL/Desktop/新建文件夹 (6)/新建文件夹/[Bai Asuka] Mama Koubi [Digital]\imgtrans_[Bai Asuka] Mama Koubi [Digital].json

**Comment by longfei796** [comment]
[还有希望能解答一下这两个是什么功能]

**Comment by dmMaze** [comment]
如果用的不是最新版更新一下看错位的问题有没有解决

**Comment by longfei796** [comment]
> 如果用的不是最新版更新一下看错位的问题有没有解决

可以了

作者，可以请您帮忙解答一下这个干什么用的吗
![381013011-1dce3571-59ca-4497-a06b-63a9ab910718](https://github.com/user-attachments/assets/e5dfc58d-a600-41a9-81f7-e5e0b48f5a4f)


还有设置里面图片质量后面的数字是不是代表百分比还是什么？
![381012017-1081edc6-e3fc-41f1-a236-70777ff32c1d](https://github.com/user-attachments/assets/7427ae77-e9b8-4686-8297-10316dfa48d4)

**Comment by dmMaze** [comment]
> > 如果用的不是最新版更新一下看错位的问题有没有解决
> 
> 可以了
> 
> 作者，可以请您帮忙解答一下这个干什么用的吗
> ![381013011-1dce3571-59ca-4497-a06b-63a9ab910718](https://github.com/user-attachments/assets/e5dfc58d-a600-41a9-81f7-e5e0b48f5a4f)
> 
> 
> 还有设置里面图片质量后面的数字是不是代表百分比还是什么？
> ![381012017-1081edc6-e3fc-41f1-a236-70777ff32c1d](https://github.com/user-attachments/assets/7427ae77-e9b8-4686-8297-10316dfa48d4)
> 

行距类型，一个是比例一个是绝对值。选比例的时候每行间距是根据当前行的字体大小决定的，选绝对值的话间距就是所填的固定数值。
质量就是图像压缩质量，这个值和保存体积成反比，具体结果因压缩算法而异。

**Comment by longfei796** [comment]
> 行距类型，一个是比例一个是绝对值。选比例的时候每行间距是根据当前行的字体大小决定的，选绝对值的话间距就是所填的固定数值。 质量就是图像压缩质量，这个值和保存体积成反比，具体结果因压缩算法而异。

十分感谢
最后请问一下，如果我不想有任何图片压缩该填多少呢？既然是反比那么填0就可以？

**Comment by dmMaze** [comment]
>  > 行距类型，一个是比例一个是绝对值。选比例的时候每行间距是根据当前行的字体大小决定的，选绝对值的话间距就是所填的固定数值。 质量就是图像压缩质量，这个值和保存体积成反比，具体结果因压缩算法而异。
> 
> 十分感谢
> 最后请问一下，如果我不想有任何图片压缩该填多少呢？既然是反比那么填0就可以？

说错了，成正比。不想压缩直接选 png

**Comment by longfei796** [comment]
> > > 行距类型，一个是比例一个是绝对值。选比例的时候每行间距是根据当前行的字体大小决定的，选绝对值的话间距就是所填的固定数值。 质量就是图像压缩质量，这个值和保存体积成反比，具体结果因压缩算法而异。
> > 
> > 
> > 十分感谢
> > 最后请问一下，如果我不想有任何图片压缩该填多少呢？既然是反比那么填0就可以？
> 
> 说错了，成正比。不想压缩直接选 png

请问作者大佬，这两个功能有无需要注意的地方

![mmexport1731470748630](https://github.com/user-attachments/assets/d85f265e-3567-4662-bcb1-28bb824482c9)
