### ISSUE TITLE
文字渲染和行距问题

### ISSUE THREAD

**Issue by fclx512** [dmMaze/BallonsTranslator#650]
字体添加轮廓后只要改变字体大小或者其他会让字体变动的操作就有可能导致轮廓渲染错位，需要保存刷新一次才能恢复正常，调整行距也会有类似的问题，有时会显示成远大于实际值的行距，同样是刷新后恢复正常。且稍早些的lssues有人提到的翻译框延迟渲染问题同样也会在我这出现，同时确定我使用的是微软拼音而不是第三方输入法
![QQ20241114-200620](https://github.com/user-attachments/assets/c0bfeca8-1e9b-4efb-a2cc-88b563ea6f3f)

**Comment by dmMaze** [comment]
用的是 8c408b14bfab66065b4917840f6c0862dfc045c2 吗，如果是需要提供能稳定复现轮廓错位、行距显示错误和延迟渲染的过程，我这里没试出来

**Comment by fclx512** [comment]
> 用的是 [8c408b1](https://github.com/dmMaze/BallonsTranslator/commit/8c408b14bfab66065b4917840f6c0862dfc045c2) 吗，如果是需要提供能稳定复现轮廓错位、行距显示错误和延迟渲染的过程，我这里没试出来

额，说来不好意思，用了快一个月还是没找到这个软件的版本号在哪显示，日期的话是11.7上传的最新版。个人测试的话是导入翻译文本后只要调整文本显示两行以上的文本框或更改文本尺寸就大概率触发且行数越多偏移的越大，保存后再调整就不会再出现了。另外新建文本框文本超过两行后同样如此，个人猜测是缓存什么的问题

**Comment by dmMaze** [comment]
我还是没法复现，更新试试有没有解决。你要是网盘下的双击一下 scripts/local_gitpull.bat 就更新了。

**Comment by fclx512** [comment]
> 我还是没法复现，更新试试有没有解决。你要是网盘下的双击一下 scripts/local_gitpull.bat 就更新了。

![QQ20241115-201051](https://github.com/user-attachments/assets/45ea7a35-6cd4-4a4d-b08b-ee19d218455a)
啊哈哈...倒不如说更新问题更大...
之前排查问题的时候流量吃紧就没删data重新去网盘只下了基础包然后解压完把data丢进去了，是这个原因吗？

**Comment by dmMaze** [comment]
> > 我还是没法复现，更新试试有没有解决。你要是网盘下的双击一下 scripts/local_gitpull.bat 就更新了。
> 
> ![QQ20241115-201051](https://private-user-images.githubusercontent.com/134525489/386590460-45ea7a35-6cd4-4a4d-b08b-ee19d218455a.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzE2NzQ1NDYsIm5iZiI6MTczMTY3NDI0NiwicGF0aCI6Ii8xMzQ1MjU0ODkvMzg2NTkwNDYwLTQ1ZWE3YTM1LTZjZDQtNGE0ZC1iMDhiLWVlMTlkMjE4NDU1YS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQxMTE1JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MTExNVQxMjM3MjZaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT02NzFlY2U3MmM4ZTg1ZWFjMzExNTk4YTFhMWI4Yjk4ZTViZDA5MjVmN2NmMDI2YmQ1ZDYyZjZjN2QwYjM1YmY5JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.Q6GN0U-Mcnmicmqybze73dPjYalMcpw_IAeb8I5yzOw) 啊哈哈...倒不如说更新问题更大... 之前排查问题的时候流量吃紧就没删data重新去网盘只下了基础包然后解压完把data丢进去了，是这个原因吗？

![图片](https://github.com/user-attachments/assets/7f3abcbc-3efa-4e31-a23e-e285c91b3bbe)
直接从项目页面下包解压覆盖也行

**Comment by Mistermozg1** [comment]
I have this problem too

**Comment by dmMaze** [comment]
还是存在这个问题而且能复现再开
