### ISSUE TITLE
目前版本，轮廓会固定在一边，不受字体居中移动

### ISSUE THREAD

**Issue by notunicorna** [dmMaze/BallonsTranslator#653]
旧版没有这个问题，有试过重新安装数据库，还是无效，所有字体都有这个问题，请问是我哪里没有设置好吗？
![搜狗高速浏览器截图20241117110855](https://github.com/user-attachments/assets/4e02b778-9198-414f-988d-347b55b9775e)
![搜狗高速浏览器截图20241117110904](https://github.com/user-attachments/assets/a2ff501b-1710-4cdd-a263-c7348a453bf7)
![搜狗高速浏览器截图20241117110911](https://github.com/user-attachments/assets/ec290485-0c1a-4036-bab5-ad7a7e782606)

**Comment by dmMaze** [comment]
已修复
