### ISSUE TITLE
请问是否支持chatgpt中转api

### ISSUE THREAD

**Issue by nietao0627** [dmMaze/BallonsTranslator#655]
如题，是否BallonsTranslator/tree/dev/modules/translators/
trans_chatgpt.py中的 '3rd party api url': '',就可以了？或者有其他方法可以修改支持中转API接口的

PS：是否支持claude？

**Comment by dmMaze** [comment]
试试就知道了

**Comment by ArtoriaShu** [comment]
> 试试就知道了

可以麻烦问一下大大用的是哪个Claude中转吗，我这边的中转都不能用，显示连接错误，谢谢
