### ISSUE TITLE
missing dll

### ISSUE THREAD

**Issue by qwe278** [dmMaze/BallonsTranslator#658]
![image](https://github.com/user-attachments/assets/cc28c217-a58c-4956-b93c-1d4460035839)
And do i have to install python ?

**Comment by dmMaze** [comment]
The provided packages are not runnable on Windows 7, install [Python 3.8](https://www.python.org/downloads/release/python-3810/) and run the [source code](https://github.com/dmMaze/BallonsTranslator/blob/dev/README_EN.md#run-the-source-code)
