### ISSUE TITLE
导入翻译意外套用了不正确的样式

### ISSUE THREAD

**Issue by fclx512** [dmMaze/BallonsTranslator#659]
某些时候没有注意到ocr出的文本框使用了错误的样式，导入翻译后完全乱套（很不巧的是我上一个项目字体设置的非常大而当前项目又是超长文本的小字），这种情况下如何快速用正确的样式覆盖掉它们？（最好能把文本框一并调整回来）

**Comment by dmMaze** [comment]
![图片](https://github.com/user-attachments/assets/509f5bfa-50b1-4435-a200-94c818138711)
