### ISSUE TITLE
突然error

### ISSUE THREAD

**Issue by hiokk336** [dmMaze/BallonsTranslator#660]
我重開機就遇到了error (PyTorch is not linked with support for mps devicesFailed to set module.)
I have encounter an error after i restart my computer

![Screenshot 2024-11-23 100222](https://github.com/user-attachments/assets/24dceffd-47df-4b9e-9b87-37789152a1ad)

**Comment by hiokk336** [comment]
When RUN there is new error

Traceback (most recent call last):
  File "C:\Users\Downloads\BallonsTranslator_dev_src_with_gitpython\BallonsTranslator_dev_src_with_gitpython\ui\module_manager.py", line 381, in _imgtrans_pipeline
    self.ocr.run_ocr(img, blk_list)
AttributeError: 'NoneType' object has no attribute 'run_ocr'

I have choose OCR as manga_ocr and device as cpu
我選擇 manga_ocr，設備為 cpu

![Uploading Screenshot 2024-11-23 102401.png…]()

**Comment by bropines** [comment]
1. Do you have a MAC? MPS is only available for mac (or arm chips)
2. What windows do you have?
3. Try deleting config.json in the config folder and check if it works

**Comment by dmMaze** [comment]
Check if you have other modules (other ocr, detector, inpainters, etc) set device to mps and correct it. 
Or delete config/config.json.
