### ISSUE TITLE
更新完后发现轮廓与字体不重叠

### ISSUE THREAD

**Issue by longfei796** [dmMaze/BallonsTranslator#663]
重新打开作业一半的文件后发现之前的文字与轮廓不重叠
重新打字并没有这种情况，
![1732787732053](https://github.com/user-attachments/assets/fe805aa5-85f6-4f21-9989-cb2d7eadfd14)
![1732787732050](https://github.com/user-attachments/assets/9aee756a-abb9-4a3d-a38b-4d8b081a0e9e)
![1732787732034(1)](https://github.com/user-attachments/assets/b2a95903-46ea-47dd-b118-b54d2233abce)
![1732787732034](https://github.com/user-attachments/assets/7418e4d9-b6e6-414a-9964-1bc53a57f231)

**Comment by dmMaze** [comment]
打开旧的项目就会出现这个问题？还是你重新打字后保存的新的项目再打开也会出现这个问题？
这都是啥字体？

**Comment by longfei796** [comment]
> 打开旧的项目就会出现这个问题？还是你重新打字后保存的新的项目再打开也会出现这个问题？ 这都是啥字体？

打开旧的项目（更新前），重新打字保存并没有这个问题
分别是方正大黑，方正舒体

**Comment by longfei796** [comment]
> 打开旧的项目就会出现这个问题？还是你重新打字后保存的新的项目再打开也会出现这个问题？ 这都是啥字体？

报告作者。我才发现更新后的也有这个问题，轮廓问题
好像跟文本框大小写有关，但是改变文本框并不能百分之百解决问题，而且竖排的文字越长，轮廓约不符合
![1732974827139](https://github.com/user-attachments/assets/de0734bb-e64d-46c5-bbda-dec1d8d16c16)
![fde51cd39244ee23939cd8cb8a10048](https://github.com/user-attachments/assets/949e4dce-4862-462c-929f-951066d63947)
![fbe35135c199c5c4da5f2d0a4da1d6c](https://github.com/user-attachments/assets/ad6a2367-dfbf-4df9-9df7-3046828e6a5e)
![bccd4f9e0c0fcd296da9843671c224e](https://github.com/user-attachments/assets/5081fe64-b204-4085-acb2-96085e503fa8)
![8507a644744a38db9202ea5875b3980](https://github.com/user-attachments/assets/5534fa59-9cfd-42f5-81fc-c0d880147646)
![44fc614bb4b85f370e6f1c57056f094](https://github.com/user-attachments/assets/1eeab25b-0862-4fff-8d60-bc4b2379584c)
![e51230594c08f7cee87e98e5aab0fce](https://github.com/user-attachments/assets/403927de-e7ea-4972-98b5-33abb69d3ade)

还有我想请问，原文文字颜色可以自动识别改变吗，我记得跑图的时候字体颜色是贴合的，但是现在不行了
可以添加这个功能吗

**Comment by longfei796** [comment]
> 打开旧的项目就会出现这个问题？还是你重新打字后保存的新的项目再打开也会出现这个问题？ 这都是啥字体？

竖排文字轮廓与标点符号有关
![1732976620937](https://github.com/user-attachments/assets/3f9f4ae8-7daf-4aa1-a3e6-3e2b6cd15ded)
![1732976620944](https://github.com/user-attachments/assets/802ac4aa-2dc0-4c9d-b81a-180d57aced45)
![1732976620950](https://github.com/user-attachments/assets/e966abb3-7d92-4744-bb66-e1b509f61146)

**Comment by dmMaze** [comment]
2d72206a2a9eb1dd33bfcba09c38ea6085e3a17b 应该修好了
RUN 的时候本来就能检测颜色啊，你是不是在设置-嵌字里把字体颜色改成使用全局设置了

**Comment by longfei796** [comment]
> [2d72206](https://github.com/dmMaze/BallonsTranslator/commit/2d72206a2a9eb1dd33bfcba09c38ea6085e3a17b) 应该修好了 RUN 的时候本来就能检测颜色啊，你是不是在设置-嵌字里把字体颜色改成使用全局设置了

请问大佬字体可以单独识别颜色吗？有时候run完想改成与原文一致的颜色要重新run吗？

还有更新时有时总是失败因为什么

![image](https://github.com/user-attachments/assets/a08d5584-5fec-48fc-a40b-3fca06f57db8)
![image](https://github.com/user-attachments/assets/88d0c858-a2d5-4434-a14d-a42ff30eabc2)

D:\0001翻译文件\001\BallonsTranslator_dev_src_with_gitpython>git config http.sslVerify false  这个的false要紧吗
还有这个ocr需要安装吗？
WARNING:root:PaddleOCR is not installed, so the module will not be initialized.
Install core it by following https://www.paddlepaddle.org.cn/en/install/quick?docurl
and then run `pip install paddleocr`
