### ISSUE TITLE
issue with the googldrive version

### ISSUE THREAD

**Issue by snektailmeat** [dmMaze/BallonsTranslator#665]
so i got one of the older versions working and wanted to update, so i downloaded the newest version from gd but it won start an just throws these ![image](https://github.com/user-attachments/assets/b913cd2b-38ca-4fb1-b85a-9d3e97015cdf) 

and running it as admin gives this
![image](https://github.com/user-attachments/assets/54b47fa3-7b28-47e0-b53a-2f354542b8c5)
no idea whats going on

**Comment by bropines** [comment]
There is no point in starting from the admin. And now I'm going to see what went wrong with my module

**Comment by dmMaze** [comment]
It should be fixed now, try the new uploaded package.
