### ISSUE TITLE
报错ImportError: cannot import name 'SyncSocketStream' from 'httpcore._backends.sync' 

### ISSUE THREAD

**Issue by youyi0218** [dmMaze/BallonsTranslator#666]
py version:  3.10.11 (tags/v3.10.11:7d4cc5a, Apr  5 2023, 00:38:17) [MSC v.1929 64 bit (AMD64)]
py executable:  E:\python\python 3.10.11\python.exe
version: 1.4.0
branch: dev
Commit hash: 2d72206a2a9eb1dd33bfcba09c38ea6085e3a17b
[INFO   ] config:load_config:193 - D:\AItool\BallonsTranslator\config/config.json does not exist, new config file will be created.
[INFO   ] launch:main:187 - QT_API: pyqt6, QT Version: 6.6.1
Traceback (most recent call last):
  File "D:\AItool\BallonsTranslator\launch.py", line 312, in <module>
    main()
  File "D:\AItool\BallonsTranslator\launch.py", line 203, in main
    load_modules()
  File "D:\AItool\BallonsTranslator\launch.py", line 128, in load_modules
    _load_module(**kwargs)
  File "D:\AItool\BallonsTranslator\launch.py", line 120, in _load_module
    importlib.import_module(module_path + module_name.replace('.py', ''))
  File "E:\python\python 3.10.11\lib\importlib\__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1050, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1006, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 688, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "D:\AItool\BallonsTranslator\modules\ocr\ocr_google_lens.py", line 8, in <module>
    from httpx_socks import SyncProxyTransport
  File "E:\python\python 3.10.11\lib\site-packages\httpx_socks\__init__.py", line 11, in <module>
    from ._sync_transport import SyncProxyTransport
  File "E:\python\python 3.10.11\lib\site-packages\httpx_socks\_sync_transport.py", line 2, in <module>
    from httpcore._backends.sync import SyncSocketStream  # noqa
ImportError: cannot import name 'SyncSocketStream' from 'httpcore._backends.sync' (E:\python\python 3.10.11\lib\site-packages\httpcore\_backends\sync.py)
[INFO   ] utils:dump_compile_times:302 - TorchDynamo compilation metrics:
Function, Runtimes (s)
[INFO   ] utils:dump_compile_times:302 - TorchDynamo compilation metrics:
Function, Runtimes (s)
[2024-12-01 12:04:45,476] torch._dynamo.utils: [INFO] TorchDynamo compilation metrics:
[2024-12-01 12:04:45,476] torch._dynamo.utils: [INFO] Function, Runtimes (s)

**Comment by bropines** [comment]
You can wait for a while, or you can download a file from my repository and put it in `bt\modules\ocr`
https://github.com/bropines/BallonsTranslator/blob/dev/modules/ocr/ocr_google_lens.py

**Comment by youyi0218** [comment]
> You can wait for a while, or you can download a file from my repository and put it in `bt\modules\ocr` https://github.com/bropines/BallonsTranslator/blob/dev/modules/ocr/ocr_google_lens.py

Thank you for your response, but I have already found a solution. Updating the httpcore and httpx libraries resolved the issue.

**Comment by bropines** [comment]
> > You can wait for a while, or you can download a file from my repository and put it in `bt\modules\ocr`📋 [bropines/BallonsTranslator@`dev`📋/modules/ocr/ocr_google_lens.py](https://github.com/bropines/BallonsTranslator/blob/dev/modules/ocr/ocr_google_lens.py?rgh-link-date=2024-12-01T04%3A25%3A26Z)
> 
> Thank you for your response, but I have already found a solution. Updating the httpcore and httpx libraries resolved the issue.

Anyway, just in case, I did the work in the code via `httpx` instead of `httpx-socks`. It will be easier and more convenient this way. I don't know why I didn't do it before

**Comment by youyi0218** [comment]
> > > You can wait for a while, or you can download a file from my repository and put it in `bt\modules\ocr`📋 [bropines/BallonsTranslator@`dev`📋/modules/ocr/ocr_google_lens.py](https://github.com/bropines/BallonsTranslator/blob/dev/modules/ocr/ocr_google_lens.py?rgh-link-date=2024-12-01T04%3A25%3A26Z)
> > 
> > 
> > Thank you for your response, but I have already found a solution. Updating the httpcore and httpx libraries resolved the issue.
> 
> Anyway, just in case, I did the work in the code via `httpx` instead of `httpx-socks`. It will be easier and more convenient this way. I don't know why I didn't do it before

But there's still a bug here. I've already upgraded those three dependencies, but when I use the `launch_win.bat` file to start it, it still gives an error, just like the issue I originally raised. However, when I start it using the command `python launch.py` in the cmd window, it runs normally.

**Comment by bropines** [comment]
And stop. Did you install from the source code?

**Comment by dmMaze** [comment]
> > > > You can wait for a while, or you can download a file from my repository and put it in `bt\modules\ocr`📋 [bropines/BallonsTranslator@`dev`📋/modules/ocr/ocr_google_lens.py](https://github.com/bropines/BallonsTranslator/blob/dev/modules/ocr/ocr_google_lens.py?rgh-link-date=2024-12-01T04%3A25%3A26Z)
> > > 
> > > 
> > > Thank you for your response, but I have already found a solution. Updating the httpcore and httpx libraries resolved the issue.
> > 
> > 
> > Anyway, just in case, I did the work in the code via `httpx` instead of `httpx-socks`. It will be easier and more convenient this way. I don't know why I didn't do it before
> 
> But there's still a bug here. I've already upgraded those three dependencies, but when I use the `launch_win.bat` file to start it, it still gives an error, just like the issue I originally raised. However, when I start it using the command `python launch.py` in the cmd window, it runs normally.

It's not a bug, you just ran in a different PY environment.

**Comment by bropines** [comment]
This batnik is designed to run in the version from Google drive created by DmMaze. 
Also, I would not recommend putting all packages in the common python package repository. It's better to create a venv.

**Comment by bropines** [comment]
Roughly speaking, you need to run it from the console via `python launch.py `

**Comment by youyi0218** [comment]
> Roughly speaking, you need to run it from the console via `python launch.py `

Thank you, but I have another question. My graphics card is a GTX 2060, and I have already installed CUDA and Torch. However, my OCR and text detection models can only select the CPU as the device, and I am unable to choose CUDA.

https://github.com/user-attachments/assets/26e19a62-9ce6-43e6-99e3-9cae9e1f13f9

**Comment by bropines** [comment]
> Thank you, but I have another question. My graphics card is a GTX 2060, and I have already installed CUDA and Torch. However, my OCR and text detection models can only select the CPU as the device, and I am unable to choose CUDA.

open python as a console
```bash
python 
```
Next, insert this
```bash
import torch
torch.cuda.is_available()
```

If False, then your torch is not working
