### ISSUE TITLE
paddleOCR

### ISSUE THREAD

**Issue by KirpichKrasniy** [dmMaze/BallonsTranslator#67]
can you use paddleOCR as a basis, it recognizes japanese and english characters better

for example, here it is used
https://github.com/jtl1207/comic-translation

**Comment by dmMaze** [comment]
I doubt paddleOCR could surpass current models and it is worth the effort to integrate it. You may try ctc_48px and MangaOCR in config panel.

**Comment by KirpichKrasniy** [comment]
> I doubt paddleOCR could surpass current models and it is worth the effort to integrate it. You may try ctc_48px and MangaOCR in config panel.


I have problems mainly with the recognition of English text. I chose different recognition methods, but still some texts simply do not want to be read correctly.

i use this program to quickly read english text: (it also works well with japanese text recognition) https://github.com/HIllya51/LunaTranslator
it just uses paddleOCR recognition

I use it to copy texts in English, then translate them through the dipple translator site, and then paste the translation into the program. it would be cool to see good recognition of English text in the program.

maybe I'm doing something wrong and it doesn't work for me...

**Comment by dmMaze** [comment]
> > I doubt paddleOCR could surpass current models and it is worth the effort to integrate it. You may try ctc_48px and MangaOCR in config panel.
> 
> I have problems mainly with the recognition of English text. I chose different recognition methods, but still some texts simply do not want to be read correctly.
> 
> i use this program to quickly read english text: (it also works well with japanese text recognition) https://github.com/HIllya51/LunaTranslator it just uses paddleOCR recognition
> 
> I use it to copy texts in English, then translate them through the dipple translator site, and then paste the translation into the program. it would be cool to see good recognition of English text in the program.
> 
> maybe I'm doing something wrong and it doesn't work for me...

It makes sense these recognizers perform worse on English text since there're specifically optimized for Manga text...
Just to make sure, you are working on Manga/Comics, right? For other scenarios, the detector could fail, too.

**Comment by KirpichKrasniy** [comment]
> > > I doubt paddleOCR could surpass current models and it is worth the effort to integrate it. You may try ctc_48px and MangaOCR in config panel.
> > 
> > 
> > I have problems mainly with the recognition of English text. I chose different recognition methods, but still some texts simply do not want to be read correctly.
> > i use this program to quickly read english text: (it also works well with japanese text recognition) https://github.com/HIllya51/LunaTranslator it just uses paddleOCR recognition
> > I use it to copy texts in English, then translate them through the dipple translator site, and then paste the translation into the program. it would be cool to see good recognition of English text in the program.
> > maybe I'm doing something wrong and it doesn't work for me...
> 
> It makes sense these recognizers perform worse on English text since there're specifically optimized for Japanese text... Just to make sure, you are working on Manga/Comics, right? For other scenarios, the detector could fail, too.

I don't use a program to translate manga/comics, I just translate text from similar photos:
![httpcloud3steamusercontentcomugc1906739392565112978282CE2986780DC61963736FE55974F349FAEE0A2_01](https://user-images.githubusercontent.com/109726461/209313664-45ece6a3-6d5c-4de2-82bf-eb28bbd3f965.png)

mit32
![image](https://user-images.githubusercontent.com/109726461/209314723-da9f3db4-9530-4c97-8b96-582e4b777386.png)
mangaocr
![image](https://user-images.githubusercontent.com/109726461/209315023-5ef44677-93c7-4046-824d-1c474270d6ef.png)
mit48
![image](https://user-images.githubusercontent.com/109726461/209315176-385d085d-7f4f-4a6f-b558-d0ff0f4a4a61.png)

even simple text does not want to be recognized

**Comment by KirpichKrasniy** [comment]
![image](https://user-images.githubusercontent.com/109726461/209316257-2a3da2b9-b35e-4de7-acce-dd3096287489.png)
text on a white background is recognized quite well

**Comment by dmMaze** [comment]
> 

It's definitely the detector's failure...
I'll retrain the detector in the next few weeks(hopefully

**Comment by KirpichKrasniy** [comment]
> > 
> 
> It's definitely the detector's failure... I'll retrain the detector in the next few weeks(hopefully

Thanks for the quick response!

**Comment by dmMaze** [comment]
> > > > I doubt paddleOCR could surpass current models and it is worth the effort to integrate it. You may try ctc_48px and MangaOCR in config panel.
> > > 
> > > 
> > > I have problems mainly with the recognition of English text. I chose different recognition methods, but still some texts simply do not want to be read correctly.
> > > i use this program to quickly read english text: (it also works well with japanese text recognition) https://github.com/HIllya51/LunaTranslator it just uses paddleOCR recognition
> > > I use it to copy texts in English, then translate them through the dipple translator site, and then paste the translation into the program. it would be cool to see good recognition of English text in the program.
> > > maybe I'm doing something wrong and it doesn't work for me...
> > 
> > 
> > It makes sense these recognizers perform worse on English text since there're specifically optimized for Japanese text... Just to make sure, you are working on Manga/Comics, right? For other scenarios, the detector could fail, too.
> 
> I don't use a program to translate manga/comics, I just translate text from similar photos: ![httpcloud3steamusercontentcomugc1906739392565112978282CE2986780DC61963736FE55974F349FAEE0A2_01](https://user-images.githubusercontent.com/109726461/209313664-45ece6a3-6d5c-4de2-82bf-eb28bbd3f965.png)
> 
> mit32 ![image](https://user-images.githubusercontent.com/109726461/209314723-da9f3db4-9530-4c97-8b96-582e4b777386.png) mangaocr ![image](https://user-images.githubusercontent.com/109726461/209315023-5ef44677-93c7-4046-824d-1c474270d6ef.png) mit48 ![image](https://user-images.githubusercontent.com/109726461/209315176-385d085d-7f4f-4a6f-b558-d0ff0f4a4a61.png)
> 
> even simple text does not want to be recognized

OKey it turns out the detector and recognizer both works fine (not perfectly though) for the **whole image**. Not a cropped part of it.
I'll retrain the detector anyway, and I'll consider integrate recognizer part of paddleocr (add detector would be much more troublesome)

**Comment by KirpichKrasniy** [comment]
> > > > > Я сомневаюсь, что paddleOCR сможет превзойти текущие модели, и стоит затрачивать усилия на его интеграцию. Вы можете попробовать ctc_48px и MangaOCR в панели конфигурации.
> > > > 
> > > > 
> > > > У меня проблемы в основном с распознаванием английского текста. Я выбирал разные способы распознавания, но все равно некоторые тексты просто не хотят правильно читаться. 
> > > > я использую эту программу для быстрого чтения английского текста: (она также хорошо работает с распознаванием японского текста) https://github.com/HIllya51/LunaTranslator она просто использует распознавание paddleOCR 
> > > > Я использую ее для копирования текстов на английском языке, а затем переводить их через сайт переводчика dipple, а затем вставьте перевод в программу. было бы круто увидеть хорошее распознавание английского текста в программе. 
> > > > может я что-то не так делаю и у меня не работает...
> > > 
> > > 
> > > Имеет смысл, что эти распознаватели хуже работают с английским текстом, поскольку они специально оптимизированы для японского текста... Просто чтобы убедиться, что вы работаете над мангой/комиксами, верно? В других сценариях детектор тоже может выйти из строя.
> > 
> > 
> > Я не использую программу для перевода манги/комиксов, я просто перевожу текст с похожих фотографий:![httpcloud3steamusercontentcomugc1906739392565112978282CE2986780DC61963736FE55974F349FAEE0A2_01](https://user-images.githubusercontent.com/109726461/209313664-45ece6a3-6d5c-4de2-82bf-eb28bbd3f965.png)
> > мит32 ![изображение](https://user-images.githubusercontent.com/109726461/209314723-da9f3db4-9530-4c97-8b96-582e4b777386.png)мангаокр ![изображение](https://user-images.githubusercontent.com/109726461/209315023-5ef44677-93c7-4046-824d-1c474270d6ef.png)мит48![изображение](https://user-images.githubusercontent.com/109726461/209315176-385d085d-7f4f-4a6f-b558-d0ff0f4a4a61.png)
> > даже простой текст не хочет распознаваться
> 
> OKey, оказывается, и детектор, и распознаватель работают нормально (хотя и не идеально) для **всей страницы** . Не обрезанная часть: <img alt="изображение" width="524" src="https://user-images.githubusercontent.com/51270320/209422979-201eed7e-b99e-48d2-9e64-84a3f413683b.png">
> 
> Я все равно переобучу детектор и рассмотрю возможность интеграции распознавателя в paddleocr (добавить детектор было бы намного сложнее)

I'm understood, thank you. maybe something is wrong with me... but it’s true that sometimes recognition works, sometimes it doesn’t. some random. I hope you can add new recognition engines. I think they will work well. though I'm not sure about that. thanks for the quick and clear answer. Special thanks to your Russian assistant, who has been PMing me for an hour since morning. Holy man. <3

**Comment by KirpichKrasniy** [comment]
> > 
> > 
> > OKey, оказывается, и детектор, и распознаватель работают нормально (хотя и не идеально) для **всей страницы** . Не обрезанная часть: <img alt="изображение" width="524" src="https://user-images.githubusercontent.com/51270320/209422979-201eed7e-b99e-48d2-9e64-84a3f413683b.png">
> > Я все равно переобучу детектор и рассмотрю возможность интеграции распознавателя в paddleocr (добавить детектор было бы намного сложнее)
> 
> I'm understood, thank you. maybe something is wrong with me... but it’s true that sometimes recognition works, sometimes it doesn’t. some random. I hope you can add new recognition engines. I think they will work well. though I'm not sure about that. thanks for the quick and clear answer. Special thanks to your Russian assistant, who has been PMing me for an hour since morning. Holy man. <3
