### ISSUE TITLE
新人使用问题

### ISSUE THREAD

**Issue by Djionter** [dmMaze/BallonsTranslator#68]
是否直接下载Ballonstranslator-1.30-core.7z和Ballonstranslator-1.316及data文件就可以了？然后不需要再按照说明去克隆仓库，直接命令行执行程序就可以了吗？

还有我执行程序后只能使用一键机翻对所有队列图片后才会出现OCR文字，翻译的结果，然后如果需要调整翻译文字进行嵌字的话，就只能调整好后在进行一键机翻，没有单独保存的功能吗

**Comment by dmMaze** [comment]
> 是否直接下载Ballonstranslator-1.30-core.7z和Ballonstranslator-1.316及data文件就可以了？然后不需要再按照说明去克隆仓库，直接命令行执行程序就可以了吗？

对


> 然后如果需要调整翻译文字进行嵌字的话

什么意思？ctrl+s就保存了所有编辑结果

**Comment by Djionter** [comment]
弄明白了，我以为每次修改都找不到保存的按钮。
还有使用图片修复aot好像容易闪退，每次画了矩形框后就闪退了
另外程序的设置该如何保存呢，每次重新打开好像都是默认设置

**Comment by dmMaze** [comment]
> 还有使用图片修复aot好像容易闪退，每次画了矩形框后就闪退了

有报错吗？用其他的就不会？

> 另外程序的设置该如何保存呢，每次重新打开好像都是默认设置

点右上角的×退出才会保存设置

**Comment by Djionter** [comment]
会提示

Traceback (most recent call last):
  File "D:\program files\BallonTranslator\ui\drawingpanel.py", line 678, in on_end_create_rect
  File "D:\program files\BallonTranslator\utils\textblock_mask.py", line 175, in canny_flood
  File "D:\program files\BallonTranslator\utils\textblock_mask.py", line 85, in bground_calculator
SystemError: result with error set from call

**Comment by dmMaze** [comment]
> 会提示
> 
> Traceback (most recent call last):
>   File "D:\program files\BallonTranslator\ui\drawingpanel.py", line 678, in on_end_create_rect
>   File "D:\program files\BallonTranslator\utils\textblock_mask.py", line 175, in canny_flood
>   File "D:\program files\BallonTranslator\utils\textblock_mask.py", line 85, in bground_calculator
> SystemError: result with error set from call

你是不是没把1.3.16的覆盖进去
右键属性看版本

**Comment by EasyRuby** [comment]
When using it，this will happen
Traceback (most recent call last):
  File "A:\BallonTranslator\ui\dl_manager.py", line 223, in _run_translate_pipeline
  File "A:\BallonTranslator\ui\dl_manager.py", line 187, in _translate_page
  File "A:\BallonTranslator\dl\translators\__init__.py", line 149, in translate_textblk_lst
  File "A:\BallonTranslator\dl\translators\__init__.py", line 122, in translate
  File "A:\BallonTranslator\dl\translators\__init__.py", line 207, in _translate
  File "A:\BallonTranslator\dl\translators\google_trans.py", line 193, in translate
dl.translators.exceptions.RequestError: Request exception can happen due to an api connection error. Please check your connection and try again

**Comment by dmMaze** [comment]
> When using it，this will happen Traceback (most recent call last): File "A:\BallonTranslator\ui\dl_manager.py", line 223, in _run_translate_pipeline File "A:\BallonTranslator\ui\dl_manager.py", line 187, in _translate_page File "A:\BallonTranslator\dl\translators__init__.py", line 149, in translate_textblk_lst File "A:\BallonTranslator\dl\translators__init__.py", line 122, in translate File "A:\BallonTranslator\dl\translators__init__.py", line 207, in _translate File "A:\BallonTranslator\dl\translators\google_trans.py", line 193, in translate dl.translators.exceptions.RequestError: Request exception can happen due to an api connection error. Please check your connection and try again

Set url of googletranslator to "***.com" in config panel

**Comment by EasyRuby** [comment]
可以蹲个联系方式吗，刚刚使用还是不太熟练，用网站请教感觉会比较麻烦😂😂

**Comment by dmMaze** [comment]
> 可以蹲个联系方式吗，刚刚使用还是不太熟练，用网站请教感觉会比较麻烦😂😂

读README

**Comment by EasyRuby** [comment]
出现这个问题该怎么办😂
NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x0000028D1CA99A00>: Failed to establish a new connection: [WinError 10060] 由于连接方在一段时间后没有正确答复或连接的主机没有反应，连接尝试失败。'))

**Comment by dmMaze** [comment]
> 出现这个问题该怎么办😂
> NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x0000028D1CA99A00>: Failed to establish a new connection: [WinError 10060] 由于连接方在一段时间后没有正确答复或连接的主机没有反应，连接尝试失败。'))

国内用谷歌翻译要挂代理
或者换成彩云翻译自己申请token

**Comment by Djionter** [comment]
以后更新能增加半自动的模式吗？现在抹字这块有时候把不需要消除的文字抹掉，一键情况下无法撤销

比如自己框选需要识别和OCR的位置，然后在进行操作

**Comment by dmMaze** [comment]
> 以后更新能增加半自动的模式吗？现在抹字这块有时候把不需要消除的文字抹掉，一键情况下无法撤销
> 
> 比如自己框选需要识别和OCR的位置，然后在进行操作

现在不是能选中框然后右键OCR, 翻译并抹字吗
还是说你要那种整本跨页的...问题是框出整本漫画文字块的工作量比跑完一键后删掉那些不想要的要大吧...
我可以给右键菜单加个删除并还原被抹除文字的选项

**Comment by Djionter** [comment]
另外是否可以为文本框增加方向键微调位置的功能，现在用鼠标拖拽效率有点低

**Comment by bropines** [comment]
> 另外是否可以为文本框增加方向键微调位置的功能，现在用鼠标拖拽效率有点低

Like text blocks move with pixel arrows or text entry cursor in them?

**Comment by Djionter** [comment]
> 

Like the text box in Photoshop, you can adjust the relative position of the text box in the picture by using the keyboard arrow keys, for example, I want the translation to be centered in the original picture text box (not the software text box), only by dragging and dropping with the mouse, which is not very convenient and accurate.

**Comment by dmMaze** [comment]
> 另外是否可以为文本框增加方向键微调位置的功能，现在用鼠标拖拽效率有点低

不是很明白拖拽效率为什么比方向键低了，我就嵌过一两本美漫
所以如果用方向键微调还要啥可选参数吗，比如速度啥的，可以推荐我一两个视频看看

**Comment by Djionter** [comment]
就是在微调的时候，比如我要把文本排列到和原漫画风格一样或者居中的时候，鼠标拖拽的话无法很精确的完成

可能是我强迫症LOL，如果看着嵌完字后，文字不在对话框的中间的话，就觉得很别扭

**Comment by Darkari** [comment]
> 

我也遇到类似的错误
Traceback (most recent call last):
  File "H:\COMICT~1\BALLON~1\ui\dl_manager.py", line 226, in _run_translate_pipeline
  File "H:\COMICT~1\BALLON~1\ui\dl_manager.py", line 190, in _translate_page
  File "H:\COMICT~1\BALLON~1\dl\translators\__init__.py", line 153, in translate_textblk_lst
  File "H:\COMICT~1\BALLON~1\dl\translators\__init__.py", line 126, in translate
  File "H:\COMICT~1\BALLON~1\dl\translators\__init__.py", line 213, in _translate
  File "H:\COMICT~1\BALLON~1\dl\translators\google_trans.py", line 193, in translate
dl.translators.exceptions.RequestError: Request exception can happen due to an api connection error. Please check your connection and try again

设定里我看谷歌翻译的url只有一个选项而且已经是com了， 请问是在别的什么地方改么？

**Comment by Darkari** [comment]
> > When using it，this will happen Traceback (most recent call last): File "A:\BallonTranslator\ui\dl_manager.py", line 223, in _run_translate_pipeline File "A:\BallonTranslator\ui\dl_manager.py", line 187, in _translate_page File "A:\BallonTranslator\dl\translators__init__.py", line 149, in translate_textblk_lst File "A:\BallonTranslator\dl\translators__init__.py", line 122, in translate File "A:\BallonTranslator\dl\translators__init__.py", line 207, in _translate File "A:\BallonTranslator\dl\translators\google_trans.py", line 193, in translate dl.translators.exceptions.RequestError: Request exception can happen due to an api connection error. Please check your connection and try again
> 
> Set url of googletranslator to "***.com" in config panel

我也遇到类似的错误
Traceback (most recent call last):
File "H:\COMICT1\BALLON1\ui\dl_manager.py", line 226, in run_translate_pipeline
File "H:\COMICT1\BALLON1\ui\dl_manager.py", line 190, in translate_page
File "H:\COMICT1\BALLON1\dl\translators_init.py", line 153, in translate_textblk_lst
File "H:\COMICT1\BALLON1\dl\translators_init.py", line 126, in translate
File "H:\COMICT1\BALLON1\dl\translators_init_.py", line 213, in _translate
File "H:\COMICT1\BALLON1\dl\translators\google_trans.py", line 193, in translate
dl.translators.exceptions.RequestError: Request exception can happen due to an api connection error. Please check your connection and try again

设定里我看谷歌翻译的url只有一个选项而且已经是com了， 请问是在别的什么地方改么？

**Comment by dmMaze** [comment]
> > > When using it，this will happen Traceback (most recent call last): File "A:\BallonTranslator\ui\dl_manager.py", line 223, in _run_translate_pipeline File "A:\BallonTranslator\ui\dl_manager.py", line 187, in _translate_page File "A:\BallonTranslator\dl\translators__init__.py", line 149, in translate_textblk_lst File "A:\BallonTranslator\dl\translators__init__.py", line 122, in translate File "A:\BallonTranslator\dl\translators__init__.py", line 207, in _translate File "A:\BallonTranslator\dl\translators\google_trans.py", line 193, in translate dl.translators.exceptions.RequestError: Request exception can happen due to an api connection error. Please check your connection and try again
> > 
> > 
> > Set url of googletranslator to "***.com" in config panel
> 
> 我也遇到类似的错误 Traceback (most recent call last): File "H:\COMICT1\BALLON1\ui\dl_manager.py", line 226, in run_translate_pipeline File "H:\COMICT1\BALLON1\ui\dl_manager.py", line 190, in translate_page File "H:\COMICT1\BALLON1\dl\translators_init.py", line 153, in translate_textblk_lst File "H:\COMICT1\BALLON1\dl\translators_init.py", line 126, in translate File "H:\COMICT1\BALLON1\dl\translators_init_.py", line 213, in _translate File "H:\COMICT1\BALLON1\dl\translators\google_trans.py", line 193, in translate dl.translators.exceptions.RequestError: Request exception can happen due to an api connection error. Please check your connection and try again
> 
> 设定里我看谷歌翻译的url只有一个选项而且已经是com了， 请问是在别的什么地方改么？

大陆用谷歌现在要翻墙开全局代理

**Comment by Darkari** [comment]
> > > > When using it，this will happen Traceback (most recent call last): File "A:\BallonTranslator\ui\dl_manager.py", line 223, in _run_translate_pipeline File "A:\BallonTranslator\ui\dl_manager.py", line 187, in _translate_page File "A:\BallonTranslator\dl\translators__init__.py", line 149, in translate_textblk_lst File "A:\BallonTranslator\dl\translators__init__.py", line 122, in translate File "A:\BallonTranslator\dl\translators__init__.py", line 207, in _translate File "A:\BallonTranslator\dl\translators\google_trans.py", line 193, in translate dl.translators.exceptions.RequestError: Request exception can happen due to an api connection error. Please check your connection and try again
> > > 
> > > 
> > > Set url of googletranslator to "***.com" in config panel
> > 
> > 
> > 我也遇到类似的错误 Traceback (most recent call last): File "H:\COMICT1\BALLON1\ui\dl_manager.py", line 226, in run_translate_pipeline File "H:\COMICT1\BALLON1\ui\dl_manager.py", line 190, in translate_page File "H:\COMICT1\BALLON1\dl\translators_init.py", line 153, in translate_textblk_lst File "H:\COMICT1\BALLON1\dl\translators_init.py", line 126, in translate File "H:\COMICT1\BALLON1\dl\translators_init_.py", line 213, in _translate File "H:\COMICT1\BALLON1\dl\translators\google_trans.py", line 193, in translate dl.translators.exceptions.RequestError: Request exception can happen due to an api connection error. Please check your connection and try again
> > 设定里我看谷歌翻译的url只有一个选项而且已经是com了， 请问是在别的什么地方改么？
> 
> 大陆用谷歌现在要翻墙开全局代理

不过我不需要翻墙hhh，换个翻译器就没这个问题了

**Comment by Djionter** [comment]
请问一下如何在文本检测 未检测为文本，或者文本过近将两段文本检测为一段的情况下手动调整（比如漫画里面的语气词之类的），能否手动添加文本框后自动OCR抹字？

**Comment by dmMaze** [comment]
> 请问一下如何在文本检测 未检测为文本，或者文本过近将两段文本检测为一段的情况下手动调整（比如漫画里面的语气词之类的），能否手动添加文本框后自动OCR抹字？

最新版可以，见https://github.com/dmMaze/BallonsTranslator/blob/master/CHANGELOG.md#2022-12-30

**Comment by Djionter** [comment]
> > 请问一下如何在文本检测 未检测为文本，或者文本过近将两段文本检测为一段的情况下手动调整（比如漫画里面的语气词之类的），能否手动添加文本框后自动OCR抹字？
> 
> 最新版可以，见https://github.com/dmMaze/BallonsTranslator/blob/master/CHANGELOG.md#2022-12-30

已经升级到1.3.27了，在文本编辑模式下右键添加文本框后在弹出的菜单中，无论选择OCR、或者翻译抹字等，都无法识别文本

**Comment by dmMaze** [comment]
> > > 请问一下如何在文本检测 未检测为文本，或者文本过近将两段文本检测为一段的情况下手动调整（比如漫画里面的语气词之类的），能否手动添加文本框后自动OCR抹字？
> > 
> > 
> > 最新版可以，见https://github.com/dmMaze/BallonsTranslator/blob/master/CHANGELOG.md#2022-12-30
> 
> 已经升级到1.3.27了，在文本编辑模式下右键添加文本框后在弹出的菜单中，无论选择OCR、或者翻译抹字等，都无法识别文本和翻译（抹字似乎正常）

![屏幕截图 2023-01-30 101757](https://user-images.githubusercontent.com/51270320/215373783-491b2707-5b46-47b9-abdc-a1066187d953.jpg)

**Comment by Djionter** [comment]
> > > > 请问一下如何在文本检测 未检测为文本，或者文本过近将两段文本检测为一段的情况下手动调整（比如漫画里面的语气词之类的），能否手动添加文本框后自动OCR抹字？
> > > 
> > > 
> > > 最新版可以，见https://github.com/dmMaze/BallonsTranslator/blob/master/CHANGELOG.md#2022-12-30
> > 
> > 
> > 已经升级到1.3.27了，在文本编辑模式下右键添加文本框后在弹出的菜单中，无论选择OCR、或者翻译抹字等，都无法识别文本和翻译（抹字似乎正常）
> 
> ![屏幕截图 2023-01-30 101757](https://user-images.githubusercontent.com/51270320/215373783-491b2707-5b46-47b9-abdc-a1066187d953.jpg)

我确定OCR设置没有问题

**Comment by dmMaze** [comment]
> > > > > 请问一下如何在文本检测 未检测为文本，或者文本过近将两段文本检测为一段的情况下手动调整（比如漫画里面的语气词之类的），能否手动添加文本框后自动OCR抹字？
> > > > 
> > > > 
> > > > 最新版可以，见https://github.com/dmMaze/BallonsTranslator/blob/master/CHANGELOG.md#2022-12-30
> > > 
> > > 
> > > 已经升级到1.3.27了，在文本编辑模式下右键添加文本框后在弹出的菜单中，无论选择OCR、或者翻译抹字等，都无法识别文本和翻译（抹字似乎正常）
> > 
> > 
> > ![屏幕截图 2023-01-30 101757](https://user-images.githubusercontent.com/51270320/215373783-491b2707-5b46-47b9-abdc-a1066187d953.jpg)
> 
> 我确定OCR设置没有问题
> 
> 补充一下，mit32px和mit48px对单行横排可以识别，mangocr可以对多行竖排可以识别，但是横排完全无能为力，每次识别的内容都和不一样，感觉像别人识别的内容

mangaocr对横排日文也不太行吗...
要改善只能重新训练检测或者ocr模型，或者我撸个不靠谱算法给它自动分行(写过但是我找不着了)...但是都不保证我短期内有这个时间...

**Comment by Djionter** [comment]
> > > > > > 请问一下如何在文本检测 未检测为文本，或者文本过近将两段文本检测为一段的情况下手动调整（比如漫画里面的语气词之类的），能否手动添加文本框后自动OCR抹字？
> > > > > 
> > > > > 
> > > > > 最新版可以，见https://github.com/dmMaze/BallonsTranslator/blob/master/CHANGELOG.md#2022-12-30
> > > > 
> > > > 
> > > > 已经升级到1.3.27了，在文本编辑模式下右键添加文本框后在弹出的菜单中，无论选择OCR、或者翻译抹字等，都无法识别文本和翻译（抹字似乎正常）
> > > 
> > > 
> > > ![屏幕截图 2023-01-30 101757](https://user-images.githubusercontent.com/51270320/215373783-491b2707-5b46-47b9-abdc-a1066187d953.jpg)
> > 
> > 
> > 我确定OCR设置没有问题
> > 补充一下，mit32px和mit48px对单行横排可以识别，mangocr可以对多行竖排可以识别，但是横排完全无能为力，每次识别的内容都和不一样，感觉像别人识别的内容
> 
> mangaocr对横排日文也不太行吗... 要改善只能重新训练检测或者ocr模型，或者我撸个不靠谱算法给它自动分行(写过但是我找不着了)...但是都不保证我短期内有这个时间...

但是在自动处理里面，mit32px和mit48px对多行文本都没有识别的问题，只有在手动文本·识别中出现多行无法识别

**Comment by GaoSiMoHu** [comment]
不好意思我有点弄不明白，Ballonstranslator-1.30-core.7z是直接能运行的，但是我尝试把Ballonstranslator-1.3.28-core.7z的文件解压进去，之后再运行软件，软件界面会变得混乱。
可能是我解压的位置不对吧，能否明确说明更新文件要解压到Ballonstranslator的什么路径可以吗，谢谢

**Comment by dmMaze** [comment]
> 不好意思我有点弄不明白，Ballonstranslator-1.30-core.7z是直接能运行的，但是我尝试把Ballonstranslator-1.3.28-core.7z的文件解压进去，之后再运行软件，软件界面会变得混乱。 可能是我解压的位置不对吧，能否明确说明更新文件要解压到Ballonstranslator的什么路径可以吗，谢谢

有提示替换几百个文件就对了，替换所有的同名文件
还是乱的话给我个截图看看...

**Comment by GaoSiMoHu** [comment]
我使用原装的Ballonstranslator-1.30-core.7z启动之后，出现了翻译失败的提示框，文字什么的都有去除，但是没有翻译的出现

**Comment by GaoSiMoHu** [comment]
https://great.wzznft.com/i/2023/02/14/kh3ot0.png用原装Ballonstranslator-1.30-core然后提示翻译失败
https://great.wzznft.com/i/2023/02/14/kh49ve.png第二张是解压后，界面变得奇怪了

**Comment by dmMaze** [comment]
> https://great.wzznft.com/i/2023/02/14/kh49ve.png第二张是解压后，界面变得奇怪了

怪
启动时控制台log给我看看，就是https://github.com/dmMaze/BallonsTranslator#%E4%B8%80%E9%94%AE%E7%BF%BB%E8%AF%91 下面gif启动的那个黑框内容

**Comment by GaoSiMoHu** [comment]
> > [https://great.wzznft.com/i/2023/02/14/kh49ve.png第二张是解压后，界面变得奇怪了](https://great.wzznft.com/i/2023/02/14/kh49ve.png%E7%AC%AC%E4%BA%8C%E5%BC%A0%E6%98%AF%E8%A7%A3%E5%8E%8B%E5%90%8E%EF%BC%8C%E7%95%8C%E9%9D%A2%E5%8F%98%E5%BE%97%E5%A5%87%E6%80%AA%E4%BA%86)
> 
> 怪 启动时控制台log给我看看，就是https://github.com/dmMaze/BallonsTranslator#%E4%B8%80%E9%94%AE%E7%BF%BB%E8%AF%91 下面gif启动的那个黑框内容

https://great.wzznft.com/i/2023/02/15/gu5ay1.png

**Comment by GaoSiMoHu** [comment]
> > [https://great.wzznft.com/i/2023/02/14/kh49ve.png第二张是解压后，界面变得奇怪了](https://great.wzznft.com/i/2023/02/14/kh49ve.png%E7%AC%AC%E4%BA%8C%E5%BC%A0%E6%98%AF%E8%A7%A3%E5%8E%8B%E5%90%8E%EF%BC%8C%E7%95%8C%E9%9D%A2%E5%8F%98%E5%BE%97%E5%A5%87%E6%80%AA%E4%BA%86)
> 
> 怪 启动时控制台log给我看看，就是https://github.com/dmMaze/BallonsTranslator#%E4%B8%80%E9%94%AE%E7%BF%BB%E8%AF%91 下面gif启动的那个黑框内容

https://great.wzznft.com/i/2023/02/15/gu5ay1.png
https://great.wzznft.com/i/2023/02/15/gwnma7.png
https://great.wzznft.com/i/2023/02/15/gwo8dq.png

**Comment by dmMaze** [comment]
> > > [https://great.wzznft.com/i/2023/02/14/kh49ve.png第二张是解压后，界面变得奇怪了](https://great.wzznft.com/i/2023/02/14/kh49ve.png%E7%AC%AC%E4%BA%8C%E5%BC%A0%E6%98%AF%E8%A7%A3%E5%8E%8B%E5%90%8E%EF%BC%8C%E7%95%8C%E9%9D%A2%E5%8F%98%E5%BE%97%E5%A5%87%E6%80%AA%E4%BA%86)
> > 
> > 
> > 怪 启动时控制台log给我看看，就是https://github.com/dmMaze/BallonsTranslator#%E4%B8%80%E9%94%AE%E7%BF%BB%E8%AF%91 下面gif启动的那个黑框内容
> 
> https://great.wzznft.com/i/2023/02/15/gu5ay1.png https://great.wzznft.com/i/2023/02/15/gwnma7.png https://great.wzznft.com/i/2023/02/15/gwo8dq.png

<img width="731" alt="image" src="https://user-images.githubusercontent.com/51270320/218920113-50c110a9-681a-45a5-80da-47051468e7cf.png">
你找找看这个文件存不存在
然后试试把路径里的中文改成英文

**Comment by GXSSGX** [comment]
![image](https://user-images.githubusercontent.com/103052252/221368607-102e17cb-385e-44c8-9be7-33188d06317a.png)
大佬，我已经新建了替换文本，但是依旧无法改变翻译的结果，哪怕退出后，重新用原来的图片翻译，得到的结果依旧和没有替换文本的一样，是哪里操作有问题么？

**Comment by dmMaze** [comment]
> ![image](https://user-images.githubusercontent.com/103052252/221368607-102e17cb-385e-44c8-9be7-33188d06317a.png) 大佬，我已经新建了替换文本，但是依旧无法改变翻译的结果，哪怕退出后，重新用原来的图片翻译，得到的结果依旧和没有替换文本的一样，是哪里操作有问题么？

被替换的关键词得是机翻结果的，不是原文的

**Comment by GXSSGX** [comment]
> > ![image](https://user-images.githubusercontent.com/103052252/221368607-102e17cb-385e-44c8-9be7-33188d06317a.png) 大佬，我已经新建了替换文本，但是依旧无法改变翻译的结果，哪怕退出后，重新用原来的图片翻译，得到的结果依旧和没有替换文本的一样，是哪里操作有问题么？
> 
> 被替换的关键词得是机翻结果的，不是原文的

是这样啊，谢谢大佬的解答
