### ISSUE TITLE
希望提供一个按钮“所有页面全局选中”可以全选上"所有页面"上的所有对象（文字和框）

### ISSUE THREAD

**Issue by gsxgmpkt9020** [dmMaze/BallonsTranslator#684]
希望提供一个按钮“所有页面全局选中”可以全选上"所有页面"上的所有对象（文字和框）

**Comment by dmMaze** [comment]
ctrl+a

**Comment by gsxgmpkt9020** [comment]
> ctrl+a

早就试过了，我这边ctrl+a （CONTROL ALL）的结果是只能选中"当前页面"(SINGLE PAGE)的对象

我发现自己之前文字表述不严谨，产生了汉语中的歧义

**Comment by dmMaze** [comment]
> > ctrl+a
> 
> 早就试过了，我这边ctrl+a （CONTROL ALL）的结果是只能选中"当前页面"(SINGLE PAGE)的对象
> 
> 我发现自己之前文字表述不严谨，产生了汉语中的歧义

为啥需要全选整个项目的文字块？

**Comment by gsxgmpkt9020** [comment]
> > > ctrl+a
> > 
> > 
> > 早就试过了，我这边ctrl+a （CONTROL ALL）的结果是只能选中"当前页面"(SINGLE PAGE)的对象
> > 我发现自己之前文字表述不严谨，产生了汉语中的歧义
> 
> 为啥需要全选整个项目的文字块？

全局调节旧项目的大小颜色字体等等，特别是大项目几百页

**Comment by dmMaze** [comment]
> > > > ctrl+a
> > > 
> > > 
> > > 早就试过了，我这边ctrl+a （CONTROL ALL）的结果是只能选中"当前页面"(SINGLE PAGE)的对象
> > > 我发现自己之前文字表述不严谨，产生了汉语中的歧义
> > 
> > 
> > 为啥需要全选整个项目的文字块？
> 
> 全局调节旧项目的大小颜色字体等等，特别是大项目几百页

顶部栏去掉所有勾再重新跑一遍就会应用当前字体设置

**Comment by gsxgmpkt9020** [comment]
> > > > > ctrl+a
> > > > 
> > > > 
> > > > 早就试过了，我这边ctrl+a （CONTROL ALL）的结果是只能选中"当前页面"(SINGLE PAGE)的对象
> > > > 我发现自己之前文字表述不严谨，产生了汉语中的歧义
> > > 
> > > 
> > > 为啥需要全选整个项目的文字块？
> > 
> > 
> > 全局调节旧项目的大小颜色字体等等，特别是大项目几百页
> 
> 顶部栏去掉所有勾再重新跑一遍就会应用当前字体设置

谢谢

**Comment by gsxgmpkt9020** [comment]
edit
