### ISSUE TITLE
copying areas of text, pasting text into multiple areas of text

### ISSUE THREAD

**Issue by KirpichKrasniy** [dmMaze/BallonsTranslator#69]
hello, is it possible to add to them the ability to enter the same text when selecting several areas of text? (paste copied text) Let's say I need to paste one number "1" into 10 different text clouds, it's inconvenient to enter them in turn everywhere. is it possible to add a text alignment feature? create guides like in Photoshop so that text can align with them is it possible to make it possible to copy multiple areas with text and paste them elsewhere? Let's say I want to copy two areas of text and paste them side by side so they're aligned. sorry if there are such functions, I read the instructions in Russian and did not understand anything ... perhaps the translation of the instructions is incorrect. if you want, I can later translate the instruction into Russian and send it to you, perhaps it will come in handy for some of the Russian-speaking users

**Comment by dmMaze** [comment]
I'm not sure I can understand these feature requests correctly. Perhaps you can make a video record of these PS operations and paste it here.

**Comment by KirpichKrasniy** [comment]
> I'm not sure I can understand these feature requests correctly. Perhaps you can make a video record of these PS operations and paste it here.

ok i will try to show it on video

**Comment by KirpichKrasniy** [comment]
> I'm not sure I can understand these feature requests correctly. Perhaps you can make a video record of these PS operations and paste it here.

![2022-12-23 12-08-04 (1)](https://user-images.githubusercontent.com/109726461/209314123-4a07e0e6-0992-4e9d-8293-e27edded71cb.gif)

**Comment by KirpichKrasniy** [comment]
sorry for the quality, i had to compress the gif to 10mb

**Comment by dmMaze** [comment]
> > I'm not sure I can understand these feature requests correctly. Perhaps you can make a video record of these PS operations and paste it here.
> 
> ![2022-12-23 12-08-04 (1)](https://user-images.githubusercontent.com/109726461/209314123-4a07e0e6-0992-4e9d-8293-e27edded71cb.gif)
> 

Seems comes in handy! I'll take my time to implement these.  
As for russian translation you may discuss with @bropines

**Comment by KirpichKrasniy** [comment]
> > > I'm not sure I can understand these feature requests correctly. Perhaps you can make a video record of these PS operations and paste it here.
> > 
> > 
> > ![2022-12-23 12-08-04 (1)](https://user-images.githubusercontent.com/109726461/209314123-4a07e0e6-0992-4e9d-8293-e27edded71cb.gif)
> >       
> >         [
> >           
> >             ![2022-12-23 12-08-04 (1)](https://user-images.githubusercontent.com/109726461/209314123-4a07e0e6-0992-4e9d-8293-e27edded71cb.gif)
> >           
> >         ](https://user-images.githubusercontent.com/109726461/209314123-4a07e0e6-0992-4e9d-8293-e27edded71cb.gif)
> >         
> >         
> >           
> >             
> >               
> >             
> >             
> >               
> >               
> >             
> >           
> >           [
> >             
> >               
> >             
> >           ](https://user-images.githubusercontent.com/109726461/209314123-4a07e0e6-0992-4e9d-8293-e27edded71cb.gif)
> 
> Seems comes in handy! I'll take my time to implement these. As for russian translation you may discuss with @bropines

thanks for the answer

**Comment by bropines** [comment]
> Seems comes in handy! I'll take my time to implement these.
> As for russian translation you may discuss with @bropines

Ты русский? Напиши мне в телеграмме. Такой же никнейм
---
Are you Russian? Write me a telegram. Same nickname

**Comment by bropines** [comment]
> > Seems comes in handy! I'll take my time to implement these. As for russian translation you may discuss with @bropines
> 
> thanks for the answer

I wrote to you in VK.

**Comment by bropines** [comment]
Basically, I made a fork a long time ago, in which I update the Russian language and experiment with the design, as well as introduce new models and neural networks. If you need Russian, then just go here
[Русский форк/Russian fork](https://github.com/bropines/BallonsTranslator)
