### ISSUE TITLE
手工修复的遮罩层是白色，而自动运行出来的都是不同程度的灰色

### ISSUE THREAD

**Issue by gsxgmpkt9020** [dmMaze/BallonsTranslator#695]
不知道动了什么设置变成这样了

![image](https://github.com/user-attachments/assets/c763ef94-80a7-48dd-9a70-795287765e57)

左上角的是手工处理过的，其他两个自动运行修复都变成狗皮膏药了

**Comment by gsxgmpkt9020** [comment]
![image](https://github.com/user-attachments/assets/aa43d1f1-1a34-4c4b-b8ab-f5a9d0389161)
甚至还有直接变黑的，大概是靠近头发的原因，是不是参数设置问题？paintsize之类的

**Comment by bropines** [comment]
Show inpainter parameters
![image](https://github.com/user-attachments/assets/e996d7d5-aa2f-44d3-9ee9-8525f306fdf3)

**Comment by gsxgmpkt9020** [comment]
> Show inpainter parameters ![image](https://private-user-images.githubusercontent.com/57861007/398112887-e996d7d5-aa2f-44d3-9ee9-8525f306fdf3.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzQ5NjA4NTMsIm5iZiI6MTczNDk2MDU1MywicGF0aCI6Ii81Nzg2MTAwNy8zOTgxMTI4ODctZTk5NmQ3ZDUtYWEyZi00NGQzLTllZTktODUyNWYzMDZmZGYzLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEyMjMlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMjIzVDEzMjkxM1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWQ0NDUzY2E0N2I1OTliZDQ2NjVlMWQ2YzMyYTA2YmIwYWUxNTFjMWYwYjM5YjAwZDAxZjM4MzM4MGRmY2FiZjAmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.RmBc8g1Y2hLh5VkRLpY3ZwbV2eO-lSx3_CGEI6Q9GHY)

![image](https://github.com/user-attachments/assets/f723edbc-bc63-4a80-9ff6-deba0a9ff9e5)
 I can make sure background will be right when I using manual inpaint. If I use "run" button,  background color will be wrong

**Comment by bropines** [comment]
> > Show inpainter parameters ![image](https://private-user-images.githubusercontent.com/57861007/398112887-e996d7d5-aa2f-44d3-9ee9-8525f306fdf3.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzQ5NjA4NTMsIm5iZiI6MTczNDk2MDU1MywicGF0aCI6Ii81Nzg2MTAwNy8zOTgxMTI4ODctZTk5NmQ3ZDUtYWEyZi00NGQzLTllZTktODUyNWYzMDZmZGYzLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEyMjMlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMjIzVDEzMjkxM1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWQ0NDUzY2E0N2I1OTliZDQ2NjVlMWQ2YzMyYTA2YmIwYWUxNTFjMWYwYjM5YjAwZDAxZjM4MzM4MGRmY2FiZjAmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.RmBc8g1Y2hLh5VkRLpY3ZwbV2eO-lSx3_CGEI6Q9GHY)
> 
> ![image](https://private-user-images.githubusercontent.com/2074641/398171664-f723edbc-bc63-4a80-9ff6-deba0a9ff9e5.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzQ5NjgyNjMsIm5iZiI6MTczNDk2Nzk2MywicGF0aCI6Ii8yMDc0NjQxLzM5ODE3MTY2NC1mNzIzZWRiYy1iYzYzLTRhODAtOWZmNi1kZWJhMGE5ZmY5ZTUucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MTIyMyUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDEyMjNUMTUzMjQzWiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9NTJhZDkxZGNiNmRlZTcyOTU0NjNiNmVjMzQzYTMwZGM1MmQ3ZDM3MWQ3YjE1OTA3YzNlY2NiYjc0ODU4MzYwNiZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QifQ.eQnBLxc4tn7_J12yNr0mCtXnTIOJ4BdR-q-dunXVsug) I can make sure background will be right when I using manual inpaint. If I use "run" button, background color will be wrong

Reduce the `大小` slightly. Check if it has an effect (the program has its own jokes)

**Comment by gsxgmpkt9020** [comment]
> Show inpainter parameters ![image](https://private-user-images.githubusercontent.com/57861007/398112887-e996d7d5-aa2f-44d3-9ee9-8525f306fdf3.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzQ5NjA4NTMsIm5iZiI6MTczNDk2MDU1MywicGF0aCI6Ii81Nzg2MTAwNy8zOTgxMTI4ODctZTk5NmQ3ZDUtYWEyZi00NGQzLTllZTktODUyNWYzMDZmZGYzLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEyMjMlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMjIzVDEzMjkxM1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWQ0NDUzY2E0N2I1OTliZDQ2NjVlMWQ2YzMyYTA2YmIwYWUxNTFjMWYwYjM5YjAwZDAxZjM4MzM4MGRmY2FiZjAmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.RmBc8g1Y2hLh5VkRLpY3ZwbV2eO-lSx3_CGEI6Q9GHY)

Things get improved but not perfect, for one bubble need to try many times and results are different. I don't know if it is because my images are webp format.

**Comment by dmMaze** [comment]
矩形工具拉低膨胀滑条

**Comment by gsxgmpkt9020** [comment]
> 矩形工具拉低膨胀滑条

Finally works.
