### ISSUE TITLE
一键翻译默认字体和文字轮廓都是黑色，字看不清了

### ISSUE THREAD

**Issue by yuwode** [dmMaze/BallonsTranslator#7]
碰到字体轮廓20%或其他比列就只能一个个改，能不能默认字体黑色，轮廓白色.

**Comment by dmMaze** [comment]
字体颜色和轮廓颜色是模型提取的，有色差就会加轮廓，下一版可以把这个色差取大点，顺便加全局设置

**Comment by dmMaze** [comment]
[v1.3.0](https://github.com/dmMaze/BallonsTranslator/releases/tag/v1.3.0)已引入全局字体设置和批量字体格式调整, 详见更新说明
