### ISSUE TITLE
A question

### ISSUE THREAD

**Issue by EasyRuby** [dmMaze/BallonsTranslator#70]
I'm a new guy,and I want to know how to zoom the picture,the pictures I opened seems too big,and I have no idea to zoom them

**Comment by dmMaze** [comment]
```Ctrl```+```+``` or ```Ctrl```+```-```
Or ```Ctrl```+```mouse scroll```
see https://github.com/dmMaze/BallonsTranslator/blob/master/README_EN.md#shortcuts

**Comment by EasyRuby** [comment]
God,I didn't notice it.Thanks so much.
