### ISSUE TITLE
使用几小时发现的一些bug

### ISSUE THREAD

**Issue by KFC0803** [dmMaze/BallonsTranslator#73]
1. 在文本编辑界面选择文字时，如果鼠标拖动停止的位置在文字框外，那么就无法复制
2. 在右侧修改文字后，左侧的文字经常会有奇怪的错误（如图）。
3. 图像修复的inpaint_size默认为2048，但是我这边会因为爆内存而崩溃，建议默认1024

![Snipaste_2022-12-29_16-08-08](https://user-images.githubusercontent.com/22217328/209923353-14639c64-7d9a-40be-87a1-a01543d75269.png)

另外，我发现字体颜色的识别有点问题，经常会把黑色设置成灰色（可能是jpg噪点的问题），建议增加全局修改字体颜色的功能。

**Comment by dmMaze** [comment]
> 2\. 在右侧修改文字后，左侧的文字经常会有奇怪的错误（如图）。

你得录个gif或者告诉我怎么复现... 
因为左边的和右边的文本编辑框都有自己的撤销重做栈，所以之前写了个全局撤销栈接管了qt的里面可能有一堆坑我也不一定有时间修的来，如果太麻烦我宁愿把右边译文框都删了或者做成只读的...



> 3\. 图像修复的inpaint_size默认为2048，但是我这边会因为爆内存而崩溃，建议默认1024

那个是显存README里写了...



> 建议增加全局修改字体颜色的功能。

可以在设置面板里设置启用全局字体颜色

**Comment by KFC0803** [comment]
> > 2. 在右侧修改文字后，左侧的文字经常会有奇怪的错误（如图）。
> 
> 你得录个gif或者告诉我怎么复现... 因为左边的和右边的文本编辑框都有自己的撤销重做栈，所以之前写了个全局撤销栈接管了qt的里面可能有一堆坑我也不一定有时间修的来，如果太麻烦我宁愿把右边译文框都删了或者做成只读的...
> 
> > 3. 图像修复的inpaint_size默认为2048，但是我这边会因为爆内存而崩溃，建议默认1024
> 
> 那个是显存README里写了...
> 
> > 建议增加全局修改字体颜色的功能。
> 
> 可以在设置面板里设置启用全局字体颜色

![GIF](https://user-images.githubusercontent.com/22217328/209938463-a44dec5d-5c57-4c1b-a98b-1183f9107155.gif)
好像是省略号的问题

**Comment by dmMaze** [comment]
> * 在右侧修改文字后，左侧的文字经常会有奇怪的错误（如图）。

[v1.3.18](https://github.com/dmMaze/BallonsTranslator/releases/tag/v1.3.18) 应该修好了

**Comment by KFC0803** [comment]
> > * 在右侧修改文字后，左侧的文字经常会有奇怪的错误（如图）。
> 
> [v1.3.18](https://github.com/dmMaze/BallonsTranslator/releases/tag/v1.3.18) 应该修好了

好像没有完全修好
![GIF](https://user-images.githubusercontent.com/22217328/210289823-31974988-987e-423b-874f-81cb3da06b1c.gif)

**Comment by dmMaze** [comment]
> > > * 在右侧修改文字后，左侧的文字经常会有奇怪的错误（如图）。
> > 
> > 
> > [v1.3.18](https://github.com/dmMaze/BallonsTranslator/releases/tag/v1.3.18) 应该修好了
> 
> 好像没有完全修好 ![GIF](https://user-images.githubusercontent.com/22217328/210289823-31974988-987e-423b-874f-81cb3da06b1c.gif) [ ![GIF](https://user-images.githubusercontent.com/22217328/210289823-31974988-987e-423b-874f-81cb3da06b1c.gif) ](https://user-images.githubusercontent.com/22217328/210289823-31974988-987e-423b-874f-81cb3da06b1c.gif) [ ](https://user-images.githubusercontent.com/22217328/210289823-31974988-987e-423b-874f-81cb3da06b1c.gif)

这个全角符号bug v1.3.22修好了

**Comment by KFC0803** [comment]
v1.3.22
![GIF](https://user-images.githubusercontent.com/22217328/211228122-91e8ef7c-21cd-4df5-ada1-62dfbfe081f0.gif)

**Comment by dmMaze** [comment]
> v1.3.22 ![GIF](https://user-images.githubusercontent.com/22217328/211228122-91e8ef7c-21cd-4df5-ada1-62dfbfe081f0.gif) [ ![GIF](https://user-images.githubusercontent.com/22217328/211228122-91e8ef7c-21cd-4df5-ada1-62dfbfe081f0.gif) ](https://user-images.githubusercontent.com/22217328/211228122-91e8ef7c-21cd-4df5-ada1-62dfbfe081f0.gif) [ ](https://user-images.githubusercontent.com/22217328/211228122-91e8ef7c-21cd-4df5-ada1-62dfbfe081f0.gif)

v1.3.24已修
