### ISSUE TITLE
什么时候能增加手动框选OCR的功能呢

### ISSUE THREAD

**Issue by lhj5426** [dmMaze/BallonsTranslator#74]
![image](https://user-images.githubusercontent.com/30548000/210053915-375316a2-3408-498e-a69e-d7abc6e907da.png)
尊敬的大佬 虽然AI自动识别做的很牛逼 但是还有很多极端情况 
需要手动来修正

**Comment by lhj5426** [comment]
![image](https://user-images.githubusercontent.com/30548000/210058659-dd108705-30d8-41c3-a17e-f57ce974cada.png)
举个极端的例子  这里是2句话 被识别成了一句话 而且只识别了部分
如果有手动框选识别的话
这里操作可以是这样
1删除AI自动识别的框
2手动框选识别
3翻译

**Comment by dmMaze** [comment]
争取2023前吧

**Comment by lhj5426** [comment]
> 争取2023前吧

还有一个问题 
inpainted 成品图
mask 掩码
result 涂抹过的图
在图片文件夹下会生成这3个文件夹
然后呢 CG一般分有字图和无文字的图片
![000004](https://user-images.githubusercontent.com/30548000/210063750-650e917e-5965-4bff-9b34-2025ec9acb8c.jpg)

也就是这种不需要手动去去除文字的图片
![000004 jpg-original](https://user-images.githubusercontent.com/30548000/210063773-73ac3bea-103e-4d1b-9dd9-e543854b9b12.jpg)
然后呢 我自作聪明的 以为 直接把 无文字图替换到 result  这个文件夹里就可以 
实际上并不是软件读取的还是已经不存的了的被AI涂抹去字的图
然后我又以为 是不是因为掩码的问题
我把mask  文件夹里图片删掉之后 项目就打不开了
![image](https://user-images.githubusercontent.com/30548000/210064107-b4a39245-8e67-4ab4-8756-d74688062799.png)

这个问题就是 要怎么 用 无文字图  来替换  AI 涂抹过的图片
就是 改怎么形容呢

就是 OCR的时候 用 有字图 来OCR
然后嵌字的时候呢 用 无文字图
而不是AI涂抹的图片。。

**Comment by dmMaze** [comment]
> > 争取2023前吧
> 
> 还有一个问题 inpainted 成品图 mask 掩码 result 涂抹过的图 在图片文件夹下会生成这3个文件夹 然后呢 CG一般分有字图和无文字的图片 ![000004](https://user-images.githubusercontent.com/30548000/210063750-650e917e-5965-4bff-9b34-2025ec9acb8c.jpg)
> 
> 也就是这种不需要手动去去除文字的图片 ![000004 jpg-original](https://user-images.githubusercontent.com/30548000/210063773-73ac3bea-103e-4d1b-9dd9-e543854b9b12.jpg) 然后呢 我自作聪明的 以为 直接把 无文字图替换到 result 这个文件夹里就可以 实际上并不是软件读取的还是已经不存的了的被AI涂抹去字的图 然后我又以为 是不是因为掩码的问题 我把mask 文件夹里图片删掉之后 项目就打不开了 ![image](https://user-images.githubusercontent.com/30548000/210064107-b4a39245-8e67-4ab4-8756-d74688062799.png)
> 
> 这个问题就是 要怎么 用 无文字图 来替换 AI 涂抹过的图片 就是 改怎么形容呢
> 
> 就是 OCR的时候 用 有字图 来OCR 然后嵌字的时候呢 用 无文字图 而不是AI涂抹的图片。。



> 然后呢 我自作聪明的 以为 直接把 无文字图替换到 result 这个文件夹里就可以

这个思路是对的，丢到inpainted里不是result里，还得保证你用来替换的图尺寸和后缀名都跟被替换的一样

**Comment by lhj5426** [comment]
> > > 争取2023前吧
> > 
> > 
> > 还有一个问题 inpainted 成品图 mask 掩码 result 涂抹过的图 在图片文件夹下会生成这3个文件夹 然后呢 CG一般分有字图和无文字的图片 ![000004](https://user-images.githubusercontent.com/30548000/210063750-650e917e-5965-4bff-9b34-2025ec9acb8c.jpg)
> > 也就是这种不需要手动去去除文字的图片 ![000004 jpg-original](https://user-images.githubusercontent.com/30548000/210063773-73ac3bea-103e-4d1b-9dd9-e543854b9b12.jpg) 然后呢 我自作聪明的 以为 直接把 无文字图替换到 result 这个文件夹里就可以 实际上并不是软件读取的还是已经不存的了的被AI涂抹去字的图 然后我又以为 是不是因为掩码的问题 我把mask 文件夹里图片删掉之后 项目就打不开了 ![image](https://user-images.githubusercontent.com/30548000/210064107-b4a39245-8e67-4ab4-8756-d74688062799.png)
> > 这个问题就是 要怎么 用 无文字图 来替换 AI 涂抹过的图片 就是 改怎么形容呢
> > 就是 OCR的时候 用 有字图 来OCR 然后嵌字的时候呢 用 无文字图 而不是AI涂抹的图片。。
> 
> > 然后呢 我自作聪明的 以为 直接把 无文字图替换到 result 这个文件夹里就可以
> 
> 这个思路是对的，丢到inpainted里不是result里，还得保证你用来替换的图尺寸和后缀名都跟被替换的一样

原来是替换错 文件夹了我再去重新跑一遍替换到 inpainted 试试 谢谢

**Comment by lhj5426** [comment]
> > > 争取2023前吧
> > 
> > 
> > 还有一个问题 inpainted 成品图 mask 掩码 result 涂抹过的图 在图片文件夹下会生成这3个文件夹 然后呢 CG一般分有字图和无文字的图片 ![000004](https://user-images.githubusercontent.com/30548000/210063750-650e917e-5965-4bff-9b34-2025ec9acb8c.jpg)
> > 也就是这种不需要手动去去除文字的图片 ![000004 jpg-original](https://user-images.githubusercontent.com/30548000/210063773-73ac3bea-103e-4d1b-9dd9-e543854b9b12.jpg) 然后呢 我自作聪明的 以为 直接把 无文字图替换到 result 这个文件夹里就可以 实际上并不是软件读取的还是已经不存的了的被AI涂抹去字的图 然后我又以为 是不是因为掩码的问题 我把mask 文件夹里图片删掉之后 项目就打不开了 ![image](https://user-images.githubusercontent.com/30548000/210064107-b4a39245-8e67-4ab4-8756-d74688062799.png)
> > 这个问题就是 要怎么 用 无文字图 来替换 AI 涂抹过的图片 就是 改怎么形容呢
> > 就是 OCR的时候 用 有字图 来OCR 然后嵌字的时候呢 用 无文字图 而不是AI涂抹的图片。。
> 
> > 然后呢 我自作聪明的 以为 直接把 无文字图替换到 result 这个文件夹里就可以
> 
> 这个思路是对的，丢到inpainted里不是result里，还得保证你用来替换的图尺寸和后缀名都跟被替换的一样


![image](https://user-images.githubusercontent.com/30548000/210066885-d5295901-35ea-414a-893e-1c47c3dce2fc.png)
确实好使 先把JPG的图片格式转换成png 然后丢到 inpainted 里就可以在无文字图上签字了
