### ISSUE TITLE
能否增加文本替换功能？

### ISSUE THREAD

**Issue by lhj5426** [dmMaze/BallonsTranslator#78]
![image](https://user-images.githubusercontent.com/30548000/210403794-838517cb-8684-4749-93b0-45fd52812c94.png)
本软件里内置了一堆翻译但是我只有彩云的API 
（其实还有百度 有道 腾讯 火山 等等的API 帐号 但是 软件没有内置我也不会写所以能用的只有彩云aPI）
而彩云API有个问题 每隔几句话就出一个 something
能否增加个这种功能
![image](https://user-images.githubusercontent.com/30548000/210404108-185f2e8d-595c-4687-8880-3400c4187872.png)
可以 快速修正翻译文本
![image](https://user-images.githubusercontent.com/30548000/210404407-0cbb2715-6d86-4266-9c6e-646814189415.png)
 图片是截图自隔壁的翻译软件
https://github.com/HIllya51/LunaTranslator

**Comment by lhj5426** [comment]
这样在一定程度上可以减少手动修正的操作
比如晚上好这句话 机器翻译没毛病就可以过了
但是现在是晚上好something 本来可以过的但是现在需要手动修正掉something
这样增加了工作量

**Comment by dmMaze** [comment]
有了，左侧那个搜索图标或者快捷键见#45

**Comment by lhj5426** [comment]
> 有了，左侧那个搜索图标或者快捷键见#45

这个是 。。。。。。。手动替换 每次
我说的是 设置一次 就自动替换了
还是有区别的

**Comment by dmMaze** [comment]
v1.3.24已支持

**Comment by lhj5426** [comment]
> v1.3.24已支持，详见更新日志

这个是手动替换？
就是说每次按 设置的快捷键来替换
而不是在机翻的过程中软件自动替换？

**Comment by lhj5426** [comment]
sorry 看错了 看的是沙拉划词的功能了 
![image](https://user-images.githubusercontent.com/30548000/215127347-2862aff8-5040-41fb-91fd-763737416be2.png)

**Comment by dmMaze** [comment]
> > v1.3.24已支持，详见更新日志
> 
> 这个是手动替换？
> 就是说每次按 设置的快捷键来替换
> 而不是在机翻的过程中软件自动替换？

自动的
