### ISSUE TITLE
倾斜旋转如何快速归0

### ISSUE THREAD

**Issue by lhj5426** [dmMaze/BallonsTranslator#79]
https://user-images.githubusercontent.com/30548000/210500234-bb34a7d4-b9fc-41d9-899b-d5c3e246755e.mp4

怎么调整最近一次也是0,1 默认的0.0 要怎么快速复位呀

**Comment by dmMaze** [comment]
这个肉眼差别不大吧...
我可以限制旋转值为整数

**Comment by lhj5426** [comment]
> 这个肉眼差别不大吧... 我可以限制旋转值为整数

这个可能就是所谓的逼死强迫症吧 本来有00显示然后怎么调整都调整不回去了就很烦吧


![image](https://user-images.githubusercontent.com/30548000/210502235-8613b81a-77a6-4a9f-b75d-9cfca2bb1d12.png)

简单粗暴点 在右键里增加一个 旋转复位 这样 一键回归角度0.0
现在的难受是 转动了就永远别想归0
所以需要的只是一个快速归0复位的 功能 感觉放在右键里不碍事用的时候也就在旁边
不知道这样是否可行？

**Comment by lhj5426** [comment]
现在这种旋转没毛病 问题就是不好归零 只要增加个一键归0旋转复位 就解决这个问题了

**Comment by dmMaze** [comment]
> 所以需要的只是一个快速归0复位的 功能 感觉放在右键里不碍事用的时候也就在旁边

右键挺好，可以批量复位

**Comment by dmMaze** [comment]
v1.3.22已支持角度复位
