### ISSUE TITLE
DeepL: python module needs update

### ISSUE THREAD

**Issue by haode333** [dmMaze/BallonsTranslator#80]
Free Tier DeepL users won't be able to use it because the python module is too old and is using wrong api endpoint.
updating to latest (1.12.0) fix the issue

**Comment by bropines** [comment]
> Free Tier DeepL users won't be able to use it because the python module is too old and is using wrong api endpoint. updating to latest (1.12.0) fix the issue

Is it possible to use it for free?

**Comment by dmMaze** [comment]
Thanks for mentioning it, however I don't have access to deepl so I would not be able to confirm any fix actually work.

> updating to latest (1.12.0) fix the issue

Just updating the package and no modification is required, right? Otherwise, it will be much appreciated if you could make a pr to fix it.

**Comment by haode333** [comment]
> > Free Tier DeepL users won't be able to use it because the python module is too old and is using wrong api endpoint. updating to latest (1.12.0) fix the issue
> 
> Is it possible to use it for free?

Yes they have a free tier

**Comment by haode333** [comment]
> Thanks for mentioning it, however I don't have access to deepl so I would not be able to confirm any fix actually work.
> 
> > updating to latest (1.12.0) fix the issue
> 
> Just updating the package and no modification is required, right? Otherwise, it will be much appreciated if you could make a pr to fix it.

Yes, just updating the package.
I would love to PR but I'm not sure where the DeepL package is in the codebase.

**Comment by dmMaze** [comment]
@haode333  I have just updated it in the released package.

**Comment by haode333** [comment]
Thanks @dmMaze 
I can verify that it works fine.
