### ISSUE TITLE
请问这个是什么问题呢

### ISSUE THREAD

**Issue by HDZM** [dmMaze/BallonsTranslator#82]
TypeError: 'str' object does not support item assignment

**Comment by dmMaze** [comment]
我也不知道，需要完整的错误记录或者操作过程

**Comment by HDZM** [comment]
这个错误已解决，现在是单页想要ocr某一方格内容识别不出来，但是run全部图片却可以文字识别并翻译

**Comment by dmMaze** [comment]
> 这个错误已解决，现在是单页想要ocr某一方格内容识别不出来，但是run全部图片却可以文字识别并翻译

如果是日语可以换mangaocr，其它ocr只能逐行识别（框得贴紧一行
要改善得重新训练模型

**Comment by HDZM** [comment]
更换了，然后 给单独一页的一个方格内容ocr文字识别，会卡死然后闪退
比较奇妙的是点击run反倒是能成功识别并翻译

**Comment by dmMaze** [comment]
> 更换了，然后 给单独一页的一个方格内容ocr文字识别，会卡死然后闪退 比较奇妙的是点击run反倒是能成功识别并翻译

修了
