### ISSUE TITLE
闪退的有点严重

### ISSUE THREAD

**Issue by lhj5426** [dmMaze/BallonsTranslator#9]
不知道为什么管理员权限也会闪退 各种操作下都会发生闪退
好不稳定啊

**Comment by dmMaze** [comment]
闪退的时候命令行终端有啥输出

**Comment by lhj5426** [comment]
> 哪个版本，闪退的时候命令行终端有啥输出

120 没任何提示就是突然就没了 全部都消失了

**Comment by dmMaze** [comment]
> > 哪个版本，闪退的时候命令行终端有啥输出
> 
> 120 没任何提示就是突然就没了 全部都消失了

命令行终端不会消失的吧，看主页一键翻译下面那个gif。
如果这个终端在程序闪退的时候也没有任何信息，那你只能告诉我哪些步骤引起闪退好让我复现

**Comment by lhj5426** [comment]
> > > 哪个版本，闪退的时候命令行终端有啥输出
> > 
> > 
> > 120 没任何提示就是突然就没了 全部都消失了
> 
> 命令行终端不会消失的吧，看主页一键翻译下面那个gif。 如果这个终端在程序闪退的时候也没有任何信息，那你只能告诉我哪些步骤引起闪退好让我复现 还有就是这个新版本是一个完整的包不要覆盖旧版

是完整的包 只有 BallonTranslator.exe启动这个之后 有一个黑框一个GUI界面
什么操作闪退？
OCR修复检测
修复检测
OCR翻译修复检测
单独一张图进行涂抹操作
甚至点击保存 都会导致闪退 非常不稳定 基本上每一个操作都会导致闪退

**Comment by dmMaze** [comment]
> > > > 哪个版本，闪退的时候命令行终端有啥输出
> > > 
> > > 
> > > 120 没任何提示就是突然就没了 全部都消失了
> > 
> > 命令行终端不会消失的吧，看主页一键翻译下面那个gif。 如果这个终端在程序闪退的时候也没有任何信息，那你只能告诉我哪些步骤引起闪退好让我复现 还有就是这个新版本是一个完整的包不要覆盖旧版
> 
> 是完整的包 只有 BallonTranslator.exe启动这个之后 有一个黑框一个GUI界面
> 什么操作闪退？
> OCR修复检测
> 修复检测
> OCR翻译修复检测
> 单独一张图进行涂抹操作
> 甚至点击保存 都会导致闪退 非常不稳定 基本上每一个操作都会导致闪退
> 
> 一共2个界面消失的时候是2个一起消失 包括黑框框  

你看下主页那个一键翻译下面的gif, 就是先启动一个终端再把exe拖进去回车运行，这样gui闪退了那个终端应该会留下有用信息，把那个截图给我
这些操作我自己运行不会崩溃，这个程序已知bug就是一些按键冲突，在我自己的环境下比较稳定

**Comment by lhj5426** [comment]
![image](https://user-images.githubusercontent.com/30548000/172011701-d48d939f-4461-48c5-8036-1c7a730383d8.png)
这个两个框 一个是 打开JSON 闪退了 一共是 导出DOCS闪退了

**Comment by dmMaze** [comment]
> ![image](https://user-images.githubusercontent.com/30548000/172011701-d48d939f-4461-48c5-8036-1c7a730383d8.png)
> 这个两个框 一个是 打开JSON 闪退了 一共是 导出DOCS闪退了 

导出docs和导入json我都还没实现（还不确定要不要加这个导出docs的功能和工程文件最终是个什么结构
你上面说的那几步操作报的啥错？

**Comment by dmMaze** [comment]
> 导出docs和导入json我都还没实现
[v1.3.8](https://github.com/dmMaze/BallonsTranslator/releases/tag/v1.3.8)开始支持docx导入导出  
我先关闭这个issue, 有其他崩溃问题附上记录后可以再开

**Comment by lhj5426** [comment]
> > 导出docs和导入json我都还没实现
> 
> [v1.3.8](https://github.com/dmMaze/BallonsTranslator/releases/tag/v1.3.8)开始支持docx导入导出 我先关闭这个issue, 有其他崩溃问题附上记录后可以再开

嗯 谢谢 刚才看到 github 的通知 发现更新了 下载了138 之后稳定性 比之前发issues 时候提升了很多 
之前 就是涂抹图片的时候也会闪退 现在 涂抹半天了 都已经机器翻译识别完
这本 (C100) [規制当局 (リヒャルト・バフマン)] 放課後代理妻・桜 -夫婦の寝室で種付けされる娘- (オリジナル) [DL版]  
60多页的 漫画了也没有发生闪退

**Comment by dmMaze** [comment]
@lhj5426 
第一次传1.3.8的时候忘了加汉化包，可以再下一遍patch覆盖下
