### ISSUE TITLE
找不到python38.dll

### ISSUE THREAD

**Issue by SpaceThing** [dmMaze/BallonsTranslator#91]
下载python38.dll放到文件夹内也启动不了，安装了Python 3.11.1

**Comment by dmMaze** [comment]
分享文件夹里有两个压缩包，先解压那个大的，再用那个小的解压出来的文件覆盖那个大的
以后一段时间内更新也是用更高版本的小包覆盖现有文件，我暂时没时间做自动更新(#87) 而且比较重的那几个依赖库可能会有大变动
