### ISSUE TITLE
[已弃用] 国内网盘下载连接

### ISSUE THREAD

**Issue by HA-JD** [dmMaze/BallonsTranslator#93]
**所有旧版（用exe执行的）都不再推荐使用** 新版阅读dev分支的readme运行，有人愿意用国内网盘分流还是可以贴到这里

https://www.aliyundrive.com/s/Ut5tAy7f4tR
无任何修改因为阿里云网盘不让裸上传7z zip等压缩包，重新压缩exe自解压格式，压缩包工具直接打开就行
![image](https://user-images.githubusercontent.com/47666701/221201471-e5bc8195-250b-4e8d-87ee-49ded9d9983b.png)

**Comment by dmMaze** [comment]
感谢
之前试了几个国内盘总被违规就懒得传了

**Comment by pboymt** [comment]
大佬能不能做一个data目录的压缩包？直接从源码运行有点难受的，Google Drive下载目录的压缩非常非常慢……

**Comment by HA-JD** [comment]
意思是要我打包完整的？

**Comment by pboymt** [comment]
是 Google Drive 分享里面那个 data 目录，打包完应该是 1.3G 的 zip 文件，好像 OpenCV 的 dll 还有一些模型都在里面。

core.zip 这个完整包里面应该有完整的源代码+ data 目录吧。🤔

**Comment by dmMaze** [comment]
> 是 Google Drive 分享里面那个 data 目录，打包完应该是 1.3G 的 zip 文件，好像 OpenCV 的 dll 还有一些模型都在里面。
> 
> core.zip 这个完整包里面应该有完整的源代码+ data 目录吧。🤔

发现mangaocr下面的.git没删，现在谷歌盘压缩速度应该正常了...

**Comment by pboymt** [comment]
> > 是 Google Drive 分享里面那个 data 目录，打包完应该是 1.3G 的 zip 文件，好像 OpenCV 的 dll 还有一些模型都在里面。
> > 
> > core.zip 这个完整包里面应该有完整的源代码+ data 目录吧。🤔
> 
> 发现mangaocr下面的.git没删，现在谷歌盘压缩速度应该正常了...

我就说为啥文件对不上😰

**Comment by HA-JD** [comment]
![image](https://user-images.githubusercontent.com/47666701/221630325-451a7fae-1c67-4d90-b53f-336590ef88be.png)
