### ISSUE TITLE
奶牛快传(国内网盘)下载

### ISSUE THREAD

**Issue by VOIA14** [dmMaze/BallonsTranslator#94]
后续有更新会及时上传 包括软件本体和更新包
以及对于"小白"的详细安装说明
![image](https://user-images.githubusercontent.com/44628495/221332610-d9c230cd-1a92-42f7-8f2b-f63002cf01df.png)
![image](https://user-images.githubusercontent.com/44628495/221332643-8bec0d6c-bbde-4788-8d6c-daa8a0e750e4.png)

**Comment by dmMaze** [comment]
Duplicate of #93
网盘链接丢那里
另外奶牛快传有流量限制
