### ISSUE TITLE
The latest version does not match the repository.

### ISSUE THREAD

**Issue by My12123** [dmMaze/BallonsTranslator#99]
![2023-02-26_14-24-15](https://user-images.githubusercontent.com/49092250/221407616-25bb9bbc-6de0-4b7d-aa5a-6c5103003790.png)
![2023-02-26_14-25-10](https://user-images.githubusercontent.com/49092250/221407620-4c2b1a6f-f461-4856-8800-2a0096a8c938.png)

- [ ] Keeping the program up to date.

**Comment by bropines** [comment]
> ![2023-02-26_14-24-15](https://user-images.githubusercontent.com/49092250/221407616-25bb9bbc-6de0-4b7d-aa5a-6c5103003790.png) ![2023-02-26_14-25-10](https://user-images.githubusercontent.com/49092250/221407620-4c2b1a6f-f461-4856-8800-2a0096a8c938.png)
> 
> * [ ]  Keeping the program up to date.

Person. If we send every commit to a release, we're going to screw everything up. We are so comfortable. If you need to, run from the source code, the instructions are there.

**Comment by dmMaze** [comment]
> ![2023-02-26_14-24-15](https://user-images.githubusercontent.com/49092250/221407616-25bb9bbc-6de0-4b7d-aa5a-6c5103003790.png) ![2023-02-26_14-25-10](https://user-images.githubusercontent.com/49092250/221407620-4c2b1a6f-f461-4856-8800-2a0096a8c938.png)
> 
> * [ ]  Keeping the program up to date.

<img width="756" alt="image" src="https://user-images.githubusercontent.com/51270320/221408931-01195b84-f08a-42ae-8ac2-3dd77e1b6a01.png">
